src/Apttus Quote/Proposal-Configuration Integration/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
</CustomObject>

src/objects/Quote_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Administration_Fee_Rate__c</fullName>
        <description>Administration Fee Rate that will be used on Repayment calculation</description>
        <label>Administration Fee Rate</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>CTI MGI Quote Setting</label>
</CustomObject>

src/objects/Repayment_Calculator__c.object
<CustomObject>
    <description>CTI Payment Calculator for Templet report.</description>
    <fields>
        <fullName>Beginning_Balance__c</fullName>
        <description>prposals remaining payment Amount</description>
        <label>Beginning Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount_Reversed__c</fullName>
        <description>Begning balance * interest rate % /12</description>
        <label>Discount Reversed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ending_Balance__c</fullName>
        <description>Beginning Balance - principal Amount</description>
        <label>Ending Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Extra_Payment__c</fullName>
        <label>Extra Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <description>proposal.First payment date,
increment by 1 month for each sequence</description>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Principal__c</fullName>
        <description>Total Payment - Discount Recived</description>
        <label>Principal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote_Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Proposal</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Repayment Calculator</relationshipLabel>
        <relationshipName>Repayment_Calculator</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_Payment__c</fullName>
        <description>proposal  Scheduled monthly payments</description>
        <label>Scheduled Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sequence_No__c</fullName>
        <description>sequence of payment</description>
        <label>Sequence No</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Payment__c</fullName>
        <description>Scheduled Payment  +  Extra Payment</description>
        <label>Total Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Repayment Calculator</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Repayment  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Calculator</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Repayment_Calculator.cls
//Apex class "Repayment_Calculator" to create or Delete Repayment Calculator records.
public class Repayment_Calculator{
    
    /** method to create Repayment Calculator records  **/
    public void create_Repayment_Calculator(List<Apttus_Proposal__Proposal__c> proposals){
        List<Repayment_Calculator__c> create_Repayment_Calculator = new  List<Repayment_Calculator__c>();
        Quote_Settings__c qsvalue = Quote_Settings__c.getValues(Utils_allfields.customSettingName);
       
        
        for(Apttus_Proposal__Proposal__c eachpropsal : proposals){
            
            Repayment_Calculator__c temp_Repayment_Calculator = new Repayment_Calculator__c();
                   temp_Repayment_Calculator.Quote_Proposal__c = eachpropsal.ID;
                  
                   temp_Repayment_Calculator.Payment_Date__c = eachpropsal.First_Payment_Date__c;
                   temp_Repayment_Calculator.Beginning_Balance__c = eachpropsal.Remaining_Payment_Amount_f__c;
                   temp_Repayment_Calculator.Scheduled_Payment__c = eachpropsal.Scheduled_Monthly_Payments_f__c;
                   temp_Repayment_Calculator.Interest_Rate__c = qsvalue.Administration_Fee_Rate__c;
                   temp_Repayment_Calculator.Extra_Payment__c = null;
                   temp_Repayment_Calculator.Discount_Reversed__c = temp_Repayment_Calculator.Beginning_Balance__c * (qsvalue.Administration_Fee_Rate__c / 100) / 12;
                   temp_Repayment_Calculator.Total_Payment__c = eachpropsal.Scheduled_Monthly_Payments_f__c;// - temp_Repayment_Calculator.Extra_Payment__c;
                   temp_Repayment_Calculator.Principal__c = temp_Repayment_Calculator.Total_Payment__c- temp_Repayment_Calculator.Discount_Reversed__c ;
                   temp_Repayment_Calculator.Ending_Balance__c = eachpropsal.Remaining_Payment_Amount_f__c - temp_Repayment_Calculator.Principal__c;
            
            /*system.debug('  Beginning_Balance:'+temp_Repayment_Calculator.Beginning_Balance__c);
            system.debug('  Scheduled_Payment:'+temp_Repayment_Calculator.Scheduled_Payment__c);
            system.debug('  Interest_Rate:'+temp_Repayment_Calculator.Interest_Rate__c);
            system.debug('  Extra_Payment:'+temp_Repayment_Calculator.Extra_Payment__c );
            system.debug('  Discount_Reversed  :'+temp_Repayment_Calculator.Discount_Reversed__c);
            system.debug('  Total_Payment:'+temp_Repayment_Calculator.Total_Payment__c );
            system.debug('  Principal :'+ temp_Repayment_Calculator.Principal__c);
            system.debug('  Ending_Balance:'+temp_Repayment_Calculator.Ending_Balance__c);*/
            
            
           for(integer count = 1 ; count <= Integer.valueof(eachpropsal.Payment_Period_In_Month__c); count++){
               
                   Repayment_Calculator__c Repayment_Calculator = new Repayment_Calculator__c();
                   Repayment_Calculator.Quote_Proposal__c = temp_Repayment_Calculator.Quote_Proposal__c;
                   Repayment_Calculator.Sequence_No__c = count;
                   Repayment_Calculator.Payment_Date__c = temp_Repayment_Calculator.Payment_Date__c;
                   Repayment_Calculator.Beginning_Balance__c = temp_Repayment_Calculator.Beginning_Balance__c;
                   Repayment_Calculator.Scheduled_Payment__c = temp_Repayment_Calculator.Scheduled_Payment__c;
                   Repayment_Calculator.Interest_Rate__c = temp_Repayment_Calculator.Interest_Rate__c;
                   Repayment_Calculator.Extra_Payment__c = temp_Repayment_Calculator.Extra_Payment__c;
                   Repayment_Calculator.Discount_Reversed__c = temp_Repayment_Calculator.Discount_Reversed__c;
                   Repayment_Calculator.Total_Payment__c = temp_Repayment_Calculator.Total_Payment__c;
                   Repayment_Calculator.Principal__c = temp_Repayment_Calculator.Principal__c;
                   Repayment_Calculator.Ending_Balance__c = temp_Repayment_Calculator.Ending_Balance__c;
                   create_Repayment_Calculator.add(Repayment_Calculator);
                   
                   // logic for Repayment calculation.
                   temp_Repayment_Calculator.Payment_Date__c = temp_Repayment_Calculator.Payment_Date__c.addMonths(1);
                   temp_Repayment_Calculator.Beginning_Balance__c = temp_Repayment_Calculator.Ending_Balance__c;
                   temp_Repayment_Calculator.Scheduled_Payment__c = eachpropsal.Scheduled_Monthly_Payments_f__c;
                   temp_Repayment_Calculator.Interest_Rate__c = qsvalue.Administration_Fee_Rate__c;
                   temp_Repayment_Calculator.Extra_Payment__c = null;
                   temp_Repayment_Calculator.Discount_Reversed__c = temp_Repayment_Calculator.Beginning_Balance__c * (qsvalue.Administration_Fee_Rate__c /100) / 12;
                   temp_Repayment_Calculator.Total_Payment__c = eachpropsal.Scheduled_Monthly_Payments_f__c;// - temp_Repayment_Calculator.Extra_Payment__c;
                   temp_Repayment_Calculator.Principal__c = temp_Repayment_Calculator.Total_Payment__c- temp_Repayment_Calculator.Discount_Reversed__c ;
                   temp_Repayment_Calculator.Ending_Balance__c = temp_Repayment_Calculator.Beginning_Balance__c - temp_Repayment_Calculator.Principal__c;
               
           }
           system.debug('create_Repayment_Calculator  :'+create_Repayment_Calculator);
           
           
        }
        
        if(!create_Repayment_Calculator.isEmpty()){
            try{
                insert create_Repayment_Calculator;
            }catch (DMLException e) {
                        System.debug('Exception: Repayment_Calculator deleting records');   
                        throw e;        
                    }
            
        }
        
        
    }
    
    //Method to delete Repayment_Calculator records given list of proposals
    
    public void delete_Repayment_Calculator(List<Id> ProposalId){
        List <Repayment_Calculator__c> Del_Repayment_Calculator = new List <Repayment_Calculator__c>();
       if(ProposalId != Null && !ProposalId.isEmpty()){
           Del_Repayment_Calculator = [select Id from Repayment_Calculator__c where Quote_Proposal__c in:ProposalId];
       }
       if(!Del_Repayment_Calculator.isEmpty()){
           try{
               delete Del_Repayment_Calculator;
           }catch (DMLException e) {
                        System.debug('Exception: Repayment_Calculator deleting records');      
                        throw e;     
                    }
           
           
       }
        
    }

}