src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Vista_Account_Number__c</fullName>
        <description>CORE Integration field - Unique ID in the VISTA system.</description>
        <inlineHelpText>Unique ID in the Socrates system.</inlineHelpText>
        <label>Vista Account Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AccountContact__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE:  The Account linked to the Contact</description>
        <inlineHelpText>The Account linked to the Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>CORE: The Contact linked to the Account</description>
        <inlineHelpText>The Contact linked to the Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>AOC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestAccountContactTrigger.cls
@isTest
private class TestAccountContactTrigger {
/* AA (Deloitte) - Deactivated as UK Users not onboarded yet
 
 
    public static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Test.startTest();
         String AcctRecordTypeId;
        String ContactRecordTypeId;
        String DiscRecordTypeId;
        String ClusterRecordTypeId;
        String OptyRecordTypeId;                        
        
        List<RecordType> RecordTypeList = new List<RecordType>([select Id,Name from RecordType]);
        
        for (RecordType i : RecordTypeList) {
          if (i.Name == 'Bookshop') {
            AcctRecordTypeId = i.Id;
          }
          if (i.Name == 'Bookshop Contact') {
             ContactRecordTypeId = i.Id;
          }
          
          if (i.Name == '3) Discipline') {
            DiscRecordTypeId = i.Id;
          }
          if (i.Name == '2) Cluster') {
            ClusterRecordTypeId = i.Id;
          }
          if (i.Name == 'New Multi-Component') {
            OptyRecordTypeId = i.Id;
          }                    
        }        
        Account acct = new Account (name = 'Test1',BillingStreet = 'Street1',
                   BillingCity = 'London', BillingPostalCode = 'ABC DEF', BillingCountry = 'UK',
                    Vista_Account_Number__c = 'xyz',RecordTypeId= AcctRecordTypeId);
        insert acct;
        
        Contact ct  = new Contact (FirstName = 'testfnm', LastName = 'testln', AccountId = acct.Id,
          RecordTypeId=ContactRecordTypeId);
        insert ct;
		*/
        /*AccountContact__c aoc1 = new AccountContact__c (Account__c = acct.Id, Contact__c = ct.Id,
                   AccountContactComboId__c = acct.Id + '-' + ct.Id);
        insert aoc1;*/
		/* AA (Deloitte) - Deactivated as UK Users not onboarded yet
 
 
        AccountContact__c aoc2 = [select Account__c, Contact__c from AccountContact__c 
                    where Account__c = :acct.Id and Contact__c = :ct.Id];
        
        System.assertEquals(ct.Id, aoc2.Contact__c);
        Test.stopTest();
        //insert ct;
        
    }
    
    */
}