src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Describes the Pearson &apos;Line of Business&apos; the account creator is assigned to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>Used to capture the Market of the Contact Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s Line of Business per their user record</description>
        <formula>TEXT(Owner.Line_of_Business__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line of Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s User record identified market.</description>
        <formula>TEXT(Owner.Market__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityUniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - This stores the link between the Opportunity and University Course</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity University Courses</relationshipLabel>
        <relationshipName>Opportunity_University_Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <formula>HYPERLINK(UniversityCourse__r.Id ,  UniversityCourse__r.Course_Name__c,&quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <description>Opportunity Name field to hold name</description>
        <label>Opportunity Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_University_Course_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>This contains the opportunity.</description>
        <inlineHelpText>This contains the opportunity.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Courses</relationshipLabel>
        <relationshipName>OpportunityUniversityCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UniversityCourse__c</fullName>
        <description>This contains the University course.</description>
        <inlineHelpText>This contains the University course.</inlineHelpText>
        <label>University Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Course Opportunities</relationshipLabel>
        <relationshipName>OpportunityUniversityCourses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Course</label>
    <nameField>
        <displayFormat>OPTYUC-{00000}</displayFormat>
        <label>OpportunityUniversityCourse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>CTIMGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Field Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Indicates which Market is utilizing this product.</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <description>Core: Captures information about Pearson Products</description>
        <label>Product</label>
    </recordTypes>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Catalog_Code__c</fullName>
        <label>Catalog Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <description>Name of the course at the university or department.</description>
        <inlineHelpText>Name of the course at the university or department.</inlineHelpText>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>The business unit the user is assigned to within Pearson</description>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>CTIMGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Field Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The user&apos;s line of business</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OppProductToAssetTest.cls
@isTest
private class OppProductToAssetTest {

    static testMethod void testSearchTermCleansing() {
    test.StartTest();
        User us = [select Market__c,Line_of_Business__c,Business_Unit__c from User where id =:UserInfo.getUserId() limit 1];
        system.RunAs(us){
        
        
        TestClassAutomation.FillAllFields = true;
    
    Account sAccount        = (Account)TestClassAutomation.createSObject('Account');
    sAccount.BillingCountry      = 'Australia';
    sAccount.BillingState      = 'Victoria';
    sAccount.BillingCountryCode    = 'AU';
    sAccount.BillingStateCode    = 'VIC';
    sAccount.ShippingCountry    = 'Australia';
    sAccount.ShippingState      = 'Victoria';
    sAccount.ShippingCountryCode  = 'AU';
    sAccount.ShippingStateCode    = 'VIC';
    
    insert sAccount;
    
    Product2 sProduct            = (Product2)TestClassAutomation.createSObject('Product2');
    sProduct.Market__c = us.Market__c;
    sProduct.Line_of_Business__c= us.Line_of_Business__c;
    sProduct.Business_Unit__c = us.Business_Unit__c ;
    insert sProduct;
     system.debug('product details---'+sProduct);
     
    PriceBookEntry newPriceBookEntry = new PriceBookEntry();
    newPriceBookEntry.Pricebook2Id = Test.getStandardPricebookId();//listWithPriceBook[0].Id;
    newPriceBookEntry.UnitPrice = 10.0;
    newPriceBookEntry.Product2Id = sProduct.Id;
    newPriceBookEntry.CurrencyIsoCode= 'GBP';
    newPriceBookEntry.IsActive = true;
    insert newPriceBookEntry;

    
    Opportunity sOpportunity        = (Opportunity)TestClassAutomation.createSObject('Opportunity');
    sOpportunity.AccountId          = sAccount.Id;
    sOpportunity.StageName          = 'Closed';
    sOpportunity.RecordTypeId       = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Opportunity').getRecordTypeId();
   // sOpportunity.Pricebook2Id       = Test.getStandardPricebookId();
    sOpportunity.CurrencyIsoCode= 'GBP';
    insert sOpportunity;
    
    UniversityCourse__c course = new UniversityCourse__c(Name= 'TestCourse',Account__c = sAccount.Id, Catalog_Code__c = 'C01',Course_Name__c = 'TestCourse');
    insert course;
    
    OpportunityUniversityCourse__c ouc = new OpportunityUniversityCourse__c(Opportunity__c = sOpportunity.Id, UniversityCourse__c = course.Id,Account__c = sAccount.Id,Opportunity_Name__c = sOpportunity.Id, Close_Date__c = system.Today(),Opportunity_University_Course_Amount__c = 100);
    insert ouc;
    
     List<Contact> contactList=TestDataFactory.createContact(1);
    contactList[0].AccountId = sAccount.id;
    insert contactList;
    
    system.debug('---------MArket------------'+us.Market__c+'---Business Unit---'+us.Business_Unit__c +'---Lie of business---'+us.Line_of_Business__c);
        
         
    //Test.startTest();
    
      OpportunityLineItem sOLI      = new OpportunityLineItem();
      sOLI.OpportunityId          = sOpportunity.Id;
      sOLI.PricebookEntryId        = newPriceBookEntry.Id;
      //sOLI.TotalPrice            = 200;
      sOLI.UnitPrice = 10.0;      
      sOLI.Quantity            = 1;
      
      system.debug('sOLI:::' + sOLI);
      insert sOLI;
        
        try{
            OppProductToAsset.setOLIS();          
        }catch(Exception e){}  
        
        try{
            OppProductToAsset.setAssetList();
        }catch(Exception e){} 
        try{
            OppProductToAsset.convert();
        }catch(Exception e){} 
        try{
            OppProductToAsset.setOUCS();       
        }catch(Exception e){} 
        OppProductToAsset.convertToAsset(sOpportunity.Id,sAccount.Id);
        OppProductToAsset obj = new OppProductToAsset();
        
        
        OpportunityContactRole ocr = new OpportunityContactRole(ContactId = contactList[0].Id, OpportunityId = sOpportunity.Id, IsPrimary = true, Role= 'Desicion Maker');
        insert ocr;
        OppProductToAsset.setAssetList();
        delete sOLI;
        List<OpportunityLineItem> li = obj.getOlis();
        OppProductToAsset.setOLIS();
        }test.StopTest();
    }
}