src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Action__c.object
<CustomObject>
    <description>Based component of the Action Framework functionality</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the action</description>
        <inlineHelpText>Description of the action</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DueTo__c</fullName>
        <description>Date/Time to complete the action</description>
        <inlineHelpText>Date/Time to complete the action</inlineHelpText>
        <label>Due To</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Lead</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Number to represent the order of execution of the action within the template</description>
        <inlineHelpText>Order of execution of the action within the template</inlineHelpText>
        <label>Sequence</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates the stage of progress of the action</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <description>Name of source template of the action to identify the business process</description>
        <label>Source Template</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Briefly description of the action</description>
        <inlineHelpText>Briefly description of the action</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Action Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <recordTypes>
        <fullName>Default_Action</fullName>
        <active>true</active>
        <label>Default Action</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ActionTemplateItem__c.object
<CustomObject>
    <description>Represent the information to use as a templates for the action creation on the Action Framework solution</description>
    <fields>
        <fullName>AssignToType__c</fullName>
        <description>Specify if the action is assigned to a Queue or a User</description>
        <inlineHelpText>Specify if the action is assigned to a Queue or a User</inlineHelpText>
        <label>Assign To Type</label>
        <picklist>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the action</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ParentObjectType__c</fullName>
        <description>Identifies the action parent object type</description>
        <label>Parent Object Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QueueName__c</fullName>
        <description>Name of the queue to assign the action to</description>
        <inlineHelpText>Name of the queue to assign the action to</inlineHelpText>
        <label>Queue Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Number to represent the order of execution of the action</description>
        <label>Sequence</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TemplateName__c</fullName>
        <description>Name of template to identify the business process</description>
        <label>Template Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeToComplete__c</fullName>
        <description>Time in minutes from the creation to complete the action</description>
        <inlineHelpText>Time in minutes from the creation to complete the action</inlineHelpText>
        <label>Time To Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Briefly description of the action</description>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User to assign the action to</description>
        <inlineHelpText>User to assign the action to</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Action_Template_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action Template Item</label>
    <nameField>
        <displayFormat>ATI-{00000}</displayFormat>
        <label>Action Template Item Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Template Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to record whether the case relates to an Opportunity</description>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Status field is used to define the status of the opportunity</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ActionFrameworkPlugin.cls
/*******************************************************************************************************************
* Apex Class Name  : ActionFrameworkPlugin
* Version          : 1.0 
* Created Date     : 19 March 2015
* Function         : Plugin of the ActionFramework functinality to use in flows
* Modification Log :
*
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
*                          19/03/2015                 Created Initial Version
*******************************************************************************************************************/
global without sharing class ActionFrameworkPlugin implements Process.Plugin
{

   global Process.PluginResult invoke(Process.PluginRequest request)
   {   
        String TemplateName = (String)request.inputParameters.get('TemplateName');
        String ParentObjectType = (String)request.inputParameters.get('ParentObjectType');
        String ParentObjectID = (String)request.inputParameters.get('ParentObjectID');
   
       Map<String,Object> result = new Map<String,Object>();
       
       result = GenerateActions(TemplateName, ParentObjectType ,ParentObjectID);
       
       return new Process.PluginResult(result);
   }
   
   /*************************************************************************************************************
    * Description : Returns the describe information for the interface (input parameters, output paramenters)
    *************************************************************************************************************/
   global Process.PluginDescribeResult describe()
   {
        // Set up plugin metadata
        Process.PluginDescribeResult result = new Process.PluginDescribeResult();
        result.description = 'The Action Framework plugin generate action records related with the parent object provided based on the specified action template definition';
        result.tag = 'Action Framework';
        
        // Define plugin input parameters
        result.inputParameters = new List<Process.PluginDescribeResult.InputParameter>
        {
                // Template Name
                new Process.PluginDescribeResult.InputParameter('TemplateName', Process.PluginDescribeResult.ParameterType.STRING, true),
                // Parent Object Type
                new Process.PluginDescribeResult.InputParameter('ParentObjectType', Process.PluginDescribeResult.ParameterType.STRING, true),
                // Parent Object Id
                new Process.PluginDescribeResult.InputParameter('ParentObjectID', Process.PluginDescribeResult.ParameterType.STRING, true)
        };
        
        // Define plugin output parameters
        result.outputParameters = new List<Process.PluginDescribeResult.OutputParameter>
        {
            // Actions Inserted
            new Process.PluginDescribeResult.OutputParameter('ActionsInserted', Process.PluginDescribeResult.ParameterType.BOOLEAN),
            // Result Message
            new Process.PluginDescribeResult.OutputParameter('ResultMessage', Process.PluginDescribeResult.ParameterType.STRING)
        };
        
        return result;
    }
   
    /*************************************************************************************************************
    * Name        : GenerateActions
    * Description : Insert Action records related with the specified object id based on the action template
    * Input       : ActionTemplateName (String) - Name of the action template
    *               ParentObjectTypeName (String) - Type of parent object
    *               ParentObjectId (String) - Id of the parent object
    * Output      : Message with the result of the action generation ( 'Suscess' if the action where successfully inserted)
    *************************************************************************************************************/
    public Map<String,Object> GenerateActions(String ActionTemplateName, String ParentObjectType, String ParentObjectId){
    
        try
        {
            Map<String,Object> result = new Map<String,Object>();
            
            String resultMessage = 'Success';
            
            // Get the list of items related with the actions template
            List<ActionTemplateItem__c> TemplateItemsList = [SELECT Id, Sequence__c, Title__c, Description__c, TimeToComplete__c, AssignToType__c, User__c, QueueName__c  FROM ActionTemplateItem__c WHERE TemplateName__c =:ActionTemplateName AND ParentObjectType__c=:ParentObjectType];
            
            // Get the list of available queues
            Map<String,QueueSobject> mapAvailableQueues = GetAvailableQueues('Action__c');
            
            // Get the list of active users
            List<User> ActiveUserList = [SELECT Id, Username FROM User WHERE IsActive = true];  
            Map<ID,User> mapActiveUsers = new Map<ID,User>(ActiveUserList);
            
            // Get the Action active record type
            List<RecordType> ActionActiveRecordTypesList = [SELECT Id FROM RecordType WHERE SobjectType = 'Action__c' AND DeveloperName = 'Default_Action'];
                        
            List<Action__c> ActionsToInsert = new List<Action__c>();
            
            // Generate the actions
            for(ActionTemplateItem__c item :TemplateItemsList)
            {
                Action__c act = new Action__c();
                
                act.Template__c = ActionTemplateName;
                act.Title__c = item.Title__c;
                act.Description__c = item.Description__c;
                act.Status__c = 'New';
                act.Sequence__c = item.Sequence__c;
                
                if(ActionActiveRecordTypesList.size()>0)
                {
                    act.RecordTypeId = ActionActiveRecordTypesList.get(0).Id;
                }
                //Define the time to complete the action
                if((item.TimeToComplete__c != null)&&(item.TimeToComplete__c <> 0))
                {
                    act.DueTo__c = DateTime.Now().addMinutes(Integer.valueOf(item.TimeToComplete__c));
                }
                
                //Define the owner
                if(item.AssignToType__c == 'User')
                {
                    if(mapActiveUsers.containsKey(item.User__c))
                    {
                       act.OwnerId = mapActiveUsers.get(item.User__c).Id;
                    }
                }
                else if(item.AssignToType__c == 'Queue')
                {
                    if(mapAvailableQueues.containsKey(item.QueueName__c))
                    {
                       act.OwnerId = mapAvailableQueues.get(item.QueueName__c).QueueId;
                    }
                }
                else
                {
                    act.OwnerId = UserInfo.getUserId();
                }
                
                // Define Parent Object
                if(ParentObjectType == 'Account')
                {
                    List<Account> accnts = [SELECT Id FROM Account WHERE Id =:ParentObjectId];
                    
                    if(accnts.size()>0){
                        act.Account__c = accnts.get(0).Id;
                    }
                }
                else if(ParentObjectType == 'Contact')
                {
                    List<Contact> conts = [SELECT Id FROM Contact WHERE Id =:ParentObjectId];
                    
                    if(conts.size()>0){
                        act.Contact__c= conts.get(0).Id;
                    }
                }
                else if(ParentObjectType == 'Case')
                {
                    List<Case> cases = [SELECT Id FROM Case WHERE Id =:ParentObjectId];
                    
                    if(cases.size()>0){
                        act.Case__c = cases.get(0).Id;
                    }
                }
                else if(ParentObjectType == 'Lead')
                {
                    List<Lead> leads = [SELECT Id FROM Lead WHERE Id =:ParentObjectId];
                    
                    if(leads.size()>0){
                        act.Lead__c= leads.get(0).Id;
                    }
                }
                else if(ParentObjectType == 'Opportunity')
                {
                    List<Opportunity> opps = [SELECT Id FROM Opportunity WHERE Id =:ParentObjectId];
                    
                    if(opps.size()>0){
                        act.Opportunity__c = opps.get(0).Id;
                    }
                }    
                
                ActionsToInsert.add(act);
            }
            
            if(ActionsToInsert.size()>0)
            {
                insert ActionsToInsert;
            }
            
            
            result.put('ActionsInserted',true);
            result.put('ResultMessage',resultMessage);
            return result;
        }
        catch(Exception e)
        {
            Map<String,Object> result = new Map<String,Object>();
            String resultMessage = e.getMessage();
            result.put('ActionsInserted',false);
            result.put('ResultMessage',resultMessage);
            return result;
        }

    }
   
    /*************************************************************************************************************
    * Name        : GetAvailableQueues
    * Description : Retrieve the a map with the available queues for the specified object type
    * Input       : ObjectType (String) - Type of object
    * Output      : Map with the queue object by name
    *************************************************************************************************************/
    public Map<String,QueueSobject> GetAvailableQueues(String ObjectType)
    {
        Map<String,QueueSobject> mapAvailableQueues = new Map<String,QueueSobject>();
            
        List<QueueSobject> QueueList = [SELECT Id, QueueId, Queue.Name FROM QueueSobject WHERE SobjectType =:ObjectType];
            
        for( QueueSobject q :QueueList)
        {
            if(mapAvailableQueues.containsKey(q.Queue.Name)== false){
                mapAvailableQueues.put(q.Queue.Name,q);
            }
        }    
           
        return mapAvailableQueues;
    }

}