src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Learner</fullName>
        <active>true</active>
        <label>Learner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AccountContact__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>AccountRole__c</fullName>
        <description>The role the contact plays on this account</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Educator</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE:  The Account linked to the Contact</description>
        <inlineHelpText>The Account linked to the Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>CORE: The Contact linked to the Account</description>
        <inlineHelpText>The Contact linked to the Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Relevant to D2L Model only. On a Learner account, the Learner is defaulted to the &apos;Primary&apos; on the account. There can only be one &apos;Primary&apos; contact per Learner Account</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_In_Progress__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a hidden field and is used to flag records that are being updated by the trigger to avoid firing the financial responsible person and primary contact validations. The field is used to prevent the trigger from firing an error when it is un-checking related records when the user sets a new primary or FS contact</description>
        <label>Sync In Progress</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>AOC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestAccountContact_Primary_Financial.cls
/*******************************************************************************************************************
* Apex Class Name   :TestAccountContact_Primary_Financial
* Created Date      : 8 MAY 2014
* Description       : Test class for AccountContact_Primary_Financial class
*******************************************************************************************************************/
@isTest
private class TestAccountContact_Primary_Financial
{
    static testMethod void myUnitTest2()
    {
    TestClassAutomation.FillAllFields = true;
        
        Account sAccount                = (Account)TestClassAutomation.createSObject('Account');
        sAccount.BillingCountry         = 'Australia';
        sAccount.BillingState           = 'Victoria';
        sAccount.BillingCountryCode     = 'AU';
        sAccount.BillingStateCode       = 'VIC';
        sAccount.ShippingCountry        = 'Australia';
        sAccount.ShippingState          = 'Victoria';
        sAccount.ShippingCountryCode    = 'AU';
        sAccount.ShippingStateCode      = 'VIC';
        
        insert sAccount;
        Contact sContact                = (Contact)TestClassAutomation.createSObject('Contact');
        sContact.AccountId              = sAccount.Id;
        sContact.OtherCountry           = 'Australia';
        sContact.OtherState             = 'Victoria';
        sContact.OtherCountryCode       = 'AU';
        sContact.OtherStateCode         = 'VIC';
        sContact.MailingCountry         = 'Australia';
        sContact.MailingState           = 'Victoria';
        sContact.MailingCountryCode     = 'AU';
        sContact.MailingStateCode       = 'VIC';
            
        Test.startTest();
            
            insert sContact;
            
        checkRecurssion.run = true;    
        AccountContact__c accContObj = new AccountContact__c();
        accContObj.Contact__c = sContact.id;
        accContObj.Account__c = sAccount.id;
        accContObj.AccountRole__c='Learner';
        accContObj.primary__c=false;
        accContObj.Sync_In_Progress__c=false;
        insert accContObj;
       //  AccountContact__c sAccountContact  = new AccountContact__c(account__c=sAccount.Id,contact__c=sContact.Id,Primary__c=true,AccountRole__c='Learner');        
         // insert sAccountContact; 
         AccountContact__c sAccountContact = [Select Id FROM AccountContact__c WHERE Contact__c = : sContact.Id limit 1];
         AccountContactRole sAccountConRole = [Select Id FROM AccountContactRole WHERE Contactid = : sContact.Id limit 1];

            checkRecurssion.run = true;       
            update sAccountContact;
            checkRecurssion.run = true; 
                        
            delete sAccountContact;
            delete sAccountConRole;
           checkRecurssion.run = true;    

           undelete sAccountContact;
        
        Test.stopTest();
    }
  /* Static testmethod void myUnitTest_1(){
         TestClassAutomation.FillAllFields = true;
        
        Account sAccount                = (Account)TestClassAutomation.createSObject('Account');
        sAccount.BillingCountry         = 'Australia';
        sAccount.BillingState           = 'Victoria';
        sAccount.BillingCountryCode     = 'AU';
        sAccount.BillingStateCode       = 'VIC';
        sAccount.ShippingCountry        = 'Australia';
        sAccount.ShippingState          = 'Victoria';
        sAccount.ShippingCountryCode    = 'AU';
        sAccount.ShippingStateCode      = 'VIC';
        
        insert sAccount;
        
        Contact sContact                = (Contact)TestClassAutomation.createSObject('Contact');
        sContact.AccountId              = sAccount.Id;
        sContact.OtherCountry           = 'Australia';
        sContact.OtherState             = 'Victoria';
        sContact.OtherCountryCode       = 'AU';
        sContact.OtherStateCode         = 'VIC';
        sContact.MailingCountry         = 'Australia';
        sContact.MailingState           = 'Victoria';
        sContact.MailingCountryCode     = 'AU';
        sContact.MailingStateCode       = 'VIC';
            
        Test.startTest();
            
           insert sContact;
         AccountContact__c sAccountContact  = new AccountContact__c(account__c=sAccount.Id,contact__c=sContact.Id,Primary__c=true,AccountRole__c='Learner');        
          insert sAccountContact; 
        // AccountContact__c sAccountContact = [Select Id FROM AccountContact__c WHERE Contact__c = : sContact.Id limit 1];
                    
         Test.stopTest();
            
     }  */
}