src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Learner</fullName>
        <active>true</active>
        <label>Learner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AccountContact__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>AccountRole__c</fullName>
        <description>The role the contact plays on this account</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Educator</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE:  The Account linked to the Contact</description>
        <inlineHelpText>The Account linked to the Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>CORE: The Contact linked to the Account</description>
        <inlineHelpText>The Contact linked to the Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Financially_Responsible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Financially responsible=True</description>
        <label>Financially Responsible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Relevant to D2L Model only. On a Learner account, the Learner is defaulted to the &apos;Primary&apos; on the account. There can only be one &apos;Primary&apos; contact per Learner Account</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>AOC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestAccountContactUtils.cls
/*******************************************************************************************************************
* Apex Class Name   :TestAccountContactUtils
* Created Date      : 8 MAY 2014
* Description       : Test class for AccountContactUtils class
*******************************************************************************************************************/
@isTest
private class TestAccountContactUtils
{
  Static testmethod void myUnitTest_1(){
  AccountContact__c sAccountContact = new AccountContact__c();

         system.debug('entered unittest1');
         TestClassAutomation.FillAllFields = true;
        
        Account sAccount                = (Account)TestClassAutomation.createSObject('Account');
        sAccount.BillingCountry         = 'Australia';
        sAccount.BillingState           = 'Victoria';
        sAccount.BillingCountryCode     = 'AU';
        sAccount.BillingStateCode       = 'VIC';
        sAccount.ShippingCountry        = 'Australia';
        sAccount.ShippingState          = 'Victoria';
        sAccount.ShippingCountryCode    = 'AU';
        sAccount.ShippingStateCode      = 'VIC';
        
        insert sAccount;
        system.debug('cccc created account-->'+sAccount);
        Contact sContact                = (Contact)TestClassAutomation.createSObject('Contact');
        system.debug('cccc contact reference is created');
        sContact.AccountId              = sAccount.Id;
        sContact.OtherCountry           = 'Australia';
        sContact.OtherState             = 'Victoria';
        sContact.OtherCountryCode       = 'AU';
        sContact.OtherStateCode         = 'VIC';
        sContact.MailingCountry         = 'Australia';
        sContact.MailingState           = 'Victoria';
        sContact.MailingCountryCode     = 'AU';
        sContact.MailingStateCode       = 'VIC';
        System.debug('cccc before contact insert-->');
     //   List<Contact> sContact = testdatafactory.createContact(2);
            
        
            
           insert sContact;
         System.debug('contact inserted-->'+sContact);
         Test.startTest();
         //sAccountContact = [Select Id,AccountContact__c.Primary__c,account__c,contact__c,AccountRole__c,
         //Financially_Responsible__c FROM AccountContact__c WHERE Contact__c = : sContact.Id limit 1];
         
         sAccountContact = new AccountContact__c(account__c=sAccount.Id,contact__c=sContact.Id,Primary__c=true,AccountRole__c='Learner');
         insert sAccountContact;
         System.debug('Accountcontact inserted-->'+sAccountContact);
         system.assert(sAccountContact != null);
        
        AccountContactTriggerHandler testa= new AccountContactTriggerHandler(true,5);
        System.assertEquals(true,  testa.bIsTriggerContext);  
           System.assertEquals(false,  testa.bIsVisualforcePageContext,false);   
           System.assertEquals(false, testa.bIsWebServiceContext,false);  
           System.assertEquals(false,  testa.bIsExecuteAnonymousContext,false); 
 AccountContact__c[] accnt;
 accnt = [Select Id,AccountContact__c.Primary__c,account__c,contact__c,AccountRole__c,Financially_Responsible__c  FROM AccountContact__c WHERE Contact__c = : sContact.Id limit 1];

AccountContact__c[] accntol;
     map<id,AccountContact__c> acc =new map<id,AccountContact__c>();
     //acc = [Select Id,AccountContact__c.Primary__c,account__c,contact__c,AccountRole__c,Financially_Responsible__c  FROM AccountContact__c WHERE Contact__c = : sContact.Id limit 1];

     map<id,AccountContact__c> acccon =new map<id,AccountContact__c>();
    
     testa.OnBeforeinsert(accnt);

         
         
         Test.stopTest();
            
     }  
}