src/objects/AccountContact__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>AccountRole__c</fullName>
        <description>The role the contact plays on this account</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Educator</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to specify which Account is the Contacts Primary Account - updating this field updates the &apos;Account Name&apos;  field on the Contact</description>
        <label>Primary Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE:  The Account linked to the Contact</description>
        <inlineHelpText>The Account linked to the Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>CORE: The Contact linked to the Account</description>
        <inlineHelpText>The Contact linked to the Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Financially_Responsible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Financially responsible=True</description>
        <label>Financially Responsible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Relevant to D2L Model only. On a Learner account, the Learner is defaulted to the &apos;Primary&apos; on the account. There can only be one &apos;Primary&apos; contact per Learner Account</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Detail__c</fullName>
        <description>Detailed information on the role</description>
        <label>Role Detail</label>
        <picklist>
            <controllingField>AccountRole__c</controllingField>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assc. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asst. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chairman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Learning Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emeritus Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjunct Faculty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visiting Lecturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lab Technician/Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secretary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>AOC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role_Detail__c</fullName>
        <label>Role Detail</label>
        <picklist>
            <controllingField>Role__c</controllingField>
            <picklistValues>
                <fullName>Adjunct Faculty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assc. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asst. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chairman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Learning Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emeritus Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visiting Lecturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lab Technician/Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secretary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Educator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isleadConvertedContact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is used to check if contact is created by lead conversion.</description>
        <label>isleadConvertedContact</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>IsLeadConvertedContact__c</fullName>
        <description>This is used to check if contact is created by lead conversion.</description>
        <formula>True</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsLeadConvertedContact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <description>Global: The user&apos;s role or job function at Pearson</description>
        <label>Function</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>TBC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ContactUtils.cls
/*******************************************************************************************************************
* Apex Class Name   : ContactUtils.cls
* Version           : 1.0 
* Created Date      : 10 MARCH 2014
* Function          : Utility Class for Contact Object
* Modification Log  :
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
* Mitch Hunt                  10/03/2014              Created Initial Version of Utility Class
*******************************************************************************************************************/

public with sharing class ContactUtils
{
    // preventDelete
    // If the current user is not the owner or an admin throw an error message on the page.
    //
    public void preventDelete(Contact[] lstContactsToDelete)
    {
        map<string, string> mapProfiles = GlobalUtils.getprofiles();
        Id sProfileId                   = system.Userinfo.getProfileId();
        
     if  (   mapProfiles.get(sProfileId) != 'Pearson Administrator' &&
                mapProfiles.get(sProfileId) != 'System Administrator' &&
                mapProfiles.get(sProfileId) != 'Pearson Data Administrator'                 
            )
        {
            for(Contact sContact : lstContactsToDelete)
            {
                GlobalUtils.Debug('ProfileId:::' + mapProfiles.get(system.Userinfo.getProfileId()));
                
                if  (sContact.OwnerId != system.Userinfo.getUserId())
                {
                    sContact.addError(System.Label.NonAdminOwnerDelete);
                }
            }
        }
        
    }
    
    // createAccountContact
    // create an associated AccountContact__c for a list of contacts.
    // 
    public void createAccountContact(Contact[] lstContacts)
    {
        list<AccountContact__c> lstAccountContact = new list<AccountContact__c>();
        
        set<Id> accountSet = new set<Id>();        
        for(Contact lc : lstContacts)
        {
        	accountSet.add(lc.AccountId);
        }
        
        list<AccountContact__c> existingAccountContacts = [SELECT Contact__c, Account__c FROM AccountContact__c where Account__c = :accountSet];
        
        map<Id, AccountContact__c> accountContactLookup = new map<Id, AccountContact__c>();
        for(AccountContact__c ac : existingAccountContacts)
        {
          accountContactLookup.put(ac.Account__c, ac);
          System.debug('@@@ putting in lookup map ' + ac.Account__c);    
        }
         
        for (Contact sContact : lstContacts)
        {
           //to block accountcontact creation on lead conversion        
            if(sContact.isleadConvertedContact__c == false && sContact.AccountId != null)
            {
              System.debug('@@@isleadConvertedContact__c'+sContact.isleadConvertedContact__c);
              System.debug('@@@ account id is ' + scontact.AccountId);
              if(!accountContactLookup.containsKey(sContact.AccountId))
              {
                lstAccountContact.add(new AccountContact__c(Account__c = sContact.AccountId, Contact__c = sContact.Id, 
                                                            Account_Name__c = true, 
                                                            AccountRole__c = sContact.Role__c,
                                                            Role_Detail__c = sContact.Role_Detail__c,
                                                            Primary__c = true,
                                                            Financially_Responsible__c = true));
                                                          
              }
              else
              {
                lstAccountContact.add(new AccountContact__c(Account__c = sContact.AccountId, Contact__c = sContact.Id, 
                                                            Account_Name__c = true, 
                                                            AccountRole__c = sContact.Role__c,
                                                            Role_Detail__c = sContact.Role_Detail__c,
                                                            Primary__c = false,
                                                            Financially_Responsible__c = false));
              }
              System.debug('@@@ContactUtils'+lstAccountContact);              
            }
        }
                    insert lstAccountContact;
    }
    
    
    
}