src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Vista_Account_Number__c</fullName>
        <description>CORE Integration field - Unique ID in the VISTA system.</description>
        <inlineHelpText>Unique ID in the Socrates system.</inlineHelpText>
        <label>Vista Account Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <description>This object contains the attributes stored at the account product association relationship</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account linked to the product.</description>
        <inlineHelpText>Bookshop that has inventory of this product.</inlineHelpText>
        <label>Bookshop</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Stocked Product</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Actual_Sold_Quantity__c</fullName>
        <description>Actual product sold quantity at a bookshop.</description>
        <inlineHelpText>Actual product sold quantity at a bookshop.</inlineHelpText>
        <label>Actual Sold Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product linked to the Account.</description>
        <inlineHelpText>Product stocked at this bookshop.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Bookshops</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stocked_Quantity__c</fullName>
        <description>Quantity of product stocked at bookshop.</description>
        <inlineHelpText>Quantity of product stocked at bookshop.</inlineHelpText>
        <label>Stocked Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <displayFormat>ACCTPRD-{0000000}</displayFormat>
        <label>Account Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestProductBookshopQtyUpdate.cls
@isTest
private class TestProductBookshopQtyUpdate {
/* AA (Deloitte) - Deactivated as UK Users not onboarded yet
 
 
    public static testMethod void myUnitTest() {
    
        Test.startTest();
        String AcctRecordTypeId;
        String ContactRecordTypeId;
        String DiscRecordTypeId;
        String ClusterRecordTypeId;
        String OptyRecordTypeId;                        
        
        List<RecordType> RecordTypeList = new List<RecordType>([select Id,Name from RecordType]);
        
        for (RecordType i : RecordTypeList) {
          if (i.Name == 'Bookshop') {
            AcctRecordTypeId = i.Id;
          }
          if (i.Name == 'Bookshop Contact') {
             ContactRecordTypeId = i.Id;
          }
          
          if (i.Name == '3) Discipline') {
            DiscRecordTypeId = i.Id;
          }
          if (i.Name == '2) Cluster') {
            ClusterRecordTypeId = i.Id;
          }
          if (i.Name == 'New Multi-Component') {
            OptyRecordTypeId = i.Id;
          }                    
        }        
        // TO DO: implement unit test
        Product2 prod1 = new Product2 (name = 'Test Prod1');
        insert prod1;

        Product2 prod2 = new Product2 (name = 'Test Prod2');
        insert prod2;
        
        Account bkshop1  = new Account (name = 'Test Bookshop1', BillingStreet = 'Street1',
                   BillingCity = 'London', BillingPostalCode = 'ABC DEF', BillingCountry = 'UK',
                    Vista_Account_Number__c = 'xyz',RecordTypeId= AcctRecordTypeId );
        insert bkshop1;
        
        Account bkshop2  = new Account (name = 'Test Bookshop2', BillingStreet = 'Street2',
                   BillingCity = 'London', BillingPostalCode = 'ABC DEF', BillingCountry = 'UK',
                    Vista_Account_Number__c = 'xyz1',RecordTypeId = AcctRecordTypeId );
        insert bkshop2;
        
        Account bkshop3  = new Account (name = 'Test Bookshop3', BillingStreet = 'Street3',
                   BillingCity = 'London', BillingPostalCode = 'ABC DEF', BillingCountry = 'UK',
                    Vista_Account_Number__c = 'xyz3',RecordTypeId = AcctRecordTypeId );
        insert bkshop3;


        Account_Product__c ap1 = new Account_Product__c (Account__c = bkshop1.Id, Product__c = prod1.Id,
                   Stocked_Quantity__c = 10,Actual_Sold_Quantity__c = 10);
        insert ap1;
        
        Account_Product__c ap2 = new Account_Product__c (Account__c = bkshop2.Id, Product__c = prod1.Id,
                   Stocked_Quantity__c = 15,Actual_Sold_Quantity__c = 20);
        insert ap2;

        //check inserted value        
        Product2 prod = [select Bookshop_Quantity__c,Actual_Sold_Quantity__c from Product2 where Id = :prod1.Id];                 
        System.assertEquals(prod.Bookshop_Quantity__c, 25);
        System.assertEquals (prod.Actual_Sold_Quantity__c,30);

        //check updates
        Account_Product__c ap3 = [select Id,Stocked_Quantity__c from Account_Product__c where Id = :ap2.Id];
        ap3.Stocked_Quantity__c = 12;
        ap3.Actual_Sold_Quantity__c  = 15;
        update ap3;
        Product2 prod_1 = [select Bookshop_Quantity__c,Actual_Sold_Quantity__c from Product2 where Id = :prod1.Id];                 
        System.assertEquals(prod_1.Bookshop_Quantity__c, 22);
        System.assertEquals (prod_1.Actual_Sold_Quantity__c,25);

        //check deletes
        delete ap3;
        Product2 prod_2 = [select Bookshop_Quantity__c,Actual_Sold_Quantity__c from Product2 where Id = :prod1.Id];                 
        System.assertEquals(prod_2.Bookshop_Quantity__c, 10);
        System.assertEquals (prod_2.Actual_Sold_Quantity__c,10);

        //Account_Product__c ap4 = new Account_Product__c (Account__c = bkshop1.Id, Product__c = prod1.Id,
        //           Stocked_Quantity__c = 15);
        //insert ap4;
                        
        Test.stopTest();        
    }
    */
}