src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Describes the Pearson Region that the creator of the Account is assigned to.</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Describes the Pearson &apos;Line of Business&apos; the account creator is assigned to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Learner</fullName>
        <active>true</active>
        <label>Learner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>Used to capture the Market of the Contact Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Enrolment_Status__c</fullName>
        <description>This field shows the status of a student&apos;s enrollment for the qualification that the opportunity represents.</description>
        <label>Enrolment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <description>The following field identifies the Opportunity owner&apos;s geography per their user record</description>
        <formula>TEXT(Owner.Geography__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>International_Student_Status__c</fullName>
        <description>This field requires the higher education consultant to identify whether the associated student is an international student or not</description>
        <inlineHelpText>Confirm if the related student will be applying as an international student or not</inlineHelpText>
        <label>International Student?</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s Line of Business per their user record</description>
        <formula>TEXT(Owner.Line_of_Business__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line of Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market2__c</fullName>
        <label>Market2</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s User record identified market.</description>
        <formula>TEXT(Owner.Market__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification__c</fullName>
        <description>This field will be stamped with the name of the qualification the student is pursuing once modules are selected</description>
        <label>Qualification Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>This task record represents the actions logged by NA HE reps to manage their opportunities</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>To which of the Pearson Geographies does this user belong</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The user&apos;s line of business</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PS_CreateAssetbasedStudentTest.cls
/*******************************************************************************************************************
* Class Name       : PS_CreateAssetbasedStudentRegistration
* Version          : 1.0 
* Created Date     : 30 March 2015
* Function         : Test Class of the PS_CreateAssetbasedStudentRegistration
* Modification Log :
*
* Developer                                Date                    Description
* ------------------------------------------------------------------------------------------------------------------
*   Accenture IDC                          9/05/2015              Created Initial Version
*******************************************************************************************************************/

@isTest 
/* a private class for creating student based on asset */            
private class PS_CreateAssetbasedStudentTest{
private static List<User> userlist;

/* a test method to ensure that students are created based on the criteria */
 static testMethod void myTest() { 

/*list<Account> accountdatalist = TestDataFactory.createAccount(3,'Learner');   
Insert accountdatalist;
Update accountdatalist;*/
    userlist = new List<User>();
    userlist = TestDataFactory.createUser(userinfo.getProfileId());
    insert userlist;
    system.runAs(userlist[0]){
    Account acc = new Account();
     acc.Name = 'Test';
     acc.Line_of_Business__c= 'Higher Ed';
     acc.Geography__c = 'North America';
     acc.Market__c = 'US';
     insert acc;
     
     
     contact con = new contact();
     con.Lastname= 'testcon';
     con.Firstname= 'testcon1';
     con.MobilePhone = '9999';     
     insert con;
     
     Test.startTest();
  //for(Account newAcc : accountdatalist){}
     List<Opportunity>opplist = new List<Opportunity>();
     Map<Id,Opportunity> optyMap = new Map<Id,Opportunity>();
     Map<Id,Opportunity> oldMapOpty = new Map<Id,Opportunity>();
     Opportunity opp = new opportunity();
      opp.AccountId = acc.id;    
      opp.Name = 'OppTest';
      opp.StageName = 'Qualification';
      opp.Type = 'New Business';
      opp.Enrolment_Status__c = 'Enrolled';
      opp.CloseDate = system.today();
      opp.International_Student_Status__c = 'Yes';
      opp.Qualification__c = 'Psychology';
      opp.Market2__c = 'US';
      
      Opportunity opp1 = new opportunity();
      opp1.AccountId = acc.id;    
      opp1.Name = 'OppTest';
      opp1.StageName = 'Qualification';
      opp1.Type = 'Returning Business';
      opp1.Enrolment_Status__c = 'Pre-enrolled';
      opp1.CloseDate = system.today();
      opp1.International_Student_Status__c = 'No';
      opp1.Qualification__c = 'Graphic Design';
      opp1.Market2__c = 'US';
      
     Opportunity opp2 = new opportunity();
      opp2.AccountId = acc.id;    
      opp2.Name = 'OppTest';
      opp2.StageName = 'Qualification';
      opp2.Type = 'New Business';
      opp2.Enrolment_Status__c = 'Enrolled';
      opp2.CloseDate = system.today();
      opp2.International_Student_Status__c = 'No';
      opp2.Qualification__c = 'Graphic Design';
      opp2.Market2__c = 'US';
      
      insert opp2;
         
      opplist.add(opp);
      opplist.add(opp1);
      //opplist.add(opp2);
      
      
      insert opplist;
      
    opp2.Qualification__c = 'Psychology';
    
    update  opp2;
    opplist.add(opp2); 
    
    Task tsk1 = new Task();
    tsk1.Status = 'Not Started';
     tsk1.WhatId = opp.Id;
     //tsk1.RecordTypeId = recId;
     tsk1.subject = 'Obtain Matric Certificate';
     tsk1.Auto_Generated__c = true;
      insert tsk1;
      
      Task tsk2 = new Task();
      tsk2.Status = 'Not Started';
      tsk2.WhatId = opp.Id;     
      tsk2.subject = 'Received Signed Enrolment Contract';
      tsk2.Auto_Generated__c = true;
      insert tsk2;
      
      Task tsk3 = new Task();
      tsk3.Status = 'Not Started';
      tsk3.WhatId = opp2.Id;
      tsk3.subject = 'Student Attended Panel Interview';
      tsk3.Auto_Generated__c = true;
      insert tsk3;     
      
             
       PS_createAssetbasedStudentRegistration.createTask(opplist);
       PS_createAssetbasedStudentRegistration.OpportunityStage(optyMap,opplist,oldMapOpty );
       PS_createAssetbasedStudentRegistration.createTask_Method(opplist);
       PS_createAssetbasedStudentRegistration.createTask_Method1(opplist);
       PS_createAssetbasedStudentRegistration.ReturningBuisinesscreateTask(opplist);
       PS_createAssetbasedStudentRegistration.createTaskOnPsychology(opplist);
       PS_createAssetbasedStudentRegistration.ValidationOnTask(optyMap,opplist);
       PS_createAssetbasedStudentRegistration.ValidationOnTaskAndEvent(optyMap,opplist);
       
       Test.stoptest();
   }    
  }
}