src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>High_Grade__c</fullName>
        <description>CORE adopted from ICOM - Integration field</description>
        <label>High Grade</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Code_s__c</fullName>
        <description>The following field identifies the territor(ies) (via territory code(s)) an account should be assigned to</description>
        <inlineHelpText>Please identify the territory code(s) an account should be assigned to</inlineHelpText>
        <label>Territory Code(s)</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestAccountTriggers.cls
@isTest
private class TestAccountTriggers
{
    static testMethod void myUnitTest()
    {
        Test.startTest();
        
        // TO DO: implement unit test
        
        TestClassAutomation.FillAllFields = true;
        
        Account sAccount                = (Account)TestClassAutomation.createSObject('Account');
        sAccount.BillingCountry         = 'Australia';
        sAccount.BillingState           = 'Victoria';
        sAccount.BillingCountryCode     = 'AU';
        sAccount.BillingStateCode       = 'VIC';
        sAccount.ShippingCountry        = 'Australia';
        sAccount.ShippingState          = 'Victoria';
        sAccount.ShippingCountryCode    = 'AU';
        sAccount.ShippingStateCode      = 'VIC';
        sAccount.Territory_Code_s__c = '2PD';
        sAccount.High_Grade__c           = '1 Acc';
        insert sAccount;
       
     
        
        
        delete sAccount;
        
        undelete sAccount;
        
        Test.stopTest();
    }
    
  }