src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <description>Core: Status of Bookmaster account</description>
        <label>Account Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Account_Number__c</fullName>
        <description>CORE - Integration field with Bookmaster</description>
        <externalId>true</externalId>
        <label>External Account Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>NPS_Rating_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NPS Rating Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CTIMGI: Captures the status of the event activity type</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>subject__c</fullName>
        <description>CTIMGI: Identifies the type of interview the interview event is.</description>
        <label>Interview Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lead Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returning Student Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exit interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor Interview</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActivityTemplate__c.object
<CustomObject>
    <description>CORE - This object is used to define default after sales activities to be created automatically to enhance the customer experience.</description>
    <fields>
        <fullName>Account_Location__c</fullName>
        <description>CORE</description>
        <label>Account Location</label>
        <picklist>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CORE - Checkbox indicating whether activities template will generate activities when criteria is met</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Days_Until_Due__c</fullName>
        <description>CORE - Days from creatiton date auto generated activity is due</description>
        <inlineHelpText>Number of Days from the triggered creation of the event</inlineHelpText>
        <label>Days Until Due</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>CORE - Description of activity</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPS_Rating_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CORE - Feedback required for activity?</description>
        <label>NPS Rating Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>CORE - Type of product activity is related to</description>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance and Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials - Software Bundles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <description>CORE</description>
        <label>Related To</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE</description>
        <label>Status</label>
        <picklist>
            <controllingField>Related_To__c</controllingField>
            <picklistValues>
                <fullName>On Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>CORE - Subject of activity created</description>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Activity Template</label>
    <nameField>
        <displayFormat>AT-{00000}</displayFormat>
        <label>Activity Template No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>custom print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>custom ebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>mylab/mastering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>custom mylab/mastering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>simulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>equella</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>learning studio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>course design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>learning catalytic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ELT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>revel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessment</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Status field is used to define the status of the opportunity</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Order Notes_old</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <description>CORE adopted from ICOM - Object to track Orders - integration with Bookmaster</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>&apos;New&apos; is the status for order that have not been completed yet
&apos;Approved&apos; is the status you should select when you want to trigger the sending of the order to Bookmaster</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hand Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <recordTypes>
        <fullName>Order</fullName>
        <active>true</active>
        <label>Order</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderLineItem__c.object
<CustomObject>
    <description>CORE adopted from ICOM</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ItemQuantity__c</fullName>
        <description>From Canonical XSD: Positive integer</description>
        <label>Item Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>OrderLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProductType__c</fullName>
        <description>CORE</description>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance and Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials - Software Bundles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TU</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/TestOrderTriggers.cls
@isTest
private class TestOrderTriggers
{
	static testMethod void myUnitTest()
	{
		TestClassAutomation.FillAllFields = true;
		
		Account sAccount				= (Account)TestClassAutomation.createSObject('Account');
		sAccount.BillingCountry			= 'Australia';
		sAccount.BillingState			= 'Victoria';
		sAccount.BillingCountryCode		= 'AU';
		sAccount.BillingStateCode		= 'VIC';
		sAccount.ShippingCountry		= 'Australia';
		sAccount.ShippingState			= 'Victoria';
		sAccount.ShippingCountryCode	= 'AU';
		sAccount.ShippingStateCode		= 'VIC';
		
		insert sAccount;
		
		Opportunity sOpportunity		= (Opportunity)TestClassAutomation.createSObject('Opportunity');
		sOpportunity.AccountId			= sAccount.Id;
		sOpportunity.StageName			= 'Prospecting';
		insert sOpportunity;
		
		
		
		Product2 sProduct 				= (Product2)TestClassAutomation.createSObject('Product2');
		sProduct.isActive				= true;
		insert sProduct;
		
		ActivityTemplate__c	sAT1 		= new ActivityTemplate__c();
		sAT1.Related_To__c				= 'Order';
		sAT1.Status__c					= 'New';
		sAT1.Subject__c					= 'Test activity 1';
		sAT1.Description__c				= 'Test description 1';
		sAT1.Active__c					= true;
		sAT1.NPS_Rating_Required__c		= true;
		sAT1.Days_Until_Due__c			= 10;
		sAT1.Account_Location__c		= 'Australia';
		sAT1.Product_Type__c 			= sProduct.ProductType__c;
		insert sAT1;
		
		ActivityTemplate__c	sAT2 		= new ActivityTemplate__c();
		sAT2.Related_To__c				= 'Order';
		sAT2.Status__c					= 'Approved';
		sAT2.Subject__c					= 'Test activity 2';
		sAT2.Description__c				= 'Test description 2';
		sAT2.Active__c					= true;
		sAT2.NPS_Rating_Required__c		= true;
		sAT2.Days_Until_Due__c			= 10;
		sAT2.Account_Location__c		= 'Australia';
		sAT2.Product_Type__c 			= sProduct.ProductType__c;
		insert sAT2;
		
		Test.startTest();
		
			Order__c	sOrder				= (Order__c)TestClassAutomation.createSObject('Order__c');
			sOrder.Account__c				= sAccount.Id;
			sOrder.Opportunity__c			= sOpportunity.Id;
			sOrder.Status__c				= 'New';
			
			insert sOrder;
			
			OrderLineItem__c sOLI			= new OrderLineItem__c();
			sOLI.Order__c 					= sOrder.Id;
			sOLI.Product__c					= sProduct.Id;
			sOLI.ItemQuantity__c			= 10;
			insert sOLI;
			
			sAccount.External_Account_Number__c = '1234567';
			sAccount.Account_Status__c			= 'A';
			update sAccount;
			
			sOrder.Status__c					= 'Approved';
			update sOrder;
			
			delete sOrder;
			
			undelete sOrder;
		
		Test.stopTest();
	}
}