src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Describes the Pearson Region that the creator of the Account is assigned to.</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Describes the Pearson &apos;Line of Business&apos; the account creator is assigned to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Learner</fullName>
        <active>true</active>
        <label>Learner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Start_Date__c</fullName>
        <description>Manually entered to denote the student&apos;s intake year and start date</description>
        <label>Academic Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <description>The following field identifies the Opportunity owner&apos;s geography per their user record</description>
        <formula>TEXT(Owner.Geography__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>International_Sponsor__c</fullName>
        <description>This field identifies whether the student is receiving international sponsorship</description>
        <label>International Sponsor?</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s Line of Business per their user record</description>
        <formula>TEXT(Owner.Line_of_Business__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line of Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s User record identified market.</description>
        <formula>TEXT(Owner.Market__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Campus__c</fullName>
        <description>Field to show the campus that the Student wants to attend to take their qualification. This is mapped on Lead conversion, and subsequently updated on the opportunity.</description>
        <label>Preferred Campus</label>
        <picklist>
            <picklistValues>
                <fullName>Bedfordview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bloemfontein</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cape Town</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durban</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durbanville</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midrand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nelspruit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Port Elizabeth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potchefstroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pretoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Randburg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vanderbijlpark</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>D2L</fullName>
        <active>true</active>
        <businessProcess>CTIMGI</businessProcess>
        <label>D2L</label>
    </recordTypes>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>To which of the Pearson Geographies does this user belong</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The user&apos;s line of business</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PaymentInfoRetrivalTest.cls
@isTest
//Class created to cover the Test code coverage for the controller PaymentInfoRetrival
public  class PaymentInfoRetrivalTest {
 //Method created to do Test class code coverage 
    public static testmethod void insertOpportunity(){
    id pid=[select id from profile where name='ACN System Admin Read Only'].id;
       User u1 = new User(Alias = 'standt', Email='standarduser11@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = pid, 
            TimeZoneSidKey='America/Los_Angeles', UserName='test1234'+Math.random()+'@gmail.com', Geography__c = 'Growth',Market__c = 'ZA',Line_of_Business__c = 'Higher Ed');
            insert u1;
            System.assertEquals(u1.Email, 'standarduser11@testorg.com');
         system.runas(u1) {
            // List<Opportunity> opp = TestDataFactory.createOpportunity(1,'D2L');
             List<Account> acc = TestDataFactory.createAccount(1, 'Learner');
             Opportunity oppobj = new Opportunity();
             oppObj.Name = 'TestOpportunityName' ;        
             oppObj.CloseDate = date.today();          
             oppObj.StageName = 'TestOpportunityStageName' ;
             oppObj.AccountId = acc[0].id;        //'0011100000rXTzD';
             oppObj.Academic_Start_Date__c = date.today();
             oppObj.Type = 'New Business'; 
             oppObj.International_Sponsor__c = 'Yes'; 
             oppObj.Preferred_Campus__c = 'Durban';
             //oppObj.RecordTypeId = '012110000004rwd';  
             insert Oppobj;     
             
             PageReference testPage = new pagereference('apex/CustomerLedger');
             id customerid= Oppobj.id;
             testPage.getParameters().put('customerid',customerid);
             Test.setCurrentPage(testPage);
             ApexPages.StandardController sc = new ApexPages.standardController(Oppobj);
             Test.starttest();
             PaymentInfoProxyClass.getPaymentInfo(customerid,'CTI');
             PaymentInfoRetrival pir = new PaymentInfoRetrival();
             pir.institution = 'CTI';
             pir.getInstitutions();
             pir.search();
             Test.setMock(WebServiceMock.class, new TestMockRetrievePaymentInfo());
             pir.retreiveinfo();
             //RetrievePaymentInfoTest.coverTypes();
               
             PaymentInfo pi = new PaymentInfo();
             pi.trandate = null;
             pi.trantype = null;
             pi.tranamount = null;
             pi.tranbalance = null;
             pi.tranreference = null;
             pi.tranearlybird = null;
             pi.tranregpayment = null;  
             retreivePaymentInfo rpi = new retreivePaymentInfo();
             rpi.getInstitutions();
             rpi.search();  
             RetrievePaymentInfo.PaymentInfoItem pii = new RetrievePaymentInfo.PaymentInfoItem();
             RetrievePaymentInfo.RetrievePaymentInfoResponse rpir = new RetrievePaymentInfo.RetrievePaymentInfoResponse(); 
                           
             Test.stopTest();
         }
       }
}