src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Account_Number__c</fullName>
        <description>CORE - Integration field with Bookmaster</description>
        <externalId>true</externalId>
        <label>External Account Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Describes the Pearson Region that the creator of the Account is assigned to.</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pearson_Account_Number__c</fullName>
        <description>Captures the Pearson &apos;Student Unique Account ID&apos; number (SUID)</description>
        <externalId>true</externalId>
        <label>Pearson Account Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>The following field identifies the Opportunity owner&apos;s geography per their user record</description>
        <formula>TEXT(Owner.Geography__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s User record identified market.</description>
        <formula>TEXT(Owner.Market__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PaymentInfoProxyClass.cls
global class PaymentInfoProxyClass{
    
   webservice static List<PaymentInfo> getPaymentInfo(String learnerId, String institution)
   {
         RetrievePaymentInfo.PaymentInfoItem[] data;
          //Creating List of Opportunity to avoid Exception           
          List<Opportunity> opptyObj = [Select id,Account.Pearson_Account_Number__c,Account.External_Account_Number__c,recordtype.name,Market__c,Geography__c from Opportunity where id =:learnerId];                    
                    
          List<PaymentInfo> paymentLst = new List<PaymentInfo>();
          //Soap Request  for setting request and getting response  
       if(!Test.isRunningTest()) {       
          RetrievePaymentInfo.RetrievePaymentInfoSOAP  soapobj = new  RetrievePaymentInfo.RetrievePaymentInfoSOAP ();
          soapobj.timeout_x=120000;
          soapobj.clientCertName_x= Label.PS_INT_RetreivePayment_CN;
          RetrievePaymentInfo.Header_element   header = new RetrievePaymentInfo.Header_element();
          //Set values to these fields of Request parament
          header.BusinessGeography  = opptyObj[0].Geography__c;
          header.Market  = opptyObj[0].Market__c;
          header.AccountType  = opptyObj[0].recordtype.name;
          header.OrganisationName  =institution;
          //Passing Header and Account Number to get response
          String accountNo ;
          if(opptyObj[0].Account.External_Account_Number__c!='' || opptyObj[0].Account.External_Account_Number__c!=null)
              accountNo =opptyObj[0].Account.External_Account_Number__c;
          else
              accountNo =opptyObj[0].account.Pearson_Account_Number__c; 
          //if(!Test.isRunningTest()) {  
           data = soapobj.RetrievePaymentInfo(header,accountNo);
          system.debug('data----->'+data);
          }
          //Complete of Soap Request and Response
        
         if(data != null)
         {
           for (RetrievePaymentInfo.PaymentInfoItem responseObj: data) {
                PaymentInfo paymentObj = new PaymentInfo();
                paymentObj.trandate = responseObj.TransactionDate;
                paymentObj.trantype = responseObj.TransactionType;
                paymentObj.tranamount = responseObj.TransactionAmount;
                paymentObj.tranbalance = responseObj.AccountBalance;
                paymentObj.tranreference = responseObj.TransactionReference;
                paymentObj.tranearlybird = responseObj.IsEarlyBirdPayment;
                paymentObj.tranregpayment = responseObj.IsRegistrationPayment;
                paymentLst.add(paymentObj);
           }
         }
         return paymentLst;
   }
}