src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Action__c.object
<CustomObject>
    <description>Based component of the Action Framework functionality</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the action</description>
        <inlineHelpText>Description of the action</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Number to represent the order of execution of the action within the template</description>
        <inlineHelpText>Order of execution of the action within the template</inlineHelpText>
        <label>Sequence</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Briefly description of the action</description>
        <inlineHelpText>Briefly description of the action</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Action Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ActionTemplateItem__c.object
<CustomObject>
    <description>Represent the information to use as a templates for the action creation on the Action Framework solution</description>
    <fields>
        <fullName>AssignToType__c</fullName>
        <description>Specify if the action is assigned to a Queue or a User</description>
        <inlineHelpText>Specify if the action is assigned to a Queue or a User</inlineHelpText>
        <label>Assign To Type</label>
        <picklist>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the action</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ParentObjectType__c</fullName>
        <description>Identifies the action parent object type</description>
        <label>Parent Object Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QueueName__c</fullName>
        <description>Name of the queue to assign the action to</description>
        <inlineHelpText>Name of the queue to assign the action to</inlineHelpText>
        <label>Queue Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Number to represent the order of execution of the action</description>
        <label>Sequence</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TemplateName__c</fullName>
        <description>Name of template to identify the business process</description>
        <label>Template Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeToComplete__c</fullName>
        <description>Time in minutes from the creation to complete the action</description>
        <inlineHelpText>Time in minutes from the creation to complete the action</inlineHelpText>
        <label>Time To Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Briefly description of the action</description>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User to assign the action to</description>
        <inlineHelpText>User to assign the action to</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Action_Template_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action Template Item</label>
    <nameField>
        <displayFormat>ATI-{00000}</displayFormat>
        <label>Action Template Item Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Template Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ActionFrameworkPluginTestClass.cls
/*******************************************************************************************************************
* Apex Class Name  : ActionFrameworkPluginTestClass
* Version          : 1.0 
* Created Date     : 19 March 2015
* Function         : Test Class of the ActionFrameworkPlugin Class
* Modification Log :
*
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
*                             19/03/2015              Created Initial Version
*******************************************************************************************************************/
@isTest                   
private class ActionFrameworkPluginTestClass
{
    /*************************************************************************************************************
    * Name        : AccountActionsInsertionTest
    * Description : Verify the insertion of actions related to an account using the Action Framework Plugin    
    * Input       : 
    * Output      : 
    *************************************************************************************************************/
    static testMethod void AccountActionsInsertionTest()
    {
        //Generate an account
        Account acc = new Account(Name = 'Account 1');
        insert acc;
    
        //Generate Action Template Items
        List<ActionTemplateItem__c> ActionTemplateItemsInserted1 = GenerateActionTemplateItems(10, 'Account', 'User', 30,'Template 1');
        List<ActionTemplateItem__c> ActionTemplateItemsInserted2 = GenerateActionTemplateItems(10, 'Account', 'Queue', 30,'Template 1');
        List<ActionTemplateItem__c> ActionTemplateItemsInserted3 = GenerateActionTemplateItems(10, 'Account', '', 30,'Template 1');
        
        List<ActionTemplateItem__c> ActionTemplateItemsInserted = new List<ActionTemplateItem__c>();
        ActionTemplateItemsInserted.addAll(ActionTemplateItemsInserted1);
        ActionTemplateItemsInserted.addAll(ActionTemplateItemsInserted2);
        ActionTemplateItemsInserted.addAll(ActionTemplateItemsInserted3);
        
        // Define Plugin input and output parameters
        ActionFrameworkPlugin actionPlugin = new ActionFrameworkPlugin();
        Map<String,Object> inputParams = new Map<String,Object>();
        Map<String,Object> outputParams = new Map<String,Object>();

        inputParams.put('TemplateName','Template 1');
        inputParams.put('ParentObjectType', 'Account');
        inputParams.put('ParentObjectID', acc.Id);

        // Execute the plugin
        test.startTest();
        Process.PluginRequest request = new Process.PluginRequest(inputParams);
        Process.PluginResult result;
        result = actionPlugin.invoke(request);
        test.stopTest();

        System.debug('ERROR MESSAGE '+result.OutputParameters.get('ResultMessage'));
        
        // Check that the plugin execution is successfull
        System.Assert(Boolean.valueOf(result.OutputParameters.get('ActionsInserted')),true);
        System.assertEquals(String.valueOf(result.OutputParameters.get('ResultMessage')),'Success');
    }  
    
    /*************************************************************************************************************
    * Name        : ContactActionsInsertionTest
    * Description : Verify the insertion of actions related to a contact using the Action Framework Plugin    
    * Input       : 
    * Output      : 
    *************************************************************************************************************/
    static testMethod void ContactActionsInsertionTest()
    {
        //Generate an account
        Account acc = new Account(Name = 'Account 1');
        insert acc;
        
        //Generate contact
        Contact con = new Contact(LastName = 'Contact 1', Email = 'test@test.com.demo', AccountId = acc.Id);
        insert con;
    
        //Generate Action Template Items
        List<ActionTemplateItem__c> ActionTemplateItemsInserted1 = GenerateActionTemplateItems(10, 'Contact', 'User', 30,'Template 1');
        List<ActionTemplateItem__c> ActionTemplateItemsInserted2 = GenerateActionTemplateItems(10, 'Contact', 'Queue', 30,'Template 1');
        
        List<ActionTemplateItem__c> ActionTemplateItemsInserted = new List<ActionTemplateItem__c>();
        ActionTemplateItemsInserted.addAll(ActionTemplateItemsInserted1);
        ActionTemplateItemsInserted.addAll(ActionTemplateItemsInserted2);
        
        // Define Plugin input and output parameters
        ActionFrameworkPlugin actionPlugin = new ActionFrameworkPlugin();
        Map<String,Object> inputParams = new Map<String,Object>();
        Map<String,Object> outputParams = new Map<String,Object>();

        inputParams.put('TemplateName','Template 1');
        inputParams.put('ParentObjectType', 'Contact');
        inputParams.put('ParentObjectID', con.Id);

        // Execute the plugin
        test.startTest();
        Process.PluginRequest request = new Process.PluginRequest(inputParams);
        Process.PluginResult result;
        result = actionPlugin.invoke(request);
        test.stopTest();

        System.debug('ERROR MESSAGE '+result.OutputParameters.get('ResultMessage'));
        
        // Check that the plugin execution is successfull
        System.assertEquals(Boolean.valueOf(result.OutputParameters.get('ActionsInserted')),true);
        System.assertEquals(String.valueOf(result.OutputParameters.get('ResultMessage')),'Success');
    }  
    
    /*************************************************************************************************************
    * Name        : CaseActionsInsertionTest
    * Description : Verify the insertion of actions related to a case using the Action Framework Plugin    
    * Input       : 
    * Output      : 
    *************************************************************************************************************/
    static testMethod void CaseActionsInsertionTest()
    {
        //Generate an account
        Account acc = new Account(Name = 'Account 1');
        insert acc;
        
        //Generate contact
        Contact con = new Contact(LastName = 'Contact 1', Email = 'test@test.com.demo', AccountId = acc.Id);
        insert con;
        
        //Generate case
        Case c = new Case( AccountId = acc.Id, ContactId = con.Id);
        insert c;
    
        //Generate Action Template Items
        List<ActionTemplateItem__c> ActionTemplateItemsInserted1 = GenerateActionTemplateItems(10, 'Case', 'User', 30,'Template 1');
        List<ActionTemplateItem__c> ActionTemplateItemsInserted2 = GenerateActionTemplateItems(10, 'Case', 'Queue', 30,'Template 1');
        
        List<ActionTemplateItem__c> ActionTemplateItemsInserted = new List<ActionTemplateItem__c>();
        ActionTemplateItemsInserted.addAll(ActionTemplateItemsInserted1);
        ActionTemplateItemsInserted.addAll(ActionTemplateItemsInserted2);
        
        // Define Plugin input and output parameters
        ActionFrameworkPlugin actionPlugin = new ActionFrameworkPlugin();
        Map<String,Object> inputParams = new Map<String,Object>();
        Map<String,Object> outputParams = new Map<String,Object>();

        inputParams.put('TemplateName','Template 1');
        inputParams.put('ParentObjectType', 'Case');
        inputParams.put('ParentObjectID', c.Id);

        // Execute the plugin
        test.startTest();
        Process.PluginRequest request = new Process.PluginRequest(inputParams);
        Process.PluginResult result;
        result = actionPlugin.invoke(request);
        test.stopTest();

        System.debug('ERROR MESSAGE '+result.OutputParameters.get('ResultMessage'));
        
        // Check that the plugin execution is successfull
        System.assertEquals(Boolean.valueOf(result.OutputParameters.get('ActionsInserted')),true);
        System.assertEquals(String.valueOf(result.OutputParameters.get('ResultMessage')),'Success');
    }  
    
    /*************************************************************************************************************
    * Name        : LeadActionsInsertionTest
    * Description : Verify the insertion of actions related to a lead using the Action Framework Plugin    
    * Input       : 
    * Output      : 
    *************************************************************************************************************/
    static testMethod void LeadActionsInsertionTest()
    {

        //Generate Lead
        Lead lead = new Lead( Company = 'Account 1', LastName = 'Contact 1');
        insert lead;
    
        //Generate Action Template Items
        List<ActionTemplateItem__c> ActionTemplateItemsInserted1 = GenerateActionTemplateItems(10, 'Lead', 'User', 30,'Template 1');
        List<ActionTemplateItem__c> ActionTemplateItemsInserted2 = GenerateActionTemplateItems(10, 'Lead', 'Queue', 30,'Template 1');
        
        List<ActionTemplateItem__c> ActionTemplateItemsInserted = new List<ActionTemplateItem__c>();
        ActionTemplateItemsInserted.addAll(ActionTemplateItemsInserted1);
        ActionTemplateItemsInserted.addAll(ActionTemplateItemsInserted2);
        
        // Define Plugin input and output parameters
        ActionFrameworkPlugin actionPlugin = new ActionFrameworkPlugin();
        Map<String,Object> inputParams = new Map<String,Object>();
        Map<String,Object> outputParams = new Map<String,Object>();

        inputParams.put('TemplateName','Template 1');
        inputParams.put('ParentObjectType', 'Lead');
        inputParams.put('ParentObjectID', lead.Id);

        // Execute the plugin
        test.startTest();
        Process.PluginRequest request = new Process.PluginRequest(inputParams);
        Process.PluginResult result;
        result = actionPlugin.invoke(request);
        test.stopTest();

        System.debug('ERROR MESSAGE '+result.OutputParameters.get('ResultMessage'));
        
        // Check that the plugin execution is successfull
        System.assertEquals(Boolean.valueOf(result.OutputParameters.get('ActionsInserted')),true);
        System.assertEquals(String.valueOf(result.OutputParameters.get('ResultMessage')),'Success');
    }
    
    /*************************************************************************************************************
    * Name        : OpportunityActionsInsertionTest
    * Description : Verify the insertion of actions related to an opportunity using the Action Framework Plugin    
    * Input       : 
    * Output      : 
    *************************************************************************************************************/
    static testMethod void OpporutniyActionsInsertionTest()
    {
        //Generate an account
        Account acc = new Account(Name = 'Account 1');
        insert acc;
        
        //Generate opportunity
        Opportunity opp = new Opportunity( Name = 'Opportunity', StageName = 'Prospecting', AccountId = acc.Id, CloseDate = System.Today());
        insert opp;
    
        //Generate Action Template Items
        List<ActionTemplateItem__c> ActionTemplateItemsInserted1 = GenerateActionTemplateItems(10, 'Opportunity', 'User', 30,'Template 1');
        List<ActionTemplateItem__c> ActionTemplateItemsInserted2 = GenerateActionTemplateItems(10, 'Opportunity', 'Queue', 30,'Template 1');
        
        List<ActionTemplateItem__c> ActionTemplateItemsInserted = new List<ActionTemplateItem__c>();
        ActionTemplateItemsInserted.addAll(ActionTemplateItemsInserted1);
        ActionTemplateItemsInserted.addAll(ActionTemplateItemsInserted2);
        
        // Define Plugin input and output parameters
        ActionFrameworkPlugin actionPlugin = new ActionFrameworkPlugin();
        Map<String,Object> inputParams = new Map<String,Object>();
        Map<String,Object> outputParams = new Map<String,Object>();

        inputParams.put('TemplateName','Template 1');
        inputParams.put('ParentObjectType', 'Opportunity');
        inputParams.put('ParentObjectID', opp.Id);

        // Execute the plugin
        test.startTest();
        Process.PluginRequest request = new Process.PluginRequest(inputParams);
        Process.PluginResult result;
        result = actionPlugin.invoke(request);
        test.stopTest();

        System.debug('ERROR MESSAGE '+result.OutputParameters.get('ResultMessage'));
        
        // Check that the plugin execution is successfull
        System.assertEquals(Boolean.valueOf(result.OutputParameters.get('ActionsInserted')),true);
        System.assertEquals(String.valueOf(result.OutputParameters.get('ResultMessage')),'Success');
    } 
    
    /*************************************************************************************************************
    * Name        : ErrorActionsInsertionTest
    * Description : Verify the error handle of an insertion of actions related to an account using the Action Framework Plugin    
    * Input       : 
    * Output      : 
    *************************************************************************************************************/
    static testMethod void ErrorActionsInsertionTest()
    {
        //Generate Action Template Items
        List<ActionTemplateItem__c> ActionTemplateItemsInserted1 = GenerateActionTemplateItems(10, 'Opportunity', 'User', 30,'Template 1');
        List<ActionTemplateItem__c> ActionTemplateItemsInserted2 = GenerateActionTemplateItems(10, 'Opportunity', 'Queue', 30,'Template 1');
        
        List<ActionTemplateItem__c> ActionTemplateItemsInserted = new List<ActionTemplateItem__c>();
        ActionTemplateItemsInserted.addAll(ActionTemplateItemsInserted1);
        ActionTemplateItemsInserted.addAll(ActionTemplateItemsInserted2);
        
        // Define Plugin input and output parameters
        ActionFrameworkPlugin actionPlugin = new ActionFrameworkPlugin();
        Map<String,Object> inputParams = new Map<String,Object>();
        Map<String,Object> outputParams = new Map<String,Object>();

        inputParams.put('TemplateName','Template 1');
        inputParams.put('ParentObjectType', 'Opportunity');
        inputParams.put('ParentObjectID', '');

        // Execute the plugin
        test.startTest();
        Process.PluginRequest request = new Process.PluginRequest(inputParams);
        Process.PluginResult result;
        result = actionPlugin.invoke(request);
        test.stopTest();

        System.debug('ERROR MESSAGE '+result.OutputParameters.get('ResultMessage'));
        
        // Check that the plugin execution is successfull
        System.assertEquals(Boolean.valueOf(result.OutputParameters.get('ActionsInserted')), false);
    } 
    
    /*************************************************************************************************************
    * Name        : describeTest
    * Description : Verify the definition of the Action Framework Plugin interface
    * Input       : 
    * Output      : 
    *************************************************************************************************************/
    static testMethod void describeTest() {

        ActionFrameworkPlugin actionPlugin = new ActionFrameworkPlugin();
        
        Process.PluginDescribeResult result = actionPlugin .describe();
        
        System.AssertEquals(result.inputParameters.size(), 3);
        System.AssertEquals(result.OutputParameters.size(), 2);
        System.AssertEquals(result.description ,  'The Action Framework plugin generate action records related with the parent object provided based on the specified action template definition');
        System.AssertEquals(result.tag , 'Action Framework');
        
     }
    
    public static List<ActionTemplateItem__c> GenerateActionTemplateItems(Integer NumberOfActionTemplateItems, String ParentObjectType, String OwnerType, Integer TimeToComplete, String TemplateName)
    {
        List<ActionTemplateItem__c> actTempItemsList = new List<ActionTemplateItem__c>();
        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        
        List<User> ActiveUsers = [SELECT Id FROM User WHERE IsActive = true];
        
        System.runAs (thisUser){
            // Create a Queue
            GenerateQueue('Action__c', 'Queue 1');
            
            for(Integer i=0; i<NumberOfActionTemplateItems; i++)
            {
                ActionTemplateItem__c tempItem = new ActionTemplateItem__c();
                
                tempItem.ParentObjectType__c = ParentObjectType;
                tempItem.TemplateName__c = TemplateName;
                tempItem.Sequence__c = (i+1);
                tempItem.Title__c = 'Title ' + (i+1);
                tempItem.Description__c = 'Description ' + (i+1);
                tempItem.TimeToComplete__c = TimeToComplete;
                
                if(OwnerType == 'User')
                {
                    tempItem.AssignToType__c = OwnerType;
                    tempItem.User__c = ActiveUsers.get(0).Id;
                }
                else if(OwnerType == 'Queue')
                {
                    tempItem.AssignToType__c = OwnerType;
                    tempItem.QueueName__c = 'Queue 1';
                }
                
                actTempItemsList.add(tempItem);
            }
            
            if(actTempItemsList.size()>0){
                insert actTempItemsList;
            }
        }
                
        return actTempItemsList;
    }
    
    public static void GenerateQueue(String ObjectType, String QueueName)
    {
        Group g = new Group(Name=QueueName, Type='Queue');
        insert g;
            
        QueuesObject q = new QueueSObject(QueueID = g.Id, SobjectType = ObjectType);
        insert q;
    }
}