src/objects/AccountContact__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>AccountRole__c</fullName>
        <description>The role the contact plays on this account</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Educator</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE:  The Account linked to the Contact</description>
        <inlineHelpText>The Account linked to the Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>CORE: The Contact linked to the Account</description>
        <inlineHelpText>The Contact linked to the Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Financially_Responsible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Financially responsible=True</description>
        <label>Financially Responsible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <description>CORE: If the linked account on the contact record is the same as the linked record to this junction object the checkbox will be true</description>
        <formula>IF(Contact__r.Account.Id = Account__r.Id, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Indicates if this is the contact&apos;s primary account.</inlineHelpText>
        <label>Primary Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Relevant to D2L Model only. On a Learner account, the Learner is defaulted to the &apos;Primary&apos; on the account. There can only be one &apos;Primary&apos; contact per Learner Account</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Detail__c</fullName>
        <description>Detailed information on the role</description>
        <label>Role Detail</label>
        <picklist>
            <controllingField>AccountRole__c</controllingField>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assc. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asst. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chairman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Learning Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emeritus Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjunct Faculty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visiting Lecturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lab Technician/Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secretary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Synchronized_Account_Contact_Role__c</fullName>
        <label>Synchronized Account Contact Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>AOC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mobile_Last_Updated__c</fullName>
        <description>Used to track when fields were last updated on the mobile app.</description>
        <label>Mobile Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Role_Detail__c</fullName>
        <label>Role Detail</label>
        <picklist>
            <controllingField>Role__c</controllingField>
            <picklistValues>
                <fullName>Adjunct Faculty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assc. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asst. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chairman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Learning Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emeritus Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visiting Lecturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lab Technician/Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secretary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestAccountcontactTriggerhandler.cls
/*
     *@name TestAccountcontactTriggerhandler() 
     *@return void 
     *@description This method for myUnitTest_3 In CLASS AccountcontactTriggerhandler .cls
     *@description This method for myUnitTest_3 In CLASS AccountContactSync .cls
     */

 
@isTest
private class TestAccountcontactTriggerhandler {
                
                    
Static testmethod void myUnitTest_3(){
         TestClassAutomation.FillAllFields = true;
        
        Account sAccount                = (Account)TestClassAutomation.createSObject('Account');
        sAccount.BillingCountry         = 'Australia';
        sAccount.BillingState           = 'Victoria';
        sAccount.BillingCountryCode     = 'AU';
        sAccount.BillingStateCode       = 'VIC';
        sAccount.ShippingCountry        = 'Australia';
        sAccount.ShippingState          = 'Victoria';
        sAccount.ShippingCountryCode    = 'AU';
        sAccount.ShippingStateCode      = 'VIC';
        
        insert sAccount;
        
        Contact sContact                = (Contact)TestClassAutomation.createSObject('Contact');
        sContact.AccountId              = sAccount.Id;
        sContact.OtherCountry           = 'Australia';
        sContact.OtherState             = 'Victoria';
        sContact.OtherCountryCode       = 'AU';
        sContact.OtherStateCode         = 'VIC';
        sContact.MailingCountry         = 'Australia';
        sContact.MailingState           = 'Victoria';
        sContact.MailingCountryCode     = 'AU';
        sContact.MailingStateCode       = 'VIC';
        sContact.Mobile_Last_Updated__c = null;
                    
        Test.startTest();
            
           insert sContact;
       
         AccountContact__c sAccountContact = [Select Id,AccountContact__c.Primary__c  FROM AccountContact__c WHERE Contact__c = : sContact.Id limit 1];
         
       AccountContactTriggerHandler testa= new AccountContactTriggerHandler(true,5);

       AccountContact__c[] accnt;
       
       accnt = [Select Id,AccountContact__c.Primary__c,account__c,contact__c,AccountRole__c,Financially_Responsible__c,Synchronized_Account_Contact_Role__c  FROM AccountContact__c WHERE Contact__c = : sContact.Id limit 1];

       AccountContact__c[] accntol;

       accntol = [Select Id,AccountContact__c.Primary__c,account__c,contact__c,AccountRole__c,Financially_Responsible__c,Synchronized_Account_Contact_Role__c, Primary_Account__c, Role_Detail__c  FROM AccountContact__c WHERE Contact__c = : sContact.Id limit 1];
  
       map<id,AccountContact__c> acc =new map<id,AccountContact__c>();
       map<id,AccountContact__c> acccon =new map<id,AccountContact__c>();
       acccon.put(accntol.get(0).Id, accntol.get(0));
     
           System.assertEquals(true,  testa.bIsTriggerContext);  
           System.assertEquals(false,  testa.bIsVisualforcePageContext,false);   
           System.assertEquals(false, testa.bIsWebServiceContext,false);  
           System.assertEquals(false,  testa.bIsExecuteAnonymousContext,false);  
                  
         testa.OnAfterUpdate(accnt,accntol,acc,acccon);
                  
         testa.OnAfterdelete(accnt,acc);
         testa.OnBeforedelete(accnt,acc);
         testa.OnBeforeUpdate(accnt,accntol,acc);
         testa.OnUndelete(accnt);  
         AccountContactSync sync = new AccountContactSync();
         sync.SetAsNotPrimary(accnt); 
         try
         {
           testa.OnBeforeInsert(null);           
         }
         catch(Exception e)
         {  
           System.assert(e != null, 'The exception was not raised');           
         }
         
         try
         {           
           testa.OnAfterInsert(null);
         }
         catch(Exception e)
         {  
           System.assert(e != null, 'The exception was not raised');           
         }           
               
         Test.stopTest();}
 }