src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Learner</fullName>
        <active>true</active>
        <label>Learner</label>
    </recordTypes>
    <recordTypes>
        <fullName>Organisation</fullName>
        <active>true</active>
        <label>Organisation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AccountContact__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>Academic_Role__c</fullName>
        <description>CORE: Describes role of a contact at an account.</description>
        <inlineHelpText>Describes role of a contact at an account.</inlineHelpText>
        <label>Academic Role</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assc. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookshop Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chairman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deputy Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deputy Head of School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deputy Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Learning Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emeritus Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Subject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lab Technician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Counsel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Librarian</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AccountRole__c</fullName>
        <description>The role the contact plays on this account</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Educator</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to specify which Account is the Contacts Primary Account - updating this field updates the &apos;Account Name&apos;  field on the Contact</description>
        <label>Primary Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE:  The Account linked to the Contact</description>
        <inlineHelpText>The Account linked to the Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>CORE: The Contact linked to the Account</description>
        <inlineHelpText>The Contact linked to the Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Financially_Responsible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Financially responsible=True</description>
        <label>Financially Responsible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Relevant to D2L Model only. On a Learner account, the Learner is defaulted to the &apos;Primary&apos; on the account. There can only be one &apos;Primary&apos; contact per Learner Account</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Detail__c</fullName>
        <description>Detailed information on the role</description>
        <label>Role Detail</label>
        <picklist>
            <controllingField>AccountRole__c</controllingField>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assc. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asst. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chairman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Learning Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emeritus Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjunct Faculty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visiting Lecturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lab Technician/Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secretary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>AOC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role_Detail__c</fullName>
        <label>Role Detail</label>
        <picklist>
            <controllingField>Role__c</controllingField>
            <picklistValues>
                <fullName>Adjunct Faculty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assc. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asst. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chairman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Learning Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emeritus Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visiting Lecturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lab Technician/Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secretary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestprimarycheckonAccountContact.cls
/*******************************************************************************************************************
* Apex Class Name   :TestprimarycheckonAccountContact 
* Created Date      : 6 MAY 2014
* Description       : Test class for primarycheckonAccountContact class
*******************************************************************************************************************/

@isTest  
private class TestprimarycheckonAccountContact{ 
    static testMethod void MyTest() {
    
    List<Account> accountList=TestDataFactory.createAccount(1,'Learner');
    insert accountList;
    
    List<Contact> contactList=TestDataFactory.createContact(2);
    //Madhu Added 
    contactList[0].accountid=accountList[0].id;
    contactList[1].accountid=accountList[0].id;
    insert contactList;

    system.debug('******contactList*******'+contactList.size());
     //List<AccountContact__c> AccountContactList = TestDataFactory.createAccountContact(1,accountList[0].Id,contactList[0].Id); 
    //Madhu added
    List<AccountContact__c> AccountContactList = [select id,Account_Name__c,primary__c,Financially_Responsible__c from AccountContact__c where account__c=:accountList[0].id];
    List<AccountContact__c> lstAccconList=new List<AccountContact__c>();
   /* for(AccountContact__c acc:AccountContactList){
        acc.Account_Name__c=true;
        acc.Financially_Responsible__c = true;
        acc.primary__c=true;
        lstAccconList.add(acc);
    }*/
        if (AccountContactList.size()>0)   {
            system.debug('AccountContactList[0].Financially_Responsible__c'+AccountContactList[0].Financially_Responsible__c);
            system.debug('AccountContactList[0].primary__c'+AccountContactList[0].primary__c);            
            system.debug('AccountContactList[1].Financially_Responsible__c'+AccountContactList[1].Financially_Responsible__c);
            system.debug('AccountContactList[1].primary__c'+AccountContactList[1].primary__c);
            AccountContactList[1].Account_Name__c=true;
            AccountContactList[1].Financially_Responsible__c=false;
            AccountContactList[1].primary__c=false;
        }
        update AccountContactList[1];
      AccountContactList = [select id,Account_Name__c,primary__c,Financially_Responsible__c from AccountContact__c where account__c=:accountList[0].id];
                if (AccountContactList.size()>0)   {
            system.debug('AccountContactList[0].Financially_Responsible__c'+AccountContactList[0].Financially_Responsible__c);
            system.debug('AccountContactList[0].primary__c'+AccountContactList[0].primary__c);            
            system.debug('AccountContactList[1].Financially_Responsible__c'+AccountContactList[1].Financially_Responsible__c);
            system.debug('AccountContactList[1].primary__c'+AccountContactList[1].primary__c);
            AccountContactList[1].Account_Name__c=true;
            AccountContactList[1].Financially_Responsible__c=true;
            AccountContactList[1].primary__c=true;
        }
        update AccountContactList[1];
        system.debug('Calling contact insert again');
     List<Contact> contactListin=TestDataFactory.createContact(3);
      // contactListin[2].accountid= accountList[0].id;
        insert contactListin[2];
     AccountContact__c nacccon=new AccountContact__c(Account__c=accountList[0].id,Contact__c=contactListin[2].id,primary__c=true,
                                                    Financially_Responsible__c=true,AccountRole__c='Learner');   
     insert nacccon;
    //Insert AccountContactList; 
   // checkRecurssionAfter.run =true;
   //update lstAccconList;
    
  // Map<Id, AccountContact__c> previousValuesMap = new Map<Id, AccountContact__c>(lstAccconList); 
             
  /*  List<AccountContact__c> accountcontact = [SELECT Account__c, Contact__c,Role_Detail__c FROM AccountContact__c WHERE Id =:AccountContactList[0].Id]; 
    List <account>Acc1 = TestDataFactory.createAccount(3,'Organisation');
    insert Acc1 ; 
    List<AccountContact__c> Aoc1 =[select Id from accountcontact__c where account__c = : Acc1[0].id];
    insert Aoc1;
    List<AccountContact__c> updateaccountcontact = new List<AccountContact__c>();    
    for(AccountContact__c acc : accountcontact) {
         acc.Primary__c = true;
         acc.Financially_Responsible__c = true;
         acc.Account_Name__c =true;
         if(acc.Account__c == AccountContactList[0].Account__c)
          updateaccountcontact.add(acc);
    }
    Update accountList;
     Update updateaccountcontact;
    primarycheckonAccountContact.updateContact(AccountContactList,accountcontact);*/
     //primarycheckonAccountContact.togglePrimaryAndFinancialFlags(lstAccconList, previousValuesMap);
   
    }
 /*   static testMethod void myUnitTest2()
    {
    TestClassAutomation.FillAllFields = true;
        
        Account sAccount                = (Account)TestClassAutomation.createSObject('Account');
        sAccount.BillingCountry         = 'Australia';
        sAccount.BillingState           = 'Victoria';
        sAccount.BillingCountryCode     = 'AU';
        sAccount.BillingStateCode       = 'VIC';
        sAccount.ShippingCountry        = 'Australia';
        sAccount.ShippingState          = 'Victoria';
        sAccount.ShippingCountryCode    = 'AU';
        sAccount.ShippingStateCode      = 'VIC';
        
        insert sAccount;
        Contact sContact                = (Contact)TestClassAutomation.createSObject('Contact');
        sContact.AccountId              = sAccount.Id;
        sContact.OtherCountry           = 'Australia';
        sContact.OtherState             = 'Victoria';
        sContact.OtherCountryCode       = 'AU';
        sContact.OtherStateCode         = 'VIC';
        sContact.MailingCountry         = 'Australia';
        sContact.MailingState           = 'Victoria';
        sContact.MailingCountryCode     = 'AU';
        sContact.MailingStateCode       = 'VIC';
            
        Test.startTest();
            
            insert sContact;
            
        checkRecurssion.run = true;    
        AccountContact__c accContObj = new AccountContact__c();
        accContObj.Contact__c = sContact.id;
        accContObj.Account__c = sAccount.id;
         accContObj.Primary__c = true;
        accContObj.Academic_Role__c = 'Learner';
        accContObj.Role_Detail__c ='this is a role desc..';
        insert accContObj;
         AccountContact__c sAccountContact  = new AccountContact__c();
         sAccountContact = [Select Id FROM AccountContact__c WHERE Contact__c = : sContact.Id limit 1];
            //checkRecurssion.run = true;       
            sAccountContact.Primary__c = true;
             sAccountContact.Financially_Responsible__c =true;
             sAccountContact.primary__c=true;
             update sAccountContact;
            //checkRecurssion.run = true; 
                        
            delete sAccountContact;
           //checkRecurssion.run = true;    

            undelete sAccountContact;
        
        Test.stopTest();
    }
   Static testmethod void myUnitTest_1(){
         TestClassAutomation.FillAllFields = true;
          Boolean blnInsert =true ; 
        Account sAccount                = (Account)TestClassAutomation.createSObject('Account');
        sAccount.BillingCountry         = 'Australia';
        sAccount.BillingState           = 'Victoria';
        sAccount.BillingCountryCode     = 'AU';
        sAccount.BillingStateCode       = 'VIC';
        sAccount.ShippingCountry        = 'Australia';
        sAccount.ShippingState          = 'Victoria';
        sAccount.ShippingCountryCode    = 'AU';
        sAccount.ShippingStateCode      = 'VIC';
        
        insert sAccount;
        
        Contact sContact                = (Contact)TestClassAutomation.createSObject('Contact');
        sContact.AccountId              = sAccount.Id;
        sContact.OtherCountry           = 'Australia';
        sContact.OtherState             = 'Victoria';
        sContact.OtherCountryCode       = 'AU';
        sContact.OtherStateCode         = 'VIC';
        sContact.MailingCountry         = 'Australia';
        sContact.MailingState           = 'Victoria';
        sContact.MailingCountryCode     = 'AU';
        sContact.MailingStateCode       = 'VIC';
           
        Test.startTest();
        insert sContact; 
           system.debug('id of contact'+scontact.id); 
          
         
         System.assert(true,blnInsert);
      List<AccountContact__c> sAccountContact  = new List<AccountContact__c>();
          sAccountContact = [Select Id FROM AccountContact__c WHERE Contact__c=:sContact.Id limit 1];
        system.debug('sAccountContact/contact'+sAccountContact+'con'+sContact);
         Update  sAccountContact;          
         Test.stopTest();
            
     }  */
    }