src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Global: Used to identify specific type of organisation</description>
        <label>Type</label>
        <picklist>
            <controllingField>Organisation_Type__c</controllingField>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Occupational Skills &amp; Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fire Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Police</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defense Forces</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Court Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comprehensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-Educational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RelatedCourse__c.object
<CustomObject>
    <description>CORE - Junction objected used to capture the relationship between university courses</description>
    <fields>
        <fullName>Course__c</fullName>
        <description>CORE - The primary course we are linking to</description>
        <inlineHelpText>The primary course we are linking to</inlineHelpText>
        <label>Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Related Courses</relationshipLabel>
        <relationshipName>RelatedCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Related_Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>CORE - The related course</description>
        <label>Related Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Related Courses (Related Course)</relationshipLabel>
        <relationshipName>Related_Courses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelationshipClone__c</fullName>
        <description>CORE - Hidden field used in the cloning of the related course</description>
        <label>RelationshipClone</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>CORE</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Partner Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross Campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Related Course</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Related Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Catalog_Code__c</fullName>
        <label>Catalog Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <description>Name of the course at the university or department.</description>
        <inlineHelpText>Name of the course at the university or department.</inlineHelpText>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImportID__c</fullName>
        <externalId>true</externalId>
        <label>ImportID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UniversityCourseAccountComboStrId__c</fullName>
        <description>Stores the combination of the ids of the account &amp; university course.</description>
        <externalId>true</externalId>
        <inlineHelpText>Stores the combination of the ids of the account &amp; university course.</inlineHelpText>
        <label>UniversityCourseAccountComboStrId</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestRelatedCourseTriggers.cls
@isTest
private class TestRelatedCourseTriggers
{
    static testMethod void myUnitTest()
    {
        
        TestClassAutomation.FillAllFields = true;
        
        Account sAccount                = (Account)TestClassAutomation.createSObject('Account');
        sAccount.BillingCountry         = 'Australia';
        sAccount.BillingState           = 'Victoria';
        sAccount.BillingCountryCode     = 'AU';
        sAccount.BillingStateCode       = 'VIC';
        sAccount.ShippingCountry        = 'Australia';
        sAccount.ShippingState          = 'Victoria';
        sAccount.ShippingCountryCode    = 'AU';
        sAccount.ShippingStateCode      = 'VIC';
        
        insert sAccount;
        
        /* UniversityCourse__c sUniversityCourse  = (UniversityCourse__c)TestClassAutomation.createSObject('UniversityCourse__c');
        sUniversityCourse.Account__c  = sAccount.Id;
        insert sUniversityCourse;
        
        UniversityCourse__c sUniversityCourse2   = (UniversityCourse__c)TestClassAutomation.createSObject('UniversityCourse__c');
        sUniversityCourse2.ImportID__c  = 'ubywqruqwe8912';
        sUniversityCourse2.UniversityCourseAccountComboStrId__c  = null;
        sUniversityCourse2.Account__c  = sAccount.Id; 
        insert sUniversityCourse2; */
        
          List<UniversityCourse__c> courselist=new List<UniversityCourse__c>();
      for(integer i=0;i<3;i++){
          UniversityCourse__c course = new UniversityCourse__c();
          course.Name = 'TerritoryCourseNameandcode'+i;
          course.Account__c = sAccount.id;
          course.Catalog_Code__c = 'Territorycoursecode'+i;
          course.Course_Name__c = 'Territorycoursename'+i;
          course.CurrencyIsoCode = 'USD';
          courselist.add(course);
      }

      insert courselist;
        
        Test.startTest();
        
            RelatedCourse__c     sRelatedCourse     = (RelatedCourse__c)TestClassAutomation.createSObject('RelatedCourse__c');
            sRelatedCourse.Course__c                = courselist[0].Id;
            sRelatedCourse.Related_Course__c        = courselist[1].Id;
            sRelatedCourse.RelationshipClone__c     = null;
            
            insert sRelatedCourse;
            
            sRelatedCourse.Type__c  = 'Other';
            
            // update sRelatedCourse;
            
            delete sRelatedCourse;
            
            undelete sRelatedCourse;
        
        Test.stopTest();
    }
}