src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Describes the Pearson Region that the creator of the Account is assigned to.</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Describes the Pearson &apos;Line of Business&apos; the account creator is assigned to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>To which of the Pearson Geographies does this user belong</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The user&apos;s line of business</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PS_Account_RecordTagging_Ctrlr.cls
/* ----------------------------------------------------------------------------------------------------------------------------------------------------------
   Name:            PS_Account_RecordTagging_Ctrlr.cls 
   Description:     On insert/update/ of Account record 
   Date             Version         Author                             Summary of Changes 
   -----------      ----------      -----------------    ---------------------------------------------------------------------------------------------------
  05/2015         1.0               Davi Borges                       Initial Release 
------------------------------------------------------------------------------------------------------------------------------------------------------------ */
public class PS_Account_RecordTagging_Ctrlr
{  
  public static void accountRecordTagging(List<Account> accountUpdateList)
  {

        //List<User> userLst = new List<User>();//Commented for R3

        //Commented for R3 sicne this is not used any more , PS_Utill class is used to get user details
         /*String user_id = UserInfo.getUserId();

         List <User> userdetails = [select Market__c , Line_of_Business__c , Geography__c from User where id =:user_id limit 1];*/
         
         User userRecord = PS_Util.getUserDetail(UserInfo.getUserId());

        // System.debug(userdetails);
       if(userRecord!=null){
           if(userRecord.Market__c != null && userRecord.Line_of_Business__c != null && userRecord.Geography__c != null)
            { 
            for(Account newAcc: accountUpdateList)
            {
                newAcc.Market__c = userRecord.Market__c;
                newAcc.Line_of_Business__c = userRecord.Line_of_Business__c;
                newAcc.Geography__c = userRecord.Geography__c;
            }
                //leadLst.add(newlead);
                
                 //system.debug(newlead);
    
             }
             //Commented for R3 Since there is only blank Elseif
            /* else if(accountUpdateList[0].Market__c != null && accountUpdateList[0].Line_of_Business__c != null && accountUpdateList[0].Geography__c != null )
             {
             }*/
             
             else
             {
                for(Account newAcc: accountUpdateList)
                    newAcc.addError(Label.PS_AccountHandler_Error);
            }
    
             //if(!leadLst.isEmpty())
             //{
                 //update leadLst;
                 
                  //system.debug(leadLst);
            // } 
            
           }          
    }
}