src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Describes the Pearson Region that the creator of the Account is assigned to.</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Describes the Pearson &apos;Line of Business&apos; the account creator is assigned to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Code_s__c</fullName>
        <description>The following field identifies the territor(ies) (via territory code(s)) an account should be assigned to</description>
        <inlineHelpText>Please identify the territory code(s) an account should be assigned to</inlineHelpText>
        <label>Territory Code(s)</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Organisation</fullName>
        <active>true</active>
        <label>Organisation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Identifies the Course for the Asset</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Course is not associated to the Account for this Product in Use.</errorMessage>
            <filterItems>
                <field>UniversityCourse__c.Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Products in Use</relationshipLabel>
        <relationshipName>Products_In_Use</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if Product in Use is Primary for a University Course</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Asset for NA and SA.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>Used to capture the Market of the Contact Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>CTIMGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Field Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Indicates which Market is utilizing this product.</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TU</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Catalog_Code__c</fullName>
        <label>Catalog Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <description>Name of the course at the university or department.</description>
        <inlineHelpText>Name of the course at the university or department.</inlineHelpText>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>To show whether a University Course is Active or Not</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>The business unit the user is assigned to within Pearson</description>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>CTIMGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Field Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <description>To which of the Pearson Geographies does this user belong</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The user&apos;s line of business</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price_List__c</fullName>
        <description>Associated Price List, Sales Force</description>
        <label>Price List</label>
        <picklist>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Humanities &amp; Social Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Math &amp; Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional &amp; Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US HE All</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PS_assetTriggerTest.cls
@isTest
public class PS_assetTriggerTest
{
     

    @isTest static void myTest1(){
    
    
         Profile pfile = [Select Id,name from profile where name = 'System Administrator'];
     
      //code for creating an User
      User u = new User();
      u.LastName = 'territoryuser';
      u.alias = 'terrusr'; 
      u.Email = 'territoryuser@gmail.com';  
      u.Username='territoryuser@gmail.com';
      u.LanguageLocaleKey='en_US'; 
      u.TimeZoneSidKey='America/New_York';
      u.Price_List__c='Humanities & Social Science';
      u.LocaleSidKey='en_US';
      u.EmailEncodingKey='ISO-8859-1';
      u.ProfileId = pfile.id;       // '00eg0000000M99E';    currently hardcoded  for admin         
      u.Geography__c = 'Growth';
      u.Market__c = 'US';
      u.Business_Unit__c = 'US Field Sales';
      u.Line_of_Business__c = 'Higher Ed';
      u.isactive=true;
      u.CurrencyIsoCode='USD';
      insert u;       
             
        
      System.runAs(u){
      
       List<Account> Acc = TestDataFactory.createAccount(1, 'Organisation');
       Acc[0].Territory_Code_s__c = '2ZZ'; 
       Acc[0].Market__c = 'US'; 
       Acc[0].Line_of_Business__c = 'Higher Ed'; 
       Acc[0].Geography__c = 'Growth'; 
       insert Acc; 
          //code for creating course
      List<UniversityCourse__c> courselist=new List<UniversityCourse__c>();
      for(integer i=0;i<1;i++){
          UniversityCourse__c course = new UniversityCourse__c();
          course.Name = 'TerritoryCourseNameandcode'+i;
          course.Account__c = Acc[0].id;
          course.Catalog_Code__c = 'Territorycoursecode'+i;
          course.Course_Name__c = 'Territorycoursename'+i;
          course.CurrencyIsoCode = 'USD';
          courselist.add(course);
      }
      insert courselist;
      List<Contact> contactList=TestDataFactory.createContact(1);
      insert contactList;
      Product2 pf = TestDataFactory.insertRelatedProducts();
      List<Product2> rp = [select id,name from Product2 where id in (select Apttus_Config2__RelatedProductId__c  from
        Apttus_Config2__RelatedProduct__c where Apttus_Config2__ProductId__c = :pf.id and Apttus_Config2__RelatedProductId__r.name like 'NA Territory%')];      
      test.StartTest();
     List<Asset> asstlist=new List<Asset>();
      for(integer i=0;i<2;i++){
        Asset asset = new Asset();
       asset.name = 'TerritoryAsset'+i;
       asset.Product2Id = rp[0].id;
       asset.AccountId = Acc[0].id;
       asset.Course__c = courselist[0].id;
       asset.Primary__c = True;
       asset.Status__c = 'Active';
       asset.ContactId = contactList[0].Id;
       asstlist.add(asset);
      } 
      insert asstlist;
     
     asstlist[0].Quantity = 1;
     update asstlist[0];
       test.stopTest();
       }
      
      
     
    }
    
}