src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Learner</fullName>
        <active>true</active>
        <label>Learner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AccountContact__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE:  The Account linked to the Contact</description>
        <inlineHelpText>The Account linked to the Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Financially_Responsible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Financially responsible=True</description>
        <label>Financially Responsible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Relevant to D2L Model only. On a Learner account, the Learner is defaulted to the &apos;Primary&apos; on the account. There can only be one &apos;Primary&apos; contact per Learner Account</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_In_Progress__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a hidden field and is used to flag records that are being updated by the trigger to avoid firing the financial responsible person and primary contact validations. The field is used to prevent the trigger from firing an error when it is un-checking related records when the user sets a new primary or FS contact</description>
        <label>Sync In Progress</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>AOC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AccountContact_Primary_Financial.cls
public class AccountContact_Primary_Financial {
    
    public static void checkPrimaryAndFinancialFlags(List<AccountContact__c> triggeredAccountcontacts) {
        List<ID> accountRecordIDs = new List<ID>();
        List<AccountContact__c> relatedAccountContactRecords = new List<AccountContact__c>();
                
        // Build the related account list
        for(AccountContact__c ac : triggeredAccountcontacts) { 
            accountRecordIDs.add(ac.Account__c);
        } // End for
        
        // Retrieve the related accounts contact records
        if (!accountRecordIDs.isEmpty())
            relatedAccountContactRecords = [SELECT Id, Account__c, Account__r.RecordTypeId, Financially_Responsible__c, Primary__c 
                                            FROM AccountContact__c WHERE Account__c IN :accountRecordIDs];
            //Get RecordType Id for Learner Account Type                                
            Id learnerRTId = [SELECT Id from RecordType WHERE sObjectType='Account' AND Name='Learner'].Id;                                 
        
        // RD-00287
        // - An account contact must have at least 1 financially responsible contact, if not raise error
        // - An account contact must have at least 1 primary contact, if not raise error
        
        // Iterate through the triggered account contact records and check the field values based on the following business logic
        for(AccountContact__c ac : triggeredAccountcontacts) { 
            // Check for primary account contacts
            if (!ac.Primary__c && !ac.Sync_In_Progress__c ) {
              if (numberOfOtherPrimaryAccountContacts(relatedAccountContactRecords, ac.Account__c, ac.Id) == 0 && ac.Account__r.RecordTypeId==learnerRTId ) {
                     // Ignore validation if there are no other records to allow the user to create an account contact for the first time
                     if (relatedAccountContactRecords.size() > 1)
                         ac.Primary__c.addError(Label.AC001_Primary_Contact_Error);
                }
            }
            // Check for FS account contacts
            if (!ac.Financially_Responsible__c && !ac.Sync_In_Progress__c ) {
                if (numberOfOtherFSAccountContacts(relatedAccountContactRecords, ac.Account__c, ac.Id) == 0 && ac.Account__r.RecordTypeId==learnerRTId) {
                    // Ignore validation if there are no other records to allow the user to create an account contact for the first time
                    if (relatedAccountContactRecords.size() > 1)
                        ac.Financially_Responsible__c.addError(Label.AC001_Financial_Responsible_Person_Error);
                }
            }
            // Reset the account sync flag
            ac.Sync_In_Progress__c = FALSE;
        } // End for
        
    }
    
    private static Integer numberOfOtherFSAccountContacts(List<AccountContact__c> relatedAccountContactRecords,
                                                                    String strAccountID,
                                                                                     String strTriggeredAccountContactID) {
        Integer intCount = 0;
        
        for (AccountContact__c rac : relatedAccountContactRecords) {
            if (rac.Account__c == strAccountID) {
                if (rac.Id != strTriggeredAccountContactID && rac.Financially_Responsible__c)
                    intCount++;
            }
        } // End for
            
        return intCount;
    }
    
    
    private static Integer numberOfOtherPrimaryAccountContacts(List<AccountContact__c> relatedAccountContactRecords,
                                                                    String strAccountID,
                                                                                     String strTriggeredAccountContactID) {
        Integer intCount = 0;
        
        for (AccountContact__c rac : relatedAccountContactRecords) {
            if (rac.Account__c == strAccountID) {
                if (rac.Id != strTriggeredAccountContactID && rac.Primary__c)
                    intCount++;
            }
        } // End for
            
        return intCount;
    }
    
}