src/objects/AccountContact__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE:  The Account linked to the Contact</description>
        <inlineHelpText>The Account linked to the Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>CORE: The Contact linked to the Account</description>
        <inlineHelpText>The Contact linked to the Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Financially_Responsible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Financially responsible=True</description>
        <label>Financially Responsible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Relevant to D2L Model only. On a Learner account, the Learner is defaulted to the &apos;Primary&apos; on the account. There can only be one &apos;Primary&apos; contact per Learner Account</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>AOC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Mass_Opportunity_Generation_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The following field identifies whether the opportunity was created using the mass opportunity generation functionality</description>
        <label>Generated from Potential Targets</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PS_opportunity_MapAccountcontactRole.cls
/*--------------------------------------------------------------------------------------------------------------------------------------------------------
   Name:            PS_opportunity_MapAccountcontactRole.cls 
   Description:    MapAccountcontactRole 
   
   Date             Version         Author                             Summary of Changes 
   -----------      ----------      -----------------    ---------------------------------------------------------------------------------------------------                 
  04/2015            1.0             karthik.A.S                         Initial Release 
----------------- ------------------------------------------------------------------------------------------------------------------------------------------- */

public without sharing class PS_opportunity_MapAccountcontactRole{

public static void MapAccountcontactRole(list<Opportunity> oppty)
{
  List<opportunity> opp=[select Id ,AccountId from opportunity where id in:oppty and Mass_Opportunity_Generation_Indicator__c=false]; 
    
  List<AccountContact__c> acc = new List<AccountContact__c>();
  
  List<OpportunityContactRole> ContactRoles = new List<OpportunityContactRole>();
  
  Map<Id,Id> accountopptyIds = new Map<Id,Id>();
  
  
  for(Opportunity o:opp){

    accountopptyIds.put(o.AccountId,o.Id);
  }
  
  acc = [SELECT Contact__c,Account__c,Primary__c,Financially_Responsible__c from AccountContact__c where Account__c IN: accountopptyIds.keySet()];
 
  for(AccountContact__c a:acc){
   
   OpportunityContactRole oc = new OpportunityContactRole();
   oc.ContactId = a.Contact__c;
   oc.opportunityId = accountopptyIds.get(a.Account__c);
   oc.IsPrimary = a.Primary__c;
   
   system.debug('oc.IsPrimary..'+oc.IsPrimary);
   system.debug('a.IsPrimary..'+a.Primary__c);

   if(a.Financially_Responsible__c) oc.Role = 'Primary Sales Contact';

   if(a.Primary__c) oc.Role = 'Business User';

   ContactRoles.add(oc);

   system.debug('ContactRoles..' + ContactRoles);
  }
 
  for(OpportunityContactRole ocr :ContactRoles ){
     system.debug('ocr.isprimary : '+ocr.IsPrimary);
  
  }
 
  if(ContactRoles.size()>0){

    List<OpportunityContactRole> oldContactRoles = [SELECT Id FROM OpportunityContactRole WHERE opportunityId IN: accountopptyIds.values()];

    if(oldContactRoles !=null && oldContactRoles.size() >0 ) delete oldContactRoles;

    Insert ContactRoles;
     
    system.debug('ContactRoles1...'+ContactRoles);
  }
  

}

}