src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Vista_Account_Number__c</fullName>
        <description>CORE Integration field - Unique ID in the VISTA system.</description>
        <inlineHelpText>Unique ID in the Socrates system.</inlineHelpText>
        <label>Vista Account Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Bookstore</fullName>
        <active>true</active>
        <description>Core: Captures Bookstore accounts from Bookmaster</description>
        <label>Bookstore</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UniversityCourseContact__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Contains the relationship between Unversity course and contact.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>This is the contact linked to the course.</description>
        <inlineHelpText>This is the contact linked to the course.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Contacts</relationshipLabel>
        <relationshipName>CourseContact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UniversityCourse__c</fullName>
        <description>This is the university course.</description>
        <inlineHelpText>This is the university course.</inlineHelpText>
        <label>Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Course Contacts</relationshipLabel>
        <relationshipName>University_Course_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Course Contact</label>
    <nameField>
        <displayFormat>CRSCT-{00000}</displayFormat>
        <label>Course Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestUniversityCourseContactDupInsert.cls
@isTest
private class TestUniversityCourseContactDupInsert {

    public static testMethod void myUnitTest() {
    
        Test.startTest();
        String AcctRecordTypeId;
        String ContactRecordTypeId;
        String DiscRecordTypeId;
        String ClusterRecordTypeId;
        String OptyRecordTypeId;                        
        
        List<RecordType> RecordTypeList = new List<RecordType>([select Id,Name from RecordType]);
        
        for (RecordType i : RecordTypeList) {
          if (i.Name == 'Bookstore') {
            AcctRecordTypeId = i.Id;
          }
          if (i.Name == 'Contact') {
             ContactRecordTypeId = i.Id;
          }
          
          if (i.Name == '3) Discipline') {
            DiscRecordTypeId = i.Id;
          }
          if (i.Name == '2) Cluster') {
            ClusterRecordTypeId = i.Id;
          }
          if (i.Name == 'Opportunity') {
            OptyRecordTypeId = i.Id;
          }                    
        }        
        Account bkshop1  = new Account (name = 'Test Bookshop1', BillingStreet = 'Street1',
                   BillingCity = 'Sydney', BillingPostalCode = 'ABC DEF', BillingCountry = 'Australia',
                    //Vista_Account_Number__c = 'xyz',
                    RecordTypeId= AcctRecordTypeId );
        insert bkshop1;
        
        Account bkshop2  = new Account (name = 'Test Bookshop2', BillingStreet = 'Street2',
                   BillingCity = 'London', BillingPostalCode = 'ABC DEF', BillingCountry = 'Australia',
                   //Vista_Account_Number__c = 'xyz1',
                   RecordTypeId = AcctRecordTypeId );
        insert bkshop2;
        
        Contact ct1 = new Contact (Firstname = 'TestF1', LastName = 'TestL1', AccountId = bkshop1.Id,email='test@test.com',
                        RecordTypeId=ContactRecordTypeId );
        insert ct1;
        
        UniversityCourse__c UC1 = new UniversityCourse__c (name = 'TestUC1', Account__c = bkshop1.Id);
        insert UC1;
        
        //check inserted value        
        UniversityCourseContact__c UCT1 = new UniversityCourseContact__c (UniversityCourse__c = UC1.Id, Contact__c = ct1.Id);
        insert UCT1;

        //UniversityCourseContact__c UCT2 = new UniversityCourseContact__c (UniversityCourse__c = UC1.Id, Contact__c = ct1.Id);
        //insert UCT2;        
        //System.assertEquals(prod.Bookshop_Quantity__c, 25);

                        
        Test.stopTest();        
    }
}