src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Describes the Pearson Region that the creator of the Account is assigned to.</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Describes the Pearson &apos;Line of Business&apos; the account creator is assigned to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Organisation_Type__c</fullName>
        <description>Identifies the type of organisation the Account record is e.g. School/Higher Education etc</description>
        <label>Organisation</label>
        <picklist>
            <picklistValues>
                <fullName>Government/Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Higher Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NGO/ Association</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institution</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>School</fullName>
        <active>true</active>
        <description>Core: Captures School accounts from Bookmaster</description>
        <label>School</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Identifies the Course for the Asset</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Course is not associated to the Account for this Product in Use.</errorMessage>
            <filterItems>
                <field>UniversityCourse__c.Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Products in Use</relationshipLabel>
        <relationshipName>Products_In_Use</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Product in Use</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <picklist>
            <picklistValues>
                <fullName>Pearson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wiley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>McGraw-Hill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cengage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palgrave/Macmillan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oxford University Press</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elsevier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lipincott</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scholastic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>The following field identifies the Opportunity owner&apos;s geography per their user record</description>
        <formula>TEXT(Owner.Geography__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s Line of Business per their user record</description>
        <formula>TEXT(Owner.Line_of_Business__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line of Business</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity_Pearson_Course_Code__c.object
<CustomObject>
    <description>Junction linking Opportunities with Category Hierarchy (Pearson Course Equivalent)</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Pearson_Course_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Pearson_Course_Code_Name__c</fullName>
        <description>This is the Pearson course code .</description>
        <inlineHelpText>This is the Pearson course code.</inlineHelpText>
        <label>Pearson Course Code Name</label>
        <referenceTo>Apttus_Config2__ClassificationHierarchy__c</referenceTo>
        <relationshipName>Opportunity_Pearson_Course_Codes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pearson Course Equivalent</label>
    <nameField>
        <displayFormat>OPC-{00000}</displayFormat>
        <label>Opportunity Pearson Course Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pearson Course Equivalents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pearson_Course_Equivalent__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Identifies if the association between the  Course and the Pearson Course Code is Active.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <description>This contains the Course.</description>
        <inlineHelpText>This contains the Course.</inlineHelpText>
        <label>Course/Catalog Code</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Pearson Course Equivalent</relationshipLabel>
        <relationshipName>Pearson_Course_Equivalent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Pearson_Course_Code__c</fullName>
        <description>This contains the Pearson Course Code.</description>
        <inlineHelpText>This contains the Pearson Course Code.</inlineHelpText>
        <label>Pearson Course Code</label>
        <referenceTo>Apttus_Config2__ClassificationHierarchy__c</referenceTo>
        <relationshipLabel>Pearson Course Equivalent</relationshipLabel>
        <relationshipName>Pearson_Course_Equivalent</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Pearson Course Equivalent</label>
    <nameField>
        <displayFormat>CPCS-{000000}</displayFormat>
        <label>Pearson Course Equivalent	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pearson Course Equivalent</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_Edition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Edition</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Next Edition)</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To show whether a University Course is Active or Not</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Catalog_Code__c</fullName>
        <label>Catalog Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <description>Name of the course at the university or department.</description>
        <inlineHelpText>Name of the course at the university or department.</inlineHelpText>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fall_Enrollment__c</fullName>
        <description>Course enrollment for the fall semester.</description>
        <inlineHelpText>Course enrollment for the fall semester.</inlineHelpText>
        <label>Fall</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UniversityCourseContact__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Contains the relationship between Unversity course and contact.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Active identifies if the contact is involved and has a role related to the course</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>This is the contact linked to the course.</description>
        <inlineHelpText>This is the contact linked to the course.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Contacts</relationshipLabel>
        <relationshipName>CourseContact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UniversityCourse__c</fullName>
        <description>This is the university course.</description>
        <inlineHelpText>This is the university course.</inlineHelpText>
        <label>Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Course Contacts</relationshipLabel>
        <relationshipName>University_Course_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Course Contact</label>
    <nameField>
        <displayFormat>CRSCT-{00000}</displayFormat>
        <label>Course Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateOpportunityfromCoursetest.cls
@istest(seealldata =true)
private class CreateOpportunityfromCoursetest{
static testmethod void constructorTest() {
try{
Test.startTest();
       
       

        Account acc = new Account(Name = 'AccTest1',Line_of_Business__c='Schools',CurrencyIsoCode='GBP',Geography__c = 'Growth',Organisation_Type__c = 'Higher Education',Type = 'School');
        insert acc;
        
        Contact con = new Contact(FirstName='karthik',LastName ='A.S',Phone='9999888898',Email='test@gmail.com', AccountId = acc.Id);
        insert con;
        UniversityCourse__c UnivCourse =new UniversityCourse__c(Name='testcourse',Account__c= acc.id,Catalog_Code__c='testcode',Course_Name__c='testcoursename',CurrencyIsoCode='GBP',Active__c=true,Fall_Enrollment__c=10);
        insert UnivCourse;
       
         opportunity ld = new opportunity(Name='Test', StageName='Needs Analysis', CloseDate=system.today());         
        insert ld;
        

        system.debug('@@date'+date.today());
       UniversityCourseContact__c uni = new UniversityCourseContact__c(UniversityCourse__c=UnivCourse.id,Contact__c = con.Id);
         insert uni;
   
 

CreateOpportunityfromCourse testnew = new CreateOpportunityfromCourse();

 //testnew.createOppty();
 
 
PageReference createOppty = new pagereference('apex/CreateOpportunityfromCourse');

                        id courseid=  UnivCourse.id;
                        id ldid= ld.id;
                       system.debug('$$$$courseid'+UnivCourse.id);
                        Test.setCurrentPage(createOppty);
                        createOppty.getParameters().put('id', courseid);
                        createOppty.getParameters().put('command', 'Opportunitycreate');
                       
                        createOppty.getParameters().put('command', 'CreateOpportunityUniversityCourse');
                        

                        createOppty.getParameters().put('opptyid', ldid);
                   ApexPages.StandardController sc = new ApexPages.standardController(UnivCourse);
          CreateOpportunityfromCourse testnew1 = new CreateOpportunityfromCourse();
        
 CreateOpportunityfromCourse testnew2 = new CreateOpportunityfromCourse();      
  CreateOpportunityfromCourse testnew3 = new CreateOpportunityfromCourse();             
 testnew1.onLoad_CourseOpptyEdit();
  Apttus_Config2__ClassificationName__c category = new Apttus_Config2__ClassificationName__c(Name='testcategoryy',Apttus_Config2__HierarchyLabel__c='testlabele');
 insert category;
 
 Apttus_Config2__ClassificationHierarchy__c catre= new Apttus_Config2__ClassificationHierarchy__c(Name ='testcategory',Apttus_Config2__HierarchyId__c=category.id,Apttus_Config2__Label__c='testlabel');
  
insert catre;
List<Opportunity_Pearson_Course_Code__c> opppearson =new List<Opportunity_Pearson_Course_Code__c>();
Opportunity_Pearson_Course_Code__c opppearsonitem =new Opportunity_Pearson_Course_Code__c();

for(integer i=0;i<3;i++)
{
opppearsonitem.Opportunity__c =ld.id;
opppearsonitem.Pearson_Course_Code_Name__c=catre.id;
opppearson.add(opppearsonitem);
}
insert opppearson;
Apttus_Config2__ClassificationHierarchy__c csa =new Apttus_Config2__ClassificationHierarchy__c(name ='estt',Apttus_Config2__HierarchyId__c=category.id,Apttus_Config2__Label__c='testlabel');
insert csa; 
List<Pearson_Course_Equivalent__c> perasoncourese = new List<Pearson_Course_Equivalent__c>();
Pearson_Course_Equivalent__c perasoncoureseitem = new Pearson_Course_Equivalent__c();
for(integer i=0;i<3;i++)
{
perasoncoureseitem = new Pearson_Course_Equivalent__c();
perasoncoureseitem.Pearson_Course_Code__c = csa.id;
perasoncoureseitem.Course__c=UnivCourse.id;
perasoncourese.add(perasoncoureseitem);
}
insert perasoncourese;
system.debug('perasoncourese'+perasoncourese);
//Pearson_Course_Equivalent__c perasoncouresee = new Pearson_Course_Equivalent__c(Pearson_Course_Code__c = csa.id,Course__c=UnivCourse.id);
//insert perasoncouresee ;
product2 produ= new product2(name ='testproduct',Next_Edition__c=null,Publisher__c='Pearson'/*,Relevance__c[0]=10Date.today()*/);
insert produ;
asset asse = new asset(name ='test asset',AccountId = acc.Id,Contactid = con.id ,Course__c=UnivCourse.id,/*IsCompetitorProduct=true,*/product2=produ);
 insert asse;
 


system.debug('$$$$asse'+asse);
      system.debug('$$$$produ'+produ);           
 system.debug('$$$$courseid'+courseid);
                   system.debug('$$$$UnivCourse'+UnivCourse);
         system.debug('$$$$createOppty'+createOppty);
         system.debug('$$$$ldid'+ldid);

createOppty.getParameters().put( 'id' , opppearson[0].id);
 testnew1.today_date = system.today();

testnew1.Fall_start_date = system.today()-1;
testnew1.Fall_end_date = system.today()+1;
  testnew1.Spring_start_date = system.today();
  testnew1.Spring_end_date = system.today();
  System.debug(testnew1.Fall_end_date);
  System.debug(testnew1.Spring_end_date);
  
// testnew2.createOppty();

testnew1.createOppty();
//testnew2.onLoad_CourseOpptyEdit(); 
   //testnew2.CreateOpportunityUniversityCourse(); 
testnew.CreateOpportunityUniversityCourse();
testnew.DeleteOppty();

 testnew.CreatePearsonCourse();
 
 Test.stopTest();}
 catch(Exception e){return ;}
}         
   static testmethod void constructorTest1() {
try{Test.startTest();
      Account acc = new Account(Name = 'AccTest1',Line_of_Business__c='Schools',CurrencyIsoCode=null,Geography__c = 'Growth',Organisation_Type__c = 'Higher Education',Type = 'School');
        insert acc;
        
        Contact con = new Contact(FirstName='karthik',LastName ='A.S',Phone='9999888898',Email='test@gmail.com', AccountId = acc.Id);
        insert con;
        UniversityCourse__c UnivCourse =new UniversityCourse__c(Name='testcourse',Account__c= acc.id,Catalog_Code__c='testcode',Course_Name__c='testcoursename',CurrencyIsoCode='GBP',Active__c=true);
        insert UnivCourse;
       
         opportunity ld = new opportunity(Name='Test', StageName='Needs Analysis', CloseDate=Date.newInstance(2015,04,15));
        insert ld;
        
       

CreateOpportunityfromCourse testnew = new CreateOpportunityfromCourse();
testnew.onLoad_CourseOpptyEdit ();
 //testnew.createOppty();
 
 
PageReference createOppty = new pagereference('apex/CreateOpportunityfromCourse');

                        id courseid=  UnivCourse.id;
                        id ldid= ld.id;
                       system.debug('$$$$courseid'+UnivCourse.id);
                        Test.setCurrentPage(createOppty);
                        createOppty.getParameters().put('id', courseid);
                        createOppty.getParameters().put('command', 'Opportunitycreate');
                       
                                               
                        createOppty.getParameters().put('opptyid', ldid);
                   //ApexPages.StandardController sc = new ApexPages.standardController(UnivCourse);
          CreateOpportunityfromCourse testnew1 = new CreateOpportunityfromCourse();
          
 CreateOpportunityfromCourse testnew2 = new CreateOpportunityfromCourse();      
  CreateOpportunityfromCourse testnew3 = new CreateOpportunityfromCourse();             
 testnew1.onLoad_CourseOpptyEdit();
  date today_date = system.today();
date Spring_start_date=system.today()-1;
date Spring_end_date=system.today()+1; 
 // testnew1.Fall_start_date;
 testnew1.today_date = system.today();

testnew1.Fall_start_date = system.today()-1;
testnew1.Fall_end_date = system.today()+1;
  testnew1.Spring_start_date = system.today();
  testnew1.Spring_end_date = system.today();
  System.debug(testnew1.Fall_end_date);
  System.debug(testnew1.Spring_end_date);
  
// testnew2.createOppty();

testnew1.createOppty();
 //opportunity ldd = new opportunity(Name='Test', StageName='Needs Analysis', CloseDate=Date.newInstance(2015,04,15));
       // update ldd;

 

Test.stopTest();}
catch(exception e){return ;}
  }   
   static testmethod void constructorTest2() {
try{Test.startTest();
        Account acc = new Account(Name = 'AccTest1',Line_of_Business__c='Schools',CurrencyIsoCode='GBP',Geography__c = 'Growth',Organisation_Type__c = 'Higher Education',Type = 'School');
        insert acc;
        
        Contact con = new Contact(FirstName='karthik',LastName ='A.S',Phone='9999888898',Email='test@gmail.com', AccountId = acc.Id);
        insert con;
        UniversityCourse__c UnivCourse =new UniversityCourse__c(Name='testcourse',Account__c= acc.id,Catalog_Code__c='testcode',Course_Name__c='testcoursename',CurrencyIsoCode='GBP',Active__c=true);
        insert UnivCourse;
       
         opportunity ld = new opportunity(Name='Test', StageName='Needs Analysis', CloseDate=Date.newInstance(2015,04,15));

        insert ld;
        
       UniversityCourseContact__c uni = new UniversityCourseContact__c(UniversityCourse__c=UnivCourse.id,Contact__c = con.Id);
         insert uni;
   

CreateOpportunityfromCourse testnew = new CreateOpportunityfromCourse();
testnew.onLoad_CourseOpptyEdit ();
 //testnew.createOppty();
 date today_date = system.today();
date Spring_start_date=system.today()+1;
date Spring_end_date=system.today()-1; 
 
PageReference createOppty = new pagereference('apex/CreateOpportunityfromCourse');

                        id courseid=  UnivCourse.id;
                        id ldid= ld.id;
                       system.debug('$$$$courseid'+UnivCourse.id);
                        Test.setCurrentPage(createOppty);
                        createOppty.getParameters().put('id', courseid);
                        createOppty.getParameters().put('command', 'CreatePearsonCourse');
                       
                                               
                        createOppty.getParameters().put('opptyid', ldid);
                   //ApexPages.StandardController sc = new ApexPages.standardController(UnivCourse);
          CreateOpportunityfromCourse testnew1 = new CreateOpportunityfromCourse();
          
 CreateOpportunityfromCourse testnew2 = new CreateOpportunityfromCourse();      
  CreateOpportunityfromCourse testnew3 = new CreateOpportunityfromCourse();             
 testnew1.onLoad_CourseOpptyEdit();
Apttus_Config2__ClassificationName__c category = new Apttus_Config2__ClassificationName__c(Name='testcategoryy',Apttus_Config2__HierarchyLabel__c='testlabele');
 insert category;
 
 Apttus_Config2__ClassificationHierarchy__c catre= new Apttus_Config2__ClassificationHierarchy__c(Name ='testcategory',Apttus_Config2__HierarchyId__c=category.id,Apttus_Config2__Label__c='testlabel');
  
insert catre;
Opportunity_Pearson_Course_Code__c opppearson =new Opportunity_Pearson_Course_Code__c(Opportunity__c =ld.id,Pearson_Course_Code_Name__c=catre.id);
insert opppearson;
Apttus_Config2__ClassificationHierarchy__c csa =new Apttus_Config2__ClassificationHierarchy__c(name ='estt',Apttus_Config2__HierarchyId__c=category.id,Apttus_Config2__Label__c='testlabel');
insert csa; 
Pearson_Course_Equivalent__c perasoncourese = new Pearson_Course_Equivalent__c(Pearson_Course_Code__c = csa.id,Course__c=UnivCourse.id);
insert perasoncourese ;
product2 produ= new product2(name ='testproduct',Next_Edition__c=null,Publisher__c='Pearson');//,Relevance__c=Date.today());
insert produ;
asset asse = new asset(name ='test asset',AccountId = acc.Id,Contactid = con.id ,Course__c=UnivCourse.id,IsCompetitorProduct=true,product2=produ);
 insert asse;

system.debug('$$$$asse'+asse);
      system.debug('$$$$produ'+produ);           
 system.debug('$$$$courseid'+courseid);
                   system.debug('$$$$UnivCourse'+UnivCourse);
         system.debug('$$$$createOppty'+createOppty);
         system.debug('$$$$ldid'+ldid);

createOppty.getParameters().put( 'id' ,opppearson.id);
 
 //testnew2.createOppty();
 testnew1.today_date = system.today();

testnew1.Fall_start_date = system.today()-1;
testnew1.Fall_end_date = system.today()+1;
  testnew1.Spring_start_date = system.today();
  testnew1.Spring_end_date = system.today();
  System.debug(testnew1.Fall_end_date);
  System.debug(testnew1.Spring_end_date);
  
// testnew2.createOppty();

testnew1.createOppty();

Test.stopTest();}
catch(exception e){ return ;} 
  }      
    static testmethod void constructorTest3() {
try{Test.startTest();

         Account acc = new Account(Name = 'AccTest1',Line_of_Business__c='Schools',CurrencyIsoCode='GBP',Geography__c = 'Growth',Organisation_Type__c = 'Higher Education',Type = 'School');
        insert acc;
        
        Contact con = new Contact(FirstName='karthik',LastName ='A.S',Phone='9999888898',Email='test@gmail.com', AccountId = acc.Id);
        insert con;
        UniversityCourse__c UnivCourse =new UniversityCourse__c(Name='testcourse',Account__c= acc.id,Catalog_Code__c='testcode',Course_Name__c='testcoursename',CurrencyIsoCode='GBP',Active__c=true);
        insert UnivCourse;
       
         opportunity ld = new opportunity(Name='Test', StageName='Needs Analysis', CloseDate=Date.newInstance(2015,04,15),Fall__c=10,Spring__c=10, Winter__c=10, Summer__c=10);

        insert ld;
        system.debug('@@@@ld'+ld);
       UniversityCourseContact__c uni = new UniversityCourseContact__c(UniversityCourse__c=UnivCourse.id,Contact__c = con.Id);
         insert uni;

CreateOpportunityfromCourse testnew = new CreateOpportunityfromCourse();
testnew.onLoad_CourseOpptyEdit ();
 //testnew.createOppty();

 
 
PageReference createOppty = new pagereference('apex/CreateOpportunityfromCourse');

                        id courseid=  UnivCourse.id;
                        id ldid= ld.id;
                       system.debug('$$$$courseid'+UnivCourse.id);
                        Test.setCurrentPage(createOppty);
                        createOppty.getParameters().put('id', courseid);
                        createOppty.getParameters().put('command', 'DeleteOpportunity');
                       
                                               
                        createOppty.getParameters().put('opptyid', ldid);
                   //ApexPages.StandardController sc = new ApexPages.standardController(UnivCourse);
          CreateOpportunityfromCourse testnew1 = new CreateOpportunityfromCourse();
          
 //CreateOpportunityfromCourse testnew2 = new CreateOpportunityfromCourse();      
  //CreateOpportunityfromCourse testnew3 = new CreateOpportunityfromCourse();             
 testnew1.onLoad_CourseOpptyEdit();
  testnew1.today_date = system.today();

testnew1.Fall_start_date = system.today()-1;
testnew1.Fall_end_date = system.today()+1;
  testnew1.Spring_start_date = system.today();
  testnew1.Spring_end_date = system.today();
  System.debug(testnew1.Fall_end_date);
  System.debug(testnew1.Spring_end_date);
  testnew1.createOppty();
//opportunity ldd = new opportunity(Name='Test',  CloseDate=Date.newInstance(2015,04,15),Fall__c=10,Spring__c=10, Winter__c=10, Summer__c=10);

//delete ldd;
Test.stopTest();
}
catch(exception e){ System.debug('Unwanted Excpetion Caught: ' + e.getMessage());}
  }  
 }