src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Learner</fullName>
        <active>true</active>
        <label>Learner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Correlation__c.object
<CustomObject>
    <description>Global: Object used to store many IDs for a single account. Can be used to store integration IDs or legacy IDs</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Correlation</relationshipLabel>
        <relationshipName>Legacy_IDs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ID_Name__c</fullName>
        <description>Used where the Source system holds more than one ID for each account</description>
        <label>External ID Name</label>
        <picklist>
            <controllingField>External_System__c</controllingField>
            <picklistValues>
                <fullName>Current Ocean Learner Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ocean Learner Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eVision Learner Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing Account Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Address Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Socrates ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sampling Account Number</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>The ID for the contact in an external system</description>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_System__c</fullName>
        <description>The Name of the source External System</description>
        <label>External System</label>
        <picklist>
            <controllingField>Market__c</controllingField>
            <picklistValues>
                <fullName>Ocean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eVison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Socrates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UOPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The Market that supplied the ID</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Correlation</label>
    <nameField>
        <displayFormat>AC-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Correlation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>Used to capture the Market of the Contact Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Integration_Framework_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This custom setting is used by One CRM integration framework</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoB__c</fullName>
        <label>LoB</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Event__c</fullName>
        <label>Sub-Event</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_1__c</fullName>
        <label>System 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_2__c</fullName>
        <label>System 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Framework Configuration</label>
</CustomObject>

src/objects/Integration_Request__c.object
<CustomObject>
    <description>Representation of an asynchronous integration notification request</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>The business event</description>
        <label>Event</label>
        <picklist>
            <controllingField>Object_Name__c</controllingField>
            <picklistValues>
                <fullName>Register Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Vetted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrol Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change to Financially Responsible Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify Order Line Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resend Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LoB__c</fullName>
        <label>LoB</label>
        <picklist>
            <picklistValues>
                <fullName>HE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K-12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>The ID of the primary object</description>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Event__c</fullName>
        <description>The name of the sub-event</description>
        <label>Sub-Event</label>
        <picklist>
            <controllingField>Event__c</controllingField>
            <picklistValues>
                <fullName>Change Module Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Module Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retake Module</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field captures the Application ID from eVision that may be related to this opportunity.</description>
        <label>Related Opportunity</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lost_Reason_Other__c</fullName>
        <description>If the reason for closure is &quot;other&quot;, then this field is used to capture the other value</description>
        <label>Lost Reason Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s User record identified market.</description>
        <formula>TEXT(Owner.Market__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ISBN__c</fullName>
        <description>CORE - Product ISBN</description>
        <formula>PricebookEntry.Product2.ISBN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ISBN</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Packing_Instructions__c</fullName>
        <description>Instructions for the warehouse concerning packing of the order (i.e. minimize number of boxes)</description>
        <label>Packing Instructions</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Shipping_Instructions__c</fullName>
        <description>Instructions passed to the order shipping carrier (appears on the shipping label for UPS, Fedex, USPS) - ex. Leave at front/back door</description>
        <label>Shipping Instructions</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Shipped_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product actually shipped to the client</description>
        <label>Shipped Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ISBN__c</fullName>
        <description>CORE - Book ISBN</description>
        <externalId>true</externalId>
        <label>ISBN13</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Indicates which Market is utilizing this product.</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/System_Response__c.object
<CustomObject>
    <description>System Response used by the integration framework</description>
    <fields>
        <fullName>External_System__c</fullName>
        <description>The external system name</description>
        <inlineHelpText>The external system name</inlineHelpText>
        <label>External System</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Request__c</fullName>
        <description>The linked integration request</description>
        <inlineHelpText>The linked integration request</inlineHelpText>
        <label>Integration Request</label>
        <referenceTo>Integration_Request__c</referenceTo>
        <relationshipLabel>System Responses</relationshipLabel>
        <relationshipName>System_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Response</label>
    <nameField>
        <label>System Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UpdateOneCRMTest.cls
/*******************************************************************************************************************
* Apex Class Name  : UpdateOneCRMTestTest
* Version          : 1.0 
* Created Date     : 5 May 2015
* Function         : Test Class of the UpdateOneCRMTest class 
* Modification Log :
*
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
*                             05/05/2015              Created Initial Version of AccountContactSyncTestClass
*******************************************************************************************************************/
@isTest (seeAllData=true)
public with sharing class UpdateOneCRMTest 
{
  /*************************************************************************************************************
  * Name        : verifyReportTransaction1 
  * Description : Verify the reportTransaction method   
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifyReportTransaction1()
  {
    Boolean result = false;
    List<Account> generatedAccounts = generateTestAccounts(1);
    List<Integration_Request__c> generatedIntegrationRequests = generateIntegrationRequests(1, generatedAccounts.get(0).Id );
    UpdateOneCRM.IntegrationTransaction request = new UpdateOneCRM.IntegrationTransaction(); 
    request.integrationRequestId = generatedIntegrationRequests.get(0).id;   
    request.status = System.Label.INT_Status_Received;
    request.externalSystem = 'Sys 1';
    Integration_Framework_Configuration__c ifc = new Integration_Framework_Configuration__c(Name = 'Name', 
                                                                                            Event__c = 'Enrol Student', 
                                                                                            Geo__c = 'Growth', 
                                                                                            Lob__c = 'HE', 
                                                                                            Market__c = 'ZA', 
                                                                                            Sub_Event__c = 'Sub Event', 
                                                                                            System_1__c = 'Sys 1', System_2__c = 'Sys 2');
    insert ifc;
    
    test.startTest();
    
    result = UpdateOneCRM.reportTransaction(request);
    System.assertEquals(true, result, 'Returned result is not true');
    request.status = 'New';
    result = UpdateOneCRM.reportTransaction(request);
    System.assertEquals(true, result, 'Returned result is not true');
   
    try
    {
      request.integrationRequestId = generatedAccounts.get(0).Id;
      result = false;
      result = UpdateOneCRM.reportTransaction(request);
    }
    catch(UpdateOneCRM.UpdateOneCRMException e)
    {
      System.assertEquals(false, result, 'Returned result is not false');
    }
   
    try
    {
      request.externalSystem = 'XXXXX';
      request.status = 'XXXXX';
      result = false;
      result = UpdateOneCRM.reportTransaction(request);      
    }
    catch(UpdateOneCRM.UpdateOneCRMException e)
    {
      System.assertEquals(false, result, 'Returned result is not false');
    }
    
    test.stopTest();
  }
  
  
  /*************************************************************************************************************
  * Name        : verifyReportTransaction
  * Description : Verify the reportTransaction method   
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifyReportTransaction2()
  {
    Boolean result = false;
    List<Account> generatedAccounts = generateTestAccounts(1);
    List<Integration_Request__c> generatedIntegrationRequests = generateIntegrationRequests(1, generatedAccounts.get(0).Id );
    UpdateOneCRM.IntegrationTransaction request = new UpdateOneCRM.IntegrationTransaction(); 
    request.integrationRequestId = generatedIntegrationRequests.get(0).id;   
    request.status = System.Label.INT_Status_Received;
    request.externalSystem = 'Sys 1';
    Integration_Framework_Configuration__c ifc = new Integration_Framework_Configuration__c(Name = 'Name', 
                                                                                            Event__c = 'Enrol Student', 
                                                                                            Geo__c = 'Growth', 
                                                                                            Lob__c = 'HE', 
                                                                                            Market__c = 'ZA', 
                                                                                            Sub_Event__c = 'Sub Event', 
                                                                                            System_1__c = 'Sys 1', System_2__c = 'Sys 2');
    insert ifc;
    System_Response__c sr = new System_Response__c(Integration_Request__c = generatedIntegrationRequests.get(0).id,
                                                   External_System__c = request.externalSystem);
    insert sr;
    
    Integration_Request__c ir = [SELECT id, (SELECT Id from System_Responses__r) from Integration_Request__c WHERE Id = :generatedIntegrationRequests.get(0).Id];
    update generatedIntegrationRequests.get(0);
    request.integrationRequestId = ir.Id;
    test.startTest();
    
    result = UpdateOneCRM.reportTransaction(request);
    System.assertEquals(true, result, 'Returned result is not true');
    
    test.stopTest();
  } 
  
  
  /*************************************************************************************************************
  * Name        : verifyupdateExternalReference
  * Description : Verify the updateExternalReference method   
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifyUpdateExternalReference()
  {
  	Boolean result = false;
    List<Account> generatedAccounts = generateTestAccounts(1);
    Opportunity opp = (Opportunity)TestClassAutomation.createSObject('Opportunity');
    opp.AccountId = generatedAccounts.get(0).Id;
    opp.CurrencyIsoCode = 'GBP';
    opp.Lost_Reason_Other__c = 'XXX';
    insert opp;
    List<Integration_Request__c> generatedIntegrationRequests = generateIntegrationRequests(1, opp.Id );
   
    UpdateOneCRM.UpdateRequest request = new UpdateOneCRM.UpdateRequest(); 
    request.integrationRequestId = generatedIntegrationRequests.get(0).id;   
    request.externalKeyValue = '999999999';
    request.externalKeyName = System.Label.Learner_ID;
    request.externalSystem = System.Label.EVision;
    
    test.startTest();
    
    result = UpdateOneCRM.updateExternalReference(request);
    System.assertEquals(true, result, 'Returned result is not true');

    Account_Correlation__C ac = new Account_Correlation__C(Account__C = generatedAccounts.get(0).Id, External_ID_Name__c = 'eVision Learner Number', External_ID__c = 'External ID');
    insert ac; 
    result = UpdateOneCRM.updateExternalReference(request);
    System.assertEquals(true, result, 'Returned result is not true');  
    try
    {
      request.externalSystem = 'XXXXX';
      result = false;
      result = UpdateOneCRM.updateExternalReference(request);
    }
    catch(UpdateOneCRM.UpdateOneCRMException e)
    {
      System.assertEquals(false, result, 'Returned result is not false');
    }
    try
    {
      request.externalKeyName = 'XXXXX';
      request.externalSystem = System.Label.EVision;
      result = false;
      result = UpdateOneCRM.updateExternalReference(request);
    }
    catch(UpdateOneCRM.UpdateOneCRMException e)
    {
      System.assertEquals(false, result, 'Returned result is not false');
    }
    
    request.externalKeyName = System.Label.Application_ID;
    result = UpdateOneCRM.updateExternalReference(request); 
    System.assertEquals(true, result, 'Returned result is not true');
    
    
    request.integrationRequestId = 'a3bg00000008UPHAA4';
    result = UpdateOneCRM.updateExternalReference(request); 
    System.assertEquals(false, result, 'Returned result is not false');
    
    generatedIntegrationRequests.get(0).Object_Id__c = '006b0000007YFwEAAW';
    update generatedIntegrationRequests.get(0);
    request.integrationRequestId = generatedIntegrationRequests.get(0).id; 
    result = UpdateOneCRM.updateExternalReference(request); 
    System.assertEquals(false, result, 'Returned result is not false');
    
    test.stopTest();
  }
  
  /*************************************************************************************************************
  * Name        : verifyUpdateOrderLineItem1
  * Description : Verify the updateOrderLineItem method   
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifyUpdateOrderLineItem1()
  {   
    List<User> usrLst = TestDataFactory.createUser(Userinfo.getProfileId());
    insert usrLst;
    
    List <PermissionSet> permList = [SELECT Id FROM PermissionSet WHERE name = 'Pearson_Backend_Order_Creation'];  
    PermissionSetAssignment psa = new PermissionSetAssignment();
    psa.AssigneeId = usrLst[1].Id;
    psa.PermissionSetId = permList[0].Id;
    insert psa;
    
    System.runas(usrLst[1])
    {
    UpdateOneCRM.OrderLineItem oli = new UpdateOneCRM.OrderLineItem();
    oli.id = '0011100000hXHFgAAO';
    oli.orderId = '0011100000hXHFgAAO';
    oli.itemNumber = '12345';
    oli.orderNumber = '12345';
    oli.status = 'New Status';
    oli.statusReason = 'New Status Reason';
    oli.externalOrderNumber = '123456';
    oli.quantity = 7;
    
    UpdateOneCRM.OrderLineItem oli2 = new UpdateOneCRM.OrderLineItem();
    oli2.orderId = '0011100000hXHFgAAO';
    oli2.itemNumber = '12345';
    oli2.orderNumber = '12345';
    oli2.status = 'New Status';
    oli2.statusReason = 'New Status Reason';
    oli2.quantity = 7;
    
    UpdateOneCRM.OrderLineItem oli3 = new UpdateOneCRM.OrderLineItem();
    oli3.orderId = '0011100000hXHFgAAO';
    oli3.itemNumber = '12345';
    oli3.orderNumber = '12345';
    oli3.status = 'New Status';
    oli3.statusReason = 'New Status Reason';
    oli3.quantity = 7;
    
    
    Account acc = (Account)TestClassAutomation.createSObject('Account');
    acc.Name = 'Test';
    acc.billingStateCode = '';
    acc.ShippingStateCode = '';
    insert acc;
     
    contact con = (Contact)TestClassAutomation.createSObject('Contact');
    con.Lastname= 'testcon';
    con.Firstname= 'testcon1';
    con.MobilePhone = '9999';     
    insert con;     
    
    Opportunity opp = (Opportunity)TestClassAutomation.createSObject('Opportunity');
    opp.AccountId = acc.Id;
    opp.CurrencyIsoCode = 'GBP';
    opp.Lost_Reason_Other__c = 'XXX';
    insert opp;
    
    Product2 prod = (Product2)TestClassAutomation.createSObject('Product2');
    prod.ISBN__c = '67890';
    insert prod;

    Pricebook2 priceBook = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];
    priceBook.IsActive = true;
    update priceBook;
        
    PriceBookEntry sPriceBookEntry = (PriceBookEntry)TestClassAutomation.createSObject('PriceBookEntry');
    sPriceBookEntry.IsActive = true;
    sPriceBookEntry.Product2Id = prod.Id;
    sPriceBookEntry.Pricebook2Id = priceBook.Id;
    sPriceBookEntry.UnitPrice = 34.95;
    sPriceBookEntry.CurrencyIsoCode = 'GBP';
    insert sPriceBookEntry;
    
    OpportunityLineItem oli1 = new OpportunityLineItem();
    oli1.OpportunityId = opp.Id;
    oli1.PricebookEntryId = sPriceBookEntry.Id;
    oli1.TotalPrice = 200;
    oli1.Quantity = 1;
            
    insert oli1;
     
    order ord = new order();
    ord.OpportunityId=opp.Id;
    ord.Accountid = acc.Id;
    ord.EffectiveDate = system.today();
    ord.status = 'Open';
    ord.Pricebook2Id = priceBook.id;
    ord.CurrencyIsoCode = 'GBP';
    ord.Packing_Instructions__c = 'Packing Instructions';
    ord.Shipping_Instructions__c = 'Shipping instructions';
    insert ord;
    Order o2 = [select id, ordernumber from Order where id = :ord.id];
    
    OrderItem oi = new OrderItem();
    oi.orderid=ord.id;
    oi.Shipped_Product__c = prod.id;
    oi.Quantity = 6;
    oi.pricebookentryid= sPriceBookEntry.id;
    oi.unitprice =1.00;
    insert oi;    
	  OrderItem oi2 = [select id, orderitemnumber from OrderItem where id = :oi.id];	
		
    oli.orderNumber = o2.orderNumber;
    oli.id = o2.id;    
    //oli.id = oi2.id;
    oli2.orderNumber = o2.orderNumber;
    oli3.orderNumber = o2.orderNumber;
    oli.itemNumber = oi2.OrderItemNumber;
    oli2.itemNumber = oi2.OrderItemNumber;
    oli3.itemNumber = oi2.OrderItemNumber;
    oli.externalOrderNumber = '999';
    oli2.externalOrderNumber = '999';
    oli3.externalOrderNumber = '999';
    INT_BookProduct shippedBook = new INT_BookProduct();
    shippedBook.isbn10  = '123456';
    shippedBook.isbn13 = '67890';
    oli.shipped = shippedBook;
    oli2.shipped = shippedBook;
    oli3.shipped = shippedBook;
    
    List<UpdateOneCRM.OrderLineItem> orderLineItemList = new List<UpdateOneCRM.OrderLineItem>();
    orderLineItemList.add(oli);
    orderLineItemList.add(oli2);
    orderLineItemList.add(oli3);
    
    test.startTest();
    
    Boolean result = UpdateOneCRM.updateOrderLineItem(orderLineItemList);
    System.assertEquals(false, result, 'The result is not false');
    
    test.stopTest();
    }
  }
  
  /*************************************************************************************************************
  * Name        : verifyUpdateOrderLineItem2
  * Description : Verify the updateOrderLineItem method   
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifyUpdateOrderLineItem2()
  {   
    List<User> usrLst = TestDataFactory.createUser(Userinfo.getProfileId());
    insert usrLst;
    
    List <PermissionSet> permList = [SELECT Id FROM PermissionSet WHERE name = 'Pearson_Backend_Order_Creation'];  
    PermissionSetAssignment psa = new PermissionSetAssignment();
    psa.AssigneeId = usrLst[1].Id;
    psa.PermissionSetId = permList[0].Id;
    insert psa;
    
    System.runas(usrLst[1])
    {
    INT_BookProduct bp = new INT_BookProduct();
    bp.isbn13 = '12345';
    
    UpdateOneCRM.OrderLineItem oli = new UpdateOneCRM.OrderLineItem();
    oli.id = '0011100000hXHFgAAO';
    oli.orderId = '0011100000hXHFgAAO';
    oli.itemNumber = '12345';
    oli.orderNumber = '12345';
    oli.status = 'New Status';
    oli.statusReason = 'New Status Reason';
    oli.quantity = 7;
    oli.externalOrderNumber = '123456';
    oli.shipped = bp;
    
    UpdateOneCRM.OrderLineItem oli2 = new UpdateOneCRM.OrderLineItem();
    oli2.orderId = '0011100000hXHFgAAO';
    oli2.itemNumber = '12345';
    oli2.orderNumber = '12345';
    oli2.status = 'New Status';
    oli2.statusReason = 'New Status Reason';
    oli2.quantity = 7;
    oli2.externalOrderNumber = '123456';
    oli2.shipped = bp;
    
    UpdateOneCRM.OrderLineItem oli3 = new UpdateOneCRM.OrderLineItem();
    oli3.orderId = '0011100000hXHFgAAO';
    oli3.itemNumber = '12345';
    oli3.orderNumber = '12345';
    oli3.status = 'New Status';
    oli3.statusReason = 'New Status Reason';
    oli3.quantity = 7;
    oli3.externalOrderNumber = '123456';
    oli3.shipped = bp;
    
    Account acc = (Account)TestClassAutomation.createSObject('Account');
    acc.Name = 'Test';
    acc.billingStateCode = '';
    acc.ShippingStateCode = '';
    insert acc;
     
    contact con = (Contact)TestClassAutomation.createSObject('Contact');
    con.Lastname= 'testcon';
    con.Firstname= 'testcon1';
    con.MobilePhone = '9999';     
    insert con;     
    
    Opportunity opp = (Opportunity)TestClassAutomation.createSObject('Opportunity');
    opp.AccountId = acc.Id;
    opp.CurrencyIsoCode = 'GBP';
    opp.Lost_Reason_Other__c = 'XXX';
    insert opp;
    
    Product2 prod = (Product2)TestClassAutomation.createSObject('Product2');
    prod.ISBN__c = '12345';
    insert prod;

    Pricebook2 priceBook = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];
    priceBook.IsActive = true;
    update priceBook;
        
    PriceBookEntry sPriceBookEntry = (PriceBookEntry)TestClassAutomation.createSObject('PriceBookEntry');
    sPriceBookEntry.IsActive = true;
    sPriceBookEntry.Product2Id = prod.Id;
    sPriceBookEntry.Pricebook2Id = priceBook.Id;
    sPriceBookEntry.UnitPrice = 34.95;
    sPriceBookEntry.CurrencyIsoCode = 'GBP';
    insert sPriceBookEntry;
    
    OpportunityLineItem oli1 = new OpportunityLineItem();
    oli1.OpportunityId = opp.Id;
    oli1.PricebookEntryId = sPriceBookEntry.Id;
    oli1.TotalPrice = 200;
    oli1.Quantity = 1;
            
    insert oli1;
     
    order ord = new order();
    //ord.OpportunityId=opp.Id;
    ord.Accountid = acc.Id;
    ord.EffectiveDate = system.today();
    ord.status = 'Open';
    ord.Pricebook2Id = priceBook.id;
    ord.CurrencyIsoCode = 'GBP';
    ord.Packing_Instructions__c = 'Packing Instructions';
    ord.Shipping_Instructions__c = 'Shipping instructions';
    insert ord;

    Order o2 = [select id, ordernumber from Order where id = :ord.id];
    
    OrderItem oi = new OrderItem();
    oi.orderid=ord.id;
    oi.Shipped_Product__c = prod.id;
    oi.Quantity = 6;
    oi.pricebookentryid= sPriceBookEntry.id;
    oi.unitprice =1.00;
    insert oi;    
	  OrderItem oi2 = [select id, orderitemnumber from OrderItem where id = :oi.id];	
		
    oli.orderNumber = o2.orderNumber;
    //oli.id = o2.id;    
    oli.id = oi2.id;
    oli2.orderNumber = o2.orderNumber;
    oli3.orderNumber = o2.orderNumber;
    oli.itemNumber = oi2.OrderItemNumber;
    oli2.itemNumber = oi2.OrderItemNumber;
    oli3.itemNumber = oi2.OrderItemNumber;
    
    List<UpdateOneCRM.OrderLineItem> orderLineItemList = new List<UpdateOneCRM.OrderLineItem>();
    orderLineItemList.add(oli);
    
    test.startTest();
        
    Boolean result = UpdateOneCRM.updateOrderLineItem(orderLineItemList);
    System.assertEquals(true, result, 'The result is not true');
    
    try
    {
      result = false;
      bp.isbn13 = 'ABC123456';
      result = UpdateOneCRM.updateOrderLineItem(orderLineItemList); 
      bp.isbn13 = '12345';     
    }
    catch(Exception e)
    {
      System.assertEquals(false, result, 'The result is not false');
    }    
    
    oli.id = null;
    oli.itemNumber = '';
    oli.orderNumber = '';
    try
    {
      result = false;
      result = UpdateOneCRM.updateOrderLineItem(orderLineItemList);      
    }
    catch(Exception e)
    {
      System.assertEquals(false, result, 'The result is not false');
    }
    
    
    test.stopTest();
    }
  }  
     
  /*************************************************************************************************************
  * Name        : verifyUpdateOrderLineItem3
  * Description : Verify the updateOrderLineItem method   
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifyUpdateOrderLineItem3()
  {   
    List<User> usrLst = TestDataFactory.createUser(Userinfo.getProfileId());
    insert usrLst;
    
    List <PermissionSet> permList = [SELECT Id FROM PermissionSet WHERE name = 'Pearson_Backend_Order_Creation'];  
    PermissionSetAssignment psa = new PermissionSetAssignment();
    psa.AssigneeId = usrLst[1].Id;
    psa.PermissionSetId = permList[0].Id;
    insert psa;
    
    System.runas(usrLst[1])
    {
    UpdateOneCRM.OrderLineItem oli = new UpdateOneCRM.OrderLineItem();
    oli.id = '0011100000hXHFgAAO';
    oli.orderId = '0011100000hXHFgAAO';
    oli.itemNumber = '12345';
    oli.orderNumber = '12345';
    oli.status = 'New Status';
    oli.statusReason = 'New Status Reason';
    oli.quantity = 7;
    oli.externalOrderNumber = '123456';
    
    UpdateOneCRM.OrderLineItem oli2 = new UpdateOneCRM.OrderLineItem();
    oli2.orderId = '0011100000hXHFgAAO';
    oli2.status = 'New Status';
    oli2.statusReason = 'New Status Reason';
    oli2.quantity = 7;
    oli2.externalOrderNumber = '123456';
    
    UpdateOneCRM.OrderLineItem oli3 = new UpdateOneCRM.OrderLineItem();
    oli3.orderId = '0011100000hXHFgAAO';
    oli3.itemNumber = '12345';
    oli3.orderNumber = '12345';
    oli3.status = 'New Status';
    oli3.statusReason = 'New Status Reason';
    oli3.quantity = 7;
    oli3.externalOrderNumber = '123456';
        
    Account acc = (Account)TestClassAutomation.createSObject('Account');
    acc.Name = 'Test';
    acc.billingStateCode = '';
    acc.ShippingStateCode = '';
    insert acc;
     
    contact con = (Contact)TestClassAutomation.createSObject('Contact');
    con.Lastname= 'testcon';
    con.Firstname= 'testcon1';
    con.MobilePhone = '9999';     
    insert con;     
    
    Opportunity opp = (Opportunity)TestClassAutomation.createSObject('Opportunity');
    opp.AccountId = acc.Id;
    opp.CurrencyIsoCode = 'GBP';
    opp.Lost_Reason_Other__c = 'XXX';
    insert opp;
    
    Product2 prod = (Product2)TestClassAutomation.createSObject('Product2');
    insert prod;

    Pricebook2 priceBook = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];
    priceBook.IsActive = true;
    update priceBook;
        
    PriceBookEntry sPriceBookEntry = (PriceBookEntry)TestClassAutomation.createSObject('PriceBookEntry');
    sPriceBookEntry.IsActive = true;
    sPriceBookEntry.Product2Id = prod.Id;
    sPriceBookEntry.Pricebook2Id = priceBook.Id;
    sPriceBookEntry.UnitPrice = 34.95;
    sPriceBookEntry.CurrencyIsoCode = 'GBP';
    insert sPriceBookEntry;
    
    OpportunityLineItem oli1 = new OpportunityLineItem();
    oli1.OpportunityId = opp.Id;
    oli1.PricebookEntryId = sPriceBookEntry.Id;
    oli1.TotalPrice = 200;
    oli1.Quantity = 1;
            
    insert oli1;
     
    order ord = new order();
    //ord.OpportunityId=opp.Id;
    ord.Accountid = acc.Id;
    ord.EffectiveDate = system.today();
    ord.status = 'Open';
    ord.Pricebook2Id = priceBook.id;
    ord.CurrencyIsoCode = 'GBP';
    ord.Packing_Instructions__c = 'Packing Instructions';
    ord.Shipping_Instructions__c = 'Shipping instructions';
    insert ord;

    Order o2 = [select id, ordernumber from Order where id = :ord.id];
    
    OrderItem oi = new OrderItem();
    oi.orderid=ord.id;
    oi.Shipped_Product__c = prod.id;
    oi.Quantity = 6;
    oi.pricebookentryid= sPriceBookEntry.id;
    oi.unitprice =1.00;
    insert oi;    
	  OrderItem oi2 = [select id, orderitemnumber from OrderItem where id = :oi.id];	
		
    oli.orderNumber = o2.orderNumber;
    //oli.id = o2.id;    
    oli.id = oi2.id;
    oli2.orderNumber = o2.orderNumber;
    oli3.orderNumber = o2.orderNumber;
    oli.itemNumber = oi2.OrderItemNumber;
    oli2.itemNumber = oi2.OrderItemNumber;
    oli3.itemNumber = oi2.OrderItemNumber;
    
    List<UpdateOneCRM.OrderLineItem> orderLineItemList = new List<UpdateOneCRM.OrderLineItem>();
    orderLineItemList.add(oli2);
    
    test.startTest();
    
    Boolean result = UpdateOneCRM.updateOrderLineItem(orderLineItemList);
    System.assertEquals(false, result, 'The result is not false');
    
    test.stopTest();
    }
  }  
    
  /*************************************************************************************************************
  * Name        : verifyExceptions1
  * Description : Verify the exceptions   
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifyExceptions1()
  {
    Boolean result = false;
    List<Account> generatedAccounts = generateTestAccounts(1);
    List<Integration_Request__c> generatedIntegrationRequests = generateIntegrationRequests(1, generatedAccounts.get(0).Id );
    UpdateOneCRM.IntegrationTransaction request = new UpdateOneCRM.IntegrationTransaction(); 
    request.integrationRequestId = generatedIntegrationRequests.get(0).id;   
    request.status = System.Label.INT_Status_Received;
    request.externalSystem = 'XXXX';
    Integration_Framework_Configuration__c ifc = new Integration_Framework_Configuration__c(Name = 'Name', 
                                                                                            Event__c = 'Enrol Student', 
                                                                                            Geo__c = 'Growth', 
                                                                                            Lob__c = 'HE', 
                                                                                            Market__c = 'ZA', 
                                                                                            Sub_Event__c = 'Sub Event', 
                                                                                            System_1__c = 'Sys 1', System_2__c = 'Sys 2');
    insert ifc;
    test.startTest();
    try
    {
      result = UpdateOneCRM.reportTransaction(request);
    }
    
    catch(UpdateOneCRM.UpdateOneCRMException e)
    {
      System.assertEquals(false, result, 'Returned result is not false');
    }
    
    test.stopTest();
  }    
  
  /*************************************************************************************************************
  * Name        : verifyExceptions2
  * Description : Verify the exceptions   
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifyExceptions2()
  {
    Boolean result = false;
    List<Account> generatedAccounts = generateTestAccounts(1);
    List<Integration_Request__c> generatedIntegrationRequests = generateIntegrationRequests(1, generatedAccounts.get(0).Id );
    UpdateOneCRM.IntegrationTransaction request = new UpdateOneCRM.IntegrationTransaction(); 
    request.integrationRequestId = generatedIntegrationRequests.get(0).id;   
    request.status = 'XXXX';
    request.externalSystem = 'Sys 1';
    Integration_Framework_Configuration__c ifc = new Integration_Framework_Configuration__c(Name = 'Name', 
                                                                                            Event__c = 'Enrol Student', 
                                                                                            Geo__c = 'Growth', 
                                                                                            Lob__c = 'HE', 
                                                                                            Market__c = 'ZA', 
                                                                                            Sub_Event__c = 'Sub Event', 
                                                                                            System_1__c = 'Sys 1', System_2__c = 'Sys 2');
    insert ifc;
    test.startTest();
    try
    {
      result = UpdateOneCRM.reportTransaction(request);
    }
    
    catch(UpdateOneCRM.UpdateOneCRMException e)
    {
      System.assertEquals(false, result, 'Returned result is not false');
    }
    
    test.stopTest();
  }    
  
  /*************************************************************************************************************
  * Name        : verifyExceptions3
  * Description : Verify the exceptions   
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifyExceptions3()
  {
    Boolean result = false;
    List<Account> generatedAccounts = generateTestAccounts(1);
    List<Integration_Request__c> generatedIntegrationRequests = generateIntegrationRequests(1, generatedAccounts.get(0).Id );
    UpdateOneCRM.IntegrationTransaction request = new UpdateOneCRM.IntegrationTransaction(); 
    request.integrationRequestId = generatedIntegrationRequests.get(0).id;   
    request.status = System.Label.INT_Status_Received;
    request.externalSystem = null;
    Integration_Framework_Configuration__c ifc = new Integration_Framework_Configuration__c(Name = 'Name', 
                                                                                            Event__c = 'Enrol Student', 
                                                                                            Geo__c = 'Growth', 
                                                                                            Lob__c = 'HE', 
                                                                                            Market__c = 'ZA', 
                                                                                            Sub_Event__c = 'Sub Event', 
                                                                                            System_1__c = '', System_2__c = '');
    insert ifc;
    test.startTest();
    try
    {
      result = UpdateOneCRM.reportTransaction(request);
    }
    
    catch(UpdateOneCRM.UpdateOneCRMException e)
    {
      System.assertEquals(false, result, 'Returned result is not false');
    }
    
    test.stopTest();
  }    
  
  /*************************************************************************************************************
  * Name        : generateIntegrationRequests
  * Description : Generate Integration Request records
  * Input       : NumOfIntegrationRequest - Number of Integration Request records to generate
  * INPUT       : The objectId to associate with the Integration Request
  * Output      : List of the Integration Request records generated
  *************************************************************************************************************/
  private static List<Integration_Request__c> generateIntegrationRequests(Integer numOfIntegrationRequests, Id objectId)
  {
   List<Integration_Request__c> integrationRequestsToInsert = new List<Integration_Request__c>();
       
    for(Integer i=0; i<numOfIntegrationRequests; i++)
    {
      Integration_Request__c integrationRequestToInsert = new Integration_Request__c(Object_Id__c = objectId);
      integrationRequestToInsert.Object_Name__c = 'Opportunity';
      integrationRequestToInsert.Direction__c = 'Outbound';
      integrationRequestToInsert.Event__c = 'Enrol Student';
      integrationRequestToInsert.Geo__c ='Growth';
      integrationRequestToInsert.Lob__c = 'HE';
      integrationRequestToInsert.Market__c = 'ZA'; 
      integrationRequestToInsert.Sub_Event__c = 'Sub Event';
      integrationRequestsToInsert.add(integrationRequestToInsert);
    }
       
    if(integrationRequestsToInsert.size()>0)
    {
      insert integrationRequestsToInsert;
    }
       
    return integrationRequestsToInsert;
  } 
  
  /*************************************************************************************************************
  * Name        : generateTestAccounts
  * Description : Generate Account records
  * Input       : NumOfAccounts - Number of account records to generate
  * Output      : List of the Account records generated
  *************************************************************************************************************/
  private static List<Account> generateTestAccounts(Integer numOfAccounts)
  {
    List<Account> accountsToInsert = new List<Account>();
        
    for(Integer i=0; i<numOfAccounts; i++)
    {
      Account accountToInsert = new Account(Name = 'Account' + (i+1));
      accountsToInsert.add(accountToInsert);
    }
        
    if(accountsToInsert.size()>0)
    {
      insert accountsToInsert;
    }
     
    return accountsToInsert;
  }
}