src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Account_Number__c</fullName>
        <description>CORE - Integration field with Bookmaster</description>
        <externalId>true</externalId>
        <label>External Account Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Learner</fullName>
        <active>true</active>
        <label>Learner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Correlation__c.object
<CustomObject>
    <description>Global: Object used to store many IDs for a single account. Can be used to store integration IDs or legacy IDs</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Correlation</relationshipLabel>
        <relationshipName>Legacy_IDs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ID_Name__c</fullName>
        <description>Used where the Source system holds more than one ID for each account</description>
        <label>External ID Name</label>
        <picklist>
            <controllingField>External_System__c</controllingField>
            <picklistValues>
                <fullName>Current Ocean Learner Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ocean Learner Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eVision Learner Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing Account Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Address Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Socrates ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sampling Account Number</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>The ID for the contact in an external system</description>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Account Correlation</label>
    <nameField>
        <displayFormat>AC-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Correlation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AccountContact__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE:  The Account linked to the Contact</description>
        <inlineHelpText>The Account linked to the Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>CORE: The Contact linked to the Account</description>
        <inlineHelpText>The Contact linked to the Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>AOC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Current_Campus__c</fullName>
        <description>Used to capture where the Student is currently enrolled</description>
        <label>Current Campus</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>​Bedfordview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bloemfontein</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cape Town</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durban</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durbanville</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nelspruit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Port Elizabeth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potchefstroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pretoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Randburg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vanderbijlpark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midrand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Proposed_Campus__c</fullName>
        <description>Used to record the Campus the student wants to move to</description>
        <label>Proposed Campus</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>​Bedfordview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bloemfontein</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cape Town</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durban</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durbanville</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nelspruit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Port Elizabeth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potchefstroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pretoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Randburg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vanderbijlpark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midrand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Cancellation_Request</fullName>
        <active>true</active>
        <businessProcess>Cancellation Process</businessProcess>
        <label>Cancellation Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>Change_Request</fullName>
        <active>true</active>
        <businessProcess>Change Details</businessProcess>
        <label>Change Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <businessProcess>Cancellation Process</businessProcess>
        <label>General</label>
    </recordTypes>
    <recordTypes>
        <fullName>Loan_Bursary_Request</fullName>
        <active>true</active>
        <businessProcess>Loan%2FBursary Request Process</businessProcess>
        <label>Loan/Bursary Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <description>CTIMGI: Field to capture the home phone number of the Contact record.</description>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>National_Identity_Number__c</fullName>
        <description>Encrypted field: used to capture the Contacts National Identity Number.</description>
        <label>National Identity Number</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Passport_Number__c</fullName>
        <description>Encrypted field - used to capture the contacts passport number</description>
        <label>Passport Number</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Vetting_Status__c</fullName>
        <description>This field shows the status of the academic vetting for an opportunity.</description>
        <label>Academic Vetting Status</label>
        <picklist>
            <picklistValues>
                <fullName>Un-Vetted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Vetted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vetted - Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vetted - Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field captures the Application ID from eVision that may be related to this opportunity.</description>
        <label>Related Opportunity</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lost_Reason_Other__c</fullName>
        <description>If the reason for closure is &quot;other&quot;, then this field is used to capture the other value</description>
        <label>Lost Reason Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <description>This field captures the reason an opportunity was either closed  won or closed lost.</description>
        <label>Closed\Lost Reason</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Price\Value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Available Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed Academic Vetting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Circumstances</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Status field is used to define the status of the opportunity</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Product Status</description>
        <formula>Text(PricebookEntry.Product2.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Main contact referenced to on order (if applicable)</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packing_Instructions__c</fullName>
        <description>Instructions for the warehouse concerning packing of the order (i.e. minimize number of boxes)</description>
        <label>Packing Instructions</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Shipping_Instructions__c</fullName>
        <description>Instructions passed to the order shipping carrier (appears on the shipping label for UPS, Fedex, USPS) - ex. Leave at front/back door</description>
        <label>Shipping Instructions</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Shipped_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product actually shipped to the client</description>
        <label>Shipped Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Order line item status that gets updated automatically</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Backordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requires Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resend Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shippable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TU</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/PS_INT_IntegrationRequestControllerTest.cls
@isTest (seeAllData=true)
public with sharing class PS_INT_IntegrationRequestControllerTest 
{    
  /*************************************************************************************************************
  * Name        : verifySubmisionValidation
  * Description : Verify the submissionValidation method   
  * Input       :  
  * Output      :  
  *************************************************************************************************************/
  static testMethod void verifySubmisionValidation()
  {  
   
    List<User> usrLst = TestDataFactory.createUser(Userinfo.getProfileId());
    insert usrLst;
    System.runas(usrLst[0]){
    Account acc = (Account)TestClassAutomation.createSObject('Account');
    acc.Name = 'Test';
    insert acc; 
    
    Account_Correlation__C ac = new Account_Correlation__C(Account__C = acc.Id, External_ID_Name__c = 'eVision Learner Number', External_ID__c = 'External ID');
    insert ac; 
     
    contact con = (Contact)TestClassAutomation.createSObject('Contact');
    con.Lastname= 'testcon';
    con.Firstname= 'testcon1';
    con.MobilePhone = '9999';     
    insert con;     
    
    Opportunity opp = (Opportunity)TestClassAutomation.createSObject('Opportunity');
    opp.AccountId = acc.Id;
    opp.CurrencyIsoCode = 'GBP';
    opp.Lost_Reason_Other__c = 'XXX';
    opp.Academic_Vetting_Status__c = 'XXXXX';
    opp.Type = 'New Business';
    opp.StageName = 'Negotiation';
    insert opp;
    
    Opportunity oldopp = (Opportunity)TestClassAutomation.createSObject('Opportunity');
    oldopp.AccountId = acc.Id;
    oldopp.CurrencyIsoCode = 'GBP';
    oldopp.Lost_Reason_Other__c = 'XXX';
    oldopp.Academic_Vetting_Status__c = 'XXXXX';
    oldopp.Type = 'New Business';
    oldopp.StageName = 'Negotiation';
    insert oldopp;
    
    list<OpportunityContactRole>ocrlist = new list<OpportunityContactRole>();
    OpportunityContactRole ocr = new OpportunityContactRole();
    ocr.ContactId = con.id;
    ocr.Role = 'Business User';
    ocr.IsPrimary = True;
    ocr.OpportunityId = opp.id;     
    ocrlist.add(ocr);
     
    OpportunityContactRole ocr1 = new OpportunityContactRole();
    ocr1.ContactId = con.id;
    ocr1.Role = 'Primary Sales Contact';
    ocr1.IsPrimary = True;
    ocr1.OpportunityId = opp.id;
    ocrlist.add(ocr1);
    insert ocrlist;    
    List <Opportunity> opps = new List<Opportunity>();
    Map<Id, Opportunity> oldOpps = new Map<Id, Opportunity>();
    opps.add(opp);
    oldopps.put(opp.id, oldopp);
    
    test.startTest();
    
    PS_INT_IntegrationRequestController.submissionValidation(opps, oldOpps);
    
    con.Passport_Number__c = '12345';
    con.National_Identity_Number__c = '123456';
    update con;
    ocr.ContactId = con.id;
    update ocr;
    PS_INT_IntegrationRequestController.submissionValidation(opps, oldOpps);
  
    opp.Type = 'New Business';
    opp.StageName = 'Closed';
    update opp;
  
    con.MobilePhone = null;
    con.Phone = '9999';
    update con;
    PS_INT_IntegrationRequestController.submissionValidation(opps, oldOpps);
    
    opp.Type = 'Amendment';
    opp.StageName = 'Closed';
    update opp;
    
    con.Phone = null;
    con.Home_Phone__c = '9999';
    update con;
    PS_INT_IntegrationRequestController.submissionValidation(opps, oldOpps);
    
    //con.Home_Phone__C = null;
    //update con;
    //PS_INT_IntegrationRequestController.submissionValidation(opps, oldOpps);
    
    //Map<id, SObject> oldopps = new Map<id, SObject>();
    
    opp.StageName = 'Closed';
    update opp;
    PS_INT_IntegrationRequestController.createIntegrationRequestOpp(opps, oldopps);
    
    opp.Type = 'Amendment';
    update opp;    
    PS_INT_IntegrationRequestController.createIntegrationRequestOpp(opps, oldopps);
    
    opp.Type = 'New Business';
    opp.Academic_Vetting_Status__c = 'Vetted - Approved';
    opp.StageName = 'Lost';
    opp.Lost_Reason__c = 'Other';
    update opp;
    PS_INT_IntegrationRequestController.createIntegrationRequestOpp(opps, oldopps);
    
    opp.StageName = 'Invoiced';
    update opp;
    PS_INT_IntegrationRequestController.createIntegrationRequestOpp(opps, oldopps);
    
    test.stopTest();
    }
  }
  
  /*************************************************************************************************************
  * Name        : verifySubmisionValidationForCases
  * Description : Verify the submissionValidationForCases method   
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifySubmisionValidationForCases()
  {  
    List<User> usrLst = TestDataFactory.createUser(Userinfo.getProfileId());
    insert usrLst;
     List <Case> cases = new List<Case>();
     List<Case> generatedCases  = new List<Case>();

    system.runas(usrLst[0]){
    generatedCases = generateTestCases(1, false);    
    cases.add(generatedCases.get(0));
    }
    
    test.startTest();
    
    PS_INT_IntegrationRequestController.submissionValidation(cases);
    
    /* This code cannot be executed as it causes a filter criteria exception on contactid 
    RecordType rt = [SELECT Id, Name FROM RecordType WHERE SobjectType='Case' and DeveloperName = 'Cancellation_Request']; 
    generatedCases.get(0).RecordTypeid = rt.id  = rt.Id;
    generatedCases.get(0).Status = 'Closed';
    update generatedCases.get(0);              
    PS_INT_IntegrationRequestController.createIntegrationRequestCase(cases);*/
    
    RecordType rt = [SELECT Id, Name FROM RecordType WHERE SobjectType='Case' and DeveloperName = 'Change_Request']; 
    generatedCases.get(0).RecordTypeid = rt.id  = rt.Id;
    generatedCases.get(0).Type = 'Change Sponsor';
    generatedCases.get(0).Status = 'Closed';
    update generatedCases.get(0);              
    PS_INT_IntegrationRequestController.createIntegrationRequestCase(cases);
    
    generatedCases.get(0).Type = 'Change Campus';
    generatedCases.get(0).Current_Campus__c = 'Bedfordview';
    generatedCases.get(0).Proposed_Campus__c = 'Durban';
    update generatedCases.get(0);              
    PS_INT_IntegrationRequestController.createIntegrationRequestCase(cases);
    
    test.stopTest();
  }
  
  /*************************************************************************************************************
  * Name        : verifyCreateIntegrationRequestOrder
  * Description : Verify the createIntegrationRequestOrder method   
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifyCreateIntegrationRequestOrder()
  {  
    List<User> usrLst = TestDataFactory.createUser(Userinfo.getProfileId());
    insert usrLst;
    
    List <PermissionSet> permList = [SELECT Id FROM PermissionSet WHERE name = 'Pearson_Backend_Order_Creation'];  
    PermissionSetAssignment psa = new PermissionSetAssignment();
    psa.AssigneeId = usrLst[1].Id;
    psa.PermissionSetId = permList[0].Id;
    insert psa;
    
    System.runas(usrLst[1])
    {
    Account acc = (Account)TestClassAutomation.createSObject('Account');
    acc.Name = 'Test';
    insert acc;
     
    contact con = (Contact)TestClassAutomation.createSObject('Contact');
    con.Lastname= 'testcon';
    con.Firstname= 'testcon1';
    con.MobilePhone = '9999';     
    insert con;     
    
    Opportunity opp = (Opportunity)TestClassAutomation.createSObject('Opportunity');
    opp.AccountId = acc.Id;
    opp.CurrencyIsoCode = 'GBP';
    opp.Lost_Reason_Other__c = 'XXX';
    insert opp;
    
    Product2 prod = (Product2)TestClassAutomation.createSObject('Product2');
    insert prod;

    Pricebook2 priceBook = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];
    priceBook.IsActive = true;
    update priceBook;
        
    PriceBookEntry sPriceBookEntry = (PriceBookEntry)TestClassAutomation.createSObject('PriceBookEntry');
    sPriceBookEntry.IsActive = true;
    sPriceBookEntry.Product2Id = prod.Id;
    sPriceBookEntry.Pricebook2Id = priceBook.Id;
    sPriceBookEntry.UnitPrice = 34.95;
    sPriceBookEntry.CurrencyIsoCode = 'GBP';
    insert sPriceBookEntry;
    
    OpportunityLineItem oli1 = new OpportunityLineItem();
    oli1.OpportunityId = opp.Id;
    oli1.PricebookEntryId = sPriceBookEntry.Id;
    oli1.TotalPrice = 200;
    oli1.Quantity = 1;
            
    insert oli1;
     
    order ord = new order();
    ord.OpportunityId=opp.Id;
    ord.Accountid = acc.Id;
    ord.EffectiveDate = system.today();
    ord.status = 'Open';
    ord.Pricebook2Id = priceBook.id;
    ord.CurrencyIsoCode = 'GBP';
    ord.Packing_Instructions__c = 'Packing Instructions';
    ord.Shipping_Instructions__c = 'Shipping instructions';
    insert ord;

    Orderitem oi = new OrderItem();
    oi.orderid=ord.id;
    oi.Shipped_Product__c = prod.id;
    oi.Quantity = 6;
    oi.pricebookentryid= sPriceBookEntry.id;
    oi.unitprice = 1.00;
    insert oi;  
    
    Orderitem oldoi = new OrderItem();
    oldoi.orderid=ord.id;
    oldoi.Shipped_Product__c = prod.id;
    oldoi.Quantity = 6;
    oldoi.pricebookentryid= sPriceBookEntry.id;
    oldoi.unitprice = 1.00;
    oldoi.Status__c = 'New';
    insert oldoi;    
    
    test.startTest();
    
    List<Order> orders = new List<Order>();
    orders.add(ord);
    Map<Id, SObject> oldorders = new Map<Id, SObject>();
    oldorders.put(ord.Id, ord); 
    PS_INT_IntegrationRequestController.createIntegrationRequestOrder(orders, oldorders);
    
    oi.Status__c = 'Cancelled';
    update oi;
    List<OrderItem> orditems = new List<OrderItem>();
    orditems.add(oi);
    Map<Id, SObject> oldorderitems = new Map<Id, SObject>();
    oldorderitems.put(oi.id, oldoi);
    PS_INT_IntegrationRequestController.createIntegrationRequestOrderLine(orditems, oldorderitems);
    
    oi.Status__c = 'Approved';
    update oi;   
    PS_INT_IntegrationRequestController.createIntegrationRequestOrderLine(orditems, oldorderitems);
    
    test.stopTest();
    }
  }

  /*************************************************************************************************************
  * Name        : generateTestCases
  * Description : Generate Cases records
  * Input       : NumOfCases - Number of case records to generate
  * Output      : List of the Case records generated
  *************************************************************************************************************/
  private static List<Case> generateTestCases(Integer numOfCases, Boolean setExternalId)
  {
    List<Case> casesToInsert = new List<Case>();
    
    //Generate an account
    Account acc = new Account(Name = 'Account 1');
    if(setExternalId)
    {
      acc.External_Account_Number__c = 'External';  
    }
    insert acc;
        
    //Generate contact
    Contact con = new Contact(LastName = 'Contact 1', FirstName = 'fn', Email = 'test@test.com.demo', AccountId = acc.Id);
    insert con;
    
    AccountContact__c accCon = new  AccountContact__c(Account__c = acc.Id, Contact__c = con.Id, AccountRole__c = 'Role', Primary__c = true, Financially_Responsible__c = True);
    insert accCon;
    
    Account_Correlation__C ac = new Account_Correlation__C(Account__C = acc.Id, External_ID_Name__c = 'eVision Learner Number', External_ID__c = 'External ID');
    insert ac;
     
    RecordType rt = [SELECT Id,Name FROM RecordType WHERE SobjectType='Case' and DeveloperName = 'Loan_Bursary_Request'];                        
    for(Integer i=0; i<numOfCases; i++)
    {    
      Case caseToInsert = new Case( AccountId = acc.Id, RecordTypeid = rt.id, Type ='General', ContactId = con.Id, Sponsor_name__c = con.Id, Reason_if_Other__c = 'Other');          
      casesToInsert.add(caseToInsert);
    }
        
    if(casesToInsert.size()>0)
    {
      insert casesToInsert;
    }
     
    return casesToInsert;
  }
  
   static testMethod void ChatterComponentTest()
  {  
        Test.startTest();
        List<User> usrLst = TestDataFactory.createUser(Userinfo.getProfileId());
        insert usrLst;
         System.runas(usrLst[0]){
         Account acc = (Account)TestClassAutomation.createSObject('Account');
         acc.Name = 'Test';
         insert acc; 
        
        Test.setCurrentPageReference(new PageReference('ChatterComponent'));
        System.currentPageReference().getParameters().put('id', acc.id);
        ChatterComponent chatCompObj = new ChatterComponent();
        chatCompObj.getRecordId();
         }
        Test.stopTest();
  }
}