src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Nearest_Pearson_Campus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the closest Pearson South Africa campus to the Student account</description>
        <label>Nearest Pearson Campus</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AccountContact__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to specify which Account is the Contacts Primary Account - updating this field updates the &apos;Account Name&apos;  field on the Contact</description>
        <label>Primary Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE:  The Account linked to the Contact</description>
        <inlineHelpText>The Account linked to the Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>CORE: The Contact linked to the Account</description>
        <inlineHelpText>The Contact linked to the Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Financially_Responsible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Financially responsible=True</description>
        <label>Financially Responsible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Relevant to D2L Model only. On a Learner account, the Learner is defaulted to the &apos;Primary&apos; on the account. There can only be one &apos;Primary&apos; contact per Learner Account</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_In_Progress__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a hidden field and is used to flag records that are being updated by the trigger to avoid firing the financial responsible person and primary contact validations. The field is used to prevent the trigger from firing an error when it is un-checking related records when the user sets a new primary or FS contact</description>
        <label>Sync In Progress</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>AOC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/primarycheckonAccountContact.cls
public class primarycheckonAccountContact{
    
    public static void togglePrimaryAndFinancialFlags(List<AccountContact__c> triggeredAccountcontacts, Map<Id, AccountContact__c> previousValuesMap) {
        List<ID> accountRecordIDs = new List<ID>();
        List<AccountContact__c> relatedAccountContactRecords = new List<AccountContact__c>();
        Map<Id, AccountContact__c> updatedAccountContactRecordsMap = new Map<Id, AccountContact__c>();
        Boolean blnInsert = (previousValuesMap == NULL);
        
        // Build the related account list
        for(AccountContact__c ac : triggeredAccountcontacts) { 
            accountRecordIDs.add(ac.Account__c);
        } // End for
        
        // Retrieve the related accounts contact records
        if (!accountRecordIDs.isEmpty())
            relatedAccountContactRecords = [SELECT Id, Account__c, Financially_Responsible__c, Primary__c 
                                            FROM AccountContact__c 
                                            WHERE Account__c IN :accountRecordIDs AND Id NOT IN :triggeredAccountcontacts];
        
        // RD-00287
        // - When an account contact is selected as primary, any previous primary records should be deselected
        // - When an account contact is selected as financially responsible, any previous FS records should be deselected
        
        // Iterate through the triggered account contact records and check the field values based on the following business logic
        for(AccountContact__c ac : triggeredAccountcontacts) { 
            
            // If either primary contact or FS checkboxes are checked, then retrieve the related account contact records
            // The record has to be updated once, otherwise the DML will fail
            if (ac.Primary__c || ac.Financially_Responsible__c) {
                for (AccountContact__c rac : relatedAccountContactRecords) {
                    if (rac.Account__c == ac.Account__c) {
                        
                        if (ac.Primary__c) {
                            if (blnInsert) {
                                system.debug(updatedAccountContactRecordsMap.size());
                                if (!updatedAccountContactRecordsMap.containsKey(rac.Id))
                                    updatedAccountContactRecordsMap.put(rac.Id, rac);
                                updatedAccountContactRecordsMap.get(rac.Id).Primary__c = FALSE;
                                updatedAccountContactRecordsMap.get(rac.Id).Sync_In_Progress__c = TRUE;
                            } else {
                                if (!previousValuesMap.get(ac.Id).Primary__c) {
                                    if (!updatedAccountContactRecordsMap.containsKey(rac.Id))
                                        updatedAccountContactRecordsMap.put(rac.Id, rac);
                                    updatedAccountContactRecordsMap.get(rac.Id).Primary__c = FALSE;
                                    updatedAccountContactRecordsMap.get(rac.Id).Sync_In_Progress__c = TRUE;
                                }
                            }
                        }
                        
                        if (ac.Financially_Responsible__c) {
                            if (blnInsert) {
                                if (!updatedAccountContactRecordsMap.containsKey(rac.Id))
                                    updatedAccountContactRecordsMap.put(rac.Id, rac);
                                updatedAccountContactRecordsMap.get(rac.Id).Financially_Responsible__c= FALSE;
                                updatedAccountContactRecordsMap.get(rac.Id).Sync_In_Progress__c = TRUE;
                            } else {
                                if (!previousValuesMap.get(ac.Id).Financially_Responsible__c) {
                                    if (!updatedAccountContactRecordsMap.containsKey(rac.Id))
                                        updatedAccountContactRecordsMap.put(rac.Id, rac);
                                    updatedAccountContactRecordsMap.get(rac.Id).Financially_Responsible__c= FALSE;
                                    updatedAccountContactRecordsMap.get(rac.Id).Sync_In_Progress__c = TRUE;
                                }
                            }
                        }
                    }
                }    
            } // End Primary/FS check
        } // End for
        
        // Update the related records
        if (!updatedAccountContactRecordsMap.isEmpty())
            Database.Update(updatedAccountContactRecordsMap.Values());
    }
    
  /*public static void updateContact(List<AccountContact__c> acList,List<AccountContact__c> oldList){
  
   List<AccountContact__c> tempacList = new List<AccountContact__c>();
   List<contact> conlist = new List<contact>();
   Map<Id,Id> tempMap = new Map<Id,Id>();
   Map<Id,AccountContact__c> tempActMap = new Map<Id,AccountContact__c>();
   Set<ID> acIds = new Set<ID>();
   List<AccountContact__c> accconlist = [select id,Account__c,Contact__c,Account_Name__c from AccountContact__c where ID IN :acList AND Contact__c <> null];
       
       for(AccountContact__c ac: accconlist ){
       
        if(ac.Account_Name__c ){
            
            tempMap.put(ac.Contact__c,ac.Account__c);
            acIds.add(ac.id);
            tempActMap.put(ac.Account__c,ac);
            
        }
       
       
       }
   
     for(Contact c : [select Id,AccountID,(select Id,Account_Name__c from Accounts__r) from Contact where Id IN :tempMap.keySet() ]){
     
        c.AccountId = tempMap.get(c.ID); 
        system.debug('############'+c.AccountId);       
        conList.add(c);
        for(AccountContact__c ac : c.Accounts__r){
            if(ac.Account_Name__c && !acIds.contains(ac.Id)){
                ac.Account_Name__c = false;
                tempacList.add(ac);
            }
        }
    }
    
    
    for(Account c : [select Id,(select Id,Account_Name__c from Contacts__r) from Account where Id IN :tempActMap.keySet() ]){
         
        for(AccountContact__c ac : c.Contacts__r){
            if(ac.Account_Name__c && !acIds.contains(ac.Id)){
                ac.Account_Name__c = false;
                tempacList.add(ac);
            }
        }
    }   
    
    
    
    
    if(!conList.isEmpty()){
        update conList;
    }
    if(!tempacList.isEmpty()){
        update tempacList;
    }
  }*/

}