src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Describes the Pearson Region that the creator of the Account is assigned to.</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Describes the Pearson &apos;Line of Business&apos; the account creator is assigned to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Event template used for Global needs</description>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Integration_Framework_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This custom setting is used by One CRM integration framework</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoB__c</fullName>
        <label>LoB</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Event__c</fullName>
        <label>Sub-Event</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_1__c</fullName>
        <label>System 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_2__c</fullName>
        <label>System 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Framework Configuration</label>
</CustomObject>

src/objects/Integration_Request__c.object
<CustomObject>
    <description>Representation of an asynchronous integration notification request</description>
    <fields>
        <fullName>Direction__c</fullName>
        <description>Direction of interaction</description>
        <label>Direction</label>
        <picklist>
            <picklistValues>
                <fullName>Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>The business event</description>
        <label>Event</label>
        <picklist>
            <controllingField>Object_Name__c</controllingField>
            <picklistValues>
                <fullName>Register Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Vetted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrol Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change to Financially Responsible Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify Order Line Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resend Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LoB__c</fullName>
        <label>LoB</label>
        <picklist>
            <picklistValues>
                <fullName>HE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K-12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>The ID of the primary object</description>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>The name of the primary object</description>
        <label>Object Name</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Line Item</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready For Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Error</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Event__c</fullName>
        <description>The name of the sub-event</description>
        <label>Sub-Event</label>
        <picklist>
            <controllingField>Event__c</controllingField>
            <picklistValues>
                <fullName>Change Module Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Module Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retake Module</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>check_responses__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used at trigger to check if the system responses need to be check to determine the status of the Integration Request</description>
        <label>check Responses</label>
        <type>Checkbox</type>
    </fields>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/System_Response__c.object
<CustomObject>
    <description>System Response used by the integration framework</description>
    <fields>
        <fullName>Error_Code__c</fullName>
        <description>The error code</description>
        <inlineHelpText>The error code</inlineHelpText>
        <label>Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>The error message</description>
        <inlineHelpText>The error message</inlineHelpText>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_System__c</fullName>
        <description>The external system name</description>
        <inlineHelpText>The external system name</inlineHelpText>
        <label>External System</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Request__c</fullName>
        <description>The linked integration request</description>
        <inlineHelpText>The linked integration request</inlineHelpText>
        <label>Integration Request</label>
        <referenceTo>Integration_Request__c</referenceTo>
        <relationshipLabel>System Responses</relationshipLabel>
        <relationshipName>System_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status</description>
        <inlineHelpText>The status</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>System Response</label>
    <nameField>
        <label>System Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IntegrationRequestTriggerTest.cls
/*******************************************************************************************************************
* Apex Class Name  : IntegrationRequestTriggerTest
* Version          : 1.0 
* Created Date     : 24 April 2015
* Function         : Test Class of the Integration Request Trigger 
* Modification Log :
*
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
*                         24/04/2015              Created Initial Version of AccountContactSyncTestClass
*******************************************************************************************************************/
@isTest  
public with sharing class IntegrationRequestTriggerTest 
{
  /*************************************************************************************************************
  * Name        : verifyInsert
  * Description : Verify the insert of Integration Request Objects         
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifyInsert()
  {
  	test.startTest();
    List<Account> generatedAccounts = generateTestAccounts(1);	
    List<Integration_Request__c> generatedIntegrationRequests = generateIntegrationRequests(1, generatedAccounts.get(0).Id );
    List<Integration_Request__c> recordsInserted = [SELECT id from Integration_Request__c];
    System.AssertEquals(recordsInserted.size(), generatedIntegrationRequests.size(), 'The IntegrationRequests were not inserted into the database');
    test.stopTest();
  }
  
  /*************************************************************************************************************
  * Name        : verifyUpdate
  * Description : Verify the updating of Integration Request Objects         
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifyUpdate()
  {
  	test.startTest();
    List<Account> generatedAccounts = generateTestAccounts(1);	
    List<Integration_Request__c> generatedIntegrationRequests = generateIntegrationRequests(2, generatedAccounts.get(0).Id );
    List<Integration_Request__c> recordsInserted = [SELECT id from Integration_Request__c];
    System.AssertEquals(recordsInserted.size(), generatedIntegrationRequests.size(), 'The IntegrationRequests were not inserted into the database');
    generatedIntegrationRequests.get(0).Status__c = 'Completed';
    update generatedIntegrationRequests.get(0);
    List<Integration_Request__c> recordsUpdated = [SELECT Status__c from Integration_Request__c];
    System.AssertEquals(recordsUpdated.get(0).Status__c, 'Completed', 'The IntegrationRequests were not updated');
    generatedIntegrationRequests.get(0).Status__c = 'Functional Error';
    update generatedIntegrationRequests.get(0);
    generatedIntegrationRequests.get(0).Status__c = 'Technical Error';
    update generatedIntegrationRequests.get(0);
    generatedIntegrationRequests.get(0).check_responses__c = true;
    System_Response__c sr = new System_Response__c(External_System__c = 'External', Error_Code__c = '-1', Error_Message__c = 'Message', Status__c = 'Status', Integration_Request__c = generatedIntegrationRequests.get(0).Id);
    insert sr;
    Integration_Framework_Configuration__c ifc = new Integration_Framework_Configuration__c(Name = 'Name', Event__c = 'Event', Geo__c = 'Geo', Lob__c = 'Lob', Market__c = 'Market', Sub_Event__c = 'Sub Event', System_1__c = 'Sys 1', System_2__c = 'Sys 2');
    insert ifc;
    update generatedIntegrationRequests.get(0);
    test.stopTest();
  }
  
  /*************************************************************************************************************
  * Name        : verifyDelete
  * Description : Verify the deleting of Integration Request Objects         
  * Input       : 
  * Output      : 
  *************************************************************************************************************/
  static testMethod void verifyDelete()
  {
  	test.startTest();
    List<Account> generatedAccounts = generateTestAccounts(1);	
    List<Integration_Request__c> generatedIntegrationRequests = generateIntegrationRequests(1, generatedAccounts.get(0).Id );
    List<Integration_Request__c> recordsInserted = [SELECT id from Integration_Request__c];
    System.AssertEquals(recordsInserted.size(), generatedIntegrationRequests.size(), 'The IntegrationRequests were not inserted into the database');
    delete generatedIntegrationRequests.get(0);
    List<Integration_Request__c> recordsDeleted = [SELECT Id from Integration_Request__c];
    System.AssertEquals(recordsDeleted.size(), 0, 'The IntegrationRequests were not deleted');
    undelete generatedIntegrationRequests.get(0);
    List<Integration_Request__c> recordsUndeleted = [SELECT Id from Integration_Request__c];
    System.AssertEquals(recordsUndeleted.size(), 1, 'The IntegrationRequests were not undeleted');
    test.stopTest();
  }
    
  /*************************************************************************************************************
  * Name        : generateIntegrationRequests
  * Description : Generate Integration Request records
  * Input       : NumOfIntegrationRequest - Number of Integration Request records to generate
  * INPUT       : The objectId to associate with the Integration Request
  * Output      : List of the Integration Request records generated
  *************************************************************************************************************/
  private static List<Integration_Request__c> generateIntegrationRequests(Integer numOfIntegrationRequests, Id objectId)
  {
   List<Integration_Request__c> integrationRequestsToInsert = new List<Integration_Request__c>();
       
    for(Integer i=0; i<numOfIntegrationRequests; i++)
    {
      Integration_Request__c integrationRequestToInsert = new Integration_Request__c(Object_Id__c = objectId);
      integrationRequestToInsert.Object_Name__c = 'Account';
      integrationRequestToInsert.Direction__c = 'Outbound';
      integrationRequestToInsert.Event__c = 'Enrol Student';
      integrationRequestToInsert.Geo__c ='Growth';
      integrationRequestToInsert.Lob__c = 'HE';
      integrationRequestToInsert.Market__c = 'ZA'; 
      integrationRequestsToInsert.add(integrationRequestToInsert);
    }
       
    if(integrationRequestsToInsert.size()>0)
    {
      insert integrationRequestsToInsert;
    }
       
    return integrationRequestsToInsert;
  }
    
  /*************************************************************************************************************
  * Name        : generateTestAccounts
  * Description : Generate Account records
  * Input       : NumOfAccounts - Number of account records to generate
  * Output      : List of the Account records generated
  *************************************************************************************************************/
  private static List<Account> generateTestAccounts(Integer numOfAccounts)
  {
    List<Account> accountsToInsert = new List<Account>();
        
    for(Integer i=0; i<numOfAccounts; i++)
    {
      Account accountToInsert = new Account(Name = 'Account' + (i+1), Market__c = 'ZA', Line_of_Business__c = 'Schools', Geography__c='Growth');
      accountsToInsert.add(accountToInsert);
    }
        
    if(accountsToInsert.size()>0)
    {
      insert accountsToInsert;
    }
     
    return accountsToInsert;
  }
}