src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Global: Used to identify specific type of organisation</description>
        <label>Type</label>
        <picklist>
            <controllingField>Organisation_Type__c</controllingField>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Occupational Skills &amp; Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fire Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Police</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defense Forces</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Court Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comprehensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-Educational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vista_Account_Number__c</fullName>
        <description>CORE Integration field - Unique ID in the VISTA system.</description>
        <inlineHelpText>Unique ID in the Socrates system.</inlineHelpText>
        <label>Vista Account Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Bookstore</fullName>
        <active>true</active>
        <description>Core: Captures Bookstore accounts from Bookmaster</description>
        <label>Bookstore</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityPearsonCourseStructure__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Junction linking Opportunities with Pearson Courses</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Pearson Course Structure</relationshipLabel>
        <relationshipName>OpportunityPearsonCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Pearson_Course_Structure__c</fullName>
        <description>This is the Pearson course structure.</description>
        <inlineHelpText>This is the Pearson course structure.</inlineHelpText>
        <label>Pearson Course Structure</label>
        <referenceTo>PearsonCourseStructure__c</referenceTo>
        <relationshipLabel>Opportunity Pearson Course Structure</relationshipLabel>
        <relationshipName>OpportunityPearsonCourseStructure</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Pearson Course Structure</label>
    <nameField>
        <displayFormat>OPC-{00000}</displayFormat>
        <label>OpportunityPearsonCourseStructure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Pearson Course Structure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityUniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - This stores the link between the Opportunity and University Course</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity University Courses</relationshipLabel>
        <relationshipName>Opportunity_University_Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <description>Opportunity Name field to hold name</description>
        <label>Opportunity Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_University_Course_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>This contains the opportunity.</description>
        <inlineHelpText>This contains the opportunity.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Courses</relationshipLabel>
        <relationshipName>OpportunityUniversityCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Rollover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Takeway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sampling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UniversityCourse__c</fullName>
        <description>This contains the University course.</description>
        <inlineHelpText>This contains the University course.</inlineHelpText>
        <label>University Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Course Opportunities</relationshipLabel>
        <relationshipName>OpportunityUniversityCourses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Course</label>
    <nameField>
        <displayFormat>OPTYUC-{00000}</displayFormat>
        <label>OpportunityUniversityCourse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PearsonCourseStructure__c.object
<CustomObject>
    <description>Pearson marketing segment codes like discipline, cluster, course</description>
    <fields>
        <fullName>Active_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Pearson course code is active or inactive.</description>
        <inlineHelpText>Indicates if the Pearson course code is active or inactive.</inlineHelpText>
        <label>Active Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Pearson_Course_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Filtered Lookup for the Parent Course Structure of a Cluster and/or Course.</description>
        <inlineHelpText>A parent must be a higher level in the Pearson Course Structure (E.g Course can&apos;t be be the parent of a Cluster)</inlineHelpText>
        <label>Parent Pearson Course Structure</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.Type__c</field>
                <operation>equals</operation>
                <value>Course</value>
            </filterItems>
            <filterItems>
                <field>PearsonCourseStructure__c.Type__c</field>
                <operation>equals</operation>
                <value>Discipline, Cluster</value>
            </filterItems>
            <filterItems>
                <field>$Source.Type__c</field>
                <operation>equals</operation>
                <value>Cluster</value>
            </filterItems>
            <filterItems>
                <field>PearsonCourseStructure__c.Type__c</field>
                <operation>equals</operation>
                <value>Discipline</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PearsonCourseStructure__c</referenceTo>
        <relationshipLabel>Pearson Course Structure</relationshipLabel>
        <relationshipName>Pearson_Course_Structure</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Describes the type of the record.</description>
        <inlineHelpText>Describes the type of the record.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Course</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discipline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cluster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Super Discipline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Pearson Course Structure</label>
    <nameField>
        <label>Pearson Course Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pearson Course Structure</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UniversityCoursePearsonCourseStructure__c.object
<CustomObject>
    <description>CORE adopted from UKHE</description>
    <fields>
        <fullName>PearsonCourseStructure__c</fullName>
        <description>This contains the Pearson course structure.</description>
        <inlineHelpText>This contains the Pearson course structure.</inlineHelpText>
        <label>Pearson Course Structure</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PearsonCourseStructure__c.Active_Indicator__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PearsonCourseStructure__c</referenceTo>
        <relationshipName>UniversityCoursePearsonCourseStructure</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UniversityCourse__c</fullName>
        <description>This contains the University course.</description>
        <inlineHelpText>This contains the University course.</inlineHelpText>
        <label>Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipName>UniversityCoursePearsonCourseStructure</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Univ Course Pearson Course</label>
    <nameField>
        <displayFormat>UCPCS-{000000}</displayFormat>
        <label>Pearson Course Code N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Univ Course Pearson Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestOpportunityCourseTrigger.cls
@isTest
private class TestOpportunityCourseTrigger {

    public static testMethod void myUnitTest() {
        Test.startTest();
        // TO DO: implement unit test
        //create the account
        String AcctRecordTypeId;
        String DiscRecordTypeId;
        String ClusterRecordTypeId;
        String OptyRecordTypeId;                        
        
        List<RecordType> RecordTypeList = new List<RecordType>([select Id,Name from RecordType]);
        
        for (RecordType i : RecordTypeList) {
          if (i.Name == 'Bookstore') {
            AcctRecordTypeId = i.Id;
          }
          if (i.Name == '3) Discipline') {
            DiscRecordTypeId = i.Id;
          }
          if (i.Name == '2) Cluster') {
            ClusterRecordTypeId = i.Id;
          }
          if (i.Name == 'Opportunity') {
            OptyRecordTypeId = i.Id;
          }                    
        }
        
        Account acct = new Account (name = 'Test1', BillingStreet = 'Street1',
                   BillingCity = 'London', BillingPostalCode = 'ABC DEF', BillingCountry = 'Australia',
                  //Vista_Account_Number__c = 'xyz',
                  RecordTypeId= AcctRecordTypeId); //'012E0000000Ll83');
        insert acct;
        
        //link account to universtiy course
        UniversityCourse__c univcrs = new UniversityCourse__c (Account__c = acct.Id, name = 'acct mgmt1');
        insert univcrs;
        
        //create pearson course structures
        PearsonCourseStructure__c disc = new PearsonCourseStructure__c (Name = 'Accounting & Taxation',
          Active_Indicator__c = True,Type__c = 'Discipline'); //,RecordTypeId = DiscRecordTypeId);
        insert disc;
        
        
        PearsonCourseStructure__c cluster = new PearsonCourseStructure__c (Name = 'Financial Accounting',
          Active_Indicator__c = True,Type__c = 'Cluster',Parent_Pearson_Course_Structure__c = disc.Id);
            //RecordTypeId = ClusterRecordTypeId );
        insert cluster;

        PearsonCourseStructure__c cluster2 = new PearsonCourseStructure__c (Name = 'Business Accounting',
          Active_Indicator__c = True,Type__c = 'Cluster',Parent_Pearson_Course_Structure__c = disc.Id);
          //RecordTypeId = ClusterRecordTypeId );
        insert cluster2;

        //associate university course to pearson course structures
        UniversityCoursePearsonCourseStructure__c univcrspearsoncrs = 
          new UniversityCoursePearsonCourseStructure__c (PearsonCourseStructure__c = cluster.Id,
            UniversityCourse__c = univcrs.Id);
        insert univcrspearsoncrs;

        UniversityCoursePearsonCourseStructure__c univcrspearsoncrs2 = 
          new UniversityCoursePearsonCourseStructure__c (PearsonCourseStructure__c = cluster2.Id,
            UniversityCourse__c = univcrs.Id);
           insert univcrspearsoncrs2;
              
        //create opportunity for account
        Opportunity opty_1 = new Opportunity (name = 'Test Opty1',Account = acct, StageName = 'Identification',
          CloseDate = System.Today(),RecordTypeId = OptyRecordTypeId );
        insert opty_1;
        
        //associate opportunity to university course
        OpportunityUniversityCourse__c optyunivcrs = new OpportunityUniversityCourse__c (Account__c=acct.id,Close_Date__c = system.today()+7,
          Opportunity_Name__c='Test',Opportunity_University_Course_Amount__c=100.00,Opportunity__c = opty_1.Id,UniversityCourse__c = univcrs.Id);
        insert optyunivcrs;
        
        //Validate that opportunity is linked to the pearson course structure associated to the university course
        OpportunityPearsonCourseStructure__c optypearsoncrs = [select Opportunity__c,Pearson_Course_Structure__c
          from OpportunityPearsonCourseStructure__c where Opportunity__c = :opty_1.Id
          and Pearson_Course_Structure__c = :cluster.Id];
        
        System.assertEquals (optypearsoncrs.Pearson_Course_Structure__c, cluster.Id);
        
        OpportunityPearsonCourseStructure__c optypearsoncrs2 = [select Opportunity__c,Pearson_Course_Structure__c
          from OpportunityPearsonCourseStructure__c where Opportunity__c = :opty_1.Id
          and Pearson_Course_Structure__c = :cluster2.Id];
        
        System.assertEquals (optypearsoncrs2.Pearson_Course_Structure__c, cluster2.Id);

        //associate opportunity to university course again
        //OpportunityUniversityCourse__c optyunivcrs_1 = new OpportunityUniversityCourse__c (
       //  Opportunity__c = opty_1.Id,UniversityCourse__c = univcrs.Id);
        //insert optyunivcrs_1;
        
        //Validate that opportunity is linked to the pearson course structure associated to the university course
        OpportunityPearsonCourseStructure__c optypearsoncrs3 = [select Opportunity__c,Pearson_Course_Structure__c
          from OpportunityPearsonCourseStructure__c where Opportunity__c = :opty_1.Id
          and Pearson_Course_Structure__c = :cluster.Id];
        
        System.assertEquals (optypearsoncrs3.Pearson_Course_Structure__c, cluster.Id);
        
        OpportunityPearsonCourseStructure__c optypearsoncrs4 = [select Opportunity__c,Pearson_Course_Structure__c
          from OpportunityPearsonCourseStructure__c where Opportunity__c = :opty_1.Id
          and Pearson_Course_Structure__c = :cluster2.Id];
        
        System.assertEquals (optypearsoncrs4.Pearson_Course_Structure__c, cluster2.Id);        
                
        Test.stopTest();
    }
}