src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Describes the Pearson &apos;Line of Business&apos; the account creator is assigned to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Identifies the Course for the Asset</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Course is not associated to the Account for this Product in Use.</errorMessage>
            <filterItems>
                <field>UniversityCourse__c.Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Products in Use</relationshipLabel>
        <relationshipName>Products_In_Use</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if Product in Use is Primary for a University Course</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Author__c</fullName>
        <label>Product Author</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Asset for NA and SA.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>Used to capture the Market of the Contact Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>CTIMGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Field Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Indicates which Market is utilizing this product.</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Author__c</fullName>
        <description>Cretaed To Refer Author Field.</description>
        <formula>Author__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product_Author</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TU</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Catalog_Code__c</fullName>
        <label>Catalog Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <description>Name of the course at the university or department.</description>
        <inlineHelpText>Name of the course at the university or department.</inlineHelpText>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>To show whether a University Course is Active or Not</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>The business unit the user is assigned to within Pearson</description>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>CTIMGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Field Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The user&apos;s line of business</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price_List__c</fullName>
        <description>Associated Price List, Sales Force</description>
        <label>Price List</label>
        <picklist>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Humanities &amp; Social Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Math &amp; Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional &amp; Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US HE All</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BulkPIUEditControllerTest.cls
/**
 * Name : BulkPIUEditControllerTest 
 * Author : Accenture
 * Description : Test class used for testing the BulkPIUEditController
 * Date : 7/01/15 
 * Version : <intial Draft> 
 */


@isTest
public class BulkPIUEditControllerTest
{

    static testMethod void testUpdateContactList(){
    test.startTest();
    
    List<User> listWithUser = new List<User>();
    listWithUser  = TestDataFactory.createUser([select Id from Profile where Name =: 'System Administrator'].Id,1);
    if(listWithUser != null && !listWithUser.isEmpty())
    {
        listWithUser[0].Market__c = 'US';
        listWithUser[0].Price_List__c = 'Math & Science';
        listWithUser[0].Business_Unit__c = 'US Field Sales';
        insert listWithUser;
    }
    
    Boolean selected=false;
    
    List<Account> accountList =new List<Account>();
    List<AssetWrapper> asw= new List<AssetWrapper>();
    
    accountList=TestDataFactory.createAccount(1,'Direct SPH Inter-Division');
    insert accountList ;
    List<Contact> contactList=TestDataFactory.createContact(1);
    insert contactList;
    UniversityCourse__c course=new UniversityCourse__c(Name='T0001-kyama',Catalog_Code__c='T0001',Course_Name__c='kyama',Account__c= accountList[0].Id);
    insert course;
    system.runAs(listWithUser[0]){
    Product2 prod=new Product2 (Name='testProd',Market__c='US',Business_Unit__c='US Field Sales',Line_of_Business__c='Higher Ed');
    insert prod;
    
    Asset ass = new Asset(Product2id=prod.id,status__c='Active',Name='kyama',Product_Author__c='Kyama',AccountId= accountList[0].Id,ContactId=contactList[0].id,Course__c=course.id);
    insert ass;
    
    Asset ass1 = new Asset(Product2id=prod.id,primary__c = true,status__c='Active',Name='kyama',Product_Author__c='Kyama',AccountId= accountList[0].Id,ContactId=contactList[0].id,Course__c=course.id);
    insert ass1;
    
    BulkPIUEditController.AssetsWrapper wp = new BulkPIUEditController.AssetsWrapper(ass,true);
    
    system.assert(ass.Product_Author__c!=null);
    
   } 
    
    test.stopTest();
    PageReference pageRef = Page.BulkContactPIUEditPage;
    Test.setCurrentPage(pageRef);
    ApexPages.currentPage().getParameters().put('courseId', course.Id);
    BulkPIUEditController testBulk = new BulkPIUEditController();
    testBulk.schangedcId = contactList[0].Id;
    testBulk.schangedflg = false;
    testBulk.getPIUContacts();
     List<BulkPIUEditController.AssetsWrapper> s = new  List<BulkPIUEditController.AssetsWrapper>();
    testBulk.assetList = s; 
    testBulk.getAsset();
    testBulk.getProductIdWithName();
    testBulk.getAssetSelected();
    testBulk.updateContactList();
    testBulk.courseCancelDetailPage();
    //system.assert(testBulk.editAll());
    testBulk.selectedAssets.clear();
    testBulk.getSelectedAssets();
    
    

}
 }