src/objects/AccountContact__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>AccountRole__c</fullName>
        <description>The role the contact plays on this account</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Educator</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE:  The Account linked to the Contact</description>
        <inlineHelpText>The Account linked to the Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>CORE: The Contact linked to the Account</description>
        <inlineHelpText>The Contact linked to the Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Financially_Responsible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Financially responsible=True</description>
        <label>Financially Responsible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Relevant to D2L Model only. On a Learner account, the Learner is defaulted to the &apos;Primary&apos; on the account. There can only be one &apos;Primary&apos; contact per Learner Account</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Detail__c</fullName>
        <description>Detailed information on the role</description>
        <label>Role Detail</label>
        <picklist>
            <controllingField>AccountRole__c</controllingField>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assc. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asst. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chairman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Learning Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emeritus Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjunct Faculty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visiting Lecturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lab Technician/Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secretary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>AOC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role_Detail__c</fullName>
        <label>Role Detail</label>
        <picklist>
            <controllingField>Role__c</controllingField>
            <picklistValues>
                <fullName>Adjunct Faculty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assc. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asst. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chairman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Learning Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emeritus Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visiting Lecturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lab Technician/Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secretary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Educator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestAccountContactTriggers.cls
/*
         *@name TestAccountContactTriggers() 
         *@return void 
         *@description This method for myUnitTest In CLASS AccountcontactTriggerhandler .cls
         *@description This method for myUnitTest In trigger AccountContact.Triggers
         */



    @isTest
    private class TestAccountContactTriggers
    {
        static testMethod void myUnitTest()
        {
            
            TestClassAutomation.FillAllFields = true;
            
            Account sAccount                = (Account)TestClassAutomation.createSObject('Account');
            sAccount.BillingCountry         = 'Australia';
            sAccount.BillingState           = 'Victoria';
            sAccount.BillingCountryCode     = 'AU';
            sAccount.BillingStateCode       = 'VIC';
            sAccount.ShippingCountry        = 'Australia';
            sAccount.ShippingState          = 'Victoria';
            sAccount.ShippingCountryCode    = 'AU';
            sAccount.ShippingStateCode      = 'VIC';
            
            insert sAccount;
            
            Contact sContact                = (Contact)TestClassAutomation.createSObject('Contact');
            sContact.AccountId              = sAccount.Id;
            sContact.OtherCountry           = 'Australia';
            sContact.Role__c                   = 'Educator';
            sContact.Role_Detail__c         = 'Director';
            sContact.OtherState             = 'Victoria';
            sContact.OtherCountryCode       = 'AU';
            sContact.OtherStateCode         = 'VIC';
            sContact.MailingCountry         = 'Australia';
            sContact.MailingState           = 'Victoria';
            sContact.MailingCountryCode     = 'AU';
            sContact.MailingStateCode       = 'VIC';
                
            Test.startTest();
                
                insert sContact;
                
            checkRecurssion.run = true;    
            AccountContact__c accContObj = new AccountContact__c();
            accContObj.Contact__c = sContact.id;
            accContObj.Account__c = sAccount.id;
            accContObj.AccountRole__c= 'Educator';
            accContObj.Role_Detail__c= 'Director';
            insert accContObj;

             checkRecurssion.run = true; 
            accContObj.Role_Detail__c= 'Dean';
            update accContObj;

                checkRecurssion.run = true; 
            delete accContObj;

            


            
             
                
    AccountContactTriggerHandler testa= new AccountContactTriggerHandler(true,5);
     

     AccountContact__c[] accnt;
     
    //accnt = [Select Id,AccountContact__c.Primary__c,account__c,contact__c,AccountRole__c,Financially_Responsible__c  FROM AccountContact__c WHERE Contact__c = : sContact.Id limit 1];
                // testa.OnBeforeInsert(accnt);
                
    //if(accnt!=null){         testa.OnAfterInsert(accnt);}
                 
            Test.stopTest();
        }
       Static testmethod void myUnitTest_1(){
             TestClassAutomation.FillAllFields = true;
            
            Account sAccount                = (Account)TestClassAutomation.createSObject('Account');
            sAccount.BillingCountry         = 'Australia';
            sAccount.BillingState           = 'Victoria';
            sAccount.BillingCountryCode     = 'AU';
            sAccount.BillingStateCode       = 'VIC';
            sAccount.ShippingCountry        = 'Australia';
            sAccount.ShippingState          = 'Victoria';
            sAccount.ShippingCountryCode    = 'AU';
            sAccount.ShippingStateCode      = 'VIC';
            
            insert sAccount;
            
            Contact sContact                = (Contact)TestClassAutomation.createSObject('Contact');
            sContact.AccountId              = sAccount.Id;
            sContact.OtherCountry           = 'Australia';
            sContact.OtherState             = 'Victoria';
            sContact.Role__c                = 'Educator';
            sContact.Role_Detail__c         = 'Director';
            sContact.OtherCountryCode       = 'AU';
            sContact.OtherStateCode         = 'VIC';
            sContact.MailingCountry         = 'Australia';
            sContact.MailingState           = 'Victoria';
            sContact.MailingCountryCode     = 'AU';
            sContact.MailingStateCode       = 'VIC';
                
            Test.startTest();
                
               insert sContact;
               
                checkRecurssion.run = true;    
            AccountContact__c accContObj = new AccountContact__c();
            accContObj.Contact__c = sContact.id;
            accContObj.Account__c = sAccount.id;
             accContObj.AccountRole__c= 'Educator';
            accContObj.Role_Detail__c= 'Director';
            insert accContObj;

             checkRecurssion.run = true; 
            accContObj.Role_Detail__c= 'Dean';
            update accContObj;
            
            checkRecurssion.run = true; 
            delete accContObj;


            
           
             //AccountContact__c sAccountContact = [Select Id,AccountContact__c.Primary__c,account__c,contact__c,AccountRole__c,Financially_Responsible__c FROM AccountContact__c WHERE Contact__c = : sContact.Id limit 1];
             
    AccountContactTriggerHandler testa= new AccountContactTriggerHandler(true,5);
    System.assertEquals(true,  testa.bIsTriggerContext);  
               System.assertEquals(false,  testa.bIsVisualforcePageContext,false);   
               System.assertEquals(false, testa.bIsWebServiceContext,false);  
               System.assertEquals(false,  testa.bIsExecuteAnonymousContext,false); 
     AccountContact__c[] accnt;
     accnt = [Select Id,AccountContact__c.Primary__c,account__c,contact__c,AccountRole__c,Financially_Responsible__c  FROM AccountContact__c WHERE Contact__c = : sContact.Id limit 1];

    AccountContact__c[] accntol;
         map<id,AccountContact__c> acc =new map<id,AccountContact__c>();
         //acc = [Select Id,AccountContact__c.Primary__c,account__c,contact__c,AccountRole__c,Financially_Responsible__c  FROM AccountContact__c WHERE Contact__c = : sContact.Id limit 1];

         map<id,AccountContact__c> acccon =new map<id,AccountContact__c>();
        
         testa.OnBeforeinsert(accnt);

             
             
             Test.stopTest();
                
         }  
    }