src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Account Region. Dependent on Geography.</description>
        <label>Region</label>
        <picklist>
            <controllingField>Geography__c</controllingField>
            <picklistValues>
                <fullName>UK - North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK - South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scandi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Israel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Global: Used to identify specific type of organisation</description>
        <label>Type</label>
        <picklist>
            <controllingField>Organisation_Type__c</controllingField>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Occupational Skills &amp; Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fire Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Police</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defense Forces</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Court Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comprehensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-Educational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Corporate</fullName>
        <active>true</active>
        <description>CORE - Used to Corporate Accounts</description>
        <label>Corporate</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pearson_Course_Equivalent__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Identifies if the association between the  Course and the Pearson Course Code is Active.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <description>This contains the Course.</description>
        <inlineHelpText>This contains the Course.</inlineHelpText>
        <label>Course/Catalog Code</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Pearson Course Equivalent</relationshipLabel>
        <relationshipName>Pearson_Course_Equivalent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Pearson_Course_Code__c</fullName>
        <description>This contains the Pearson Course Code.</description>
        <inlineHelpText>This contains the Pearson Course Code.</inlineHelpText>
        <label>Pearson Course Code</label>
        <referenceTo>Apttus_Config2__ClassificationHierarchy__c</referenceTo>
        <relationshipLabel>Pearson Course Equivalent</relationshipLabel>
        <relationshipName>Pearson_Course_Equivalent</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate that the Pearson Course Code is the Primary Pearson Course Code for the Course.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Pearson Course Equivalent</label>
    <nameField>
        <displayFormat>CPCS-{000000}</displayFormat>
        <label>Pearson Course Equivalent	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pearson Course Equivalent</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To show whether a University Course is Active or Not</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Adoption_Type__c</fullName>
        <description>Indicates whether the University Course Products in Use is decided by a Committee or Individual</description>
        <label>Adoption Type</label>
        <picklist>
            <picklistValues>
                <fullName>Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual Choice</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <description>Name of the course at the university or department.</description>
        <inlineHelpText>Name of the course at the university or department.</inlineHelpText>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fall_Enrollment__c</fullName>
        <description>Course enrollment for the fall semester.</description>
        <inlineHelpText>Course enrollment for the fall semester.</inlineHelpText>
        <label>Fall</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fall_Front_List__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fall Front List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Spring_Enrollment__c</fullName>
        <description>Course enrollment for the spring semester.</description>
        <inlineHelpText>Course enrollment for the spring semester.</inlineHelpText>
        <label>Spring</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spring_Front_List__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Spring Front List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Winter_Enrollment__c</fullName>
        <description>Course Enrollment for the Winter Semester</description>
        <inlineHelpText>Course Enrollment for the Winter Semester</inlineHelpText>
        <label>Winter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PS_BatchUpdateCoursesFrontlists_Test.cls
/**
 * Name : PS_BatchUpdateCoursesFrontlists_Test 
 * Author : Accenture
 * Description : Test class used for testing the PS_BatchUpdateCoursesFrontlists
 * Date : 7/01/15 
 * Version : <intial Draft> 
 */
@isTest
public class PS_BatchUpdateCoursesFrontlists_Test {

    static testmethod void testBatchUpdateCourses()
    { 
        List<Account> accList = TestDataFactory.createAccount(2,'Direct Corporate');
        insert accList;
        
        UniversityCourse__c unvobject = new UniversityCourse__c(); 
        unvobject.Account__c = accList[0].Id;
        unvobject.Active__c = true;
        unvobject.Name = 'Test Univ course Name';
        unvobject.Adoption_Type__c = 'committee';
        unvobject.Course_Name__c = 'Test course Name';
        unvobject.Fall_Enrollment__c = 121;
        unvobject.Spring_Enrollment__c = 110;
        unvobject.Winter_Enrollment__c = 415;
        unvobject.Fall_Front_List__c= true;
        unvobject.Spring_Front_List__c= true;
        integer iMonth = system.today().month();
               // unvobject.  = Course
      // unvobject.
          insert unvobject;
        List<UniversityCourse__c> lstUnivcourse = new List<UniversityCourse__c>();
       // lstUnivcourse.add(unvobject);
       // lstUnivcourse.clear();
        Apttus_Config2__ClassificationName__c category = new Apttus_Config2__ClassificationName__c(Name='testcategoryy',Apttus_Config2__HierarchyLabel__c='testlabele');
        insert category; 
        Apttus_Config2__ClassificationHierarchy__c csa =new Apttus_Config2__ClassificationHierarchy__c(name ='estt',Apttus_Config2__HierarchyId__c=category.id,Apttus_Config2__Label__c='testlabel');
        csa.Region__c = 'US';
        csa.Type__c ='Course';
        csa.Current_Period__c = true;
        csa.Prior_Period__c = true;
        insert csa;                 
        Pearson_Course_Equivalent__c  pcourseObject = new Pearson_Course_Equivalent__c();
        pcourseObject.Course__c  =unvobject.Id;
        pcourseObject.Active__c = true;  
        pcourseObject.Primary__c =true;
        pcourseObject.Pearson_Course_Code__c = csa.Id;
       
        insert pcourseObject;
        
     PS_BatchUpdateCoursesFrontlists batchObject = new PS_BatchUpdateCoursesFrontlists('US',unvobject.Id, true);   
      Test.startTest();  
      database.executeBatch(batchObject) ; 
   //  system.schedule();
     SchedulableContext sc = null;
     // tsc.execute(sc);
     batchObject.execute(sc);
        Test.stopTest();
     
    }
    
}