src/objects/AccountContact__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>AccountRole__c</fullName>
        <description>The role the contact plays on this account</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Educator</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to specify which Account is the Contacts Primary Account - updating this field updates the &apos;Account Name&apos;  field on the Contact</description>
        <label>Primary Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE:  The Account linked to the Contact</description>
        <inlineHelpText>The Account linked to the Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>CORE: The Contact linked to the Account</description>
        <inlineHelpText>The Contact linked to the Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <description>CORE: If the linked account on the contact record is the same as the linked record to this junction object the checkbox will be true</description>
        <formula>IF(Contact__r.Account.Id = Account__r.Id, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Indicates if this is the contact&apos;s primary account.</inlineHelpText>
        <label>Primary Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role_Detail__c</fullName>
        <description>Detailed information on the role</description>
        <label>Role Detail</label>
        <picklist>
            <controllingField>AccountRole__c</controllingField>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assc. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asst. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chairman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Learning Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emeritus Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adjunct Faculty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visiting Lecturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lab Technician/Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secretary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>AOC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mobile_Last_Updated__c</fullName>
        <description>Used to track when fields were last updated on the mobile app.</description>
        <label>Mobile Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Role_Detail__c</fullName>
        <label>Role Detail</label>
        <picklist>
            <controllingField>Role__c</controllingField>
            <picklistValues>
                <fullName>Adjunct Faculty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assc. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asst. Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chairman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Learning Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emeritus Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instructor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visiting Lecturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Chairperson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lab Technician/Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secretary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Educator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PrimaryAccountUtilities.cls
public with sharing class PrimaryAccountUtilities 
{
  public static void updateRoleInformationOnAccountContact(Contact[] lstOldContacts, Contact[] lstNewContacts, map<ID, Contact> NewMapIDContact, map<ID, Contact> oldMapIDContact)
  { 
    List <AccountContact__c> accountContactsToUpdate = new List<AccountContact__c>();
     Map<Id , List<AccountContact__c>> accContMap = new  Map<Id , List<AccountContact__c>>();
    
    for(AccountContact__c accContactObj : [select Id, Account_Name__c, Primary_Account__c, AccountRole__c, Role_Detail__c,Contact__c from AccountContact__c where Contact__c in :NewMapIDContact.keySet()]){
            if(accContMap.containsKey(accContactObj.Contact__c)){
                accContMap.get(accContactObj.Contact__c).add(accContactObj);
            }
            
            else{
                List<AccountContact__c> tempLst = new List<AccountContact__c>();
                tempLst.add(accContactObj);
                accContMap.put(accContactObj.Contact__c,tempLst);
            }
          
            
    }
    
    for(Contact con : lstNewContacts)
    {
      Contact oldContact = oldMapIDContact.get(con.Id);
      
      if((con.role__c != null && !con.Role__c.equals(oldContact.Role__c)) || (con.Role_Detail__c != null && !con.Role_Detail__c.equals(oldContact.Role_Detail__c)) || (con.AccountId != oldContact.AccountId))
      {
        //Contact c = [select Id, (select Id, Account_Name__c, Primary_Account__c, AccountRole__c, Role_Detail__c from Accounts__r) from Contact where Id = :con.Id];
        if(accContMap.containsKey(con.id)){
            for(AccountContact__c ac : accContMap.get(con.id))
            {
              if(ac.Primary_Account__c)
              {  
                Boolean changed = false;
                if(!con.Role__c.equals(ac.AccountRole__c))
                {
                  ac.AccountRole__c = con.Role__c;
                  changed = true;
                }
                if(con.Role_Detail__c != ac.Role_Detail__c)
                {
                  ac.Role_Detail__c = con.Role_Detail__c;
                  changed = true;
                }
            
                if(changed)
                {
                  accountContactsToUpdate.add(ac);
                  changed = false;
                }
              }
            }
        }
      }
    }
    if(!accountContactsToUpdate.isEmpty())
    {
      update accountContactsToUpdate;
    }
  }
  
  public static void updateRoleInformationOnContact(AccountContact__c[] lstOldAccountContacts, AccountContact__c[] lstNewAccountContacts, map<ID, AccountContact__c> mapNewIDAccountContact, map<ID, AccountContact__c> mapOldIDAccountContact)
  { 
    List <Contact> contactsToUpdate = new List<Contact>();
    Set<Id> contIdSet = new Set<Id>();
    
    for(AccountContact__c accConObj :lstNewAccountContacts){
        contIdSet.add(accConObj.Contact__c);
        
    }

    Map<Id,Contact> mapContact = new Map<Id,Contact>([SELECT id, Role__c, Role_Detail__c FROM Contact WHERE Id in:contIdSet]);
            
  
    for(AccountContact__c ac : lstNewAccountContacts)
    {
      if(ac.Primary_Account__c)
      {
        AccountContact__c oldAccountContact = mapOldIDAccountContact.get(ac.Id);
        if((ac.AccountRole__c != null && !ac.AccountRole__c.equals(oldAccountContact.AccountRole__c)) || (ac.Role_Detail__c != null && !ac.Role_Detail__c.equals(oldAccountContact.Role_Detail__c)))
        {
          boolean changed = false; 
          //Contact c = [SELECT id, Role__c, Role_Detail__c FROM Contact WHERE Id = : ac.Contact__c];
          if(mapContact.containsKey(ac.Contact__c)){
              if(!ac.AccountRole__c.equals(mapContact.get(ac.Contact__c).Role__c)) 
              {
                mapContact.get(ac.Contact__c).Role__c = ac.AccountRole__c;
                changed = true;
              }
              if(ac.Role_Detail__c != mapContact.get(ac.Contact__c).Role_Detail__c) 
              {
                mapContact.get(ac.Contact__c).Role_Detail__c = ac.Role_Detail__c;
                changed = true;
              }
              if(changed)
              {
                contactsToUpdate.add(mapContact.get(ac.Contact__c));
                changed = false;
              }
          }
        }
      }
    }
    if(!contactsToUpdate.isEmpty())
    {
      update contactsToUpdate;
    }
  }  

  public static void checkAccountContactExists(Contact[] lstNewContacts)
  {
    List <AccountContact__c> accountContactsToInsert = new List<AccountContact__c>();
    
    Map<Id , List<AccountContact__c>> accContMap = new  Map<Id , List<AccountContact__c>>();
    
    for(AccountContact__c accContactObj : [select Id, Account_Name__c, Account__c ,Primary_Account__c, AccountRole__c, Role_Detail__c,Contact__c from AccountContact__c where Contact__c in :lstNewContacts]){
            if(accContMap.containsKey(accContactObj.Contact__c)){
                accContMap.get(accContactObj.Contact__c).add(accContactObj);
            }
            
            else{
                List<AccountContact__c> tempLst = new List<AccountContact__c>();
                tempLst.add(accContactObj);
                accContMap.put(accContactObj.Contact__c,tempLst);
            }
          
            
    }
    
    
    
    for(Contact con : lstNewContacts)
    {
      //Contact c = [select Id, (select Id, Account_Name__c,Account__c , Primary_Account__c, AccountRole__c, Role_Detail__c, Account__c from Accounts__r) from Contact where Id = :con.Id];
      boolean foundAccount = false;
      if(accContMap.containsKey(con.Id)){
          for(AccountContact__c ac : accContMap.get(con.Id))
          {
            if(ac.Account__c == con.AccountId)
            {
              foundAccount = true;
              break;
            }
          }
      }
      if(!foundAccount  && con.Mobile_Last_Updated__c == null)
      {
        AccountContact__c newac = new AccountContact__c();
        newac.Account__c = con.AccountId;
        newac.Contact__c = con.Id;
        newac.AccountRole__c = con.Role__c;
        newac.Role_Detail__c = con.Role_Detail__c;
        accountContactsToInsert.add(newac);
      }
      foundAccount=false;
    }
    
    if(!accountContactsToInsert.isEmpty())
    {
      insert accountContactsToInsert;
    }
  }

}