src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Account Region. Dependent on Geography.</description>
        <label>Region</label>
        <picklist>
            <controllingField>Geography__c</controllingField>
            <picklistValues>
                <fullName>UK - North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK - South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scandi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Israel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Global: Used to identify specific type of organisation</description>
        <label>Type</label>
        <picklist>
            <controllingField>Organisation_Type__c</controllingField>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Occupational Skills &amp; Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fire Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Police</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defense Forces</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Court Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comprehensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-Educational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookstore</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PearsonCourseStructure__c.object
<CustomObject>
    <description>Pearson marketing segment codes like discipline, cluster, course</description>
    <fields>
        <fullName>Active_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Pearson course code is active or inactive.</description>
        <inlineHelpText>Indicates if the Pearson course code is active or inactive.</inlineHelpText>
        <label>Active Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Pearson_Course_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Filtered Lookup for the Parent Course Structure of a Cluster and/or Course.</description>
        <inlineHelpText>A parent must be a higher level in the Pearson Course Structure (E.g Course can&apos;t be be the parent of a Cluster)</inlineHelpText>
        <label>Parent Pearson Course Structure</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.Type__c</field>
                <operation>equals</operation>
                <value>Course</value>
            </filterItems>
            <filterItems>
                <field>PearsonCourseStructure__c.Type__c</field>
                <operation>equals</operation>
                <value>Discipline, Cluster</value>
            </filterItems>
            <filterItems>
                <field>$Source.Type__c</field>
                <operation>equals</operation>
                <value>Cluster</value>
            </filterItems>
            <filterItems>
                <field>PearsonCourseStructure__c.Type__c</field>
                <operation>equals</operation>
                <value>Discipline</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PearsonCourseStructure__c</referenceTo>
        <relationshipLabel>Pearson Course Structure</relationshipLabel>
        <relationshipName>Pearson_Course_Structure</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pearson_Course_Structure_Code__c</fullName>
        <description>Contains the code of the Pearson course structure.</description>
        <externalId>true</externalId>
        <inlineHelpText>Contains the code of the Pearson course structure.</inlineHelpText>
        <label>Pearson Course Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pearson_Course_Structure_Name__c</fullName>
        <description>Description for the Pearson course structure.</description>
        <inlineHelpText>Description for the Pearson course structure.</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Describes the type of the record.</description>
        <inlineHelpText>Describes the type of the record.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Course</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discipline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cluster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Super Discipline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Pearson Course Structure</label>
    <nameField>
        <label>Pearson Course Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pearson Course Structure</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Midran</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>X</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Y</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Z</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestData.cls
/*
 *Author: Matt Hime (tquila)
 *Date: 21/8/2012
 *Description:  Data creation class for use by any and all test methods
 *              Add new methods to create objects as required.
 */
 
 public with sharing class TestData {
    
    /*
     *Build an account with just enough data to save to the db
     */
    public static Account buildAccount(string accountName){
        Account a = new Account();
        a.Name = accountName;
        a.BillingCity = 'The Big Smoke';
        a.BillingCountry = 'Australia';
        a.BillingPostalCode = 'VA23454';
        a.Type = 'University';
        return a;
    }
    
    /*
     *Build an opportunity with just enough data to save to the db
     */
    public static Opportunity buildOpportunity(Id accId){
        Opportunity o = new Opportunity();
        o.Name = 'Test Opp';
        o.AccountId = accId;
        o.StageName = 'Identification';
        o.CloseDate = date.today().addDays(1);
        return o;
    }
    
    /*
     *Build an University Course with just enough data to save to the db
     */
    public static UniversityCourse__c buildUniversityCourse(Id accId){
        UniversityCourse__c u = new UniversityCourse__c();
        u.Account__c = accId;
        
        return u;
    }
    
    /*
     *Build PearsonCourseStructure__c objects
     *parentIds can be null, in which case,  these are top tier items
     *to create,  we need to know what kind of PCS is being requested - courseType
     *itemName is just a useful identifier provided by the user as part of the object Name
     */
    public static PearsonCourseStructure__c[] buildPearsonCourseStructure(Id[] parentIds, integer howMany, string courseType, string itemName){
        //Get the record type based upon the type specified by the user
        //string recordTypeLikeName = '%' + courseType + '%';
        
        //RecordType[] rt = [select Id, Name
        //                    from RecordType
        //                    where SobjectType = 'PearsonCourseStructure__c'
        //                    and Name like :recordTypeLikeName];
        //Make sure this has returned just one record
        //system.assertEquals(1, rt.size(), 'Problem finding PearsonCourseStructure__c recordtype for ' + courseType);
        
        list<PearsonCourseStructure__c> courses = new list<PearsonCourseStructure__c>();
        
        //If these items are top of the heap,  we don't need to add parent ids
        if(parentIds == null){
            for(integer i = 0 ; i < howMany ; i++){
                //courses.add(buildSinglePearsonCourseStructure(null, itemName, courseType, rt[0].Id, i));
                courses.add(buildSinglePearsonCourseStructure(null, itemName, courseType, i));
            }
        }
        else{
            //If they're child items,  loop though each parent and add the id to the item as it's created
            for(Id parent : parentIds){
                for(integer i = 0 ; i < howMany ; i++){
                    //courses.add(buildSinglePearsonCourseStructure(parent, itemName, courseType, rt[0].Id, i));
                    courses.add(buildSinglePearsonCourseStructure(parent, itemName, courseType, i));
                }
            }
        }
        
        return courses;
    }
    
    /*
     *A course has a couple of extra items of data,  so,  call the generic PCS builder first and then add to it
     */
    public static PearsonCourseStructure__c[] buildPearsonCourse(Id[] parentIds, integer howMany, string itemName){
        PearsonCourseStructure__c[] courses = buildPearsonCourseStructure(parentIds, howMany, 'Course', itemName);
        
        integer i = 0;
        for(PearsonCourseStructure__c item : courses){
            item.Pearson_Course_Structure_Name__c = item.Name;
            item.Pearson_Course_Structure_Code__c = 'XXX' + datetime.now().millisecond() + i++;
        }
        
        return courses;
    }
    
    /*
     *Build a SINGLE generic PearsonCourseStructure__c object
     */
    //private static PearsonCourseStructure__c buildSinglePearsonCourseStructure(Id parentId, string itemName, string courseType, Id recordType, integer itemCount){
     private static PearsonCourseStructure__c buildSinglePearsonCourseStructure(Id parentId, string itemName, string courseType, integer itemCount){
        
        PearsonCourseStructure__c pcs = new PearsonCourseStructure__c();
        pcs.Active_Indicator__c = true;
        pcs.Type__c = courseType;
        //pcs.RecordTypeId = recordType;
        pcs.Name = itemName + string.valueOf(itemCount);
        pcs.Parent_Pearson_Course_Structure__c = parentId;
        
        return pcs;
    }
    
    
    public static Apttus_Config2__ClassificationName__c buildCategories(){
        
        Apttus_Config2__ClassificationName__c cat = new Apttus_Config2__ClassificationName__c(Name = 'TestCat', Apttus_Config2__HierarchyLabel__c = 'TestCat', Apttus_Config2__Active__c = true);
        insert cat;
        return cat;
    }
    
    private static Apttus_Config2__ClassificationHierarchy__c buildSingleClassificationHierarchy(Id parentId, string itemName, string courseType, integer itemCount){
        
        Apttus_Config2__ClassificationHierarchy__c pcs = new Apttus_Config2__ClassificationHierarchy__c();
        //pcs.Active_Indicator__c = true;
        pcs.Type__c = courseType;
        //pcs.RecordTypeId = recordType;
        pcs.Name = itemName + string.valueOf(itemCount);
        pcs.Apttus_Config2__AncestorId__c = parentId;
        pcs.Apttus_Config2__Label__c = itemName + string.valueOf(itemCount);
        pcs.Apttus_Config2__HierarchyId__c = buildCategories().Id;
        pcs.Region__c = 'US';
        return pcs;
    }
    public static Apttus_Config2__ClassificationHierarchy__c[] buildClassificationHier(Id[] parentIds, integer howMany, string courseType, string itemName){
        //Get the record type based upon the type specified by the user
        //string recordTypeLikeName = '%' + courseType + '%';
        
        //RecordType[] rt = [select Id, Name
        //                    from RecordType
        //                    where SobjectType = 'PearsonCourseStructure__c'
        //                    and Name like :recordTypeLikeName];
        //Make sure this has returned just one record
        //system.assertEquals(1, rt.size(), 'Problem finding PearsonCourseStructure__c recordtype for ' + courseType);
        
        list<Apttus_Config2__ClassificationHierarchy__c> courses = new list<Apttus_Config2__ClassificationHierarchy__c>();
        
        //If these items are top of the heap,  we don't need to add parent ids
        if(parentIds == null){
            for(integer i = 0 ; i < howMany ; i++){
                //courses.add(buildSinglePearsonCourseStructure(null, itemName, courseType, rt[0].Id, i));
                courses.add(buildSingleClassificationHierarchy(null, itemName, courseType, i));
            }
        }
        else{
            //If they're child items,  loop though each parent and add the id to the item as it's created
            for(Id parent : parentIds){
                for(integer i = 0 ; i < howMany ; i++){
                    //courses.add(buildSinglePearsonCourseStructure(parent, itemName, courseType, rt[0].Id, i));
                    courses.add(buildSingleClassificationHierarchy(parent, itemName, courseType, i));
                }
            }
        }
        
        return courses;
    }
    
    public static Apttus_Config2__ClassificationHierarchy__c[] buildPearsonCourseHier(Id[] parentIds, integer howMany, string itemName){
        Apttus_Config2__ClassificationHierarchy__c[] courses = buildClassificationHier(parentIds, howMany, 'Course', itemName);
        
        integer i = 0;
        for(Apttus_Config2__ClassificationHierarchy__c item : courses){
            item.Pearson_Course_Structure_Name__c = item.Name;
            item.Pearson_Course_Structure_Code__c = 'XXX' + datetime.now().millisecond() + i++;
        }
        
        return courses;
    }
}