src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Describes the Pearson Region that the creator of the Account is assigned to.</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Describes the Pearson &apos;Line of Business&apos; the account creator is assigned to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Account Region. Dependent on Geography.</description>
        <label>Region</label>
        <picklist>
            <controllingField>Geography__c</controllingField>
            <picklistValues>
                <fullName>UK - North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK - South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scandi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Israel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>The following field identifies the Opportunity owner&apos;s geography per their user record</description>
        <formula>TEXT(Owner.Geography__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s Line of Business per their user record</description>
        <formula>TEXT(Owner.Line_of_Business__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line of Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s User record identified market.</description>
        <formula>TEXT(Owner.Market__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity_Pearson_Course_Code__c.object
<CustomObject>
    <description>Junction linking Opportunities with Category Hierarchy (Pearson Course Equivalent)</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Pearson_Course_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Pearson_Course_Code_Name__c</fullName>
        <description>This is the Pearson course code .</description>
        <inlineHelpText>This is the Pearson course code.</inlineHelpText>
        <label>Pearson Course Code Name</label>
        <referenceTo>Apttus_Config2__ClassificationHierarchy__c</referenceTo>
        <relationshipName>Opportunity_Pearson_Course_Codes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pearson Course Equivalent</label>
    <nameField>
        <displayFormat>OPC-{00000}</displayFormat>
        <label>Opportunity Pearson Course Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pearson Course Equivalents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityPearsonCourseStructure__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Junction linking Opportunities with Pearson Courses</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Pearson Course Structure</relationshipLabel>
        <relationshipName>OpportunityPearsonCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Pearson_Course_Structure__c</fullName>
        <description>This is the Pearson course structure.</description>
        <inlineHelpText>This is the Pearson course structure.</inlineHelpText>
        <label>Pearson Course Structure</label>
        <referenceTo>PearsonCourseStructure__c</referenceTo>
        <relationshipLabel>Opportunity Pearson Course Structure</relationshipLabel>
        <relationshipName>OpportunityPearsonCourseStructure</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Pearson Course Structure</label>
    <nameField>
        <displayFormat>OPC-{00000}</displayFormat>
        <label>OpportunityPearsonCourseStructure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Pearson Course Structure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pearson_Course_Equivalent__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <description>This contains the Course.</description>
        <inlineHelpText>This contains the Course.</inlineHelpText>
        <label>Course/Catalog Code</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Pearson Course Equivalent</relationshipLabel>
        <relationshipName>Pearson_Course_Equivalent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Pearson_Course_Code__c</fullName>
        <description>This contains the Pearson Course Code.</description>
        <inlineHelpText>This contains the Pearson Course Code.</inlineHelpText>
        <label>Pearson Course Code</label>
        <referenceTo>Apttus_Config2__ClassificationHierarchy__c</referenceTo>
        <relationshipLabel>Pearson Course Equivalent</relationshipLabel>
        <relationshipName>Pearson_Course_Equivalent</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Pearson Course Equivalent</label>
    <nameField>
        <displayFormat>CPCS-{000000}</displayFormat>
        <label>Pearson Course Equivalent	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pearson Course Equivalent</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PearsonCourseStructure__c.object
<CustomObject>
    <description>Pearson marketing segment codes like discipline, cluster, course</description>
    <fields>
        <fullName>Pearson_Course_Structure_Code__c</fullName>
        <description>Contains the code of the Pearson course structure.</description>
        <externalId>true</externalId>
        <inlineHelpText>Contains the code of the Pearson course structure.</inlineHelpText>
        <label>Pearson Course Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Pearson Course Structure</label>
    <nameField>
        <label>Pearson Course Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pearson Course Structure</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PearsonCourseStructureSearchTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>CORE - contains a list of type values that should not be filtered out of the course page</description>
    <fields>
        <fullName>Search_Sort_Order__c</fullName>
        <description>The order that this type of course should appear relative to others on the CourseSearchGlobal page. Lower number indicates higher position</description>
        <inlineHelpText>CORE - The order that this type of course should appear relative to others on the CourseSearchGlobal page. Lower number indicates higher position</inlineHelpText>
        <label>Search Sort Order</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>PearsonCourseStructureSearchTypes</label>
</CustomObject>

src/objects/UniversityCoursePearsonCourseStructure__c.object
<CustomObject>
    <description>CORE adopted from UKHE</description>
    <fields>
        <fullName>PearsonCourseStructure__c</fullName>
        <description>This contains the Pearson course structure.</description>
        <inlineHelpText>This contains the Pearson course structure.</inlineHelpText>
        <label>Pearson Course Structure</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PearsonCourseStructure__c.Active_Indicator__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PearsonCourseStructure__c</referenceTo>
        <relationshipName>UniversityCoursePearsonCourseStructure</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UniversityCourse__c</fullName>
        <description>This contains the University course.</description>
        <inlineHelpText>This contains the University course.</inlineHelpText>
        <label>Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipName>UniversityCoursePearsonCourseStructure</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Univ Course Pearson Course</label>
    <nameField>
        <displayFormat>UCPCS-{000000}</displayFormat>
        <label>Pearson Course Code N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Univ Course Pearson Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>To which of the Pearson Geographies does this user belong</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The user&apos;s line of business</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Midran</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>X</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Y</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Z</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DemoCourseSearchGlobalControllerTester.cls
@isTest
private class DemoCourseSearchGlobalControllerTester {
    private static Opportunity opp;
    private static UniversityCourse__c uniCourse;
    private static Apttus_Config2__ClassificationHierarchy__c[] tier1;
    private static Apttus_Config2__ClassificationHierarchy__c[] tier2;
    private static Apttus_Config2__ClassificationHierarchy__c[] tier3;
    

  //Allows the user to enter any information in the search term fields, has to be at least 2 characters
  //Asteric at the beginnning and the end
    static testMethod void testSearchTermCleansing() {
      //buildTestData method created in the bottom of the class below; the parameter takes in a boolean value
        buildTestData(false);
        
        //Get the page object and add opening parameters
        PageReference testPage = Page.DemoCourseSearchGlobal; 
        testPage.getParameters().put('Id', opp.id); //Page requires an object id (Opportunity or University Course)
        testPage.getParameters().put('type', '0');  //0 indicates opportunity, 1 indicates Universtity Course
        
        //Set the page as the one we'll be using for these tests
        Test.setCurrentPageReference(testPage);
        
        //Instantiate the controller
        DemoCourseSearchGlobalController pageController = getController();
        
        test.startTest();
        
        //invalid characters are removed to leave a clean string
        pageController.CourseCode = '*123"456\\789*';
        pageController.CourseName = '\'123*456%789';
        
        pageController.SearchCourses();
        system.assertEquals('*123456789*', pageController.CourseCode);
        system.assertEquals('123456789', pageController.CourseName);
        
        //invalid characters are removed to leave a string that is too short
        pageController.CourseCode = '*%\'*';
        pageController.CourseName = '';
        
        pageController.SearchCourses();
        system.assert(pageController.ShowUserMessage);
        //system.assertEquals('Search term is too Short', pageController.UserMessageTitle);
        //system.assertEquals('Course Code or Course Name search must contain at least 2 characters.', pageController.UserMessage);
        
        test.stopTest();
    }

  /*
  Each Course has its own PCC Code
  When we search this time around it returns 8 again
  this time we look at Course Code instead of Course Name
  */
    static testMethod void testSearchOnCourseCode() {
        buildTestData(false);
        
        //Get the page object and add opening parameters
        PageReference testPage = Page.DemoCourseSearchGlobal; 
        testPage.getParameters().put('Id', opp.id); //Page requires an object id (Opportunity or University Course)
        testPage.getParameters().put('type', '0');  //0 indicates opportunity, 1 indicates Universtity Course
        
        //Set the page as the one we'll be using for these tests
        Test.setCurrentPageReference(testPage);
        
        //Instantiate the controller
        DemoCourseSearchGlobalController pageController = getController();
        
        test.startTest();
        
        pageController.CourseCode = 'XXX*';
        pageController.SearchCourses();
        
        //system.assertEquals(true, pageController.ShowResults);

        test.stopTest();
    }

  /*Tests the SearchResults, pulls back all the rows expected
  it builds 2 disciplines and each discipline has 2 Clusters and then those 2 Clusters have 2 course each
  8 total*/
    static testMethod void testSearchOnCourseName() {
        buildTestData(false);
        
        //Get the page object and add opening parameters
        PageReference testPage = Page.DemoCourseSearchGlobal; 
        testPage.getParameters().put('Id', uniCourse.id); //Page requires an object id (Opportunity or University Course)
        testPage.getParameters().put('type', '1');  //0 indicates opportunity, 1 indicates Universtity Course
        
        //Set the page as the one we'll be using for these tests
        Test.setCurrentPageReference(testPage);
        
        //Instantiate the controller
        DemoCourseSearchGlobalController pageController = new DemoCourseSearchGlobalController();
        
        test.startTest();
        system.debug('!!!tier3: ' + tier3);
        pageController.CourseName = 'CO*';
        pageController.SearchCourses();
        
        //system.assertEquals(true, pageController.ShowResults);

        test.stopTest();
    }

  /*
  runs a search and takes the first result from that search and attaches it to the Opportunity
  */
   /* static testMethod void testAttachToOpportunity() {
        buildTestData(false);
        
        //Get the page object and add opening parameters
        PageReference testPage = Page.DemoCourseSearchGlobal; 
        testPage.getParameters().put('Id', opp.id); //Page requires an object id (Opportunity or University Course)
        testPage.getParameters().put('type', '0');  //0 indicates opportunity, 1 indicates Universtity Course
        
        //Set the page as the one we'll be using for these tests
        Test.setCurrentPageReference(testPage);
        
        //Instantiate the controller
        DemoCourseSearchGlobalController pageController = getController();
        
        test.startTest();
        
        pageController.CourseCode = 'XXX*';
        pageController.SearchCourses();
        
        //We've found some data,  so,  populate the appropriate item
        ((DemoCourseSearchGlobalSearchResultCntrlr)(pageController.getSearchResultComponentControllerMap().get('Course'))).InboundResults = pageController.CourseSearchResults;
        
        //Select some data to attach
        system.debug('--->>'+((DemoCourseSearchGlobalSearchResultCntrlr)(pageController.getSearchResultComponentControllerMap().get('Course'))).Results[0]);
        system.debug('!!!!-----'+((DemoCourseSearchGlobalSearchResultCntrlr)(pageController.getSearchResultComponentControllerMap().get('Course'))));        
        ((DemoCourseSearchGlobalSearchResultCntrlr)(pageController.getSearchResultComponentControllerMap().get('Course'))).Results[0].isSelected = true;
        PageReference pr = pageController.Attach();
        //system.assertEquals('/' + opp.Id, pr.getUrl());
         
        Opportunity_Pearson_Course_Code__c[] opcs = [select id, Pearson_Course_Code_Name__c
                                                        from Opportunity_Pearson_Course_Code__c
                                                        where Opportunity__c = :opp.Id];        
        
        //Just check that the OpportunityPearsonCourseStructure__c exists,  the CourseSearchHelperTester checks that the correct one is assigned
        //system.assertEquals(1, opcs.size());
       // DemoCourseSearchHelper demo = new DemoCourseSearchHelper (opp.Id,2);
       // list<Apttus_Config2__ClassificationHierarchy__c> li =  demo.getExistingCourses();
        
        test.stopTest();
    }*/

  /*
  runs a search and takes the first result from that search and attaches it to the UniversityCourse
  */
    static testMethod void testAttachToUniversityCourse() {
        test.startTest();
        buildTestData(false);
        
     
        List<Apttus_Config2__ClassificationHierarchy__c> pceList = [select name,Pearson_Course_Structure_Code__c from Apttus_Config2__ClassificationHierarchy__c];
        system.Debug('pcelist-----'+pceList);
        //Get the page object and add opening parameters
        PageReference testPage = Page.DemoCourseSearchGlobal; 
        testPage.getParameters().put('Id', uniCourse.id);   //Page requires an object id (Opportunity or University Course)
        testPage.getParameters().put('type', '1');  //0 indicates opportunity, 1 indicates Universtity Course
        
        //Set the page as the one we'll be using for these tests
        Test.setCurrentPageReference(testPage);
        
        //Instantiate the controller
        DemoCourseSearchGlobalController pageController = getController();
        
        
       
        pageController.CourseCode = 'XXX*';
        pageController.SearchCourses();
        
        //We've found some data,  so,  populate the appropriate item
        ((DemoCourseSearchGlobalSearchResultCntrlr)(pageController.getSearchResultComponentControllerMap().get('Course'))).InboundResults = pageController.CourseSearchResults;
        
        //Select some data to attach
        ((DemoCourseSearchGlobalSearchResultCntrlr)(pageController.getSearchResultComponentControllerMap().get('Course'))).Results[0].isSelected = true;
        PageReference pr = pageController.Attach();
       // system.assertEquals('/' + uniCourse.Id, pr.getUrl());
         
        Pearson_Course_Equivalent__c [] upcs = [select Course__c, Pearson_Course_Code__c 
                                                        from Pearson_Course_Equivalent__c
                                                        where Course__c = :uniCourse.Id];  
                                                        
        //Just check that the UniversityCoursePearsonCourseStructure__c exists,  the CourseSearchHelperTester checks that the correct one is assigned
        //system.assertEquals(1, upcs.size());
    
        test.stopTest();
    }

  //Tests that something useful is displayed, if there is no data found the error messages in this class will be displayed
    static testMethod void testNoDataFound() {
        buildTestData(false);
        
        //Get the page object and add opening parameters
        PageReference testPage = Page.DemoCourseSearchGlobal; 
        testPage.getParameters().put('Id', uniCourse.id);
        testPage.getParameters().put('type', '1');
        
        //Set the page as the one we'll be using for these tests
        Test.setCurrentPageReference(testPage);
        
        //Instantiate the controller
        DemoCourseSearchGlobalController pageController = getController();
        
        test.startTest();
        
        pageController.CourseCode = 'YXX*';
        pageController.SearchCourses();
        
        system.assertEquals(false, pageController.ShowResults);
        
        system.assert(pageController.ShowUserMessage);
        //system.assertEquals('No Results Found', pageController.UserMessageTitle);
        //system.assertEquals('No Pearson Course Structures were found for the search criteria you entered, please try again.', pageController.UserMessage);
    
        test.stopTest();
    }

  
  

//Tests that when the user hits the Cancel button, nothing is added and takes them back to the Opportunity
    static testMethod void testCancelFromOpportunity() {
        buildTestData(false);
        
        //Get the page object and add opening parameters
        PageReference testPage = Page.DemoCourseSearchGlobal; 
        testPage.getParameters().put('Id', opp.id);
        testPage.getParameters().put('type', '0');
        
        //Set the page as the one we'll be using for these tests
        Test.setCurrentPageReference(testPage);
        
        //Instantiate the controller
        DemoCourseSearchGlobalController pageController = getController();
        
        Pagereference pr = pageController.ReturnToCaller();
        //system.assertEquals('/' + opp.Id, pr.getUrl());
    }

  //Tests that when the user hits the Cancel button, nothing is added and takes them back to the University Course
    static testMethod void testCancelFromUniCourse() {
        buildTestData(false);
        
        //Get the page object and add opening parameters
        PageReference testPage = Page.CourseSearchGlobal; 
        testPage.getParameters().put('Id', uniCourse.id);
        testPage.getParameters().put('type', '1');
        
        //Set the page as the one we'll be using for these tests
        Test.setCurrentPageReference(testPage);
        
        //Instantiate the controller
        DemoCourseSearchGlobalController pageController = getController();
        
        Pagereference pr = pageController.ReturnToCaller();
        //system.assertEquals('/' + uniCourse.Id, pr.getUrl());
        
    }

  /*
  Attaching PearsonCourse to a UniversityCourse that is already on the Opportunity
  this prevents us from creating a duplicate
  */
    /*static testMethod void testAttachToOpportunityWithExistingPCS() {
        buildTestData(false);
      
      //Add some OpportunityPearsonCourseStructure__c data to the opportunity
      OpportunityPearsonCourseStructure__c existingPCS = new OpportunityPearsonCourseStructure__c();
      existingPCS.Opportunity__c = opp.Id;
      existingPCS.Pearson_Course_Structure__c = tier3[0].Id;
      insert existingPCS;
        
        //Get the page object and add opening parameters
        PageReference testPage = Page.CourseSearchGlobal; 
        testPage.getParameters().put('Id', opp.id); //Page requires an object id (Opportunity or University Course)
        testPage.getParameters().put('type', '0');  //0 indicates opportunity, 1 indicates Universtity Course
        
        //Set the page as the one we'll be using for these tests
        Test.setCurrentPageReference(testPage);
        
        //Instantiate the controller
        CourseSearchGlobalController pageController = getController();
        
        test.startTest();
        
        pageController.CourseCode = 'XXX*';
        pageController.SearchCourses();
        
        //We've found some data,  so,  populate the appropriate item
        pageController.getSearchResultComponentController('Course').InboundResults = pageController.CourseSearchResults;
        
        //Select some data to attach
        pageController.getSearchResultComponentController('Course').Results[1].isSelected = true;
        PageReference pr = pageController.Attach();
        //system.assertEquals('/' + opp.Id, pr.getUrl());
         
        OpportunityPearsonCourseStructure__c[] opcs = [select id, Pearson_Course_Structure__c
                                                        from OpportunityPearsonCourseStructure__c
                                                        where Opportunity__c = :opp.Id
                                                        order by id];  
                                                        
        //Just check that the OpportunityPearsonCourseStructure__c exists,  the CourseSearchHelperTester checks that the correct one is assigned
        system.assertEquals(2, opcs.size());
    
        test.stopTest();
    }*/

  /*
  Attaching PearsonCourse to a UniversityCourse that is already on the University Course
  this prevents us from creating a duplicate
  */
    /*static testMethod void testAttachToUniversityCourseWithExistingPCS() {
        buildTestData(false);
      
      //Add some OpportunityPearsonCourseStructure__c data to the university course
      UniversityCoursePearsonCourseStructure__c existingPCS = new UniversityCoursePearsonCourseStructure__c();
      existingPCS.UniversityCourse__c = uniCourse.Id;
      existingPCS.PearsonCourseStructure__c = tier3[0].Id;
      insert existingPCS;
        
        //Get the page object and add opening parameters
        PageReference testPage = Page.CourseSearchGlobal; 
        testPage.getParameters().put('Id', uniCourse.id);   //Page requires an object id (Opportunity or University Course)
        testPage.getParameters().put('type', '1');  //0 indicates opportunity, 1 indicates Universtity Course
        
        //Set the page as the one we'll be using for these tests
        Test.setCurrentPageReference(testPage);
        
        //Instantiate the controller
        CourseSearchGlobalController pageController = getController();
    system.assertEquals(1, pageController.ExistingCourses.size());
        
        test.startTest();
        
        pageController.CourseCode = 'XXX*';
        pageController.SearchCourses();
        
        //We've found some data,  so,  populate the appropriate item
        pageController.getSearchResultComponentController('Course').InboundResults = pageController.CourseSearchResults;
        
        //Select some data to attach
        pageController.getSearchResultComponentController('Course').Results[1].isSelected = true;
        PageReference pr = pageController.Attach();
        system.assertEquals('/' + uniCourse.Id, pr.getUrl());
         
        UniversityCoursePearsonCourseStructure__c[] upcs = [select UniversityCourse__c, PearsonCourseStructure__c 
                                                        from UniversityCoursePearsonCourseStructure__c
                                                        where UniversityCourse__c = :uniCourse.Id
                                                        order by id];
                                                        
        //Just check that the UniversityCoursePearsonCourseStructure__c exists,  the CourseSearchHelperTester checks that the correct one is assigned   
        system.assertEquals(2, upcs.size());
    
        test.stopTest();
    }*/

  /*
  This piece ensures we don't add duplicate PearsonCourseStructures to an Opportunity or a University Course
  */
   /* static testMethod void testCannotAttachTheSamePCSTwice() {
        buildTestData(false);
      
      //Add some OpportunityPearsonCourseStructure__c data to the university course
      UniversityCoursePearsonCourseStructure__c existingPCS = new UniversityCoursePearsonCourseStructure__c();
      existingPCS.UniversityCourse__c = uniCourse.Id;
      existingPCS.PearsonCourseStructure__c = tier3[0].Id;
      insert existingPCS;
        
        //Get the page object and add opening parameters
        PageReference testPage = Page.CourseSearchGlobal; 
        testPage.getParameters().put('Id', uniCourse.id);   //Page requires an object id (Opportunity or University Course)
        testPage.getParameters().put('type', '1');  //0 indicates opportunity, 1 indicates Universtity Course
        
        //Set the page as the one we'll be using for these tests
        Test.setCurrentPageReference(testPage);
        
        //Instantiate the controller
        CourseSearchGlobalController pageController = getController();
        
        test.startTest();
        
        pageController.CourseCode = 'XXX*';
        pageController.SearchCourses();
        
        //We've found some data,  so,  populate the appropriate item
        pageController.getSearchResultComponentController('Course').InboundResults = pageController.CourseSearchResults;
        
        //Select some data to attach
        pageController.getSearchResultComponentController('Course').Results[0].isSelected = true;
        //pageController.Courses[0].isSelected = true;
        PageReference pr = pageController.Attach();
        system.assertEquals('/' + uniCourse.Id, pr.getUrl());
         
        UniversityCoursePearsonCourseStructure__c[] upcs = [select UniversityCourse__c, PearsonCourseStructure__c 
                                                        from UniversityCoursePearsonCourseStructure__c
                                                        where UniversityCourse__c = :uniCourse.Id
                                                        order by id];     
        system.assertEquals(1, upcs.size());
    
        test.stopTest();
    }
  */
  private static DemoCourseSearchGlobalController getController(){
        DemoCourseSearchGlobalController pageController = new DemoCourseSearchGlobalController();
        
        for(SelectOption so : pageController.PearsonCourseStructureTypes){
          if(so.getValue() != 'All'){
            pageController.setComponentControllerMap(so.getValue(), getSearchResultComponent(pageController, so.getValue(), null, so.getValue() + 's'));
          }
        }
        String stri = pageController.ReturnLinkTitle;
        return pageController;
  }
   
  private static DemoCourseSearchGlobalSearchResultCntrlr getSearchResultComponent(PageControllerBase pageController, string key, Apttus_Config2__ClassificationHierarchy__c[] inboundData, string resultsTitle){
      DemoCourseSearchGlobalSearchResultCntrlr controller = new DemoCourseSearchGlobalSearchResultCntrlr();
      controller.key = key;
      controller.pageController = pageController;
      controller.InboundResults = inboundData;
      controller.title = resultsTitle;
  
      return controller;
  }

//These last 2 methods are helper methods for the class
    private static void buildTestData(boolean massiveData){
        integer quantity;
        //tests if this is more than 1,000 rows
        if(massiveData){
            quantity = 11; //11x11x11=1331 rows of data (okay,  not massive massive,  but, pretty big!)
        }
        else{
            quantity = 2;
        }
        system.debug('!!!buildTestData.quantity: ' + quantity);
        
      // Delete data from custom setting if it exists and repopulate with values we're expecting
      delete [select Id from PearsonCourseStructureSearchTypes__c];
      List<PearsonCourseStructureSearchTypes__c> pcsst = new List<PearsonCourseStructureSearchTypes__c>
        {  new PearsonCourseStructureSearchTypes__c(name='Discipline', Search_Sort_Order__c=1),
        new PearsonCourseStructureSearchTypes__c(name='Cluster', Search_Sort_Order__c=2),
           new PearsonCourseStructureSearchTypes__c(name='Course', Search_Sort_Order__c=3)
      }; 
      insert pcsst;
        
        //Create an opportunity to work with - needs an account
        Account a = TestData.buildAccount('Test Account');
        a.Geography__c = 'North America';
        a.Region__c = 'United States';
        a.Line_of_Business__c ='Schools';
        a.Market__c = 'US';
        insert a;
        
        //add an opportunity to the account
        opp = TestData.buildOpportunity(a.id);
        insert opp;
        
        //add an opportunity to the account
        uniCourse = TestData.buildUniversityCourse(a.id);
        insert uniCourse;
        
        //Apttus_Config2__ClassificationHierarchy__c clh = new Apttus_Config2__ClassificationHierarchy__c(Name = 'Testdata1', Label_c = 'TestData1');
        
        String pric = [select Price_List__c from User where id =:UserInfo.getUserId()].Price_List__c;
        system.debug('--pricelist---'+pric);
        Apttus_Config2__PriceList__c pl = new Apttus_Config2__PriceList__c(Name = pric);
        insert pl;
        system.debug('--pl--'+pl +'--user--'+UserInfo.getUserId());
        //Create some data to work with...
        tier1 = TestData.buildClassificationHier(null, quantity, 'Discipline', 'DIS');
        insert tier1;
        system.debug('!!!tier1: ' + tier1.size());
        
        //...and some child objects
        
        tier2 = TestData.buildClassificationHier(getIds(tier1), quantity, 'Cluster', 'CLUS');
        insert tier2;
        system.debug('!!!tier2: ' + tier2.size());
               
        tier3 = TestData.buildPearsonCourseHier(getIds(tier2), quantity, 'COUR');
        insert tier3;
        system.debug('!!!tier3: ' + tier3.size());
        
        Apttus_Config2__PriceListCategory__c plc = new Apttus_Config2__PriceListCategory__c(Apttus_Config2__HierarchyId__c = tier3[0].Apttus_Config2__HierarchyId__c,Apttus_Config2__PriceListId__c = pl.id,Apttus_Config2__Sequence__c = 1);
        system.debug('Category-----'+TestData.buildCategories().Id + '---'+pl.id);
        insert plc;
        
        Pearson_Course_Equivalent__c pce = new Pearson_Course_Equivalent__c(Course__c = uniCourse.Id, Pearson_Course_Code__c=tier3[1].id, Active__c = true);
        insert pce;
    }
    
    /*
     * Takes an array of ANY object and returns an array of ids for them
     */
    private static Id[] getIds(Sobject[] items){
        list<Id> allIds = new list<Id>();
        
        for(Sobject item : items){
            id itemId = (Id)item.get('Id');
            allIds.add(item.Id);
        }
        
        return allIds;
    }
}