src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Describes the Pearson Region that the creator of the Account is assigned to.</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Describes the Pearson &apos;Line of Business&apos; the account creator is assigned to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Code_s__c</fullName>
        <description>The following field identifies the territor(ies) (via territory code(s)) an account should be assigned to</description>
        <inlineHelpText>Please identify the territory code(s) an account should be assigned to</inlineHelpText>
        <label>Territory Code(s)</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Organisation</fullName>
        <active>true</active>
        <label>Organisation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pearson_Course_Equivalent__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Identifies if the association between the  Course and the Pearson Course Code is Active.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <description>This contains the Course.</description>
        <inlineHelpText>This contains the Course.</inlineHelpText>
        <label>Course/Catalog Code</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Pearson Course Equivalent</relationshipLabel>
        <relationshipName>Pearson_Course_Equivalent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Pearson_Course_Code__c</fullName>
        <description>This contains the Pearson Course Code.</description>
        <inlineHelpText>This contains the Pearson Course Code.</inlineHelpText>
        <label>Pearson Course Code</label>
        <referenceTo>Apttus_Config2__ClassificationHierarchy__c</referenceTo>
        <relationshipLabel>Pearson Course Equivalent</relationshipLabel>
        <relationshipName>Pearson_Course_Equivalent</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate that the Pearson Course Code is the Primary Pearson Course Code for the Course.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Pearson Course Equivalent</label>
    <nameField>
        <displayFormat>CPCS-{000000}</displayFormat>
        <label>Pearson Course Equivalent	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pearson Course Equivalent</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To show whether a University Course is Active or Not</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Catalog_Code__c</fullName>
        <label>Catalog Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <description>Name of the course at the university or department.</description>
        <inlineHelpText>Name of the course at the university or department.</inlineHelpText>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>To which of the Pearson Geographies does this user belong</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The user&apos;s line of business</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price_List__c</fullName>
        <description>Associated Price List, Sales Force</description>
        <label>Price List</label>
        <picklist>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Humanities &amp; Social Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Math &amp; Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional &amp; Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US HE All</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PS_PrimaryPearsonCourse_Test.cls
@isTest(SeeAllData = true)
private class PS_PrimaryPearsonCourse_Test
{
    static testMethod void myUnitTest()
    {
     Boolean b = Boolean.valueOf('true');
     PS_PrimaryPearsonCourse ppc = new PS_PrimaryPearsonCourse ();   
     List<Pearson_Course_Equivalent__c> newlist= new List<Pearson_Course_Equivalent__c>();
     List<Pearson_Course_Equivalent__c> oldlist= new List<Pearson_Course_Equivalent__c>();
     map<id,Pearson_Course_Equivalent__c> oldmap = new map<id,Pearson_Course_Equivalent__c> ();
     //query to get the profile of sales user OneCRM
     Profile pfile = [Select Id,name from profile where name = 'Pearson Sales User OneCRM'];
     
      //code for creating an User
      User u = new User();
      u.LastName = 'primarycourseuser';
      u.alias = 'pmryusr'; 
      u.Email = 'primarycourse@gmail.com';  
      u.Username='primarycourse@gmail.com';
      u.LanguageLocaleKey='en_US'; 
      u.TimeZoneSidKey='America/New_York';
      u.Price_List__c='US HE All';
      u.LocaleSidKey='en_US';
      u.EmailEncodingKey='ISO-8859-1';
      u.ProfileId = pfile.id;       // '00eg0000000M99E';    currently hardcoded  for admin         
      u.Geography__c = 'Growth';
      u.Market__c = 'ZA';
      u.Line_of_Business__c = 'Higher Ed';
      insert u;
      
    
    System.runAs(u){
    
      //code written for creating an account.
     
     
     //query to get the Recordtype of the Account
     RecordType accrdtype = [Select Id,name from RecordType where name = 'Organisation'];
      Account Acc = new Account();
          Acc.Name = 'primarycourseAccount';
          Acc.Phone = '+910000055';
          Acc.ShippingCountry = 'India';
          Acc.ShippingCity = 'Bangalore';
          Acc.ShippingStreet = 'BNGECO';
          Acc.ShippingPostalCode = '5600374';
          Acc.RecordTypeId = accrdtype.id;     //'012g00000004tzM';  //currently hardcoded 
          Acc.Territory_Code_s__c = '2ZZ';   
          insert Acc;           
       
       
      //code for creating course
      UniversityCourse__c course = new UniversityCourse__c();
          course.Name = 'PrimaryCourseNameandcode';
          course.Account__c = Acc.id;
          course.Catalog_Code__c = 'Primarycoursecode';
          course.Course_Name__c = 'Primarycoursename';
          course.CurrencyIsoCode = 'USD';
          insert course;
          
      UniversityCourse__c course1 = new UniversityCourse__c();
          course1.Name = 'PrimaryCourseNameandcode1';
          course1.Account__c = Acc.id;
          course1.Catalog_Code__c = 'Primarycoursecode1';
          course1.Course_Name__c = 'Primarycoursename1';
          course1.CurrencyIsoCode = 'USD';
          insert course1;
      
      UniversityCourse__c course2 = new UniversityCourse__c();
          course2.Name = 'PrimaryCourseNameandcode2';
          course2.Account__c = Acc.id;
          course2.Catalog_Code__c = 'Primarycoursecode2';
          course2.Course_Name__c = 'Primarycoursename2';
          course2.CurrencyIsoCode = 'USD';
          insert course2;
          
           //code for creating the Hirarchy
        Apttus_Config2__ClassificationName__c cn = new Apttus_Config2__ClassificationName__c();
      cn.Apttus_Config2__HierarchyLabel__c = 'TestcategoryName';
      cn.Apttus_Config2__Type__c = 'Offering';
      cn.Apttus_Config2__Active__c = true;
      cn.Market__c = 'US';
      cn.Name = 'TestcategoryName';
      insert cn; 
           
            //code for inserting Category Hierarchy 
      Apttus_Config2__ClassificationHierarchy__c categoryhierarchy = new Apttus_Config2__ClassificationHierarchy__c();
      categoryhierarchy.Apttus_Config2__HierarchyId__c = cn.id;  //'a1cg00000003ePw';
      categoryhierarchy.Apttus_Config2__Label__c = 'TestCategoryHierarchy';
      categoryhierarchy.Name = 'TestCategoryHierarchy';
      insert categoryhierarchy; 
      
      Test.startTest();
      //code for mapping Pearson Course with the category Hirarchy
     /*  Pearson_Course_Equivalent__c pce = new Pearson_Course_Equivalent__c();
          pce.Active__c = true;   
          pce.Course__c = course.id;
          pce.Primary__c = True;
          pce.Pearson_Course_Code__c = categoryhierarchy.id; //'a1bg00000003RKD'; 
          Insert pce;   
      
      Pearson_Course_Equivalent__c pce1 = new Pearson_Course_Equivalent__c();
          pce1.Active__c = true;   
          pce1.Course__c = course1.id;
          pce1.Primary__c = false;
          pce1.Pearson_Course_Code__c = categoryhierarchy.id; //'a1bg00000003RKN'; 
          Insert pce1;
          pce1.Primary__c = true;
          update pce1;
       
      Pearson_Course_Equivalent__c pce2 = new Pearson_Course_Equivalent__c();
          pce2.Active__c = true;   
          pce2.Course__c = course2.id;
          pce2.Primary__c = True;
          pce2.Pearson_Course_Code__c = categoryhierarchy.id; //'a1bg00000003RKN'; 
          Insert pce2;
          update pce2;            
       //PS_PrimaryPearsonCourse ppc = new PS_PrimaryPearsonCourse();
       
       Pearson_Course_Equivalent__c pce3 = new Pearson_Course_Equivalent__c();
          pce3.Active__c = true;   
          pce3.Course__c = course1.id;
          pce3.Primary__c = True;
          pce3.Pearson_Course_Code__c = categoryhierarchy.id; //'a1bg00000003RKN'; 
          Insert pce3;
          pce3.Primary__c = true;
          update pce3; 
          */
          
           
     
           Pearson_Course_Equivalent__c pce4 = new Pearson_Course_Equivalent__c();
          pce4.Active__c = true;   
          pce4.Course__c = course.id;
          pce4.Primary__c = True;
          pce4.Pearson_Course_Code__c = categoryhierarchy.id; //'a1bg00000003RKD'; 
         // Insert pce4;
          newlist.add(pce4);
          
           Pearson_Course_Equivalent__c pce5 = new Pearson_Course_Equivalent__c();
          pce5.Active__c = true;   
          pce5.Course__c = course.id;
          pce5.Primary__c = True;
          pce5.Pearson_Course_Code__c = categoryhierarchy.id; //'a1bg00000003RKD'; 
        //  Insert pce5;
          newlist.add(pce5);
           system.debug('newlist--> afterinsert'+newlist);
          insert newlist;
          
           Pearson_Course_Equivalent__c pce6 = new Pearson_Course_Equivalent__c();
          pce6.Active__c = true;   
          pce6.Course__c = course.id;
          pce6.Primary__c = false;
          pce6.Pearson_Course_Code__c = categoryhierarchy.id; //'a1bg00000003RKD'; 
         // Insert pce6;
          oldlist.add(pce6);
          
           Pearson_Course_Equivalent__c pce7 = new Pearson_Course_Equivalent__c();
          pce7.Active__c = true;   
          pce7.Course__c = course.id;
          pce7.Primary__c = false;
          pce7.Pearson_Course_Code__c = categoryhierarchy.id; //'a1bg00000003RKD'; 
         // Insert pce7;
          system.debug('oldlist before insert-->'+oldlist);
          oldlist.add(pce7);
          insert oldlist;
          for(Pearson_Course_Equivalent__c pce9 :newlist)
          for(Pearson_Course_Equivalent__c pce8 :oldlist)
          oldmap.put(pce9.id ,pce8);
          system.debug('oldlist-->'+oldlist+ 'boolean-->' +b);
           system.debug('newlist-->'+newlist);
          ppc.updatePrimaryFlag(newlist,oldmap,b,b);
          
          
        Test.stopTest(); 
        
        }// run as close
    }
    
}