src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Learner</fullName>
        <active>true</active>
        <label>Learner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Correlation__c.object
<CustomObject>
    <description>Global: Object used to store many IDs for a single account. Can be used to store integration IDs or legacy IDs</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Correlation</relationshipLabel>
        <relationshipName>Legacy_IDs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ID_Name__c</fullName>
        <description>Used where the Source system holds more than one ID for each account</description>
        <label>External ID Name</label>
        <picklist>
            <controllingField>External_System__c</controllingField>
            <picklistValues>
                <fullName>Current Ocean Learner Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ocean Learner Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eVision Learner Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing Account Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Address Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Socrates ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sampling Account Number</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>The ID for the contact in an external system</description>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_System__c</fullName>
        <description>The Name of the source External System</description>
        <label>External System</label>
        <picklist>
            <controllingField>Market__c</controllingField>
            <picklistValues>
                <fullName>Ocean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eVison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Socrates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UOPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The Market that supplied the ID</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Correlation</label>
    <nameField>
        <displayFormat>AC-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Correlation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Integration_Request__c.object
<CustomObject>
    <description>Representation of an asynchronous integration notification request</description>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>The ID of the primary object</description>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready For Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Error</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>check_responses__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used at trigger to check if the system responses need to be check to determine the status of the Integration Request</description>
        <label>check Responses</label>
        <type>Checkbox</type>
    </fields>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field captures the Application ID from eVision that may be related to this opportunity.</description>
        <label>Related Opportunity</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Opportunity_Number__c</fullName>
        <description>The following field houses the opportunity number that is associated to this record as it is recorded in an external system</description>
        <externalId>true</externalId>
        <label>External Opportunity Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s User record identified market.</description>
        <formula>TEXT(Owner.Market__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Status field is used to define the status of the opportunity</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>ERP_Order_Number__c</fullName>
        <description>order number from ERP</description>
        <label>ERP Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Number__c</fullName>
        <description>this field generate an unique Id for the Item inside the order. this field should not be editable directly by the user. It is automatically assigned upon the status of the order is changed to Open</description>
        <externalId>true</externalId>
        <label>Item Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipped_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product actually shipped to the client</description>
        <label>Shipped Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StatusReason__c</fullName>
        <label>Status Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Shows reason for a status at line item level</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Order line item status that gets updated automatically</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Backordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requires Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resend Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shippable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ISBN__c</fullName>
        <description>CORE - Book ISBN</description>
        <externalId>true</externalId>
        <label>ISBN13</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Indicates which Market is utilizing this product.</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TU</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <description>Core: Captures information about Pearson Products</description>
        <label>Product</label>
    </recordTypes>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <description>Core - used to record and track Services</description>
        <label>Service</label>
    </recordTypes>
</CustomObject>

src/objects/System_Response__c.object
<CustomObject>
    <description>System Response used by the integration framework</description>
    <fields>
        <fullName>Error_Code__c</fullName>
        <description>The error code</description>
        <inlineHelpText>The error code</inlineHelpText>
        <label>Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>The error message</description>
        <inlineHelpText>The error message</inlineHelpText>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_System__c</fullName>
        <description>The external system name</description>
        <inlineHelpText>The external system name</inlineHelpText>
        <label>External System</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Request__c</fullName>
        <description>The linked integration request</description>
        <inlineHelpText>The linked integration request</inlineHelpText>
        <label>Integration Request</label>
        <referenceTo>Integration_Request__c</referenceTo>
        <relationshipLabel>System Responses</relationshipLabel>
        <relationshipName>System_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status</description>
        <inlineHelpText>The status</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>System Response</label>
    <nameField>
        <label>System Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateOneCRM.cls
/*******************************************************************************************************************
* Apex Class Name  : UpdateOneCRM
* Version          : 1.0 
* Created Date     : 07 June 2015
* Function         : Web service class used for input operations
* Modification Log :
*
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
* Davi Borges               07/06/2015              Created Initial Version of AccountContactSyncTestClass
*******************************************************************************************************************/

global class UpdateOneCRM 
{
  
/*************************************************************************************************************
  * @Name        : reportTransaction
  * @Description : Used to receive update about integration request sent to ESB 
  * 
  * @Todo        : This method need to merge with is R1 counterpart
  * @Input       : request information about the integration request to be updated
  * @Output      : true if the operation was successfully  executed
  *************************************************************************************************************/
  
  webservice static Boolean reportTransaction(IntegrationTransaction request)
  {    
    
    //Retreive Integration Request

    Integration_Request__c integrationRequest =
          IntegrationFrameworkUtilities.retreiveIntegrationRequest(request.integrationRequestId);

    //Validate if the integration request was found, otherwise returns a SOAP Fault (via Exception)

    if(integrationRequest == null)
    {
      String errorMessage= 'Cloud not find Integration Request:[' + request.integrationRequestId + ']';
      System.debug(errorMessage);   
      throw new UpdateOneCRMException('2|' + errorMessage);
    }

    Boolean isValidExternalSystem = false;

    try
    {
      isValidExternalSystem = IntegrationFrameworkUtilities.validExternalSystem(integrationRequest, request.externalSystem);
    
    }catch(Exception ex)
    {
      throw new UpdateOneCRMException('-1|' + ex.getMessage());
    }

      
    if(request.status != 'Received' && ! isValidExternalSystem)
    {
      String errorMessage= 'Invalid external system name:[' + request.externalSystem + ']';
      System.debug(errorMessage);
      throw new UpdateOneCRMException('1|' + errorMessage);
    }

    Set<String> status = IntegrationFrameworkUtilities.retreiveListOfStatus();
    
    if( ! IntegrationFrameworkUtilities.retreiveListOfStatus().contains(request.status))
    {

       throw new UpdateOneCRMException('3 | Invalid Status' );

    }

    if(request.externalSystem == null || request.externalSystem =='')
    {
            integrationRequest.Status__c = request.status;
            
            update integrationRequest;

            return true;

    }

    Boolean found = false;

    for(System_Response__c response : integrationRequest.System_Responses__r)
    {
        if(response.External_System__c == request.externalSystem)
        {
            found = true;
            
            response.Error_Code__c = request.errorCode;
            response.Error_Message__c = request.errorMessage;
            response.Status__c = request.status;

            update response;

        }

    }

    if(!found)
    {
        System_Response__c response = new System_Response__c
            (External_System__c = request.externalSystem,
                Error_Code__c = request.errorCode, 
                Error_Message__c = request.errorMessage, 
                Status__c = request.status,
                Integration_Request__c = integrationRequest.Id
            );

        insert response;
     
    }

    integrationRequest.check_responses__c = true;

    update integrationRequest;

    return true;
      
  }


  webservice static Boolean updateExternalReference(UpdateRequest request)
  {
    // validate the parameters
    UpdateOneCRMResult result = new UpdateOneCRMResult();
    result.errorCode = 0;
    result.errorMessage ='';
    
    if(request.externalSystem != System.Label.EVision)
    {
      String errorMessage= 'Invalid external system name:[' + request.externalSystem + ']';
      System.debug(errorMessage);
      result.errorCode = 1;
      result.errorMessage = errorMessage;
      throw new UpdateOneCRMException(result.errorCode + '|' + errorMessage);
    }
        
    if(request.externalKeyName != System.Label.Learner_ID &&
       request.externalKeyName != System.Label.Application_ID)
    {
      String errorMessage= 'Invalid external external key name:[' + request.externalKeyName + ']';
      System.debug(errorMessage);
      result.errorCode = 1;
      result.errorMessage = errorMessage;
      throw new UpdateOneCRMException(result.errorCode + '|' + errorMessage);
    }
    
    // get the integration request object        
    List<Integration_Request__c> integrationRequests = [SELECT Object_Id__c FROM Integration_Request__c WHERE Id = :request.integrationRequestId];
    Integration_Request__c integrationRequest = null;
    if(!integrationRequests.isEmpty())
    {
      integrationRequest = integrationRequests.get(0);
    }
        
    // if we have an integration request get the opportunity object
    if(integrationRequest != null)
    {
      List<Opportunity> opportunities = [SELECT External_Opportunity_Number__c, AccountId, Account.Id  FROM Opportunity WHERE Id = :integrationRequest.Object_Id__c];
      Opportunity opp = null;
      if(!opportunities.isEmpty())
      {
        opp = opportunities.get(0);
      }
      if(opp != null)
      {
        // if we are processing the Application ID key name update the 
        // External_Opportunity_Number__c and update the object
        if(request.externalKeyName == System.Label.Application_ID)
        {        
          opp.External_Id__c = request.externalKeyValue;
          update opp;
        }
        else if(request.externalKeyName == System.Label.Learner_ID)
        {
          // if we are processing the Learner ID key name update the account correlation
          // if it exists or create a new one if it doesnt exist
          List<Account_Correlation__c> accountCorrelations = [SELECT External_ID_Name__c,External_ID__c,External_System__c 
                                                             FROM Account_Correlation__c WHERE Account__c =: opp.Account.Id AND External_ID_Name__c = 'eVision Learner Number' LIMIT 1];

          if(accountCorrelations != null && !accountCorrelations.isEmpty())
          {
            accountCorrelations.get(0).External_ID__c = request.externalKeyValue;
            update accountCorrelations.get(0);            
          }
          else
          {
            // create a new account correlation
            Account_Correlation__c ac = new Account_Correlation__c(Account__c = opp.Account.Id, 
                                                                  External_ID__c = request.externalKeyValue, 
                                                                  External_ID_Name__c='eVision Learner Number',
                                                                  External_System__c = System.Label.EVision, 
                                                                  Market__c = 'ZA');
           insert ac;      
          }
        }
      }
      else
      {
        return false;
      } 
    }
    else
    {
      return false;
    }
        
    // updates or inserts performed - return true
    return true;
  }

  webservice static Boolean updateOrderLineItem(List<OrderLineItem> item)
  {
    UpdateOneCRMResult result = new UpdateOneCRMResult();
    result.errorCode = 0;
    result.errorMessage ='';
    
    List<OrderItem> updatedOrderLineItems = new List<OrderItem>();
    
    Map<String, Map<String,OrderLineItem>> orderMapItem = new  Map<String, Map<String,OrderLineItem>>();
    
    Map<Id,OrderLineItem> orderIdMapItem = new  Map<Id, OrderLineItem>();
    
    for(OrderLineItem oli : item){
     	analyseInputOrderLineItem(oli,orderIdMapItem,orderMapItem);       
    }
    
    List<Order> orders = new List<Order>();
    List<OrderItem> orderItems = new List<OrderItem>();
    
    if(orderMapItem.size() >0){
    	orders = [SELECT OrderNumber,(SELECT OrderItemNumber,Item_Number__c , Status__c FROM OrderItems) 
                  FROM Order WHERE OrderNumber IN : orderMapItem.keySet()];
    }
    
    System.debug('key set is ' + orderIdMapItem.keySet());
    
    if(orderIdMapItem.size() >0){
    	orderItems = [SELECT OrderItemNumber, Item_Number__c  , Status__c 
                      FROM OrderItem WHERE Id IN : orderIdMapItem.keySet()];    
    }
    
    
    for(Order ord: orders){
    	
      Map<String,OrderLineItem> mapItems = orderMapItem.get(ord.OrderNumber);
    	
    	for(OrderItem ordItem: ord.OrderItems){
    		
        if(mapItems.containsKey(String.ValueOf(ordItem.Item_Number__c))){

    			OrderLineItem oli = mapItems.get(String.ValueOf(ordItem.Item_Number__c));
    		
    			Boolean changed = checkForOrderLineItemChanges(oli,ordItem) ;
			      
		      	if(changed){
		      		updatedOrderLineItems.add(ordItem);
		     	  }
    			
    		}
    	}
    }	
	
	for(OrderItem ordItem: orderItems){
		
    OrderLineItem oli = orderIdMapItem.get(ordItem.Id);
		
		Boolean changed = checkForOrderLineItemChanges(oli,ordItem) ;
	      
    if(changed){
      		updatedOrderLineItems.add(ordItem);
    }	
	}   	
        
    if(!updatedOrderLineItems.isEmpty())
    {
      update updatedOrderLineItems;
      return true;
    }
    return false;
  }
  
  private static Boolean checkForOrderLineItemChanges(OrderLineItem oli, OrderItem ordItem)
  {
  	  // used to work out if we need to update the object
      boolean changed = false;  
    
      // do we need to update the status                      
	  if(!String.isBlank(oli.status))
	  {
	  	ordItem.Status__c = oli.status;
	  	
	  	//clean the status reason every time the status is changed 
	  	ordItem.StatusReason__c = '';     	
	    changed = true;
	  }
      
      // do we need to update the status reason
      if(!String.isBlank(oli.statusReason))
      {
      	ordItem.StatusReason__c = oli.statusReason;
      	changed = true;      	
      }
      
      // do we need to update the queantity
      if(oli.quantity > 0 )
      {
      	ordItem.Quantity = oli.quantity;
        changed = true;
      } 

	    // do we need to update the queantity
	    if(!String.isBlank(oli.externalOrderNumber))
	    {
	      ordItem.ERP_Order_Number__c = oli.externalOrderNumber;
	      changed = true;
	    }       
     
      // if we have a shipped object get the product and update the order line item
      if(oli.shipped != null && oli.shipped.isbn13 != null)
      {
      	List<Product2> prod = [SELECT Id FROM product2 where ISBN__c = :oli.shipped.isbn13 LIMIT 1];
      	if(prod.isEmpty())
      	{
      	  String errorMessage= 'Product doesnt exist for :[' + oli.shipped.isbn13 + ']';
          System.debug(errorMessage);
          throw new UpdateOneCRMException('1|' + errorMessage);  	
      	}
      	ordItem.Shipped_Product__c = prod.get(0).id;    	
        changed = true;      
      }
      
      return changed;
  }
  
  private static void analyseInputOrderLineItem(OrderLineItem oli,Map<Id,OrderLineItem> olisById ,Map<String, Map<String,OrderLineItem>> olisByNumber)
  {  	 
  	 // perform some validation on the input parameters;
      if(oli.id == null && (String.isBlank(oli.itemNumber) || String.isBlank(oli.orderNumber)))
      {
        String errorMessage= 'Invalid Ids were provided';
        System.debug(errorMessage);
        throw new UpdateOneCRMException('2|' + errorMessage);
      }
      
      if(oli.id != null)
      {
      	olisById.put(oli.id, oli);
      	return;
      }
      
      Map<String,OrderLineItem> mapItems = null;
      
      if(!olisByNumber.containsKey(oli.orderNumber))
      {
       	mapItems =  new Map<String,OrderLineItem>();
      	olisByNumber.put(oli.orderNumber, mapItems);
      	
      }else
      {
      	mapItems = olisByNumber.get(oli.orderNumber);
      }
      
      if(!mapItems.containsKey(oli.itemNumber))
      {
       	mapItems.put(oli.itemNumber,oli);
      }
  }

  global class IntegrationTransaction
  {
    webservice Id integrationRequestId;
    webservice String status;
    webservice String externalSystem;
    webservice String errorCode;
    webservice String errorMessage;
  }

  global class UpdateRequest
  {
    webservice Id integrationRequestId;
    webservice String externalSystem;
    webservice String externalKeyValue;
    webservice String externalKeyName;
  }

  global class OrderLineItem
  {
    webservice Id id;
    webservice Id orderId;
    webservice String itemNumber;
    webservice String orderNumber;
    webservice String status; //
    webservice String statusReason;
    webservice Integer quantity;
    webservice String externalOrderNumber;
    webservice INT_BookProduct shipped;
  }

  global class UpdateOneCRMResult
  {
    webService Integer errorCode;
    webService String errorMessage;
  }
    
  public class UpdateOneCRMException extends Exception 
  {
  }
}