src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Describes the Pearson Region that the creator of the Account is assigned to.</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Describes the Pearson &apos;Line of Business&apos; the account creator is assigned to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Account Region. Dependent on Geography.</description>
        <label>Region</label>
        <picklist>
            <controllingField>Geography__c</controllingField>
            <picklistValues>
                <fullName>UK - North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK - South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scandi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Israel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <description>Core: Bookmaster account territory code</description>
        <label>Territory Code</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Territory_Code_s__c</fullName>
        <description>The following field identifies the territor(ies) (via territory code(s)) an account should be assigned to</description>
        <inlineHelpText>Please identify the territory code(s) an account should be assigned to</inlineHelpText>
        <label>Territory Code(s)</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Digital_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Automatically populates based when digital products are added to opportunity</description>
        <label>Technology Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <description>The following field identifies the Opportunity owner&apos;s geography per their user record</description>
        <formula>TEXT(Owner.Geography__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geography</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s Line of Business per their user record</description>
        <formula>TEXT(Owner.Line_of_Business__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line of Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s User record identified market.</description>
        <formula>TEXT(Owner.Market__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>B2B</fullName>
        <active>true</active>
        <businessProcess>US HE</businessProcess>
        <label>B2B</label>
    </recordTypes>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Territory2.object
<CustomObject>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <description>The following field represents the territory code aligned to this territory-account association</description>
        <label>Territory Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>The business unit the user is assigned to within Pearson</description>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>CTIMGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Field Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <description>To which of the Pearson Geographies does this user belong</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The user&apos;s line of business</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price_List__c</fullName>
        <description>Associated Price List, Sales Force</description>
        <label>Price List</label>
        <picklist>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Humanities &amp; Social Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Math &amp; Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional &amp; Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US HE All</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Midran</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>X</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Y</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Z</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PS_TerritoryMovedAddeddeletedTest.cls
/* Test Class to Cover PS_TerritoryMovedAddeddeleted Trigger & its Handler, PS_UserAdderorRemovedNotificationTrigger and its handler
 and cdsOpportunityClosingNotification() of Opportunity Trigger and Handler.
 Author : Accenture IDC */


@isTest
private class PS_TerritoryMovedAddeddeletedTest
{
    static testMethod void myUnitTest()
    {
        
         //query to get the profile of sales user OneCRM
     Profile pfile = [Select Id,name from profile where name = 'Pearson Sales User OneCRM'];
     //UserRole rol = [Select Id,name from UserRole where name = 'Customer Digital Success Agent'];
     User us = [select Market__c,Line_of_Business__c,Business_Unit__c from User where id =:UserInfo.getUserId() limit 1];
      //code for creating an User
      User u = new User();
      u.LastName = 'territoryuser';
      u.alias = 'terrusr'; 
      u.Email = 'territoryuser@gmail.com';  
      u.Username='territoryuser@gmail.com';
     // u.UserRole = rol;
      u.LanguageLocaleKey='en_US'; 
      u.TimeZoneSidKey='America/New_York';
      u.Price_List__c='Humanities & Social Science';
      u.LocaleSidKey='en_US';
      u.EmailEncodingKey='ISO-8859-1';
      u.ProfileId = pfile.id;       // '00eg0000000M99E';    currently hardcoded  for admin         
      u.Geography__c = 'Growth';
      u.Market__c = 'ZA';
      u.Business_Unit__c = 'US Field Sales';
      u.Line_of_Business__c = 'Higher Ed';
      insert u;
      test.StartTest();
      //Territory2Model tm = [select id from Territory2Model limit 1]; 
     // Territory2Model t2m = new Territory2Model (Name = 'TestModel', DeveloperName ='TestModel');
     // insert t2m;
      Territory2 tr0 = TestDataFactory.createTerritory();
      tr0.Territory_Code__c = 'AAA';
      insert tr0;
     // List<Territory2> childTerritoryList = new List<Territory2>();
      Territory2 tr = new Territory2();
      tr.DeveloperName = 'TestTerritory';
      tr.Name = 'TestTerritory';
     tr.Territory2ModelId = tr0.Territory2ModelId;
     tr.Territory2TypeId = tr0.Territory2TypeId;
      tr.ParentTerritory2Id = tr0.id;
      tr.Territory_Code__c = 'XXX';
      insert tr;
      
      Territory2 tr1 = new Territory2();
      tr1.DeveloperName = 'TestTerritory1';
      tr1.Name = 'TestTerritory1';
     tr1.Territory2ModelId = tr0.Territory2ModelId;
     tr1.Territory2TypeId = tr0.Territory2TypeId;
      tr1.ParentTerritory2Id = tr0.Id;
      tr1.Territory_Code__c = 'YYY';
      insert tr1;
     
      tr1.ParentTerritory2Id = tr.Id;
      update tr1;
      Territory2 tr2 = new Territory2();
      tr2.DeveloperName = 'TestTerritory2';
       tr2.Name = 'TestTerritory2';
      tr2.Territory2ModelId = tr0.Territory2ModelId;
     tr2.Territory2TypeId = tr0.Territory2TypeId;
      tr2.ParentTerritory2Id = tr.Id;
      tr2.Territory_Code__c = 'ZZZ';
      insert tr2;

     UserTerritory2Association ut2aP = new UserTerritory2Association();
      ut2aP.Territory2Id = tr.Id;   
      ut2aP.UserId = u.id;
      ut2aP.RoleInTerritory2 = 'District Manager';
      insert ut2aP;
      UserTerritory2Association ut2a = new UserTerritory2Association();
      ut2a.Territory2Id = tr1.Id;   
      ut2a.UserId = u.id;
      ut2a.RoleInTerritory2 = 'Customer Digital Success Agent';
      insert ut2a;
      UserTerritory2Association ut2a2 = new UserTerritory2Association();
      ut2a2.Territory2Id = tr2.Id;   
      ut2a2.UserId = u.id;
      ut2a2.RoleInTerritory2 = 'Sales Representative';
      insert ut2a2;
       //delete ut2a;
       
       // Code to Cover cdsOpportunityClosingNotification in Opportunity Trigger.
      system.RunAs(us){
        createAcc();
      
      delete ut2a;
      }
     test.StopTest();
     
     
      
    }
    @testSetup static void setup() {
        // Create common test accounts
        Account testAcct = new Account(Name = 'TestAcct', Geography__c = 'North America', Region__c = 'United States',Line_of_Business__c ='Schools', Market__c = 'US',BillingCountry = 'Australia',BillingState = 'Victoria',BillingCountryCode = 'AU',BillingStateCode = 'VIC',ShippingCountry = 'Australia',ShippingState = 'Victoria',ShippingCountryCode = 'AU',ShippingStateCode = 'VIC',Territory_Code_s__c = 'YYY');
       
        insert testAcct;       
    }
    public static void createAcc(){
    
    Account acct = [SELECT Id,Territory_Code_s__c FROM Account WHERE Name='TestAcct' LIMIT 1];
      
    
    Opportunity sOpportunity          = (Opportunity)TestClassAutomation.createSObject('Opportunity');
    sOpportunity.AccountId            = acct.Id;
    
    sOpportunity.RecordTypeId         = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('B2B').getRecordTypeId();
    sOpportunity.Digital_Indicator__c = true;
    insert sOpportunity;
   
    sOpportunity.StageName            = 'Closed';
    update sOpportunity;
      acct.Territory_Code_s__c = 'ZZZ';
    update acct;
    }
}