src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Describes the Pearson Region that the creator of the Account is assigned to.</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Describes the Pearson &apos;Line of Business&apos; the account creator is assigned to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Do_Not_Send_Samples__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies, when checked, that Samples should never be sent to the contact.</description>
        <label>Do Not Send Samples</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Used to capture the Market of the Contact Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Address__c</fullName>
        <description>Used in US FS Order Management, if None is selected, then the Contacts address will be used as the address to which the order should be sent</description>
        <label>Preferred Address</label>
        <picklist>
            <picklistValues>
                <fullName>Mailing Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Educator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Shipped_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product actually shipped to the client</description>
        <label>Shipped Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Order line item status that gets updated automatically</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Backordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requires Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resend Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shippable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>To which of the Pearson Geographies does this user belong</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The user&apos;s line of business</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Approver__c</fullName>
        <description>This is used to set the approver for the order generated by the sales representative</description>
        <label>Order Approver</label>
        <relationshipName>OrderApprover</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Global: The user&apos;s role or job function at Pearson</description>
        <label>Function</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>TBC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sample_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sample Approval</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PS_OrderHeaderControllerTest.cls
@isTest
public class PS_OrderHeaderControllerTest {  
public static testmethod void processorder(){
		
         id pid=[select id from profile where name='System Administrator'].id;
         User u = new User(Alias = 'standt', Email='standarduser11@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = pid, Sample_Approval__c= true,
            TimeZoneSidKey='America/Los_Angeles', UserName='test12345'+Math.random()+'@gmail.com', Geography__c = 'Growth',Market__c = 'ZA',Line_of_Business__c = 'Higher Ed');
          insert u; 
          User u1 = new User(Alias = 'standt', Email='standarduser11@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = pid, Sample_Approval__c= false,Order_Approver__c= u.id,
            TimeZoneSidKey='America/Los_Angeles', UserName='test1234'+Math.random()+'@gmail.com', Geography__c = 'Growth',Market__c = 'ZA',Line_of_Business__c = 'Higher Ed');
            insert u1;
            list<PermissionSetAssignment> psa = new list<PermissionSetAssignment>();
            list<string> permissionsetnames = new list<string>{'Pearson_Sample_Order_Approver','Pearson_Network_Sampler','Pearson_Backend_Order_Creation','Pearson_Front_End_Sampling'};
            list<permissionset> pertset = [select id from permissionset where name in :permissionsetnames]; 
            for(integer i=0;i< pertset.size();i++ )
            {        psa.add(new PermissionSetAssignment(PermissionSetId = pertset[i].id, AssigneeId=u1.id));  }
            insert psa;
        
           
    system.runas(u1) {
            order sampleorder = TestDataFactory.returnorder();       
            Test.startTest();
            PageReference testPage = new pagereference('/apex/OrderHeaderController');
            testPage.getParameters().put('oppid',sampleorder.Opportunityid);
            testPage.getParameters().put('orderid',sampleorder.id); 
            Test.setCurrentPage(testPage);
            OrderHeaderController orderheader = new OrderHeaderController();
            orderheader.fromOnclick = false;
            orderheader.ordercontactlist[0].selectedValue= 'Other';
            orderheader.setselectedaddress1();
            orderheader.ordercontactlist[0].selectedValue= 'Mailing';
            orderheader.setselectedaddress1();
            orderheader.ordercontactlist[0].selectedValue= 'Account';
            orderheader.setselectedaddress1();
            orderheader.ordercontactlist[0].selectedValue= 'Custom';
            orderheader.setselectedaddress1(); 
            orderheader.conid = sampleorder.ShipToContactid;
            orderheader.ordercontactlisttotal[0].futureshipdate = system.today();
            orderheader.ordercontactlisttotal[0].canceldate = system.today()-1;
            orderheader.ordercontactlisttotal[0].shippinginstructions='Drop at door'; 
            orderheader.getStates();
            List<SelectOption> getoptions = orderheader.getoptions();
            orderheader.conid = sampleorder.ShipToContactid;
            list<orderitem> item = [select Shipped_Product__c from orderitem where orderid = :sampleorder.id];
            orderheader.currentProduct = item[0].Shipped_Product__c;
            orderheader.hidePopup();
            orderheader.duplicateProcess();
            orderheader.createorder = true;
            orderheader.initiateaddressselction(); 
            orderheader.updatedtotalordercontactlist();
            orderheader.updatetotalordercontactlist();
            orderheader.hideselectedaddress();
            orderheader.Next();
            orderheader.Previous();
            orderheader.initiateapproval();
            orderheader.removeconid = sampleorder.ShipToContactid; 
            orderheader.removecontact();
            orderheader.removeprodid=item[0].Shipped_Product__c;
            orderheader.removeproduct();
            orderheader.cancelPopup();
            list<orderitem> itemlist =  new list<orderitem>([select id from orderitem where orderid = :sampleorder.id]);
        	OrderItemTriggerHandler itemtrigger = new OrderItemTriggerHandler();
            itemtrigger.OnAfterInsert(itemlist);
            itemtrigger.OnAfterUpdate(itemlist);
            itemtrigger.OnAfterDelete(itemlist); 
            itemtrigger.OnUnDelete(itemlist);  
            map<id,orderitem> temp = new map<id,orderitem>([select id,status__c,orderid from orderitem]);
            itemtrigger.OnBeforeDelete(temp, temp) ;
            stdOrderTriggerHandler.createListMap([select id,status from order]);
            Test.stopTest();
           
       }
        
    } 
 public static testmethod void processorder2(){
         
         id pid=[select id from profile where name='ACN System Admin Read Only'].id;
         User u = new User(Alias = 'standt', Email='standarduser11@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = pid, Sample_Approval__c= true,
            TimeZoneSidKey='America/Los_Angeles', UserName='test12345'+Math.random()+'@gmail.com', Geography__c = 'Growth',Market__c = 'ZA',Line_of_Business__c = 'Higher Ed');
         	insert u; 
          	User u1 = new User(Alias = 'standt', Email='standarduser11@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = pid, Sample_Approval__c= true,Order_Approver__c= u.id,
            TimeZoneSidKey='America/Los_Angeles', UserName='test1234'+Math.random()+'@gmail.com', Geography__c = 'Growth',Market__c = 'ZA',Line_of_Business__c = 'Higher Ed');
            insert u1;
            list<PermissionSetAssignment> psa = new list<PermissionSetAssignment>();
            list<string> permissionsetnames = new list<string>{'Pearson_Sample_Order_Approver','Pearson_Network_Sampler','Pearson_Backend_Order_Creation','Pearson_Front_End_Sampling'};
            list<permissionset> pertset = [select id from permissionset where name in :permissionsetnames]; 
            for(integer i=0;i< pertset.size();i++ )
            {        psa.add(new PermissionSetAssignment(PermissionSetId = pertset[i].id, AssigneeId=u1.id));  }
            insert psa; 
    system.runas(u1) {
            order sampleorder = TestDataFactory.returnmodifiedorder(); 
            Test.starttest(); 
            list<orderitem> itemlist =  new list<orderitem>([select Shipped_Product__c from orderitem where orderid = :sampleorder.id]);
            system.debug('$$$$$$$$$$$$$$$$$$$$345'+sampleorder+itemlist);
          	PageReference testPage = new pagereference('/apex/OrderHeaderController');
            testPage.getParameters().put('oppid',sampleorder.Opportunityid);
            testPage.getParameters().put('orderid',sampleorder.id); 
            contact con = [SELECT Id, name,Preferred_Address__c,accountid,Role__c,email,Do_Not_Send_Samples__c,	mailingaddress,
            MailingCity,MailingState,MailingCountry,MailingPostalCode,MailingStreet,
            OtherStreet,OtherCity,OtherState,OtherCountry,OtherPostalCode,
            account.shippingstreet,account.shippingcity,account.shippingstate,account.shippingcountry,account.shippingpostalcode
              FROM Contact where id = :sampleorder.ShipToContactid limit 1 ];
            Test.setCurrentPage(testPage);
            OrderHeaderController orderheader = new OrderHeaderController(); 
            orderheader.fromOnclick = false;
            orderheader.ordercontactlist[0].selectedValue= 'Custom';
            orderheader.setselectedaddress1(); 
            orderheader.ordercontactlist[0].selectedValue= 'Other';
            orderheader.setselectedaddress1();
            orderheader.ordercontactlist[0].selectedValue= 'Mailing';
            orderheader.setselectedaddress1();
            orderheader.ordercontactlist[0].selectedValue= 'Account';
            orderheader.setselectedaddress1();
            List<SelectOption> getoptions = orderheader.getoptions();
            orderheader.conid = sampleorder.ShipToContactid;
            orderheader.ordercontactlisttotal[0].futureshipdate = system.today();
            orderheader.ordercontactlisttotal[0].canceldate = system.today()-1;
            orderheader.ordercontactlisttotal[0].shippinginstructions='Drop at door'; 
            orderheader.getStates();
            orderheader.duplicateProcess();
            orderheader.hidePopup();
            orderheader.cancelPopup();
            orderheader.initiateaddressselction(); 
            orderheader.updatedtotalordercontactlist();
            orderheader.ordercontactlisttotal[0].futureshipdate = system.today()+1;
            orderheader.ordercontactlisttotal[0].canceldate = system.today()-2;
             orderheader.ordercontactlisttotal[0].shippinginstructions='Drop at doorstep'; 
            orderheader.updatetotalordercontactlist();
            orderheader.hideselectedaddress();
            orderheader.Next();
            orderheader.Previous();
            orderheader.initiateapproval();
            orderheader.removeconid = sampleorder.ShipToContactid; 
            system.debug('$$$$$$'+con); 
            con.Preferred_Address__c= System.Label.ContactMailing;
            con.MailingCountry= 'India';
            con.MailingState='Kerala';
            update con;
            OrderHeaderController.Addressfields ad1 = new OrderHeaderController.Addressfields(con);
            con.Preferred_Address__c= System.Label.Contact_Other;
            update con;
            OrderHeaderController.Addressfields ad2 = new OrderHeaderController.Addressfields(con);
            con.Preferred_Address__c= System.Label.ContactMailing;
            update con;
            orderheadercontroller.Ordercontacts orc = new orderheadercontroller.Ordercontacts (con,sampleorder,sampleorder.Opportunityid);
            con.Preferred_Address__c= System.Label.Contact_Other;
            update con;
            orderheadercontroller.Ordercontacts orc1 = new orderheadercontroller.Ordercontacts (con,sampleorder,sampleorder.Opportunityid);
            orderheader.removecontact();
            list<orderitem> item =[select id,Shipped_Product__c from orderitem where orderid = :sampleorder.id ]; 
            system.debug('!!!!!!'+item);
            orderheader.removeprodid=itemlist[0].Shipped_Product__c;
            orderheader.removeproduct();
            stdOrderTriggerHandler.createListMap([select id,status from order]);
            Test.stopTest();
        }
     } 
  public static testmethod void overridebutton()
  		{
             Test.starttest(); 
             PageReference testPage = new pagereference('/apex/OrderHeader');
             testPage.getParameters().put('RecordType','AAA');
             testPage.getParameters().put('cancelURL','AAA');
             testPage.getParameters().put('ent','AAA');
             testPage.getParameters().put('_CONFIRMATIONTOKEN','AAA');
             testPage.getParameters().put('save_new_url','AAA');
             testPage.getParameters().put('aid','AAA');
             testPage.getParameters().put('cid','AAA');
             Test.setCurrentPage(testPage);
             ContentVersion conv=new ContentVersion();
             ApexPages.StandardController controller = new ApexPages.StandardController(conv);
             PS_OverideOrderNewButton overrider = new PS_OverideOrderNewButton(controller);
             overrider.OverideOrderNewButton();
              Test.stoptest();  
        }
      
	    }