src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Describes the Pearson &apos;Line of Business&apos; the account creator is assigned to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The market of the Account Creator</description>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s Line of Business per their user record</description>
        <formula>TEXT(Owner.Line_of_Business__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line of Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>The following field identifies the Opportunity Owner&apos;s User record identified market.</description>
        <formula>TEXT(Owner.Market__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Status field is used to define the status of the opportunity</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>B2B</fullName>
        <active>true</active>
        <businessProcess>US HE</businessProcess>
        <label>B2B</label>
    </recordTypes>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Product Status</description>
        <formula>Text(PricebookEntry.Product2.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Indicates which Market is utilizing this product.</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TU</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Special_Price_Request__c.object
<CustomObject>
    <fields>
        <fullName>Is_this_a_Renewal__c</fullName>
        <description>Describes if the product has been previously requested.  Manually entered by the Sales Rep.  Used in the HE Special Pricing Approval process.</description>
        <inlineHelpText>Has this product been previously requested?</inlineHelpText>
        <label>Is this a Renewal?</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Special Price Requests</relationshipLabel>
        <relationshipName>Special_Price_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <description>Type of request the sale rep is creating. Manually entered by the Sales Rep.  Used in the HE Special Pricing Approval process.</description>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Valuepack with MyLab / Mastering Access Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valuepack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyLab/Mastering Access Code</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GM approved/ validating data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned to special pricing team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Pricing Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>included_the_Account_Numbers_for_every_S__c</fullName>
        <description>Identifier if the user has included the Account Numbers for every School Store at that School.</description>
        <inlineHelpText>For Legal reason, every college bookstore that services this particular school(both on-campus and off-campus stores, must receive the same Special Price.  Select &quot;Yes&quot; if Account Numbers for every School Store have been included.</inlineHelpText>
        <label>Included all the Account Numbers?</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Special Price Request</label>
    <nameField>
        <displayFormat>SPR-{0000000}</displayFormat>
        <label>Special Price Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The user&apos;s line of business</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestOpportunityLineItemTriggers.cls
@isTest (seeAllData=true)
private class TestOpportunityLineItemTriggers
{
	static testMethod void myUnitTest()
	{
		
		TestClassAutomation.FillAllFields = true;
		
		Account sAccount				= (Account)TestClassAutomation.createSObject('Account');
		sAccount.BillingCountry			= 'Australia';
		sAccount.BillingState			= 'Victoria';
		sAccount.BillingCountryCode		= 'AU';
		sAccount.BillingStateCode		= 'VIC';
		sAccount.ShippingCountry		= 'Australia';
		sAccount.ShippingState			= 'Victoria';
		sAccount.ShippingCountryCode	= 'AU';
		sAccount.ShippingStateCode		= 'VIC';
		
		insert sAccount;
		
		Opportunity sOpportunity				= (Opportunity)TestClassAutomation.createSObject('Opportunity');
		sOpportunity.AccountId					= sAccount.Id;
		sOpportunity.RecordTypeId               = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Opportunity').getRecordTypeId();
		
		insert sOpportunity;
		
		Product2 sProduct						= (Product2)TestClassAutomation.createSObject('Product2');
		insert sProduct;

		Pricebook2 sPriceBook = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];
		sPriceBook.IsActive = true;
		update sPriceBook;
		
		PriceBookEntry sPriceBookEntry			= (PriceBookEntry)TestClassAutomation.createSObject('PriceBookEntry');
		sPriceBookEntry.IsActive				= true;
		sPriceBookEntry.Product2Id				= sProduct.Id;
		sPriceBookEntry.Pricebook2Id			= sPriceBook.Id;
		sPriceBookEntry.UnitPrice				= 34.95;
		insert sPriceBookEntry;
		
		Pricebook2 sPriceBookANZ = [select id from Pricebook2 where Name like 'ANZ%' limit 1];
		sPriceBookANZ.IsActive = true;
		update sPriceBookANZ;
		
		PriceBookEntry sPriceBookEntry1			= (PriceBookEntry)TestClassAutomation.createSObject('PriceBookEntry');
		sPriceBookEntry1.IsActive				= true;
		sPriceBookEntry1.Product2Id				= sProduct.Id;
		sPriceBookEntry1.Pricebook2Id			= sPriceBookANZ.Id;
		sPriceBookEntry1.UnitPrice				= 34.95;
		sPriceBookEntry1.UseStandardPrice       = false;
		insert sPriceBookEntry1;
		
		Test.startTest();
		
			OpportunityLineItem sOLI			= new OpportunityLineItem();
			sOLI.OpportunityId					= sOpportunity.Id;
			sOLI.PricebookEntryId				= sPriceBookEntry1.Id;
			sOLI.TotalPrice						= 200;
			sOLI.Quantity						= 1;
			
			system.debug('sOLI:::' + sOLI);
			insert sOLI;
			
			update sOLI;
			
			delete sOLI;
		
		Test.stopTest();
	}
	
	static testMethod void myUnitTest_Delete()
	{
		
		TestClassAutomation.FillAllFields = true;
		
		Account sAccount				= (Account)TestClassAutomation.createSObject('Account');
		sAccount.BillingCountry			= 'Australia';
		sAccount.BillingState			= 'Victoria';
		sAccount.BillingCountryCode		= 'AU';
		sAccount.BillingStateCode		= 'VIC';
		sAccount.ShippingCountry		= 'Australia';
		sAccount.ShippingState			= 'Victoria';
		sAccount.ShippingCountryCode	= 'AU';
		sAccount.ShippingStateCode		= 'VIC';
		
		insert sAccount;
		
		Opportunity sOpportunity				= (Opportunity)TestClassAutomation.createSObject('Opportunity');
		sOpportunity.AccountId					= sAccount.Id;
		sOpportunity.RecordTypeId               = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('B2B').getRecordTypeId();
		
		insert sOpportunity;
		
		Product2 sProduct						= (Product2)TestClassAutomation.createSObject('Product2');
		insert sProduct;

		Pricebook2 sPriceBook = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];
		sPriceBook.IsActive = true;
		update sPriceBook;
		
		PriceBookEntry sPriceBookEntry			= (PriceBookEntry)TestClassAutomation.createSObject('PriceBookEntry');
		sPriceBookEntry.IsActive				= true;
		sPriceBookEntry.Product2Id				= sProduct.Id;
		sPriceBookEntry.Pricebook2Id			= sPriceBook.Id;
		sPriceBookEntry.UnitPrice				= 34.95;
		insert sPriceBookEntry;
		
		Test.startTest();
		
			OpportunityLineItem sOLI			= new OpportunityLineItem();
			sOLI.OpportunityId					= sOpportunity.Id;
			sOLI.PricebookEntryId				= sPriceBookEntry.Id;
			sOLI.TotalPrice						= 200;
			sOLI.Quantity						= 1;
			
			system.debug('sOLI:::' + sOLI);
			
			insert sOLI;
			
			update sOLI;

            Special_Price_Request__c objspecial = new Special_Price_Request__c(Opportunity__c = sOpportunity.id, Request_Type__c = 'Valuepack with MyLab / Mastering Access Code',Status__c = 'New',
                          included_the_Account_Numbers_for_every_S__c = 'No',Is_this_a_Renewal__c = 'No');
            insert objspecial;

			
			Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
            User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
                              EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                              LocaleSidKey='en_US', ProfileId = p.Id,
                              UserName='standarduserfortestingOLIDelete@testorg.com',
                              TimeZoneSidKey='America/Los_Angeles',
                              Line_of_Business__c = 'Higher Ed',
                              Market__c = 'US');
     
      System.runAs(u) {
          try{
             delete sOLI;
          }catch(Exception e){
              system.debug(' pending special price list request error');
          }
      }

		Test.stopTest();
	}
	
}