src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Learner</fullName>
        <active>true</active>
        <label>Learner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Correlation__c.object
<CustomObject>
    <description>Global: Object used to store many IDs for a single account. Can be used to store integration IDs or legacy IDs</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Correlation</relationshipLabel>
        <relationshipName>Legacy_IDs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ID_Name__c</fullName>
        <description>Used where the Source system holds more than one ID for each account</description>
        <label>External ID Name</label>
        <picklist>
            <controllingField>External_System__c</controllingField>
            <picklistValues>
                <fullName>Current Ocean Learner Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ocean Learner Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eVision Learner Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing Account Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Address Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Socrates ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sampling Account Number</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>The ID for the contact in an external system</description>
        <label>External ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Account Correlation</label>
    <nameField>
        <displayFormat>AC-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Correlation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Vetting_Status__c</fullName>
        <description>This field shows the status of the academic vetting for an opportunity.</description>
        <label>Academic Vetting Status</label>
        <picklist>
            <picklistValues>
                <fullName>Un-Vetted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Vetted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vetted - Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vetted - Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field captures the Application ID from eVision that may be related to this opportunity.</description>
        <label>Related Opportunity</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lost_Reason_Other__c</fullName>
        <description>If the reason for closure is &quot;other&quot;, then this field is used to capture the other value</description>
        <label>Lost Reason Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Campus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to capture the Campus from the Proposal on the Opportunity</description>
        <label>Campus</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunties</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PS_opportunity_UpdateAccountTATest.cls
@isTest
public with sharing class PS_opportunity_UpdateAccountTATest 
{
  static testMethod void verifyupdateadmin()
  {  
    List<User> usrLst = TestDataFactory.createUser(Userinfo.getProfileId());
    insert usrLst;
    System.runas(usrLst[0])
    {
      Account acc = (Account)TestClassAutomation.createSObject('Account');
      acc.Name = 'Test';
      insert acc; 
    
      Account_Correlation__C ac = new Account_Correlation__C(Account__C = acc.Id, External_ID_Name__c = 'eVision Learner Number', External_ID__c = 'External ID');
      insert ac; 
     
      contact con = (Contact)TestClassAutomation.createSObject('Contact');
      con.Lastname= 'testcon';
      con.Firstname= 'testcon1';
      con.MobilePhone = '9999';     
      insert con;     
    
      Opportunity opp = (Opportunity)TestClassAutomation.createSObject('Opportunity');
      opp.AccountId = acc.Id;
      opp.CurrencyIsoCode = 'GBP';
      opp.Lost_Reason_Other__c = 'XXX';
      opp.Academic_Vetting_Status__c = 'XXXXX';
      opp.Type = 'New Business';
      opp.StageName = 'Negotiation';
      opp.Qualification_Campus__c = acc.id;
      insert opp;
      List<Opportunity> oppty = new List<Opportunity>();
      oppty.add(opp);
      
      AccountTeamMember accountTeamMember = new AccountTeamMember();
      accountTeamMember.TeamMemberRole='Account Administrator';
      accountTeamMember.AccountId= acc.Id;
      accountTeamMember.userId = usrLst[0].id;
      insert accountTeamMember;
             
      test.startTest();
      PS_opportunity_UpdateAccountTeamAdmin.updateadmin(oppty);
      opp.Type = 'Amendment';
      PS_opportunity_UpdateAccountTeamAdmin.updateadmin(oppty);
      
      test.stopTest();
    }
  }
}