src/objects/Action__c.object
<CustomObject>
    <description>Based component of the Action Framework functionality</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates the stage of progress of the action</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Action Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CloseCase.cls
public with sharing class CloseCase {
    
    public static void cannotCloseCase(List<Case> caseList){
        
        Map<id,Case> case_IdMap = new Map<Id,Case>();
        List<Action__c> actions = new List<Action__c> ();
        for(Case c : caseList){
            if(c.Status == 'Closed')
            	case_IdMap.put(c.id,c);
        }
        
        actions = [SELECT Case__r.id,status__c FROM Action__c
                                    WHERE case__r.id IN :case_IdMap.keySet()];
        system.debug('####################Actions :'+actions);
        
        for(Action__c act : actions){
            if(!(act.Status__c == 'Completed')){
                system.debug('#####################cant close case, NonCompleted action');
                case_IdMap.get(act.Case__r.id).addError(System.Label.ErrorMsgCloseCase);
            }
        }
    }

}