src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>NPS_Rating_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NPS Rating Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CTIMGI: Captures the status of the event activity type</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>subject__c</fullName>
        <description>CTIMGI: Identifies the type of interview the interview event is.</description>
        <label>Interview Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lead Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returning Student Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exit interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor Interview</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActivityTemplate__c.object
<CustomObject>
    <description>CORE - This object is used to define default after sales activities to be created automatically to enhance the customer experience.</description>
    <fields>
        <fullName>Account_Location__c</fullName>
        <description>CORE</description>
        <label>Account Location</label>
        <picklist>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CORE - Checkbox indicating whether activities template will generate activities when criteria is met</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Days_Until_Due__c</fullName>
        <description>CORE - Days from creatiton date auto generated activity is due</description>
        <inlineHelpText>Number of Days from the triggered creation of the event</inlineHelpText>
        <label>Days Until Due</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CORE - Set default owner of created activity</description>
        <inlineHelpText>If left blank this will default to the owner of the associated record.</inlineHelpText>
        <label>Default Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activity_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>CORE - Description of activity</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPS_Rating_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CORE - Feedback required for activity?</description>
        <label>NPS Rating Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>CORE - Type of product activity is related to</description>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance and Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials - Software Bundles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <description>CORE</description>
        <label>Related To</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>CORE</description>
        <label>Stage</label>
        <picklist>
            <controllingField>Related_To__c</controllingField>
            <picklistValues>
                <fullName>Prospecting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solutioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal/Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won (Verbal Agreement)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract (If Required)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE</description>
        <label>Status</label>
        <picklist>
            <controllingField>Related_To__c</controllingField>
            <picklistValues>
                <fullName>On Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>CORE - Subject of activity created</description>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Activity Template</label>
    <nameField>
        <displayFormat>AT-{00000}</displayFormat>
        <label>Activity Template No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Clone_Oppty__c</fullName>
        <description>Hidden field, the ID to which the opportunity was cloned if this was a renewal</description>
        <label>Clone_Oppty</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsRenewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CORE - Hidden field, used to drive flag</description>
        <label>Is Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legacy_Engagement_Date__c</fullName>
        <description>CORE - hidden field that captures the original opportunities Re-engagement date and fires due date of the Re-enagement task</description>
        <label>Legacy Engagement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Oppty__c</fullName>
        <description>Hidden field, the ID from which the opportunity was cloned if this was a renewal</description>
        <label>Original_Oppty</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>custom print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>custom ebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>mylab/mastering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>custom mylab/mastering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>simulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>equella</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>learning studio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>course design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>learning catalytic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ELT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>revel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessment</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Re_engagement_Date__c</fullName>
        <description>The date when representatives should re-engage with the customer with regards to renewing this opportunity</description>
        <label>Re-engagement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Status field is used to define the status of the opportunity</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <description>CORE</description>
        <formula>PricebookEntry.Product2.IsActive</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>CORE</description>
        <formula>TEXT(PricebookEntry.Product2.ProductType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Product Status</description>
        <formula>Text(PricebookEntry.Product2.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProductType__c</fullName>
        <description>CORE</description>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance and Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials - Software Bundles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TU</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <description>Core: Captures information about Pearson Products</description>
        <label>Product</label>
    </recordTypes>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>This task record represents the actions logged by NA HE reps to manage their opportunities</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OpportunityUtils.cls
/*******************************************************************************************************************
* Apex Class Name	: OpportunityUtils.cls
* Version 			: 1.0 
* Created Date  	: 03 APRIL 2014
* Function 			: Utility Class for Opportunity Object
* Modification Log	:
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
* Mitch Hunt                  03/04/2014              Created Initial Version of Utility Class
*******************************************************************************************************************/

public without sharing class OpportunityUtils
{
	// Creates clone opportunities
	//
	public void createReEngagementClones(Set<Id> setOpportunitiesToClone, set<String> setCloneOpptyIds, list<Opportunity> opptiesToClone)
	{
		// list of fields to ignore in soql
		set<String> setOpptyOmitFields				= new set<String>{'syncedquoteid'};
		set<String> setOLIOmitFields 				= new set<String>{'syncedquoteid'};
		// dynamic soql query
		String strOppQuery 							= 'SELECT ';
		
		// get a list of cloned oppties that still exist in the system
		map<Id, Opportunity> mapClonedOppties 		= new map<Id, Opportunity>([SELECT Id FROM Opportunity WHERE Id IN: setCloneOpptyIds]);
		
		// stores new records (oppties and lines) that we will insert
		map<integer, Opportunity> mapClonesToInsert = new map<integer, Opportunity>();
		list<OpportunityLineItem> lstClonedOLI		= new list<OpportunityLineItem>();
		
		// All the fields we need to pull into our query
		Set<String> setOpptyFields 	= Opportunity.sObjectType.getDescribe().fields.getMap().keySet();
		Set<String> setOLIFields 	= OpportunityLineItem.sObjectType.getDescribe().fields.getMap().keySet();
		
		// build our SOQL query
		// add oppty fields first
		for (String sOpptyField : setOpptyFields)
		{
			if (!setOpptyOmitFields.contains(sOpptyField))
			{
				strOppQuery += sOpptyField + ', ';
			}
		}
		
		// add a relationship query for the line items
		strOppQuery += '(SELECT';
		integer intFieldPosition = 1;
		integer intCountOpptyFields = setOLIFields.size();
		for (String sOLIField : setOLIFields)
		{
			if (!setOLIOmitFields.contains(sOLIField)) {
				strOppQuery += ' ' + sOLIField;
			}
			
			if (intFieldPosition++ < intCountOpptyFields) {
				strOppQuery += ',';
			} else {
				strOppQuery += ' FROM OpportunityLineItems where PriceBookEntry.isActive = true)';
			}
		}
		
		strOppQuery += ' FROM Opportunity WHERE Id IN: setOpportunitiesToClone AND Id NOT IN: setCloneOpptyIds';
		
		map<Id, Opportunity> mapSavedOpportunitiesToBeCloned = new map<Id, Opportunity>((list<Opportunity>)database.query(strOppQuery));
		map<Id, integer> mapOriginalIdToClonePosition = new map<Id, integer>();
		integer intTriggerListPosition = 0;
		for (Opportunity sOpportunity : opptiesToClone)
		{
			// skip this record if there is an existing clone in the database
			if (sOpportunity.Clone_Oppty__c <> null && mapClonedOppties.containsKey(sOpportunity.Clone_Oppty__c))
			{
				intTriggerListPosition++;
				continue;
			}
			// Create a clone of the oppty we have queried (if it has an Id) as the dynamic soql will exclude fields we need to omit
			else if (sOpportunity.Id <> null)
			{
				mapClonesToInsert.put(intTriggerListPosition, createOpportunityClone(mapSavedOpportunitiesToBeCloned.get(sOpportunity.Id)));
				lstClonedOLI.addAll(createOLIClone(mapSavedOpportunitiesToBeCloned.get(sOpportunity.Id).OpportunityLineItems));
				mapOriginalIdToClonePosition.put(sOpportunity.Id, intTriggerListPosition);
			}
			// Otherwise create a clone of the oppty passed to the trigger (has no id means just inserted, so there won't be line items or linked quotes)
			else
			{
				mapClonesToInsert.put(intTriggerListPosition, createOpportunityClone(sOpportunity));
			}
			// increment our position in trigger.new
			intTriggerListPosition++;
		}
		
		SavePoint sp = Database.setSavePoint();
		try
		{
			insert mapClonesToInsert.values();
			// Update the Ids of the cloned OLIs to the newly inserted oppties
			list<OpportunityLineItem> lstInsertOLIs = new list<OpportunityLineItem>();
			
			for (OpportunityLineItem sOLI : lstClonedOLI) 
			{
				OpportunityLineItem sClone = sOLI.clone(false, true);
				sClone.OpportunityId = mapClonesToInsert.get(mapOriginalIdToClonePosition.get(sOLI.OpportunityId)).Id;
				sCLone.Id = null;
				lstInsertOLIs.add(sClone);
			}
			// insert the line items
			insert lstInsertOLIs;
			
			// if successful, populate Id of the cloned opportunity on the original opportunity
			integer intUpdateListPosition = 0;
			for (Opportunity sOpportunity : opptiesToClone)
			{
				sOpportunity.Clone_Oppty__c = mapClonesToInsert.get(intUpdateListPosition++).Id;
			}
		}
		catch (Exception e)
		{
			System.debug(e.getMessage());
			database.rollback(sp);
		}
	}
	
	// Helper class to separate logic of cloning Opportunities
	//
	private static Opportunity createOpportunityClone(Opportunity sOpportunity)
	{
		// Create the clone
		Opportunity sCloneOpp 				= sOpportunity.clone(false, true);
		sCloneOpp.Re_engagement_Date__c		= null;
		sCloneOpp.Renewal_Date__c			= null;
		sCloneOpp.IsRenewal__c				= sOpportunity.isWon;
		sCloneOpp.Original_Oppty__c			= sOpportunity.Id;
		sCloneOpp.Stagename					= 'Prospecting';
		sCloneOpp.Probability				= 0;
		
		if(sOpportunity.Renewal_Date__c != null) {
			sCloneOpp.closeDate	= sOpportunity.Renewal_Date__c;
		} else {
			sCloneOpp.closeDate	= system.today().addmonths(6);
		}
		
		if(sOpportunity.Re_engagement_Date__c != null) {
			sCloneOpp.Legacy_Engagement_Date__c	= sOpportunity.Re_engagement_Date__c;
		} else {
			sCloneOpp.Legacy_Engagement_Date__c	= sCloneOpp.closeDate.addmonths(-1);
		}
		
		return sCloneOpp;
	}
	
	// Helper function separate logic for cloning OpportunityLineItems
	//
	private static list<OpportunityLineItem> createOLIClone(list<OpportunityLineItem> sOLIs)
	{
		list<OpportunityLineItem> sResult = new list<OpportunityLineItem>();
		for (OpportunityLineItem sOLI : sOLIs)
		{
			OpportunityLineItem sCloneOLI 	= sOLI.clone(false, true);
			sCloneOLI.ServiceDate			= null;
			sCloneOLI.TotalPrice			= null;
			sResult.add(sCloneOLI);
		}
		return sResult;
	}
	
	// Create Opportunity Follow up activities
	//
	public void createFollowUpActivities(Opportunity[] lstOpportunities)
	{
		
		list<ActivityTemplate__c>					lstActivityTemplates				= new list<ActivityTemplate__c>();
		map<String, String>							lstOpptyIdtoBillingCountry			= new map<String, String>();
		map<String, list<OpportunityLineItem>>		lstOpptyIdtoLineItems				= new map<String, list<OpportunityLineItem>>();
		list<Task>									lstTasksToInsert					= new list<Task>();
		
		// Retrieve the list of active activity templates
		lstActivityTemplates = [	SELECT Id, Active__c, Related_To__c, Stage__c, Status__c,
									Default_Owner__c, Subject__c, Days_Until_Due__c,
									Description__c, NPS_Rating_Required__c, Product_Type__c
									FROM ActivityTemplate__c WHERE Active__c = true AND Related_To__c = 'Opportunity'];
		
		for(Opportunity sOpportunity : lstOpportunities)
		{
			lstOpptyIdtoBillingCountry.put(sOpportunity.Id, null);
			lstOpptyIdtoLineItems.put(sOpportunity.Id, null);
		}
		
		for(OpportunityLineItem sOpptyLineItem : [	SELECT Id, OpportunityId, PriceBookEntry.Product2.ProductType__c
													FROM OpportunityLineItem 
													WHERE OpportunityId 
													IN : lstOpptyIdtoLineItems.keyset()])
													{
														if(lstOpptyIdtoLineItems.get(sOpptyLineItem.OpportunityId) == null)
														{
															lstOpptyIdtoLineItems.put(sOpptyLineItem.OpportunityId, new list<OpportunityLineItem>());
														}
														
														lstOpptyIdtoLineItems.get(sOpptyLineItem.OpportunityId).add(sOpptyLineItem);
													}
		
		for(Opportunity sOpportunity : [SELECT Id, Account.BillingCountry FROM Opportunity WHERE Id IN : lstOpptyIdtoBillingCountry.keyset()])
		{
			lstOpptyIdtoBillingCountry.put(sOpportunity.Id, sOpportunity.Account.BillingCountry);
		}
		
		for(Opportunity sOpportunity : lstOpportunities)
		{
			
			//Check the current activity templtes against this oppportunity.
			for(ActivityTemplate__c sActivityTemplate : lstActivityTemplates)
			{
				if(	sActivityTemplate.Stage__c				== sOpportunity.StageName &&
					sActivityTemplate.Status__c				== sOpportunity.Status__c //&&
					//sActivityTemplate.Account_Location__c	== lstOpptyIdtoBillingCountry.get(sOpportunity.Id)
					)
				{
					Task sTask							= new Task();
					sTask.Subject						= sActivityTemplate.Subject__c;
					sTask.ActivityDate					= system.today().addDays((Integer)sActivityTemplate.Days_Until_Due__c);
					sTask.Description					= sActivityTemplate.Description__c;
					sTask.NPS_Rating_Required__c		= sActivityTemplate.NPS_Rating_Required__c;
					sTask.WhatId						= sOpportunity.Id;
					
					if(sActivityTemplate.Default_Owner__c != null)
					{
						sTask.OwnerId					= sActivityTemplate.Default_Owner__c;
					}
					else
					{
						sTask.OwnerId					= sOpportunity.OwnerId;
					}
					
					if(sActivityTemplate.Product_Type__c != null)
					{
						// We need to check the line items to check if
						
						list<OpportunityLineItem> lstRelatedLineItems = lstOpptyIdtoLineItems.get(sOpportunity.Id);
						
						if(lstRelatedLineItems != null && lstRelatedLineItems.size() > 0)
						{
							for(OpportunityLineItem oli : lstRelatedLineItems)
							{
								// Check if the product type matches
								if(sActivityTemplate.Product_Type__c == oli.PriceBookEntry.Product2.ProductType__c)
								{
									// May have multiple of the same line potentially, break loop
									lstTasksToInsert.add(sTask);
									break;
								}
							}
						}
					}
					else
					{
						// Product type is null so do not worry about line items
						lstTasksToInsert.add(sTask);
					}
				}
			}
			
		}
		
		insert lstTasksToInsert;
		
	}
}