src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>NPS_Rating_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NPS Rating Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CTIMGI: Captures the status of the event activity type</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>subject__c</fullName>
        <description>CTIMGI: Identifies the type of interview the interview event is.</description>
        <label>Interview Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lead Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returning Student Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exit interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor Interview</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActivityTemplate__c.object
<CustomObject>
    <description>CORE - This object is used to define default after sales activities to be created automatically to enhance the customer experience.</description>
    <fields>
        <fullName>Account_Location__c</fullName>
        <description>CORE</description>
        <label>Account Location</label>
        <picklist>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CORE - Checkbox indicating whether activities template will generate activities when criteria is met</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Days_Until_Due__c</fullName>
        <description>CORE - Days from creatiton date auto generated activity is due</description>
        <inlineHelpText>Number of Days from the triggered creation of the event</inlineHelpText>
        <label>Days Until Due</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>CORE - Description of activity</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPS_Rating_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CORE - Feedback required for activity?</description>
        <label>NPS Rating Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <description>CORE</description>
        <label>Related To</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>CORE</description>
        <label>Stage</label>
        <picklist>
            <controllingField>Related_To__c</controllingField>
            <picklistValues>
                <fullName>Prospecting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solutioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal/Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won (Verbal Agreement)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract (If Required)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE</description>
        <label>Status</label>
        <picklist>
            <controllingField>Related_To__c</controllingField>
            <picklistValues>
                <fullName>On Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>CORE - Subject of activity created</description>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Activity Template</label>
    <nameField>
        <displayFormat>AT-{00000}</displayFormat>
        <label>Activity Template No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Re_engagement_Date__c</fullName>
        <description>The date when representatives should re-engage with the customer with regards to renewing this opportunity</description>
        <label>Re-engagement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Received_Signed_Registration_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The following field identifies whether the student has signed and submitted the registration contract to Pearson</description>
        <label>Received Signed Registration Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Registration_Payment_Reference1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The following field identifies the Registration Payment Reference associated to the student&apos;s registration</description>
        <label>Registration Payment Reference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Status field is used to define the status of the opportunity</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Student_Registered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Automatically updated field as part of the sales process, once the status is successfully moved to &quot;Negotiation&quot; (ie registration criteria are met</description>
        <label>Student Registered</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>D2L</fullName>
        <active>true</active>
        <businessProcess>CTIMGI</businessProcess>
        <label>D2L</label>
    </recordTypes>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestOpportunityTriggers.cls
@isTest
private class TestOpportunityTriggers
{
    static testMethod void myUnitTest()
    {

        TestClassAutomation.FillAllFields = true;
        
        Account sAccount                = (Account)TestClassAutomation.createSObject('Account');
        sAccount.BillingCountry         = 'Australia';
        sAccount.BillingState           = 'Victoria';
        sAccount.BillingCountryCode     = 'AU';
        sAccount.BillingStateCode       = 'VIC';
        sAccount.ShippingCountry        = 'Australia';
        sAccount.ShippingState          = 'Victoria';
        sAccount.ShippingCountryCode    = 'AU';
        sAccount.ShippingStateCode      = 'VIC';
        
        insert sAccount;
        
        ActivityTemplate__c sAT1        = new ActivityTemplate__c();
        sAT1.Related_To__c              = 'Opportunity';
        sAT1.Status__c                  = 'On Schedule';
        sAT1.Stage__c                   = 'Prospecting';
        sAT1.Subject__c                 = 'Test opportunity activity';
        sAT1.Description__c             = 'Test opportunity activity';
        sAT1.Active__c                  = true;
        sAT1.NPS_Rating_Required__c     = true;
        sAT1.Days_Until_Due__c          = 10;
        sAT1.Account_Location__c        = 'Australia';
        insert sAT1;
        
        ActivityTemplate__c sAT2        = new ActivityTemplate__c();
        sAT2.Related_To__c              = 'Opportunity';
        sAT2.Status__c                  = 'On Schedule';
        sAT2.Stage__c                   = 'Invoiced';
        sAT2.Subject__c                 = 'Test opportunity activity 2';
        sAT2.Description__c             = 'Test opportunity activity 2';
        sAT2.Active__c                  = true;
        sAT2.NPS_Rating_Required__c     = true;
        sAT2.Days_Until_Due__c          = 10;
        sAT2.Account_Location__c        = 'Australia';
        insert sAT2;
        
        Test.startTest();
    
        Opportunity sOpportunity        = (Opportunity)TestClassAutomation.createSObject('Opportunity');
        sOpportunity.AccountId          = sAccount.Id;
        sOpportunity.StageName          = sAT1.Stage__c;
        sOpportunity.Status__c          = sAT1.Status__c;
        //sOpportunity.Registration_Payment_Reference1__c = true;
       //sOpportunity.Received_Signed_Registration_Contract__c = true;
        insert sOpportunity;
        
        sOpportunity.StageName                  = 'Invoiced';
        sOpportunity.Renewal_Date__c            = system.today().addmonths(8);
        sOpportunity.Re_engagement_Date__c      = system.today().addmonths(1);
        update sOpportunity;
        
        
        Opportunity sClosedInsert           = new opportunity(Name='Test', CloseDate=system.today());
        
        sClosedInsert.AccountId             = sAccount.Id;
        sClosedInsert.StageName             = 'In Production';
        sClosedInsert.Re_engagement_Date__c = system.today().addMonths(1);
        sClosedInsert.Renewal_Date__c       = system.today().addMonths(12);
        insert sClosedInsert;
        
        sClosedInsert.StageName = 'Prospecting';
        update sClosedInsert;
        sClosedInsert.StageName = 'In Production';
        sClosedInsert.Student_Registered__c = true;
        sClosedInsert.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('D2L').getRecordTypeId(); 
        update sClosedInsert;
        
        
        OpportunityTriggerHandler handler = new OpportunityTriggerHandler(true,1);
        
        Boolean bIsTriggerContext = handler.bIsTriggerContext;
        Boolean bIsVisualforcePageContext = handler.bIsVisualforcePageContext;
        Boolean bIsWebServiceContext = handler.bIsWebServiceContext;
        Boolean bIsExecuteAnonymousContext = handler.bIsExecuteAnonymousContext;
        
        delete sOpportunity;
        
        undelete sOpportunity;
    
        Test.stopTest();
    }   
    static testMethod void myUnitTest2()
    {
        TestClassAutomation.FillAllFields = true;
        
        Account sAccount                = (Account)TestClassAutomation.createSObject('Account');
        sAccount.BillingCountry         = 'Australia';
        sAccount.BillingState           = 'Victoria';
        sAccount.BillingCountryCode     = 'AU';
        sAccount.BillingStateCode       = 'VIC';
        sAccount.ShippingCountry        = 'Australia';
        sAccount.ShippingState          = 'Victoria';
        sAccount.ShippingCountryCode    = 'AU';
        sAccount.ShippingStateCode      = 'VIC';
        
        insert sAccount;
        Test.startTest();
    
        Opportunity sOpportunity        = (Opportunity)TestClassAutomation.createSObject('Opportunity');
        sOpportunity.AccountId          = sAccount.Id;
        sOpportunity.StageName          = 'In Production';
       // sOpportunity.Status__c          = sAT1.Status__c;
        sOpportunity.Registration_Payment_Reference1__c = true;
        sOpportunity.Received_Signed_Registration_Contract__c = true;
        insert sOpportunity;
        Test.stopTest();
    }
}