src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>NPS_Rating_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NPS Rating Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CTIMGI: Captures the status of the event activity type</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>subject__c</fullName>
        <description>CTIMGI: Identifies the type of interview the interview event is.</description>
        <label>Interview Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lead Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returning Student Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exit interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsor Interview</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActivityTemplate__c.object
<CustomObject>
    <description>CORE - This object is used to define default after sales activities to be created automatically to enhance the customer experience.</description>
    <fields>
        <fullName>Account_Location__c</fullName>
        <description>CORE</description>
        <label>Account Location</label>
        <picklist>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CORE - Checkbox indicating whether activities template will generate activities when criteria is met</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Days_Until_Due__c</fullName>
        <description>CORE - Days from creatiton date auto generated activity is due</description>
        <inlineHelpText>Number of Days from the triggered creation of the event</inlineHelpText>
        <label>Days Until Due</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CORE - Set default owner of created activity</description>
        <inlineHelpText>If left blank this will default to the owner of the associated record.</inlineHelpText>
        <label>Default Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activity_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>CORE - Description of activity</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPS_Rating_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CORE - Feedback required for activity?</description>
        <label>NPS Rating Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>CORE - Type of product activity is related to</description>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance and Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials - Software Bundles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <description>CORE</description>
        <label>Related To</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>CORE</description>
        <label>Stage</label>
        <picklist>
            <controllingField>Related_To__c</controllingField>
            <picklistValues>
                <fullName>Prospecting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solutioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal/Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won (Verbal Agreement)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract (If Required)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE</description>
        <label>Status</label>
        <picklist>
            <controllingField>Related_To__c</controllingField>
            <picklistValues>
                <fullName>On Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>CORE - Subject of activity created</description>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Activity Template</label>
    <nameField>
        <displayFormat>AT-{00000}</displayFormat>
        <label>Activity Template No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Order Notes_old</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <description>CORE adopted from ICOM - Object to track Orders - integration with Bookmaster</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>From Oracle requirements</description>
        <label>Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>&apos;New&apos; is the status for order that have not been completed yet
&apos;Approved&apos; is the status you should select when you want to trigger the sending of the order to Bookmaster</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hand Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <recordTypes>
        <fullName>Order</fullName>
        <active>true</active>
        <label>Order</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderLineItem__c.object
<CustomObject>
    <description>CORE adopted from ICOM</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>OrderLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ProductType__c</fullName>
        <description>CORE</description>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance and Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials - Software Bundles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TU</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <description>Core: Captures information about Pearson Products</description>
        <label>Product</label>
    </recordTypes>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>This task record represents the actions logged by NA HE reps to manage their opportunities</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderUtils.cls
/*******************************************************************************************************************
* Apex Class Name	: OrderUtils.cls
* Version 			: 1.0 
* Created Date  	: 06 MAY 2014
* Function 			: Utility Class for Order Object
* Modification Log	:
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
* Mitch Hunt                  06/05/2014              Created Initial Version of Utility Class
*******************************************************************************************************************/

public without sharing class OrderUtils
{
	// When an OrderLineItem is inserted or updated populate the value of Is_Active_Product__c
	//
	public void updateProductStatusByLine (OrderLineItem__c[] lstNewOrderLines)
	{
		
		Set<Id> lstOrderedProducts 			= new Set<Id>();
		Map<Id, Product2> mapActiveProducts = null;
		
		for (OrderLineItem__c sOrderLineItem : lstNewOrderLines)
		{
			lstOrderedProducts.add(sOrderLineItem.Product__c);
		}
		
		mapActiveProducts = new Map<Id, Product2>([SELECT isActive from Product2 where Id in: lstOrderedProducts]);
		
		for (OrderLineItem__c sOrderLineItem : lstNewOrderLines)
		{
			sOrderLineItem.Is_Active_Product__c = mapActiveProducts.get(sOrderLineItem.Product__c).isActive;
		}

	}
	
	// Create Order__c Follow up activities
	//
	public void createFollowUpActivities(Order__c[] lstOpportunities)
	{
		
		list<ActivityTemplate__c>					lstActivityTemplates				= new list<ActivityTemplate__c>();
		map<String, String>							lstOrderIdtoBillingCountry			= new map<String, String>();
		map<String, list<OrderLineItem__c>>			lstOrderIdtoLineItems				= new map<String, list<OrderLineItem__c>>();
		list<Task>									lstTasksToInsert					= new list<Task>();
		
		// Retrieve the list of active activity templates
		lstActivityTemplates = [	SELECT Id, Active__c, Related_To__c, Stage__c, Status__c,
									Account_Location__c, Default_Owner__c, Subject__c, Days_Until_Due__c,
									Description__c, NPS_Rating_Required__c, Product_Type__c
									FROM ActivityTemplate__c WHERE Active__c = true AND Related_To__c = 'Order'];
		
		for(Order__c sOrder : lstOpportunities)
		{
			lstOrderIdtoBillingCountry.put(sOrder.Id, null);
			lstOrderIdtoLineItems.put(sOrder.Id, null);
		}
		
		for(OrderLineItem__c sOrderLineItem : [	SELECT Id, Order__c, Product__r.ProductType__c
													FROM OrderLineItem__c 
													WHERE Order__c 
													IN : lstOrderIdtoLineItems.keyset()])
													{
														if(lstOrderIdtoLineItems.get(sOrderLineItem.Order__c)  == null)
														{
															lstOrderIdtoLineItems.put(sOrderLineItem.Order__c, new list<OrderLineItem__c>());
														}
														
														lstOrderIdtoLineItems.get(sOrderLineItem.Order__c).add(sOrderLineItem);
													}
		
		for(Order__c sOrder : [SELECT Id, Account__r.BillingCountry FROM Order__c WHERE Id IN : lstOrderIdtoBillingCountry.keyset()])
		{
			lstOrderIdtoBillingCountry.put(sOrder.Id, sOrder.Account__r.BillingCountry);
		}
		
		for(Order__c sOrder : lstOpportunities)
		{
			
			//Check the current activity templtes against this oppportunity.
			for(ActivityTemplate__c sActivityTemplate : lstActivityTemplates)
			{
				if(	sActivityTemplate.Status__c				== sOrder.Status__c &&
					sActivityTemplate.Account_Location__c	== lstOrderIdtoBillingCountry.get(sOrder.Id))
				{
					Task sTask							= new Task();
					sTask.Subject						= sActivityTemplate.Subject__c;
					sTask.ActivityDate					= system.today().addDays((Integer)sActivityTemplate.Days_Until_Due__c);
					sTask.Description					= sActivityTemplate.Description__c;
					sTask.NPS_Rating_Required__c		= sActivityTemplate.NPS_Rating_Required__c;
					sTask.WhatId						= sOrder.Id;
					
					if(sActivityTemplate.Default_Owner__c != null)
					{
						sTask.OwnerId					= sActivityTemplate.Default_Owner__c;
					}
					else
					{
						if(sOrder.Salesperson__c != null)
						{
							sTask.OwnerId					= sOrder.Salesperson__c; // No Owner, Master Detail
						}
						else
						{
							sTask.OwnerId					= sOrder.LastModifiedById;
						}
					}
					
					if(sActivityTemplate.Product_Type__c != null && sActivityTemplate.Product_Type__c != '')
					{
						// We need to check the line items to check if
						
						list<OrderLineItem__c> lstRelatedLineItems = lstOrderIdtoLineItems.get(sOrder.Id);
						
						if(lstRelatedLineItems != null && lstRelatedLineItems.size() > 0)
						{
							for(OrderLineItem__c oli : lstRelatedLineItems)
							{
								// Check if the product type matches
								if(sActivityTemplate.Product_Type__c == oli.Product__r.ProductType__c)
								{
									// May have multiple of the same line potentially, break loop
									lstTasksToInsert.add(sTask);
									break;
								}
							}
						}
					}
					else
					{
						// Product type is null so do not worry about line items
						lstTasksToInsert.add(sTask);
					}
				}
			}
			
		}
		
		insert lstTasksToInsert;
	
	}
	
}