src/objects/Action__c.object
<CustomObject>
    <description>Based component of the Action Framework functionality</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates the stage of progress of the action</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Action Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Generate_Potential_Target__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Course_Creator</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <externalId>true</externalId>
        <label>Action</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Adoption_Type__c</fullName>
        <description>created for mapping</description>
        <formula>TEXT(Course__r.Adoption_Type__c)</formula>
        <label>Adoption Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Author__c</fullName>
        <formula>Product__r.Author__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Author</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Catalog_Code_Course_Name__c</fullName>
        <formula>Course__r.Catalog_Code__c &amp;  Course__r.Name</formula>
        <label>Catalog Code/ Course Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copyright_Year__c</fullName>
        <formula>Product__r.Copyright_Year__c</formula>
        <label>Copyright Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fall_Frontlist__c</fullName>
        <formula>Course__r.Fall_Front_List__c</formula>
        <label>Fall Frontlist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fall__c</fullName>
        <formula>Course__r.Fall_Enrollment__c</formula>
        <label>Fall</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Edition_Currency__c</fullName>
        <formula>Text(Product__r.Next_Edition__r.CurrencyIsoCode)</formula>
        <label>Next Edition Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Edition__c</fullName>
        <formula>Product__r.Next_Edition__r.Id</formula>
        <label>Next Edition</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Existing Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rollover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Takeaway</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Selling_Account__c</fullName>
        <formula>Course__r.Primary_Selling_Account__c</formula>
        <label>Primary Selling Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_In_Use_Publisher__c</fullName>
        <label>Product In Use Publisher</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_In_Use__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product In Use</label>
        <referenceTo>Asset</referenceTo>
        <relationshipName>Potential_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Generate_Potential_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <formula>Product__r.Publisher__c</formula>
        <label>Publisher</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spring_Frontlist__c</fullName>
        <formula>Course__r.Spring_Front_List__c</formula>
        <label>Spring Frontlist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Spring__c</fullName>
        <formula>Course__r.Spring_Enrollment__c</formula>
        <label>Spring</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Validation In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Validation Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Summer__c</fullName>
        <description>Created for mapping</description>
        <formula>Course__r.Summer_Enrollment__c</formula>
        <label>Summer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Winter__c</fullName>
        <description>created for mapping</description>
        <formula>Course__r.Winter_Enrollment__c</formula>
        <label>Winter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Potential Target</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Potential Target</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <description>CORE - Name of the book author</description>
        <label>Author</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Copyright_Year__c</fullName>
        <description>Copyright Year for the Product</description>
        <label>Copyright Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Edition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Edition</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Next Edition)</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TU</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Adoption_Type__c</fullName>
        <description>Indicates whether the University Course Products in Use is decided by a Committee or Individual</description>
        <label>Adoption Type</label>
        <picklist>
            <picklistValues>
                <fullName>Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual Choice</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mass_Sampling__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Selected by Administrator for courses that require mass digital sampling for all attached products when the Opportunity is created.</description>
        <label>Mass Sampling</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Selling_Account__c</fullName>
        <description>Pulls the information from the Primary Selling Account field on the Account</description>
        <formula>HYPERLINK(Account__r.Primary_Selling_Account__r.Id,  Account__r.Primary_Selling_Account__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Selling Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>To show whether a University Course is Active or Not</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Summer_Enrollment__c</fullName>
        <description>Course Enrollment for the Summer Semester</description>
        <inlineHelpText>Course Enrollment for the Summer Semester</inlineHelpText>
        <label>Summer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Winter_Enrollment__c</fullName>
        <description>Course Enrollment for the Winter Semester</description>
        <inlineHelpText>Course Enrollment for the Winter Semester</inlineHelpText>
        <label>Winter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestBatchSchedulerClass.cls
@isTest(SeeAllData=TRUE)
public class TestBatchSchedulerClass{
public static testMethod void testMethodSample()
{
Test.StartTest();
PotentialTargetOpportunityCreationBatch b = new PotentialTargetOpportunityCreationBatch();
    list<Generate_Potential_Target__c> Queryq = new list<Generate_Potential_Target__c>();
    Queryq =[SELECT Account__c, Action__c, Author__c,Summer__c,Winter__c,Adoption_Type__c, Catalog_Code_Course_Name__c, Copyright_Year__c, Course__r.Mass_Sampling__c,Course__r.Summer_Enrollment__c,Course__r.Winter_Enrollment__c,Course__r.name, Fall__c, Fall_Frontlist__c,  Next_Edition__c,Next_Edition_Currency__c, Opportunity_Type__c, Primary_Selling_Account__c, Product__c,Product__r.CurrencyIsoCode , Product_In_Use__c, Product_In_Use_Publisher__c, Publisher__c, Id, Spring__c, Spring_Frontlist__c, Status__c,createdby.id FROM Generate_Potential_Target__c where Action__c =  'Create'  and Status__c =  'In Progress' and Processed__c = false];
    b.start(null);
    b.execute(null,Queryq);
    b.finish(null);    
database.executebatch(b);
Test.stopTest();
}
}