src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Copyright_Year__c</fullName>
        <description>Copyright Year for the Product</description>
        <label>Copyright Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Identifies the Course for the Asset</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Course is not associated to the Account for this Product in Use.</errorMessage>
            <filterItems>
                <field>UniversityCourse__c.Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Products in Use</relationshipLabel>
        <relationshipName>Products_In_Use</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Product in Use</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Author__c</fullName>
        <label>Product Author</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Edition__c</fullName>
        <label>Product Edition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publisher__c</fullName>
        <label>Publisher</label>
        <picklist>
            <picklistValues>
                <fullName>Pearson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wiley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>McGraw-Hill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cengage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palgrave/Macmillan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oxford University Press</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elsevier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lipincott</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scholastic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rollover__c</fullName>
        <description>Indicates whether the product related to the asset has a new edition.</description>
        <formula>NOT(ISBLANK(Product2.Next_Edition__c)) &amp;&amp;  ( Product2.Next_Edition__r.Relevance_Value__c  = 10) &amp;&amp; NOT(Product2.Competitor_Product__c = TRUE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rollover</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>University_Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field refers to a course which a professor is teaching</description>
        <label>University Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Usage__c</fullName>
        <description>Usage Values for the Products in Use to Contacts</description>
        <label>Usage</label>
        <picklist>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tech Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tech Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityUniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - This stores the link between the Opportunity and University Course</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>This contains the opportunity.</description>
        <inlineHelpText>This contains the opportunity.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Courses</relationshipLabel>
        <relationshipName>OpportunityUniversityCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UniversityCourse__c</fullName>
        <description>This contains the University course.</description>
        <inlineHelpText>This contains the University course.</inlineHelpText>
        <label>University Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Course Opportunities</relationshipLabel>
        <relationshipName>OpportunityUniversityCourses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Course</label>
    <nameField>
        <displayFormat>OPTYUC-{00000}</displayFormat>
        <label>OpportunityUniversityCourse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OpportunitieCourseAssets.cls
public class OpportunitieCourseAssets {
    private List<Asset> AssetList;
    private Opportunity Oppty; 
    private OpportunityUniversityCourse__c OUC;
    private integer totalRecs = 0;     
    private integer index = 0;
    private integer blockSize = 4;   
    private Boolean hasAssetsrecords = false;
    private Id UniversityCourse;
    
    public OpportunitieCourseAssets(ApexPages.StandardController controller) {
        this.Oppty= (Opportunity)controller.getRecord();
        try{
         OUC = [Select id, Opportunity__c, UniversityCourse__c From OpportunityUniversityCourse__c where Opportunity__c =: Oppty.Id LIMIT 1];
         system.debug('OUC  :'+OUC);
         if(OUC.UniversityCourse__c != null)
             UniversityCourse =  OUC.UniversityCourse__c;
        }catch (System.QueryException e){
            system.debug('No OpportunityUniversityCourse Record found'+e );
        }
        try{
             if(OUC != null && UniversityCourse != null){
                 totalRecs = [select count() from Asset WHERE Course__c =:UniversityCourse];
                 if(totalRecs != 0){
                     hasAssetsrecords = true;
                 }
             }
        }catch (System.QueryException e){
            system.debug('Aggregate Query error '+e );
        }

    }
    
    public List<Asset> getCourseAssets(){
        AssetList =  Database.Query('SELECT Id, University_Course__c, Name, Product_Author__c, Product_Edition__c, Copyright_Year__c, Publisher__c, ContactId, Contact.Name, Usage__c, Rollover__c, Status, InstallDate FROM Asset WHERE Course__c =:UniversityCourse LIMIT :blockSize OFFSET :index');
        
        system.debug('AssetList :' +AssetList);                   
        return AssetList;
    }
    
    public void beginning(){
        index = 0;
    }
    
    public void previous(){
        index = index - blockSize;
    }
    
    public void next(){
        index = index + blockSize;
    }
    
    public void end() { //user clicked end
        if(math.mod(totalRecs,blockSize)==0)
        index= totalrecs -blockSize; 
        else
        index = totalrecs - math.mod(totalRecs,blockSize);
    }
    
    public boolean getprev(){
        if(index == 0)
            return true;
        else
            return false;
    }
    
    public Boolean getnxt() { //this will disable the next and end buttons
        if (index + blockSize >= totalrecs) 
            return true; 
        else 
            return false;
    }
    
    public Boolean gethasAssets(){
        return hasAssetsrecords;
    }
}