src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Identifies the Course for the Asset</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Course is not associated to the Account for this Product in Use.</errorMessage>
            <filterItems>
                <field>UniversityCourse__c.Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Products in Use</relationshipLabel>
        <relationshipName>Products_In_Use</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if Product in Use is Primary for a University Course</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Asset for NA and SA.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AssetTriggerHandler.cls
public Class AssetTriggerHandler{
    public void primaryContactv2(Asset asList){       
        if(asList.contactid != null && asList.course__c != null) {
            List<Asset> asExistLists = [select id,name,Primary__c,ContactId from Asset where ContactId =:asList.contactid and 
                                    primary__c=true and status__c='Active' and product2id != '' and course__c=:asList.course__c];
        
        if   (!asExistLists.isEmpty())  {
            List<Asset> ass_toupdate=new List<Asset>();
            for(Asset asExist : asExistLists){
              if(asExist .id != asList.id){
                  asExist.primary__c=false;
                  ass_toupdate.add(asExist);                  
              }
            }
            if (!ass_toupdate.isEmpty())
                update ass_toupdate;
        }  
        }                              
    } 
}