src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Bookshop__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bookshop</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Converted_Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted Asset</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Identifies the Course for the Asset</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Course is not associated to the Account for this Product in Use.</errorMessage>
            <filterItems>
                <field>UniversityCourse__c.Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Products in Use</relationshipLabel>
        <relationshipName>Products_In_Use</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Expected_Sales_Quantity__c</fullName>
        <label>Expected Sales Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Forecasted_Install_Date__c</fullName>
        <label>Forecasted Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mode_of_Delivery__c</fullName>
        <label>Mode of Delivery</label>
        <picklist>
            <picklistValues>
                <fullName>Kiosk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Batch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Purchase/Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VS Building Block</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cartridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Product in Use</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Products in Use</relationshipLabel>
        <relationshipName>Products_in_Use</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required_by_Date__c</fullName>
        <label>Required by Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Channel__c</fullName>
        <label>Sales Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Bookshop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct to Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct to University / Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct to School</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Asset for NA and SA.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Suggested_Order_Quantity__c</fullName>
        <label>Suggested Order Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AssetUniversityCourse__c.object
<CustomObject>
    <description>CORE - This contains the association between Asset and University Course</description>
    <fields>
        <fullName>Asset__c</fullName>
        <description>This contains the Asset.</description>
        <inlineHelpText>This contains the Asset.</inlineHelpText>
        <label>Product in Use</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>University Courses</relationshipLabel>
        <relationshipName>UniversityCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UniversityCourse__c</fullName>
        <description>This contains the University Course</description>
        <inlineHelpText>This contains the University Course</inlineHelpText>
        <label>University Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Products in Use</relationshipLabel>
        <relationshipName>AssetsUniversityCourse</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Asset University Course</label>
    <nameField>
        <displayFormat>AUC-{00000}</displayFormat>
        <label>AssetUniversityCourse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset University Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary Contact of an Opportunity.  This contact is set by a Trigger that associates the primary Contact of the Contact Roles on the Opportunity.</description>
        <inlineHelpText>Primary Contact of an Opportunity.  This contact is set by a Trigger that associates the primary Contact of the Contact Roles on the Opportunity.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Converted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Product Converted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Status field is used to define the status of the opportunity</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Bookshop__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CORE</description>
        <label>Bookshop</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Sales_Quantity__c</fullName>
        <description>CORE</description>
        <label>Expected Sales Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Forecasted_Install_Date__c</fullName>
        <description>CORE</description>
        <label>Forecasted Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mode_of_Delivery__c</fullName>
        <description>CORE</description>
        <label>Mode of Delivery</label>
        <picklist>
            <picklistValues>
                <fullName>Streaming (3rd-Party Hosted)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Website/Online Only (Licensed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Website/Online Only (Free)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downloadable Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downloadable - Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehoused AND Downloadable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downloadable - DRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehoused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Streaming (Tri-Pro Hosted)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CORE - used to track primary contact against a specific Opportunity Product</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required_By_Date__c</fullName>
        <description>CORE</description>
        <label>Required By Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Channel__c</fullName>
        <description>CORE</description>
        <label>Sales Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Bookshop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct to Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct to University/Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct to School</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Product Status</description>
        <formula>Text(PricebookEntry.Product2.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suggested_Order_Quantity__c</fullName>
        <description>CORE</description>
        <label>Suggested Order Qty</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/OpportunityUniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - This stores the link between the Opportunity and University Course</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>This contains the opportunity.</description>
        <inlineHelpText>This contains the opportunity.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Courses</relationshipLabel>
        <relationshipName>OpportunityUniversityCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Product_Converted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Product Converted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UniversityCourse__c</fullName>
        <description>This contains the University course.</description>
        <inlineHelpText>This contains the University course.</inlineHelpText>
        <label>University Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Course Opportunities</relationshipLabel>
        <relationshipName>OpportunityUniversityCourses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Course</label>
    <nameField>
        <displayFormat>OPTYUC-{00000}</displayFormat>
        <label>OpportunityUniversityCourse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>To show whether a University Course is Active or Not</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OppProductToAsset.cls
global class OppProductToAsset {
    //Class to convert opportunity line items to Product in use.
    private Static Opportunity opportunity;
    private static Account account;
    private static List <OpportunityLineItem> olis {get;set;}
    private Static List<Asset> assets = new List<Asset>();
    // List of Opportunity University Courses
    public static list<OpportunityUniversityCourse__c> oucs {get;set;}   
    private static List<OpportunityContactRole> ocrs {get;set;}
    // Stores final list of assetuniversitycourses to be upserted into SFDC
    public static List<AssetUniversityCourse__c> assetuniversitycourses = new List<AssetUniversityCourse__c>();
    
     //method called from button click to convert opportunity line items to assets 
    webservice static void convertToAsset(Id oppId,Id accId) {
         try {
            //system.debug('Record you work on : '+oppId+';'+accId);
            opportunity = new Opportunity(id=oppId);
            account = new Account(id=accId);
            system.debug('Opportunity id-->'+opportunity.id);
            if(opportunity.ID == null) {
                system.Debug('Opp id or Acc id is null');
            }
            setOLIS();
            setOUCS();
            convert();
         } catch (Exception e) {
            System.debug(e.getMessage());
            throw e;
         }
            
    }
    //Method definition to get opportunity line items.
    public List<OpportunityLineItem> getOlis() {
       return olis;
    }
    
     /**
    ** setOUCS: runs query on Opportunity University Course table to retrieve University Courses on opportunity 
    **/
    public static void setOUCS() {
        try {
            oucs=[Select    o.Id, 
                            o.Opportunity__c, 
                            o.UniversityCourse__c
                            
                    from    OpportunityUniversityCourse__c o  
                    where   o.Opportunity__c=:opportunity.ID];        
        } catch (DmlException e) {
            for(Integer i = 0; i < e.getNumDml(); i++)
                System.debug(e.getDmlMessage(i));
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw e;
        }
    }
    //Method definition to pull opportunity line items
      public static void setOLIS() {
        try {
            olis=[Select    o.Id, 
                            o.IsDeleted, 
                            o.ListPrice,
                            o.OpportunityId, 
                            o.Opportunity.CloseDate,
                            o.Opportunity.Name, //added Opportunity Name for concatenation in Asset Name
                            o.PricebookEntry.Product2Id,
                            o.PricebookEntryId, 
                            o.PricebookEntry.Name, 
                            o.Quantity, 
                            o.ServiceDate, //Relabeled to the Forecasted Install Date
                            o.TotalPrice, 
                            o.UnitPrice, 
                            //o.Forecasted_Install_Date__c, //Forecasted Install Date field; Displaying in Visualforce page
                            o.Sales_Channel__c, //Sales Channel Picklist field; Displaying in Visualforce page
                            o.Bookshop__c,  //Bookshop Lookup field
                            o.Expected_Sales_Quantity__c,
                            o.Required_by_Date__c, 
                            o.Suggested_Order_Quantity__c,
                            o.Discount,
                            o.Description,
                            o.Mode_of_Delivery__c  //Mode of Delivery Picklist field; Displaying in Visualforce page
                    from    OpportunityLineItem o  
                    where   o.IsDeleted=false and 
                            o.OpportunityId=:opportunity.ID];
        
        
        } catch (DmlException e) {
            for(Integer i = 0; i < e.getNumDml(); i++)
               System.debug(e.getDmlMessage(i));
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw e;
        }
    }
    //Method definition to pull contact details along with their role definitions.
    private static void setContactRoles(){
        try {
            ocrs = [select ContactId,Contact.Name from OpportunityContactRole where OpportunityId =:opportunity.id];
            system.debug('ocrs-->'+ocrs);
        }
        catch (DmlException e) {
            for(Integer i = 0; i < e.getNumDml(); i++)
               System.debug(e.getDmlMessage(i));
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw e;
        }
    }
    //Method definition to create Product In Use
    public static void setAssetList() {
        try {
            setContactRoles();
            system.debug('>>>>>>Start-SetAssetList');
            Integer counter=0;
            Asset a1, b1;
            string combinednames;
            if(!olis.isEmpty()) {
            
                for(OpportunityLineItem o: olis) {
                    if(ocrs.size()>0){
                        for(OpportunityContactRole ocr : ocrs){
                            system.debug('>>>>>>Start2-contact' +ocr.ContactId);
                            a1 = new Asset();
                            a1.Name                     = o.PriceBookEntry.Name;
                            a1.Product2Id               = o.PriceBookEntry.Product2Id;
                            a1.AccountId                = account.Id;
                            a1.Purchase_Opportunity__c  = opportunity.Id;
                            a1.ContactId                = ocr.ContactId;
                            a1.InstallDate              = system.today();
                            a1.Converted_Asset__c       = true;
                          if(o.Discount!=null){
                            a1.Discount__c              =o.Discount;
                             }                            
                            
                            assets.add(a1);
                        }
                    }
                    else{
                        a1 = new Asset();
                            a1.Name                     = o.PriceBookEntry.Name;
                            a1.Product2Id               = o.PriceBookEntry.Product2Id;
                            a1.AccountId                = account.Id;
                            a1.Purchase_Opportunity__c  = opportunity.Id;
                            a1.Contact                  = null;
                            a1.InstallDate              = system.today();
                            a1.Converted_Asset__c       = true;
                            
                            if(o.Discount!=null){
                            a1.Discount__c              =o.Discount;
                             }
                             assets.add(a1);
                    }
                } 
            //insert assets;
            }
        }catch (Exception e){
           System.debug(e.getMessage());
            throw e;
        }
        
    }
   // public PageReference convert() {
      public static void convert() {
        
        try {
            Integer num_of_assets = 0;
     
            // Setup the assets to be upserted
            setAssetList();
            num_of_assets = assets.size();
            
            if(num_of_assets > 0) {
                // Insert or Update Assets [Upsert]
                //upsert assets;  //replaced this line with the UpsertResult line below to let us capture asset ids for writing of AssetUniversityCourse records
                
                //begin code for inserting AssetUniversityCourse for each opportunity product converted to an asset
                 Database.UpsertResult[] lur = Database.upsert(assets);
                if(oucs.size()>0){ //don't act unless there are university courses associated with this opportunity
                    //system.debug('OUCS size is '+oucs.size());           
                    id assetid;
                    id universitycourseid;
                    Integer count = 0;
                    List<Asset> Alist = new List<Asset>();
                    system.debug('Entering first for loop');
                    for(Database.UpsertResult ur : lur){ //loop through assets that were just upserted
                        assetid= ur.Id;
                        system.debug('Entered first for loop');
                        Asset assetrec = new Asset(Id=assetid);
                            count=0; 
                            system.debug('Entered if check');
                            for(OpportunityUniversityCourse__c ouc : oucs){  //loop through all university courses associated with this opportunity
                                system.debug('Inside for--->'+ouc);
                                if(count==0)
                                {
                                    system.Debug('Inside If---->'+count);
                                    OpportunityUniversityCourse__c oucRec = [select name,Opportunity__c, Opportunity__r.Primary_Contact__c,UniversityCourse__c from OpportunityUniversityCourse__c where id =: ouc.id];
                                    //assetrec.ContactId =oucRec.Opportunity__r.Primary_Contact__c;
                                    assetrec.Course__c = oucRec.UniversityCourse__c;
                                    assetrec.Status__c = 'Active';
                                    system.debug('assetrec--------->'+assetrec.Contact+ ' ststus-->'+assetrec.Status__c);
                                    Alist.add(assetrec);
                                    system.debug('Alist---------@'+Alist);
                                }
                                count+=1;
                                //universitycourseid = ouc.UniversityCourse__c;                     
                                //assetuniversitycourses.add(new AssetUniversityCourse__c(Asset__c=assetid,UniversityCourse__c=universitycourseid)); //create the junction record                                
                            }
                        
                    }
                    //insert assetuniversitycourses;
                    system.debug('Insert done');
                    update Alist;
                    system.debug('Update done');
                } 
                opportunity.Product_Converted__c = true;
                update opportunity;
                //end code for inserting AssetUniversityCourse for each opportunity product converted to an asset                                 
            }
        } catch (Exception e) {
           System.debug('Convert: ' + e.getMessage());            
           throw e;
        }
    }
}