src/objects/Call__c.object
<CustomObject>
    <description>CORE - Object to store information on Calls made to prospects and clients</description>
    <label>Call</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CallOpportunity__c.object
<CustomObject>
    <description>CORE - Object linking Calls with Opportunities</description>
    <fields>
        <fullName>Call__c</fullName>
        <description>CORE - Call regarding opportunity</description>
        <label>Call</label>
        <referenceTo>Call__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Call_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>CORE - Opportunity call is being made for</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Calls</relationshipLabel>
        <relationshipName>Call_Opportunities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Call Opportunity</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Call Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AutoCreateJunctionController.cls
public with sharing class AutoCreateJunctionController
{
	public Id originalId;
	public Id newId;
	
	public AutoCreateJunctionController()
	{
		originalId = apexPages.currentPage().getParameters().get('originalid');
		newID = apexPages.currentPage().getParameters().get('newid');
	}
	
	public pagereference createJunctionandredirect()
	{
		String originalObjectAPIName	= originalId.getSObjectType().getDescribe().getName();
		String newObjectAPIName			= newId.getSObjectType().getDescribe().getName();
		
		system.debug('newObjectAPIName:::' + newObjectAPIName);
		system.debug('originalObjectAPIName:::' + originalObjectAPIName);
		
		if(originalObjectAPIName == 'Opportunity' && newObjectAPIName == 'Call__c')
		{
			system.debug(':::1');
			CallOpportunity__c sCallOppty = new CallOpportunity__c();
			sCalloppty.Call__c = newId;
			sCalloppty.Opportunity__c = originalId;
		
			insert sCallOppty;
		}
		else if(originalObjectAPIName == 'Call__c' && newObjectAPIName == 'Opportunity')
		{
			system.debug(':::2');
			CallOpportunity__c sCallOppty = new CallOpportunity__c();
			sCalloppty.Call__c = originalId;
			sCalloppty.Opportunity__c = newId;
			
			insert sCallOppty;
		}
		
		pagereference pageref = new pagereference('/' + newId);
		return pageref;
	}
}