src/objects/Call__c.object
<CustomObject>
    <description>CORE - Object to store information on Calls made to prospects and clients</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE - Name of the account call is be</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Calls</relationshipLabel>
        <relationshipName>Calls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Call_End_Time__c</fullName>
        <defaultValue>NOW() + 0.0104175</defaultValue>
        <description>CORE - Name of the account call is being made in regards to</description>
        <inlineHelpText>If left blank the call end time will default to 1 hour from the call start time</inlineHelpText>
        <label>Call End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Call_Objective__c</fullName>
        <description>CORE - Picklist of high level objective of call</description>
        <label>Call Objective</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/solution conversation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product demonstration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training/set-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service/Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Call_Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>CORE - Start time of call</description>
        <label>Call Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Other_Call_Objective__c</fullName>
        <description>CORE - Must be filled in if other is selected in call objective</description>
        <label>Other Call Objective</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CORE - Hidden field populated via work-flow as calls are master detail to accounts thereby not having an OwnerId field which is required.</description>
        <inlineHelpText>If left blank this field will default to the current user</inlineHelpText>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Calls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_Call_Notes__c</fullName>
        <description>CORE - notes to remind user what to discuss during call</description>
        <label>Pre Call Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Call</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Event template used for Global needs</description>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CallUtils.cls
/*******************************************************************************************************************
* Apex Class Name   : CallUtils.cls
* Version           : 1.0 
* Created Date      : 30 APRIL 2014
* Function          : Utility Class for Call Object
* Modification Log  :
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
* Mitch Hunt                  30/04/2014              Created Initial Version of Utility Class
*******************************************************************************************************************/

global class CallUtils
{
    global static void DeleteEvent(list<Call__c> lstCalls)
    {
        map<string, Event>          mapExistingCallstoEvent         = new map<string, Event>();
        list<Event>                 lstEventsToDelete               = new list<Event>();
        
        for(Call__c sCall : lstCalls)
        {
            mapExistingCallstoEvent.put(sCall.Id, null);
        }
        
        for(Event sEvent : [SELECT Id, WhatId FROM Event WHERE WhatId IN : mapExistingCallstoEvent.keyset()])
        {
            lstEventsToDelete.add(sEvent);
        }
        
        try
        {
            delete lstEventsToDelete;
        }
        catch(exception ex)
        {
            system.debug('An Error has occoured in deletion of either calls or events :::' + lstEventsToDelete + ' ::///::' + lstCalls);
        }
        
    }
    
    global static void SyncEvent(list<Call__c> lstCalls)
    {
        map<string, Event>          mapExistingEventForCallRecord   = new map<string, Event>();
        map<string, string>         mapAccountIdToName              = new map<string, string>();

        //Generate Maps from Call record to assist in the sync process
        for(Call__c c : lstCalls)
        {
            mapAccountIdToName.put(c.Account__c, ' - ');
            mapExistingEventForCallRecord.put(c.Id, null);
        }
        
        // Find the Event where the WhatId is the Current Call
        for(Event e : [select Id, WhatId from Event where isChild = false and WhatId in :mapExistingEventForCallRecord.keySet()])
        {
            mapExistingEventForCallRecord.put(e.WhatId, e);
        }
        
        // Generate a map of the Account ID to Account Names
        for(Account sAcct : [select Id, Name from Account where Id in : mapAccountIdToName.keySet()])
        {
            mapAccountIdToName.put(sAcct.Id, sAcct.Name);
        }

        // Insert and update the events
        list<Event> liEventForCallRecord = new list<Event>();
        Event sEvent = null;

        for(Call__c c : lstCalls)
        {
            // If the event does not already exist create a new event record otherwise retrieve the current event.
            if(mapExistingEventForCallRecord.get(c.Id) == null)
            {
                sEvent                = new Event();
                sEvent.WhatId         = c.Id;
            }
            else
            {
                sEvent = mapExistingEventForCallRecord.get(c.Id);
            }
            if(c.Call_Objective__c == '' || c.Call_Objective__c == null)
            {
                sEvent.Subject          = mapAccountIdToName.get(c.Account__c) + ' : Ad Hoc Call';
            }
            else
            {
                sEvent.Subject          = mapAccountIdToName.get(c.Account__c) + ' : ' + c.Call_Objective__c;
            }
            sEvent.Description      			= c.Pre_Call_Notes__c;
            sEvent.StartDateTime    			= c.Call_Start_Time__c;
            sEvent.EndDateTime      			= c.Call_End_Time__c;
            sEvent.OwnerId          			= c.OwnerId__c;
            sEvent.Type             			= 'Call';
            sEvent.Meeting_Objective__c			= c.Call_Objective__c;
            sEvent.Other_Meeting_Objective__c	= c.Other_Call_Objective__c;
            
            // If the end time is null default call date to an hour after the start date
            if(c.Call_End_Time__c == null)
            {
                sEvent.EndDateTime  = sEvent.StartDateTime.addHours(1);
            }
            else
            {
                sEvent.EndDateTime = c.Call_End_Time__c;
            }

            liEventForCallRecord.add(sEvent);
        }

        upsert liEventForCallRecord;
    }
    
}