src/objects/Call__c.object
<CustomObject>
    <description>CORE - Object to store information on Calls made to prospects and clients</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE - Name of the account call is be</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Calls</relationshipLabel>
        <relationshipName>Calls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Call_End_Time__c</fullName>
        <defaultValue>NOW() + 0.0104175</defaultValue>
        <description>CORE - Name of the account call is being made in regards to</description>
        <inlineHelpText>If left blank the call end time will default to 1 hour from the call start time</inlineHelpText>
        <label>Call End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Call_Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>CORE - Start time of call</description>
        <label>Call Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Call</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CallAttendee__c.object
<CustomObject>
    <description>CORE - This object provides the ability to link multiple attendees internal &amp; external to a call record.</description>
    <fields>
        <fullName>Call__c</fullName>
        <description>CORE - The call to which the attendee is linked</description>
        <inlineHelpText>The call to which the attendee is linked</inlineHelpText>
        <label>Call</label>
        <referenceTo>Call__c</referenceTo>
        <relationshipLabel>Call Attendees</relationshipLabel>
        <relationshipName>Call_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CORE - Client contact attending call</description>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Attendances</relationshipLabel>
        <relationshipName>Call_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pearson_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CORE - Other Pearson Employee attending call</description>
        <label>Pearson Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Call_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Attendee</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Call Attendee No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCallAttendeeTriggers.cls
@isTest
private class TestCallAttendeeTriggers
{
	static testMethod void myUnitTest()
	{
		// TO DO: implement unit test
		
		TestClassAutomation.FillAllFields = true;
		
		Account sAccount				= (Account)TestClassAutomation.createSObject('Account');
		sAccount.BillingCountry			= 'Australia';
		sAccount.BillingState			= 'Victoria';
		sAccount.BillingCountryCode		= 'AU';
		sAccount.BillingStateCode		= 'VIC';
		sAccount.ShippingCountry		= 'Australia';
		sAccount.ShippingState			= 'Victoria';
		sAccount.ShippingCountryCode	= 'AU';
		sAccount.ShippingStateCode		= 'VIC';
		
		insert sAccount;
		
		Contact sContact				= (Contact)TestClassAutomation.createSObject('Contact');
		sContact.AccountId				= sAccount.ID;
		sContact.MailingCountry			= 'Australia';
		sContact.MailingState			= 'Victoria';
		sContact.MailingCountryCode		= 'AU';
		sContact.MailingStateCode		= 'VIC';
		sContact.OtherCountry			= 'Australia';
		sContact.OtherState				= 'Victoria';
		sContact.OtherCountryCode		= 'AU';
		sContact.OtherStateCode			= 'VIC';
		
		insert sContact;
	
		Call__c sCall					= (Call__c)TestClassAutomation.createSObject('Call__c');
		sCall.Account__c				= sAccount.Id;
		sCall.Call_Start_Time__c		= system.now();
		sCall.Call_End_Time__c			= system.now().addHours(1);
		
		insert sCall;
			
		Test.startTest();
			
			CallAttendee__c sCallAttendee			= (CallAttendee__c)TestClassAutomation.createSObject('CallAttendee__c');
			sCallAttendee.Call__c					= sCall.Id;
			sCallAttendee.Client__c					= sContact.Id;
			sCallAttendee.Pearson_Employee__c		= null; // You can only have one or the other
			
			insert sCallAttendee;
			
			update sCallAttendee;
			
			delete sCallAttendee;
			
			undelete sCallAttendee;
							
		Test.stopTest();
	}
}