src/objects/Call__c.object
<CustomObject>
    <description>CORE - Object to store information on Calls made to prospects and clients</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE - Name of the account call is be</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Calls</relationshipLabel>
        <relationshipName>Calls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Call_End_Time__c</fullName>
        <defaultValue>NOW() + 0.0104175</defaultValue>
        <description>CORE - Name of the account call is being made in regards to</description>
        <inlineHelpText>If left blank the call end time will default to 1 hour from the call start time</inlineHelpText>
        <label>Call End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Call_Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>CORE - Start time of call</description>
        <label>Call Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Call</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Call</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCallTriggers.cls
@isTest
private class TestCallTriggers
{
	static testMethod void myUnitTest()
	{
		// TO DO: implement unit test
		
		TestClassAutomation.FillAllFields = true;
		
		Account sAccount				= (Account)TestClassAutomation.createSObject('Account');
		sAccount.BillingCountry			= 'Australia';
		sAccount.BillingState			= 'Victoria';
		sAccount.BillingCountryCode		= 'AU';
		sAccount.BillingStateCode		= 'VIC';
		sAccount.ShippingCountry		= 'Australia';
		sAccount.ShippingState			= 'Victoria';
		sAccount.ShippingCountryCode	= 'AU';
		sAccount.ShippingStateCode		= 'VIC';
		
		insert sAccount;
		
		Contact sContact				= (Contact)TestClassAutomation.createSObject('Contact');
		sContact.AccountId				= sAccount.ID;
		sContact.MailingCountry			= 'Australia';
		sContact.MailingState			= 'Victoria';
		sContact.MailingCountryCode		= 'AU';
		sContact.MailingStateCode		= 'VIC';
		sContact.OtherCountry			= 'Australia';
		sContact.OtherState				= 'Victoria';
		sContact.OtherCountryCode		= 'AU';
		sContact.OtherStateCode			= 'VIC';
		
		insert sContact;
		
		Test.startTest();
		
			Call__c sCall					= (Call__c)TestClassAutomation.createSObject('Call__c');
			sCall.Account__c				= sAccount.Id;
			sCall.Call_Start_Time__c		= system.now();
			sCall.Call_End_Time__c			= system.now().addHours(1);
			
			insert sCall;
			
			update sCall;
			
			delete sCall;
			
			undelete sCall;
				
		Test.stopTest();
	}
}