src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>Used to tag the case record with the market of the creator</description>
        <formula>TEXT(CreatedBy.Market__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products_in_Use__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to tie a case to an  assets ( &apos;Products in Use&apos;) . Filtered to show only &apos;qualification&apos; levels assets, with a status=active
&lt;TODO&gt; Create a proper solution to only display qualifications. The filter criteria that uses campus &lt;&gt; &apos; &apos; was a workaround</description>
        <label>Products in Use</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <errorMessage>No Products In Use available for the Associated Account or the Associated Accounts &apos;Product in Use&apos; are not Active.</errorMessage>
            <filterItems>
                <field>Asset.Status</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Asset.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Asset.Campus__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_Campus__c</fullName>
        <description>Used to record the Campus the student wants to move to</description>
        <label>Proposed Campus</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>​Bedfordview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bloemfontein</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cape Town</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durban</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durbanville</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nelspruit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Port Elizabeth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potchefstroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pretoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Randburg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vanderbijlpark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midrand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Event template used for Global needs</description>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Integration_Request__c.object
<CustomObject>
    <description>Representation of an asynchronous integration notification request</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>The business event</description>
        <label>Event</label>
        <picklist>
            <controllingField>Object_Name__c</controllingField>
            <picklistValues>
                <fullName>Register Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Vetted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrol Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change to Financially Responsible Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify Order Line Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resend Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LoB__c</fullName>
        <label>LoB</label>
        <picklist>
            <picklistValues>
                <fullName>HE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K-12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>The ID of the primary object</description>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IntegrationFrameworkAssetSync.cls
/*******************************************************************************************************************
* Apex Class Name  : IntegrationFrameworkAssetSync
* Version          : 1.0 
* Created Date     : 21 April 2015
* Function         : Class to conrol the synchronise of an asset
* Modification Log :
*
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
*                             21/04/2015              Created Initial Version of IntegrationFrameworkAssetSync Class
*******************************************************************************************************************/
public without sharing class IntegrationFrameworkAssetSync 
{
  /*************************************************************************************************************
   * Name        : SynchroniseAssets
   * Description : Depending on the integration request event calls the corresponding  
   *               method in the AssetHandler class to perform the operation to synchronise the asset
   * Input       : CompletedIntReqList - List of Integration Request record completed
   * Output      : none
   *************************************************************************************************************/
  @InvocableMethod(label='Asset synchronisation' description='Synchronises an asset')
  public static void SynchroniseAssets(List<Integration_Request__c> CompletedIntReqList)
  {
  	// create an instance of the AssetHandler to delegate the sync request to
  	AssetHandler assetHandler = new AssetHandler();
  	
  	// process each Integration Request and call the corresponding AssetHandler method
  	for(Integration_Request__c intReq : CompletedIntReqList)
    { 
      System.debug('Processing Integration Request ' + intReq.Name + ' ' + intReq.Event__c + ' ' + intReq.Geo__c + ' ' + intReq.LoB__c + ' ' + intReq.Market__c);
      if(IntReq.Event__c == System.Label.Enrol_Student)
      {
        System.debug('Responding to event Enrol Student');
        assetHandler.Enrol_Student(intReq.object_id__c);
      }
      else if(IntReq.Event__c == System.Label.Change_Of_Campus)
      {
        System.debug('Responding to event Change of Campus');
        // get the case object from the integration object
        Case caseRec = [select Products_in_Use__c, Proposed_Campus__c from Case where id = :intReq.Object_Id__c ];
        if(caseRec != null)
        {
          assetHandler.ChangeofCampus_Asset(caserec.Products_in_Use__c, caserec.Proposed_Campus__c);
        }
      }
      else if(IntReq.Event__c == System.Label.Modify_Contract)
      {
        System.debug('Responding to event Modify Contract');
        assetHandler.Modify_Contract(intReq.object_id__c);
      }
      else if(IntReq.Event__c == System.Label.Contract_Cancelled)
      {
        System.debug('Responding to event Contract Cancelled');
        // get the case object from the integration object
        Case caseRec = [select Products_in_Use__c from Case where id = :intReq.Object_Id__c ];
        if(caseRec != null)
        {
          assetHandler.AssetCancelled(caserec.Products_in_Use__c);
        }
      }
    }
  }
}