src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Status field is used to define the status of the opportunity</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Price_Request__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Special Price Requests</relationshipLabel>
        <relationshipName>Special_Price_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GM approved/ validating data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned to special pricing team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Pricing Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Special Price Request</label>
    <nameField>
        <displayFormat>SPR-{0000000}</displayFormat>
        <label>Special Price Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Price_List__c</fullName>
        <description>Associated Price List, Sales Force</description>
        <label>Price List</label>
        <picklist>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Humanities &amp; Social Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Math &amp; Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional &amp; Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US HE All</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PS_oneCRMProductSelectorPermission.cls
global class PS_oneCRMProductSelectorPermission{
//public String errorString{get;set;}
//public ID opptyId{get;set;}
//public ID opptyProdId{get;set;}  
webService static String checkPermission(String oppID) 
{
    String errorString = '';
    ID slgUserId = UserInfo.getUserId(); 
    ID opptyId = oppID;
    User slgUser = new User();
    UserRecordAccess oppEditAccess = new UserRecordAccess();
    String spstatus = Label.PS_SpecialPriceStatus;
    List<Special_Price_Request__c> specialPriceRequest = new List<Special_Price_Request__c>();
    slgUser=[select id,price_list__c from User where id =: slgUserId]; 
    System.debug(slgUser.price_list__c);
    if (slgUser.price_list__c == '' || slgUser.price_list__c == null)
    { 
        System.debug(slgUser.price_list__c);
        errorString = 'User is not associated with Price List. Please check with System Administrator.';
    }//end of price list check
    else
    { 
        //To check whether user has edit access to the opportunity
        if(slgUserId != null && opptyId != null)
        {
        oppEditAccess =[Select RecordId, HasEditAccess FROM UserRecordAccess WHERE UserId =: slgUserId And RecordId =: opptyId]; 
        if(oppEditAccess.HasEditAccess == true)
            {
                //to check whether is there any special price request processing for the opportunity
                specialPriceRequest = [Select Id,Status__c from Special_Price_Request__c where Opportunity__c =: opptyId And Status__c != 'Completed' And Status__c != 'Rejected' And Status__c != 'Recalled'];
                SYstem.debug(opptyId);
                if (specialPriceRequest.size() > 0)
                    {
                        errorString = 'A Special Price Request is pending for this Opportunity. Products cannot be edited until the request is completed.';
                    }
                    else
                    {
                        errorString = 'redirectUser';  
                    }
            }//end of conditional check for user access and special price request
           
        else
        {
            errorString = 'You do not have the level of access necessary to perform the operation you requested. Please contact the owner of the record or your administrator if access is necessary.';
        }
        }
     
    }
   return errorString;
}
/*public pageReference checkPermission() 
{
    opptyId  = ApexPages.currentPage().getParameters().get('oppId');
    if(ApexPages.currentPage().getParameters().get('productfamilyid') != null)
    {
        opptyProdId  = ApexPages.currentPage().getParameters().get('productfamilyid');
    }    
    errorString = '';
    ID slgUserId = UserInfo.getUserId(); 
    User slgUser = new User();
    UserRecordAccess oppEditAccess = new UserRecordAccess();
    String spstatus = Label.PS_SpecialPriceStatus;
    List<Special_Price_Request__c> specialPriceRequest = new List<Special_Price_Request__c>();
    slgUser=[select id,price_list__c from User where id =: slgUserId]; 
    System.debug(slgUser.price_list__c);
    if (slgUser.price_list__c == '' || slgUser.price_list__c == null)
    { 
        System.debug(slgUser.price_list__c);
        errorString = 'User is not associated with Price List. Please check with System Administrator.';
    }//end of price list check
    else
    { 
        //To check whether user has edit access to the opportunity
        if(slgUserId != null && opptyId != null)
        {
        oppEditAccess =[Select RecordId, HasEditAccess FROM UserRecordAccess WHERE UserId =: slgUserId And RecordId =: opptyId]; 
        if(oppEditAccess.HasEditAccess == true)
            {
                //to check whether is there any special price request processing for the opportunity
                specialPriceRequest = [Select Id,Status__c from Special_Price_Request__c where Opportunity__c =: opptyId And Status__c != 'Completed' And Status__c != 'Rejected' And Status__c != 'Recalled'];
                SYstem.debug(opptyId);
                if (specialPriceRequest.size() > 0)
                    {
                        errorString = 'A Special Price Request is pending for this Opportunity. Products cannot be edited until the request is completed.';
                    }
                    else
                    {
                        errorString = 'redirectUser';  
                    }
            }//end of conditional check for user access and special price request
           
        else
        {
            errorString = 'You do not have the level of access necessary to perform the operation you requested. Please contact the owner of the record or your administrator if access is necessary.';
        }
        }
     }   
    return null; 
}*/
}