src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>CORE Contact</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lost_Reason_Other__c</fullName>
        <description>If the reason for closure is &quot;other&quot;, then this field is used to capture the other value</description>
        <label>Lost Reason Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Status field is used to define the status of the opportunity</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Product Status</description>
        <formula>Text(PricebookEntry.Product2.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Packing_Instructions__c</fullName>
        <description>Instructions for the warehouse concerning packing of the order (i.e. minimize number of boxes)</description>
        <label>Packing Instructions</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Shipping_Instructions__c</fullName>
        <description>Instructions passed to the order shipping carrier (appears on the shipping label for UPS, Fedex, USPS) - ex. Leave at front/back door</description>
        <label>Shipping Instructions</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Shipped_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product actually shipped to the client</description>
        <label>Shipped Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Order line item status that gets updated automatically</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Backordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requires Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resend Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shippable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TU</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/PS_OrderUpdateFactoryTest.cls
@isTest(seeAllData=true)
public with sharing class PS_OrderUpdateFactoryTest 
{
  static testMethod void testMethod1()
  { 
  	List<User> usrLst = TestDataFactory.createUser(Userinfo.getProfileId());
    insert usrLst;
    
    List <PermissionSet> permList = [SELECT Id FROM PermissionSet WHERE name = 'Pearson_Backend_Order_Creation'];  
    PermissionSetAssignment psa = new PermissionSetAssignment();
    psa.AssigneeId = usrLst[1].Id;
    psa.PermissionSetId = permList[0].Id;
    insert psa;
    
    System.runas(usrLst[1])
    {  
    Account acc = (Account)TestClassAutomation.createSObject('Account');
    acc.Name = 'Test';
    insert acc;
     
    contact con = (Contact)TestClassAutomation.createSObject('Contact');
    con.Lastname= 'testcon';
    con.Firstname= 'testcon1';
    con.MobilePhone = '9999';     
    insert con;     
    
    Opportunity opp = (Opportunity)TestClassAutomation.createSObject('Opportunity');
    opp.AccountId = acc.Id;
    opp.CurrencyIsoCode = 'GBP';
    opp.Lost_Reason_Other__c = 'XXX';
    insert opp;
    
    Product2 prod = (Product2)TestClassAutomation.createSObject('Product2');
    insert prod;

    Pricebook2 priceBook = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];
    priceBook.IsActive = true;
    update priceBook;
        
    PriceBookEntry sPriceBookEntry = (PriceBookEntry)TestClassAutomation.createSObject('PriceBookEntry');
    sPriceBookEntry.IsActive = true;
    sPriceBookEntry.Product2Id = prod.Id;
    sPriceBookEntry.Pricebook2Id = priceBook.Id;
    sPriceBookEntry.UnitPrice = 34.95;
    sPriceBookEntry.CurrencyIsoCode = 'GBP';
    insert sPriceBookEntry;
    
    OpportunityLineItem oli1 = new OpportunityLineItem();
    oli1.OpportunityId = opp.Id;
    oli1.PricebookEntryId = sPriceBookEntry.Id;
    oli1.TotalPrice = 200;
    oli1.Quantity = 1;
            
    insert oli1;
     
    order sampleorder = new order();
    sampleorder.OpportunityId=opp.Id;
    sampleorder.Accountid = acc.Id;
    sampleorder.EffectiveDate = system.today();
    sampleorder.status = 'Open';
    sampleorder.Pricebook2Id = priceBook.id;
    sampleorder.CurrencyIsoCode = 'GBP';
    sampleorder.Packing_Instructions__c = 'Packing Instructions';
    sampleorder.Shipping_Instructions__c = 'Shipping instructions';
    insert sampleorder;
    
    Orderitem oi = new OrderItem();
    oi.orderid=sampleorder.id;
    oi.Shipped_Product__c = prod.id;
    oi.Quantity = 6;
    oi.pricebookentryid= sPriceBookEntry.id;
    oi.unitprice =1.00;
    oi.status__c = 'Cancelled';
    insert oi;  
    
    Orderitem oi1 = new OrderItem();
    oi1.orderid=sampleorder.id;
    oi1.Shipped_Product__c = prod.id;
    oi1.Quantity = 6;
    oi1.pricebookentryid= sPriceBookEntry.id;
    oi1.unitprice =1.00;
    oi1.status__c = 'Shipped';
    insert oi1;  
     
    List <OrderItem> orderItems = new List<OrderItem>();
    orderItems.add(oi); 
    orderItems.add(oi1);
    
  	Test.startTest();
  	
    List<PS_OrderUpdateInterface> updates = PS_OrderUpdateFactory.createOrderUpdates(orderItems);
    for(PS_OrderUpdateInterface updateInterface: updates)
    {
     updateInterface.updateOrders();
    }
    
    oi1.status__c = 'Cancelled';
    update oi1;
    updates = PS_OrderUpdateFactory.createOrderUpdates(orderItems);
    for(PS_OrderUpdateInterface updateInterface: updates)
    {
     updateInterface.updateOrders();
    }
    
    oi1.status__c = 'On Hold';
    update oi1;
    updates = PS_OrderUpdateFactory.createOrderUpdates(orderItems);
    for(PS_OrderUpdateInterface updateInterface: updates)
    {
     updateInterface.updateOrders();
    }
    
    List <OrderItem> emptyOrderItems = new List<OrderItem>();
    updates = PS_OrderUpdateFactory.createOrderUpdates(emptyOrderItems);
    for(PS_OrderUpdateInterface updateInterface: updates)
    {
      updateInterface.updateOrders();
    }
    
    Test.stopTest();
    }
  } 
}