src/objects/Generate_Potential_Target__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipName>Course</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Validation In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Validation Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Potential Target</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Potential Target</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Order type</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pearson_Course_Equivalent__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <description>This contains the Course.</description>
        <inlineHelpText>This contains the Course.</inlineHelpText>
        <label>Course/Catalog Code</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Pearson Course Equivalent</relationshipLabel>
        <relationshipName>Pearson_Course_Equivalent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Pearson_Course_Code__c</fullName>
        <description>This contains the Pearson Course Code.</description>
        <inlineHelpText>This contains the Pearson Course Code.</inlineHelpText>
        <label>Pearson Course Code</label>
        <referenceTo>Apttus_Config2__ClassificationHierarchy__c</referenceTo>
        <relationshipLabel>Pearson Course Equivalent</relationshipLabel>
        <relationshipName>Pearson_Course_Equivalent</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Pearson Course Equivalent</label>
    <nameField>
        <displayFormat>CPCS-{000000}</displayFormat>
        <label>Pearson Course Equivalent	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pearson Course Equivalent</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PS_ExceptionLogger__c.object
<CustomObject>
    <description>KP:For handling exception</description>
    <fields>
        <fullName>ApexClassName__c</fullName>
        <label>Apex Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CallingMethod__c</fullName>
        <label>Calling Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionMessage__c</fullName>
        <label>Exception Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InterfaceName__c</fullName>
        <label>Interface Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <label>Record Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserLogin__c</fullName>
        <label>UserLogin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Exception Logger</label>
    <nameField>
        <displayFormat>Ex-{0000}</displayFormat>
        <label>ExceptionNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Fall_Front_List__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fall Front List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Spring_Front_List__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Spring Front List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>To show whether a University Course is Active or Not</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PS_BatchUpdateCoursesFrontlists.cls
global class PS_BatchUpdateCoursesFrontlists implements Database.Batchable<sObject>,Database.Stateful,Schedulable
{
    
    global set<id> setOfCourseIds = new set<id>();
    global String finalstr = 'Course ID, Course Name, Failure Reason \n';
    String sMarket;
    String sId;
    boolean initialld;
    List<Database.SaveResult> dbupres=null;
    list<UniversityCourse__c> listOfcourseObj=null;
    public PS_BatchUpdateCoursesFrontlists(String sCountry,String sCourseId,boolean initialload){
        sMarket=sCountry;
        sId=sCourseId;
        initialld=initialload;
    }//end constructor
    global Database.QueryLocator start(Database.BatchableContext BC){
        /*if (Test.isRunningtest()){
            return Database.getQueryLocator([SELECT id,name,Spring_Front_List__c ,Fall_Front_List__c,
                                        (SELECT Name,Pearson_Course_Code__c,Course__c,Course__r.Spring_Front_List__c,
                                        Course__r.Fall_Front_List__c,Pearson_Course_Code__r.Current_Period__c,
                                        Pearson_Course_Code__r.Prior_Period__c,Pearson_Course_Code__r.Region__c 
                                        FROM Pearson_Course_Equivalent__r where 
                                        (Pearson_Course_Code__r.Current_Period__c = true OR Pearson_Course_Code__r.Prior_Period__c=true) AND 
                                        Pearson_Course_Code__r.Region__c=:sMarket order by 
                                        Pearson_Course_Code__r.Current_Period__c desc,Pearson_Course_Code__r.Prior_Period__c desc)                                         
                                        from UniversityCourse__c where id =:sId]);
        }
        else{ */       
            if (initialld==true){ 
                return Database.getQueryLocator([SELECT id,name,Spring_Front_List__c ,Fall_Front_List__c
                                                 from UniversityCourse__c where Status__c='Active']);
             }
             else{
                return Database.getQueryLocator([SELECT id,name,Spring_Front_List__c ,Fall_Front_List__c
                                         from UniversityCourse__c where Status__c='Active' and id in 
                                        (select course__c from Pearson_Course_Equivalent__c where Pearson_Course_Code__r.lastmodifieddate >= YESTERDAY)]);
             }        
        //}

    }//end start
    global void execute(Database.BatchableContext BC, List<UniversityCourse__c> lstCourse){
        listOfcourseObj= new List<UniversityCourse__c>();
        List<UniversityCourse__c> courseLst = new List<UniversityCourse__c>();


        if(initialld)
            courseLst = [SELECT id,name,Spring_Front_List__c ,Fall_Front_List__c,
                                        (SELECT Name,Pearson_Course_Code__c,Course__c,Course__r.Spring_Front_List__c,
                                        Course__r.Fall_Front_List__c,Pearson_Course_Code__r.Current_Period__c,
                                        Pearson_Course_Code__r.Prior_Period__c,Pearson_Course_Code__r.Region__c 
                                        FROM Pearson_Course_Equivalent__r where 
                                        (Pearson_Course_Code__r.Current_Period__c = true OR Pearson_Course_Code__r.Prior_Period__c=true) AND 
                                        Pearson_Course_Code__r.Region__c=:sMarket order by 
                                        Pearson_Course_Code__r.Current_Period__c desc,Pearson_Course_Code__r.Prior_Period__c desc) 
                                        from UniversityCourse__c where Status__c='Active' and Id in :lstCourse];
        else
            courseLst =[SELECT id,name,Spring_Front_List__c ,Fall_Front_List__c,
                                        (SELECT Name,Pearson_Course_Code__c,Course__c,Course__r.Spring_Front_List__c,
                                        Course__r.Fall_Front_List__c,Pearson_Course_Code__r.Current_Period__c,
                                        Pearson_Course_Code__r.Prior_Period__c,Pearson_Course_Code__r.Region__c 
                                        FROM Pearson_Course_Equivalent__r where 
                                        (Pearson_Course_Code__r.Current_Period__c = true OR Pearson_Course_Code__r.Prior_Period__c=true) AND 
                                        Pearson_Course_Code__r.Region__c=:sMarket and
                                        Pearson_Course_Code__r.Type__c=:System.Label.PS_BatchFLCatType
                                        order by Pearson_Course_Code__r.Current_Period__c desc,Pearson_Course_Code__r.Prior_Period__c desc) 
                                        from UniversityCourse__c where Status__c='Active' and id in :lstCourse];

        if(courseLst.size()>0)
        {
        listOfcourseObj.addAll(courseLst);
        integer iMonth = system.today().month();
        try{
        for(UniversityCourse__c courseObj : listOfcourseObj){
            //System.debug(courseObj.name);
            boolean priorCheck = false;
            boolean currentCheck = false;
            courseObj.Fall_Front_List__c = false;   
            courseObj.Spring_Front_List__c = false;
            if(courseObj.Pearson_Course_Equivalent__r.size() > 0){
                for(Pearson_Course_Equivalent__c  pearson_equivalent : courseObj.Pearson_Course_Equivalent__r){
                    if (!(courseObj.Fall_Front_List__c && courseObj.Spring_Front_List__c)){
                    if (priorCheck == false){
                        if(pearson_equivalent.Pearson_Course_Code__r.Prior_Period__c == true){
                            if ((iMonth >=1 && iMonth <=4) || iMonth > 10){
                                courseObj.Fall_Front_List__c = true;
                            }
                            else{
                                courseObj.Spring_Front_List__c = true;
                            }
                            priorCheck=true;
                        }
                    }
                    if (currentCheck == false){
                        if(pearson_equivalent.Pearson_Course_Code__r.Current_Period__c == true){
                            if ((iMonth >=1 && iMonth <=4) || iMonth > 10){
                                courseObj.Spring_Front_List__c = true;
                            }
                            else{
                                courseObj.Fall_Front_List__c = true;
                            }
                            currentCheck=true;
                        }
                    }
                    }
                    else{break;}
                }//END LOOP THROUGH PEARSON COURSE
            }//end code to check for Pearson course
        }//end loop through course
        dbupres=Database.Update(listOfcourseObj,false);
        
        List<PS_ExceptionLogger__c> errloggerlist=new List<PS_ExceptionLogger__c>();
      try{            
          //Database.SaveResult[] srList=result;
          for (integer i=0;i<listOfcourseObj.size();i++){
              UniversityCourse__c course=listOfcourseObj[i];
              Database.SaveResult res=dbupres[i];
              String ErrMsg='';
              if (!res.isSuccess() || Test.isRunningtest()){
                  PS_ExceptionLogger__c errlogger=new PS_ExceptionLogger__c();
                  errlogger.InterfaceName__c='BatchUpdateCourseFrontList';
                  errlogger.ApexClassName__c='PS_BatchUpdateCoursesFrontlists';
                  errlogger.CallingMethod__c='finish';
                  //errlogger.ExceptionMessage__c=err.getStatusCode() + ': ' + err.getMessage(); 
                  errlogger.UserLogin__c=UserInfo.getUserName(); 
                  errlogger.RecordId__c=course.id;   
                  for(Database.Error err : res.getErrors()) {
                      ErrMsg=ErrMsg+err.getStatusCode() + ': ' + err.getMessage();
                  }   
                  errlogger.ExceptionMessage__c=ErrMsg;
                  errloggerlist.add(errlogger);                     
              }
          }
          if(errloggerlist.size()>0){insert errloggerlist;}
           
       }
       catch(DMLException e){
           throw(e);
       }
        
        }
        
        catch(Exception e){
            ExceptionFramework.LogException('BatchUpdateCourseFrontList','PS_BatchUpdateCoursesFrontlists','execute',e.getMessage(),UserInfo.getUserName(),'');
        }
       } 
    }
    global void finish(Database.BatchableContext BC){
              
    }//end batch finish
    
    global void execute(SchedulableContext sc) {
        database.executebatch(new PS_BatchUpdateCoursesFrontlists('US','',false));
    }
    
}//end class