src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Global: Identifies the geographic region that the Lead belongs to.</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_changed_Qualified__c</fullName>
        <description>Global/ CTIMGI field: Captures the date that the Lead enters the Status &apos;Qualified&apos;.</description>
        <label>Date that the Lead changed to Qualified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Global: Identifies the type of business the lead is in reference to.</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Global Identifies the country that the Lead belongs to.</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>D2L</fullName>
        <active>true</active>
        <businessProcess>Core Lead Process</businessProcess>
        <description>Leads Specific to Direct to Learner sales opportunities.</description>
        <label>D2L</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <description>To which of the Pearson Geographies does this user belong</description>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The user&apos;s line of business</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PS_Lead_RecordTagging_Ctrlr.cls
/* ----------------------------------------------------------------------------------------------------------------------------------------------------------
   Name:            PS_Lead_RecordTaggingCtrlr.cls 
   Description:     On insert/update/ of Lead record 
   Date             Version         Author                             Summary of Changes 
   -----------      ----------      -----------------    ---------------------------------------------------------------------------------------------------
  03/2015         1.0                Srinadh Reddy                       Initial Release 
------------------------------------------------------------------------------------------------------------------------------------------------------------ */
public class PS_Lead_RecordTagging_Ctrlr
{  
  public void leadRecordTagging(List<Lead> leadUpdateList)
  {

   List<User> leadLst = new List<User>();

         String user_id = UserInfo.getUserId();

         List <User> userdetails = [select Market__c , Line_of_Business__c , Geography__c from User where id =:user_id limit 1];

         System.debug(userdetails);
       if(userdetails[0].Market__c != null && userdetails[0].Line_of_Business__c != null && userdetails[0].Geography__c != null && !userdetails.isEmpty())
        { 
        for(Lead newlead: leadUpdateList)
        {
            system.debug('newlead.Market__c----->'+newlead.Market__c);
           
        //lead l = new lead();
        newlead.Market__c = userdetails[0].Market__c;
        newlead.Line_of_Business__c = userdetails[0].Line_of_Business__c;
        newlead.Geography__c = userdetails[0].Geography__c;
        }
            //leadLst.add(newlead);
            
             //system.debug(newlead);

         }
         else if(leadUpdateList[0].Market__c != null && leadUpdateList[0].Line_of_Business__c != null && leadUpdateList[0].Geography__c != null )
         {
         }
         else
         {
          leadUpdateList[0].addError('Record can’t be created without the Market, Line of Business and Geography information in Current User') ;
         }

         //if(!leadLst.isEmpty())
         //{
             //update leadLst;
             
              //system.debug(leadLst);
        // }           
    }
    
   public void updateDateforQualifiedLead(List<Lead> lstNewLead , Map<Id,Lead> oldMap){
   
        
       Map<ID, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Lead.getRecordTypeInfosById();
       Id leadRecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('D2L').getRecordTypeId();

        for(Lead leadObj : lstNewLead){
            if(leadObj.RecordTypeId == leadRecordTypeId){
                if(leadObj.status=='Qualified' && leadObj.status!=oldMap.get(leadObj.id).status)
                        leadObj.Lead_changed_Qualified__c = System.Today();
                System.debug('after leadObj --- >'+leadObj);        
             }
        }
    }
}