src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Special_Price_Request_Open__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox will be checked when a special price request is created and not in a status of rejected, approved, or recalled.</description>
        <label>Special Price Request Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Status field is used to define the status of the opportunity</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>OptionId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Module, Utilized to determine the module for downstream communication</description>
        <label>Option</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Product (Option)</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Product Status</description>
        <formula>Text(PricebookEntry.Product2.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/OpportunityTeamMember.object
<CustomObject>
    <fields>
        <fullName>Job_Function__c</fullName>
        <description>Comes from the job function of the opportunity team member on the user record</description>
        <formula>Text($User.Job_Function__c)</formula>
        <label>Job Function</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/OpportunityUniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - This stores the link between the Opportunity and University Course</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>This contains the opportunity.</description>
        <inlineHelpText>This contains the opportunity.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Courses</relationshipLabel>
        <relationshipName>OpportunityUniversityCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UniversityCourse__c</fullName>
        <description>This contains the University course.</description>
        <inlineHelpText>This contains the University course.</inlineHelpText>
        <label>University Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Course Opportunities</relationshipLabel>
        <relationshipName>OpportunityUniversityCourses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Course</label>
    <nameField>
        <displayFormat>OPTYUC-{00000}</displayFormat>
        <label>OpportunityUniversityCourse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>CORE</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Related To)</relationshipLabel>
        <relationshipName>RelatedTo</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Price_Products__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Line_Item__c</fullName>
        <inlineHelpText>Populating Opportunity line item ID through trigger.</inlineHelpText>
        <label>Opportunity Line Item</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The opportunity to which special price product belongs</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Special Price Products</relationshipLabel>
        <relationshipName>Special_Price_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product for which approval has been requested.  Used in the HE Special Pricing Approval process.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Special Price Products</relationshipLabel>
        <relationshipName>Special_Price_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Quantity of product line item.  Used in the HE Special Pricing Approval process.</description>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Special_Price_Request__c</fullName>
        <label>Special Price Request</label>
        <referenceTo>Special_Price_Request__c</referenceTo>
        <relationshipLabel>Special Price Products</relationshipLabel>
        <relationshipName>Special_Price_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <description>Sales Price of line item which approval has been requested. Used in the HE Special Pricing Approval process.</description>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Special Price Product</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Special Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Price_Request__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <formula>Opportunity__r.Account.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Numbers__c</fullName>
        <description>Account Number(s) of all Stores serving students at this campus. A comprehensive list can be found in Desktop OASIS.  Manually entered by the Sales Rep.  Used in the HE Special Pricing Approval process.</description>
        <inlineHelpText>Account Number(s) of all Stores serving students at this campus. A comprehensive list can be found in Desktop OASIS.</inlineHelpText>
        <label>Account Number(s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the course related to the Opportunity.  Auto-populated when the user comes into the approval.  Used in the HE Special Pricing Approval process.</description>
        <label>Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Special Price Requests</relationshipLabel>
        <relationshipName>Special_Price_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LTS_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the LTS rep. Manually entered by the Sales Rep. Used in the HE Special Pricing Approval process.</description>
        <inlineHelpText>This field reflects an Opportunity Team Member identified with role = &quot;LTS&quot;.  If not pre-polulated, please manually select the LTS team member.</inlineHelpText>
        <label>LTS Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Special_Price_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Special Price Requests</relationshipLabel>
        <relationshipName>Special_Price_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GM approved/ validating data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned to special pricing team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Pricing Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Special Price Request</label>
    <nameField>
        <displayFormat>SPR-{0000000}</displayFormat>
        <label>Special Price Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/UniversityCourse__c.object
<CustomObject>
    <description>CORE adopted from UKHE - Courses linked to Universities</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>To show whether a University Course is Active or Not</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Catalog Code - Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Job_Function__c</fullName>
        <description>The job title of the user. Dependent on Business Unit.</description>
        <label>Job Function</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>Business Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Partnerships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conventions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Digital Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Efficacy &amp; Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Directors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Desk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning &amp; Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Technology Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manager/Product Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Business Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Marketing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SpecialPriceRequestTriggerHandler.cls
public with sharing class SpecialPriceRequestTriggerHandler {
 
    private boolean m_isExecuting = false;
    private integer iBatchSize = 0;
 
    public SpecialPriceRequestTriggerHandler(boolean isExecuting, integer iSize){
        m_isExecuting = isExecuting;
        iBatchSize = iSize;
    }
 
    public void OnBeforeInsert(Special_Price_Request__c[] updatedObjects){
        // EXECUTE BEFORE INSERT LOGIC
       
        set<Id> setOppIds = new set<Id>();
        map<id,list<OpportunityTeamMember>> mapOppIdOppteam = new map<Id,list<OpportunityTeamMember>>();// stores Opportunity Id and List of Opp team Members.
        map<id,list<Relationship__c>> mapAccRelation = new map<Id,list<Relationship__c>>();
        Map<Id,Id> mapOppIdOUC = new Map<Id,Id>();
        Map<Id,Id> mapOppSpl= new Map<Id,Id>();
        Map<Id,Opportunity> lstOpp;// = new list<Opportunity>(); // Stores list of opportunity which satisfy the condition of status = 'completed'
        set<Id> setAccountId = new set<Id>();
        system.debug('Before Insert trigger Special Pricing Request');
        for(Special_Price_Request__c objspecial:updatedObjects){
                setOppIds.add(objspecial.Opportunity__c);
                mapOppSpl.put(objspecial.Id,objspecial.Opportunity__c);
        }
       
        if(setOppIds != null && !setOppIds.isEmpty()){
            lstOpp = new Map<Id,Opportunity>([select id,Name ,AccountId,Special_Price_Request_Open__c,(Select UserId, Name, TeamMemberRole, Job_Function__c From OpportunityTeamMembers WHERE Job_Function__c = 'Learning Technology Specialist'),(Select id, Opportunity__c, UniversityCourse__c from OpportunityUniversityCourses__r) from Opportunity WHERE Id IN: setOppIds]);
        //code added for Special_Price_Request_Open__c checkbox
        //List<Opportunity> oppToUpdate= new List<Opportunity>();
            for(Special_Price_Request__c objspecial:updatedObjects){
             if(lstOpp.get(mapOppSpl.get(objspecial.Id)) != null){ 
                 
            Opportunity op =  lstOpp.get(mapOppSpl.get(objspecial.Id));
            system.debug('Opportunity :'+op);
           // oppToUpdate.add(lstOpp.Opportunity__r)
            if(op.Special_Price_Request_Open__c){
                objspecial.addError('A Special Price Request is already open');
            }
            else{
               op.Special_Price_Request_Open__c = true;
            }
           
                setAccountId.add(op.AccountId);
                if(op.OpportunityTeamMembers.size()>0){
                    for(OpportunityTeamMember objteam:op.OpportunityTeamMembers){
                        list<OpportunityTeamMember> tempTeam = new list<OpportunityTeamMember>();
                      if(mapOppIdOppteam.get(op.Id) == null){
                          tempTeam.add(objteam);
                          mapOppIdOppteam.put(op.Id,tempTeam);
                      }else{
                          tempTeam = mapOppIdOppteam.get(op.Id);
                          tempTeam.add(objteam);
                         mapOppIdOppteam.put(op.Id,tempTeam);
                      }
                    }                  
                }
                // Assignee first courses on the opportunity to the special price request.
                if(op.OpportunityUniversityCourses__r.size()>0){
                    for(OpportunityUniversityCourse__c OUC:op.OpportunityUniversityCourses__r){
                        //List<OpportunityUniversityCourse__c> OUCtemp = new List<OpportunityUniversityCourse__c>();
                        if(mapOppIdOUC.get(OUC.Opportunity__c) == null && OUC.UniversityCourse__c != null){
                            mapOppIdOUC.put(OUC.Opportunity__c, OUC.UniversityCourse__c);
                        }
                    }
                }
            }
            }
       /* for(Opportunity op: lstOpp){
           // oppToUpdate.add(lstOpp.Opportunity__r)
            if(op.Special_Price_Request_Open__c= true){
                this.addError('A Special Price Request is already open');
            }
            else{
           op.Special_Price_Request_Open__c= true;
            }
 
       }
*/
           /* for(Opportunity obj:lstOpp){
                setAccountId.add(obj.AccountId);
                if(obj.OpportunityTeamMembers.size()>0){
                    for(OpportunityTeamMember objteam:obj.OpportunityTeamMembers){
                        list<OpportunityTeamMember> tempTeam = new list<OpportunityTeamMember>();
                      if(mapOppIdOppteam.get(obj.Id) == null){
                          tempTeam.add(objteam);
                          mapOppIdOppteam.put(obj.Id,tempTeam);
                      }else{
                          tempTeam = mapOppIdOppteam.get(obj.Id);
                          tempTeam.add(objteam);
                          mapOppIdOppteam.put(obj.Id,tempTeam);
                      }
                    }                  
                }
                // Assignee first courses on the opportunity to the special price request.
                if(obj.OpportunityUniversityCourses__r.size()>0){
                    for(OpportunityUniversityCourse__c OUC:obj.OpportunityUniversityCourses__r){
                        //List<OpportunityUniversityCourse__c> OUCtemp = new List<OpportunityUniversityCourse__c>();
                        if(mapOppIdOUC.get(OUC.Opportunity__c) == null && OUC.UniversityCourse__c != null){
                            mapOppIdOUC.put(OUC.Opportunity__c, OUC.UniversityCourse__c);
                        }
                    }
                }
            }*/
           
            for(Account objAcc:[Select id,Name, (Select Id, Name, Related_To__c,Related_To__r.Name From Relationships__r) From Account WHERE Id IN: setAccountId]){
                if(objacc.Relationships__r.size()>0){
                    for(Relationship__c objr:objacc.Relationships__r){
                        list<Relationship__c> tempRelation = new list<Relationship__c>();
                      if(mapAccRelation.get(objAcc.Id) == null){
                          tempRelation.add(objr);
                          mapAccRelation.put(objAcc.Id,tempRelation);
                      }else{
                          tempRelation = mapAccRelation.get(objAcc.Id);
                          tempRelation.add(objr);
                          mapAccRelation.put(objAcc.Id,tempRelation);
                      }
                    }
                }
            }
           
            
            for(Special_Price_Request__c objspecial:updatedObjects){
                String objAccountNum = '';
                objspecial.Account_Numbers__c = '';
                if(mapOppIdOppteam.containsKey(objspecial.Opportunity__c) && mapOppIdOppteam.get(objspecial.Opportunity__c) != null ){
                    objspecial.LTS_Name__c = mapOppIdOppteam.get(objspecial.Opportunity__c)[0].UserId;
                }
                if(mapAccRelation.containsKey(objspecial.AccountId__c) && mapAccRelation.get(objspecial.AccountId__c) != null){
                    for(Relationship__c objr : mapAccRelation.get(objspecial.AccountId__c)){
                        if(objr.Related_To__r.Name != null){
                            objAccountNum += objr.Related_To__r.Name +'\r\n';
                        }
                    }
                    objspecial.Account_Numbers__c = objAccountNum;
                }
                if(mapOppIdOUC.get(objspecial.Opportunity__c) != null){
                    objspecial.Course__c = mapOppIdOUC.get(objspecial.Opportunity__c);
                }
            }
   
                if(lstOpp != null && !lstOpp.isEmpty()){
                   
                    try{
                        update lstOpp.values();
                    }catch (exception E){
                        System.debug('Erron in updating Opportunity :'+ E );
                    }
                }
        }
    }
 
    public void OnAfterInsert(Special_Price_Request__c[] newObjects){
        // EXECUTE AFTER INSERT LOGIC
        List<Id> oppty_Id = new List<Id>();
        Map<Id,List<OpportunityLineItem>> MapOpptyLineitem = new Map<Id,List<OpportunityLineItem>>();
        List<Special_Price_Products__c> Specialproduct = new List<Special_Price_Products__c>();
        system.debug ('in SpecialPriceRequestTriggerHandler OnAfterInsert method');
        for(Special_Price_Request__c eachspecialprice :newObjects){
            if(eachspecialprice.Opportunity__c != null){
               oppty_Id.add(eachspecialprice.Opportunity__c);
            }
        }
       
        if(oppty_Id != null && !oppty_Id.isEmpty()){
          List<OpportunityLineItem> OpptyLineItem = [Select Id, OpportunityId, OptionId__c, Quantity, UnitPrice, Product2Id, CurrencyIsoCode from OpportunityLineItem where OpportunityId in: oppty_Id];
          if(OpptyLineItem != null && !OpptyLineItem.isEmpty()){
              for(OpportunityLineItem eachopptylineitem :OpptyLineItem){
                  List<OpportunityLineItem> tempopptyline = new List<OpportunityLineItem>();
                  if(MapOpptyLineitem.get(eachopptylineitem.OpportunityId) == null){
                      tempopptyline.add(eachopptylineitem);
                      MapOpptyLineitem.put(eachopptylineitem.OpportunityId,tempopptyline);
                  }else{
                      tempopptyline = MapOpptyLineitem.get(eachopptylineitem.OpportunityId);
                      tempopptyline.add(eachopptylineitem);
                      MapOpptyLineitem.put(eachopptylineitem.OpportunityId,tempopptyline);
                  }
                      
                  }
                for(Special_Price_Request__c eachspecialprice :newObjects){
                    if(eachspecialprice.Opportunity__c != null && MapOpptyLineitem.get(eachspecialprice.Opportunity__c) != null){
                        for(OpportunityLineItem eachopptylineitem :MapOpptyLineitem.get(eachspecialprice.Opportunity__c)){
                            Special_Price_Products__c tempspecialproduct = new Special_Price_Products__c();
                            tempspecialproduct.Special_Price_Request__c = eachspecialprice.Id;
                            tempspecialproduct.Opportunity__c = eachopptylineitem.OpportunityId;
                            tempspecialproduct.Product__c = eachopptylineitem.Product2Id;
                            tempspecialproduct.Quantity__c = eachopptylineitem.Quantity;
                            tempspecialproduct.UnitPrice__c = eachopptylineitem.UnitPrice;
                            tempspecialproduct.CurrencyIsoCode = eachopptylineitem.CurrencyIsoCode;
                            tempspecialproduct.Opportunity_Line_Item__c=eachopptylineitem.Id;
                           
                            
                            Specialproduct.add(tempspecialproduct);
                        }
                       
                        
                    }
                }
               
                if(Specialproduct != null && !Specialproduct.isEmpty()){
                   
                    try{
                        insert Specialproduct;
                    }catch (exception E){
                        System.debug('Erron in inserting Special_Price_Products :'+ E );
                    }
                }
                 
              }
            
              
          }
         
        }
       
    public void OnBeforeUpdate(Special_Price_Request__c[] oldObjects, Special_Price_Request__c[] updatedObjects, map<ID, Special_Price_Request__c> MapObjectMap){
         //BEFORE UPDATE LOGIC
        
                                System.debug('in before update trigger');
                               
                                List<Special_Price_Request__c>updatedRequests= new List<Special_Price_Request__c>();
                                for(Special_Price_Request__c eachspecialprice: updatedObjects){
                                   
                                  if(eachspecialprice.Status__c == 'Completed' && MapObjectMap.get(eachspecialprice.Id).Status__c !='Completed')
                                   updatedRequests.add(eachspecialprice);
                                }
                                if(updatedRequests != null && ! updatedRequests.isEmpty()){
                                    User Usr = new User();
                                    Usr = [SELECT  Id FROM User WHERE Id = : UserInfo.getUserId()];
                                    system.debug('Usr  :'+Usr);
                                                               
                                    Group Queue= [Select Id from Group where type ='Queue' and DeveloperName = 'Special_Pricing_Monitoring_Group' Limit 1];
                                    List<GroupMember> QueueMembers = [Select UserOrGroupId From GroupMember where GroupId =: Queue.Id and UserOrGroupId =: Usr.Id];
                                    system.debug('QueueMembers :'+QueueMembers);
                                   
                                    if(QueueMembers == null || QueueMembers.isEmpty()){
                                        for(Special_Price_Request__c updatePrice: updatedRequests){
                                            system.debug('throwing error');
                                                string errormsg = 'Only a Special Pricing Approver can complete approval request';
                                                updatePrice.addError(errormsg);
                                        }
                                    }
 
                                  
 
                                }
                               
                                
         
         
             
         }
    public void OnAfterUpdate(Special_Price_Request__c[] oldObjects, Special_Price_Request__c[] updatedObjects, map<ID, Special_Price_Request__c> MapObjectMap){
        // AFTER UPDATE LOGIC
        system.debug('in SpecialPriceRequestTriggerHandler OnAfterUpdate method');
        List<Special_Price_Request__c>completedspecialrequest = new List<Special_Price_Request__c>();
        List < Messaging.SingleEmailMessage > mails = new List < Messaging.SingleEmailMessage > (); // list of mail to be send.
        List<Special_Price_Request__c> specialRequests = new List<Special_Price_Request__c>();
        List<string> opptylineitemid = new List<string>();
        Map<Id,Opportunity>Optty;
        Set<Id>OpttyID= New Set<Id>();
        List<Special_Price_Products__c> specialproducts = new List<Special_Price_Products__c>();
        Map<Id,OpportunityLineItem> opptylineitem = new Map<Id,OpportunityLineItem>();
        string baseURL = URL.getSalesforceBaseUrl().toExternalForm();// building Base URL.
        list < string > teamEmail = new list < string > {System.label.SpecialPricingEmail};
       
        
        for(Special_Price_Request__c eachspecialprice :updatedObjects){
            if(eachspecialprice.Status__c == 'Completed' && MapObjectMap.get(eachspecialprice.Id).Status__c !='Completed'||
               eachspecialprice.Status__c == 'Rejected' && MapObjectMap.get(eachspecialprice.Id).Status__c !='Rejected'||
               eachspecialprice.Status__c == 'Recalled' && MapObjectMap.get(eachspecialprice.Id).Status__c !='Recalled'){
                   
               completedspecialrequest.add(eachspecialprice);
               OpttyID.add(eachspecialprice.Opportunity__c);
               specialRequests.add(eachspecialprice);
               if(eachspecialprice.Status__c == 'Completed' && MapObjectMap.get(eachspecialprice.Id).Status__c !='Completed'){
                  /*Email Body */
                   string body = ' A Special Price Request has been approved and is ready for your review.' + '<br/><br/>';
                    body += 'The Request can be viewed at the following link: <br/>' + ' ';
                    body += baseURL + '/' +eachspecialprice.id ;
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setToAddresses(teamEmail);
                    mail.setSubject('Special Price Request Approved :'+eachspecialprice.Name);
                    mail.setHtmlBody(body);
                    mails.add(mail);
               }
            }
       
        }
        system.debug('completedspecialrequest :'+completedspecialrequest);
        system.debug('OpttyID :'+OpttyID);
       
        if(OpttyID != null && !OpttyID.isEmpty()){
           Optty = new Map <Id, Opportunity> ( [Select Id,Special_Pricing_Approval__c,Special_Price_Request_Open__c From Opportunity where ID in: OpttyID]);
          
           }
           for(Special_Price_Request__c eachspecialprice :specialRequests){
             if (eachspecialprice.Status__c == 'Completed' &&  Optty.get(eachspecialprice.Opportunity__c)!= null){
                 Optty.get(eachspecialprice.Opportunity__c).Special_Price_Request_Open__c = false;
                 Optty.get(eachspecialprice.Opportunity__c).Special_Pricing_Approval__c = true;
                 system.debug('Optty.get(eachspecialprice.Opportunity__c).Special_Price_Request_Open__c :'+Optty.get(eachspecialprice.Opportunity__c).Special_Price_Request_Open__c);
                 system.debug('Optty.get(eachspecialprice.Opportunity__c).Special_Pricing_Approval__c :'+Optty.get(eachspecialprice.Opportunity__c).Special_Pricing_Approval__c);
            }
            else if (eachspecialprice.Status__c== 'Recalled' || eachspecialprice.Status__c== 'Rejected' &&  Optty.get(eachspecialprice.Opportunity__c)!= null){
            Optty.get(eachspecialprice.Opportunity__c).Special_Price_Request_Open__c= false;
            } 
           }
      
        system.debug('mails ---->'+mails);
        if(specialRequests != null && !specialRequests.isEmpty()){
            specialproducts = [Select Id,Requested_Price__c, Approved_Price__c, Opportunity_Line_Item__c From Special_Price_Products__c where Special_Price_Request__c in: specialRequests];
           
        }
        if(specialproducts != null && !specialproducts.isEmpty()){
            for(Special_Price_Products__c eachspecialprice :specialproducts){
                if(eachspecialprice.Approved_Price__c == null )
                    eachspecialprice.Approved_Price__c = eachspecialprice.Requested_Price__c;
                opptylineitemid.add(eachspecialprice.Opportunity_Line_Item__c);
            }
            for(OpportunityLineItem eachopptylineitem : [select id, Discount, UnitPrice  from OpportunityLineItem where Id in:opptylineitemid]){
                opptylineitem.put(eachopptylineitem.Id, eachopptylineitem);
            }
           
            if(opptylineitem != null && !opptylineitem.isEmpty()){
               for(Special_Price_Products__c eachspecialprice :specialproducts){
                    if(opptylineitem.get(eachspecialprice.Opportunity_Line_Item__c) != null){
                        OpportunityLineItem tempopptyline = new OpportunityLineItem();
                        tempopptyline = opptylineitem.get(eachspecialprice.Opportunity_Line_Item__c);
                        system.debug('tempopptyline.UnitPrice :'+tempopptyline.UnitPrice);
                        system.debug('eachspecialprice.Approved_Price__c :'+eachspecialprice.Approved_Price__c);
                        system.debug('eachspecialprice.Requested_Price__c :'+eachspecialprice.Requested_Price__c);
                        if(tempopptyline.UnitPrice != 0.00 && eachspecialprice.Approved_Price__c != null )
                            tempopptyline.Discount = ((tempopptyline.UnitPrice - eachspecialprice.Approved_Price__c) * 100 )/tempopptyline.UnitPrice;
                            system.debug('tempopptyline.Discount  :'+tempopptyline.Discount);
                    }
                }
            }
               try{
                   update specialproducts;
                   update opptylineitem.values();
                  
               } catch (exception E){
               System.debug('Error in updateing Special Price Products :'+ E );
            }
        }
       
        try{
            if(Optty!= null && !Optty.isEmpty()){
                       update Optty.values();
                   }
        }catch (exception E){
               System.debug('Error in updating Opportunity:'+ E );
        }
        list<Messaging.SendEmailResult> results = Messaging.sendEmail(mails);
            system.debug('results --->'+results);
    }
   
        
 
    public boolean IsTriggerContext{
        get{ return m_isExecuting;}
    }
}