src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Selling_Period__c</fullName>
        <description>This specifies the selling period for the adoption.</description>
        <inlineHelpText>This specifies the selling period for the adoption.</inlineHelpText>
        <label>Selling Period</label>
        <picklist>
            <picklistValues>
                <fullName>2014 - Fall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014 - Spring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015 - Fall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015 - Spring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016 - Fall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016 - Spring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017 - Fall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017 - Spring</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Status field is used to define the status of the opportunity</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Product Status</description>
        <formula>Text(PricebookEntry.Product2.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/OpportunityTeamMember.object
<CustomObject>
    <fields>
        <fullName>Job_Function__c</fullName>
        <description>Comes from the job function of the opportunity team member on the user record</description>
        <formula>Text($User.Job_Function__c)</formula>
        <label>Job Function</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TU</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <description>Core: Captures information about Pearson Products</description>
        <label>Product</label>
    </recordTypes>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Influence_Type__c</fullName>
        <description>Indication of the direction of influence within the relationship</description>
        <label>Influence Type</label>
        <picklist>
            <picklistValues>
                <fullName>Influences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influenced By</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchases For</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchases Through</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>CORE</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Related To)</relationshipLabel>
        <relationshipName>RelatedTo</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Selling_Period__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Used to map a date range to a selling season. New start - end dates need to be updated based on the selling season. Name field must match Opportunity.Selling_Period__c field.</description>
    <label>Selling Period</label>
</CustomObject>

src/objects/Special_Price_Request__c.object
<CustomObject>
    <fields>
        <fullName>Is_this_a_Renewal__c</fullName>
        <description>Describes if the product has been previously requested.  Manually entered by the Sales Rep.  Used in the HE Special Pricing Approval process.</description>
        <inlineHelpText>Has this product been previously requested?</inlineHelpText>
        <label>Is this a Renewal?</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Special Price Requests</relationshipLabel>
        <relationshipName>Special_Price_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <description>Type of request the sale rep is creating. Manually entered by the Sales Rep.  Used in the HE Special Pricing Approval process.</description>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Valuepack with MyLab / Mastering Access Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valuepack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Alone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyLab/Mastering Access Code</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GM approved/ validating data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned to special pricing team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Pricing Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>included_the_Account_Numbers_for_every_S__c</fullName>
        <description>Identifier if the user has included the Account Numbers for every School Store at that School.</description>
        <inlineHelpText>For Legal reason, every college bookstore that services this particular school(both on-campus and off-campus stores, must receive the same Special Price.  Select &quot;Yes&quot; if Account Numbers for every School Store have been included.</inlineHelpText>
        <label>Included all the Account Numbers?</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Special Price Request</label>
    <nameField>
        <displayFormat>SPR-{0000000}</displayFormat>
        <label>Special Price Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Job_Function__c</fullName>
        <description>The job title of the user. Dependent on Business Unit.</description>
        <label>Job Function</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>Business Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Partnerships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conventions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Digital Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Efficacy &amp; Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Directors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Desk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning &amp; Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Technology Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manager/Product Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Business Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Marketing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestSpecialPriceRequestTriggerHandler.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class TestSpecialPriceRequestTriggerHandler {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        User user = new User();
        user.ProfileID = [Select Id From Profile Where Name='System Administrator'].id;
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.FirstName = 'first';
        user.LastName = 'last';
        user.Username = 'test@test54.com';   
        user.CommunityNickname = 'testUser123';
        user.Alias = 't1';
        user.Email = 'no@email.com1';
        user.IsActive = true;
        user.Job_Function__c = 'Learning Technology Specialist';
        insert user;
        
        
        list<Account> lstAccount = new list<Account>();
        Pricebook2  standardPb = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];
        Account objacc = new Account(Name = 'Account');
        lstAccount.add(objacc);
        Account objacc1 = new Account(Name = 'Account 2');
        lstAccount.add(objacc1);
        insert lstAccount;
        
       list<Relationship__c> lstRelation = new list<Relationship__c>();
        
      Relationship__c objr= new Relationship__c(Influence_Type__c='Influences',Account__c = objacc.id,Related_To__c = objacc1.id);
      lstRelation.add(objr);
      insert lstRelation;
        
        
        Pricebook2 pbk1 = new Pricebook2 ();
		pbk1.Name='Test Pricebook Entry 1';
		pbk1.Description='Test Pricebook Entry 1';
		pbk1.isActive=true;
		insert pbk1;
		Product2 prd1 = new Product2 ();
		prd1.Name='Test Product Entry 1';
		prd1.Description='Test Product Entry 1';
		prd1.productCode = 'ABC';
		prd1.isActive = true;
		insert prd1;
		  
		PricebookEntry pbe1 = new PricebookEntry ();
	    pbe1.Product2ID=prd1.id;
	    pbe1.Pricebook2ID=standardPb.id;
	    pbe1.UnitPrice=50;
	    pbe1.isActive=true;
	    insert pbe1;
        
        list<Opportunity> lstOpp = new list<Opportunity>();
        Opportunity  objopp = new Opportunity(Name = 'Opp Name',AccountId = objacc.id,StageName='Prospecting',Type='Rollover',
        							CloseDate = system.today(),Selling_Period__c = 'Fall 2017',ForecastCategoryName='Commit');
        lstOpp.add(objOpp);
        
        insert lstOpp;
        
        OpportunityLineItem objoli = new OpportunityLineItem(OpportunityId= objOpp.id,PricebookEntryId=pbe1.Id,Quantity = 1,UnitPrice=200);
        insert objoli;
        
        list<OpportunityTeamMember> lstTeam = new list<OpportunityTeamMember>();

        OpportunityTeamMember objteam = new OpportunityTeamMember(Userid = user.id,TeamMemberRole = 'Support',OpportunityId = objOpp.id);
        lstTeam.add(objteam);
        insert lstTeam;
        
        
        list<Special_Price_Request__c> lstspecial = new list<Special_Price_Request__c>();
        Special_Price_Request__c objspecial = new Special_Price_Request__c(Opportunity__c = objOpp.id,Request_Type__c = 'Valuepack with MyLab / Mastering Access Code',Status__c = 'New',
        							included_the_Account_Numbers_for_every_S__c = 'No',Is_this_a_Renewal__c = 'No');
        lstspecial.add(objspecial);
        insert lstspecial;
        
        Test.startTest();
        System.RunAs(user){
        lstspecial.clear();
        objspecial.Status__c = 'Completed';
        lstspecial.add(objspecial);
        try{
         update lstspecial;
        } catch(exception e){
            system.debug('special price error :'+e);
        }
        Test.stopTest();
        }
        
 }
    
    static testMethod void myUnitTest1(){
        
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        System.runAs ( thisUser ){

        User user = new User();
        user.ProfileID = [Select Id From Profile Where Name='System Administrator'].id;
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.FirstName = 'first';
        user.LastName = 'last';
        user.Username = 'test@test54.com';   
        user.CommunityNickname = 'testUser123';
        user.Alias = 't1';
        user.Email = 'no@email.com1';
        user.IsActive = true;
        user.Job_Function__c = 'Learning Technology Specialist';
        insert user;
       
        
        list<Account> lstAccount = new list<Account>();
        Pricebook2  standardPb = [select id, name, isActive from Pricebook2 where IsStandard = true limit 1];
        Account objacc = new Account(Name = 'Account');
        lstAccount.add(objacc);
        Account objacc1 = new Account(Name = 'Account 2');
        lstAccount.add(objacc1);
        insert lstAccount;
        
       //list<Relationship__c> lstRelation = new list<Relationship__c>();
        
      //Relationship__c objr= new Relationship__c(Influence_Type__c='Influences',Account__c = objacc.id,Related_To__c = objacc1.id);
      //lstRelation.add(objr);
      //insert lstRelation;
        
        
        Pricebook2 pbk1 = new Pricebook2 ();
		pbk1.Name='Test Pricebook Entry 1';
		pbk1.Description='Test Pricebook Entry 1';
		pbk1.isActive=true;
		insert pbk1;
		Product2 prd1 = new Product2 ();
		prd1.Name='Test Product Entry 1';
		prd1.Description='Test Product Entry 1';
		prd1.productCode = 'ABC';
		prd1.isActive = true;
		insert prd1;
		  
		PricebookEntry pbe1 = new PricebookEntry ();
	    pbe1.Product2ID=prd1.id;
	    pbe1.Pricebook2ID=standardPb.id;
	    pbe1.UnitPrice=50;
	    pbe1.isActive=true;
	    insert pbe1;
        
        list<Opportunity> lstOpp = new list<Opportunity>();
        Opportunity  objopp = new Opportunity(Name = 'Opp Name',AccountId = objacc.id,StageName='Prospecting',Type='Rollover',
        							CloseDate = system.today(),Selling_Period__c = 'Fall 2017',ForecastCategoryName='Commit');
        lstOpp.add(objOpp);
        
        insert lstOpp;
        
        OpportunityLineItem objoli = new OpportunityLineItem(OpportunityId= objOpp.id,PricebookEntryId=pbe1.Id,Quantity = 1,UnitPrice=200);
        insert objoli;
        
        list<OpportunityTeamMember> lstTeam = new list<OpportunityTeamMember>();

        OpportunityTeamMember objteam = new OpportunityTeamMember(Userid = user.id,TeamMemberRole = 'Support',OpportunityId = objOpp.id);
        lstTeam.add(objteam);
        insert lstTeam;
        
        
        list<Special_Price_Request__c> lstspecial = new list<Special_Price_Request__c>();
        Special_Price_Request__c objspecial = new Special_Price_Request__c(Opportunity__c = objOpp.id,Request_Type__c = 'Valuepack with MyLab / Mastering Access Code',Status__c = 'New',
        							included_the_Account_Numbers_for_every_S__c = 'No',Is_this_a_Renewal__c = 'No');
        lstspecial.add(objspecial);
        insert lstspecial;
        
        System.RunAs(user){
         
        Group Queue = [Select Id from Group where type ='Queue' and DeveloperName = 'Special_Pricing_Monitoring_Group' Limit 1];
        GroupMember member = new GroupMember(GroupId = Queue.Id, UserOrGroupId = user.ID);
        
        insert member;
        
        Test.startTest();
        
        lstspecial.clear();
        objspecial.Status__c = 'Completed';
        lstspecial.add(objspecial);
        try{
         update lstspecial;
        } catch(exception e){
            system.debug('special price error :'+e);
        }
        Test.stopTest();
        }
        }
    } 
}