src/objects/OpportunityTeamMember.object
<CustomObject>
    <fields>
        <fullName>Job_Function__c</fullName>
        <description>Comes from the job function of the opportunity team member on the user record</description>
        <formula>Text($User.Job_Function__c)</formula>
        <label>Job Function</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Member_s_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Team Member&apos;s Manager - Will be auto populated from user object</description>
        <label>Team Member&apos;s Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Team</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Job_Function__c</fullName>
        <description>The job title of the user. Dependent on Business Unit.</description>
        <label>Job Function</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>Business Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Partnerships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conventions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Digital Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Efficacy &amp; Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Directors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Desk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning &amp; Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Technology Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Manager/Product Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Business Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Marketing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/oneCRMSetOpptyTeamMemberValues.cls
/*************************************************************
@Author     : Accenture IDC
@Description: Controller to set 'Job Function' and 'Team Member Manager' field in OpportunityTeamMember
@Date       : 26/03/2015
**************************************************************/
public class oneCRMSetOpptyTeamMemberValues 
{

/*************************************************************
@Param      : List of OpportunityTeamMember   
@Description: Method to pull 'Job Function' and 'Team Member Manager' field from user object and set it in OpportunityTeamMember
@Return Type: Void
**************************************************************/

 public void setJobFunAndManager(List<OpportunityTeamMember> listOpportunityTeamMember)
 {
     Map<ID,OpportunityTeamMember>  mapWithOpportunityTeamMember = new  Map<ID,OpportunityTeamMember>();  
     Map<Id,User> mapWithUserValues = new Map<Id,User>();
     if(!listOpportunityTeamMember.isEmpty())
     {
         for(OpportunityTeamMember teamMember : listOpportunityTeamMember)
         {         
             mapWithOpportunityTeamMember.put(teamMember.UserId,teamMember); 
         }       
     }     
     if(mapWithOpportunityTeamMember.size()>0 && !mapWithOpportunityTeamMember.isEmpty())
     {     
         for(User userList : [select Id,Job_Function__c,ManagerId from User where Id IN : mapWithOpportunityTeamMember.keyset()])
         {
             mapWithUserValues.put(userList.Id,userList);
         }    
     }
     if(!mapWithUserValues.isEmpty())
     {
         for(ID userVal : mapWithUserValues.keyset())
         {
             //mapWithOpportunityTeamMember.get(userVal).Job_Function__c = mapWithUserValues.get(userVal).Job_Function__c;       
             mapWithOpportunityTeamMember.get(userVal).Team_Member_s_Manager__c = mapWithUserValues.get(userVal).ManagerId;
         }  
     }    
 } 

}