src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>CORE - Status field is used to define the status of the opportunity</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postponed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Price_Request__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Special Price Requests</relationshipLabel>
        <relationshipName>Special_Price_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GM approved/ validating data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned to special pricing team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Pricing Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Special Price Request</label>
    <nameField>
        <displayFormat>SPR-{0000000}</displayFormat>
        <label>Special Price Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Price Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Price_List__c</fullName>
        <description>Associated Price List, Sales Force</description>
        <label>Price List</label>
        <picklist>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Humanities &amp; Social Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Math &amp; Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional &amp; Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US HE All</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PS_oneCRMProductSelectorPermissionTest.cls
@isTest 

public class PS_oneCRMProductSelectorPermissionTest{
static testMethod void checkPermission()
{
  List<Opportunity> listWithOpportunity = new List<Opportunity>();
  List<User> listWithUser = new List<User>();
  listWithUser  = TestDataFactory.createUser([select Id from Profile where Name =: 'System Administrator'].Id,1);
  test.StartTest();
  listWithOpportunity = TestDataFactory.createnewopportnity(1);
  
  listWithOpportunity[0].OwnerId = UserInfo.getUserId(); 
  update listWithOpportunity;
  
  if(listWithUser != null && !listWithUser.isEmpty())
    {
        //listWithUser[0].Price_List__c = 'Math & Science';
        insert listWithUser;
    }
  System.debug(listWithUser[0].Price_List__c);
  test.StopTest();
  System.runAs(listWithUser[0])
  {
      System.debug(listWithUser[0].Price_List__c);
      PS_oneCRMProductSelectorPermission callPermissionMethods = new PS_oneCRMProductSelectorPermission();
      PS_oneCRMProductSelectorPermission.checkPermission(listWithOpportunity[0].Id);
  }
}
static testMethod void checkPermissionPrice()
{
  List<Opportunity> listWithOpportunity = new List<Opportunity>();  
  List<User> listWithUser = new List<User>();
  List<User> listWithUserReadOnly = new List<User>();
  List<Special_Price_Request__c> listWithSpecialPriceRequest = new List<Special_Price_Request__c>();
  Special_Price_Request__c newSpecialPriceRequest = new Special_Price_Request__c();
  listWithUser  = TestDataFactory.createUser([select Id from Profile where Name =: 'System Administrator'].Id,1);
  listWithUserReadOnly = TestDataFactory.createUser([select Id from Profile where Name =: 'Read Only'].Id,1);
  String errorString = '';
  ID opptyId;
  ID opptyProdId;
  test.StartTest();
  if(listWithUser != null && !listWithUser.isEmpty())
    {
       listWithUser[0].Price_List__c = '';
       insert listWithUser;
    }
  listWithOpportunity = TestDataFactory.createnewopportnity(1);
  if(listWithUserReadOnly != null && !listWithUserReadOnly .isEmpty())
    {
       insert listWithUserReadOnly;
       //listWithOpportunity[0].OwnerId = listWithUserReadOnly[0].Id;
    }
  opptyId = listWithOpportunity[0].Id;
  opptyProdId = listWithOpportunity[0].Id;
  newSpecialPriceRequest.Status__c = 'New';
  newSpecialPriceRequest.Opportunity__c = listWithOpportunity[0].Id;
  listWithSpecialPriceRequest.add(newSpecialPriceRequest);
  insert listWithSpecialPriceRequest;
  test.StopTest();
  System.runAs(listWithUserReadOnly[0])
  {
      PS_oneCRMProductSelectorPermission callPermissionMethods = new PS_oneCRMProductSelectorPermission();
      PS_oneCRMProductSelectorPermission.checkPermission(listWithOpportunity[0].Id);
  }
}
}