src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <businessProcess>CORE Sales Process</businessProcess>
        <description>CORE Opportunity</description>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityToOrderEntryCriteria__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Core: Error message to display to the user if the entry condition is not met</description>
        <label>Error Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required_Value__c</fullName>
        <description>Core: Value required in the selected field to allow the mapping to proceed</description>
        <label>Required Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>OpportunityToOrderEntryCriteria</label>
</CustomObject>

src/objects/OpportunityToOrderFieldMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Core: Contains a list of field mappings for sObjects</description>
    <fields>
        <fullName>Destination_Field__c</fullName>
        <description>Core: Field in the target object to be updated by the mapping class. To be entered in the format ObjectAPIName.FieldAPIName</description>
        <label>Destination Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <label>Source Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Object__c</fullName>
        <label>Source Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OpportunityToOrderFieldMapping</label>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <description>CORE adopted from ICOM - Object to track Orders - integration with Bookmaster</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderLineItem__c.object
<CustomObject>
    <description>CORE adopted from ICOM</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>OrderLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateOrderController.cls
public without sharing class CreateOrderController
{
	private final	Opportunity		sOpportunity;
	public			Id				orderID;
	public			Id				opptyID;
	// Retreive field listings from custom settings
	list<OpportunityToOrderEntryCriteria__c>	lstcsCriteria			= OpportunityToOrderEntryCriteria__c.getall().values();
	list<OpportunityToOrderFieldMapping__c>		lstcsMappings			= OpportunityToOrderFieldMapping__c.getall().values();
	
	public CreateOrderController(ApexPages.StandardController stdController)
	{
		list<String> stringstoQuery = new list<String>();
		
		for(OpportunityToOrderFieldMapping__c csMapping : lstcsMappings)
		{
			if(csMapping.Source_Object__c == 'Opportunity')
			{
				stringstoQuery.add(csMapping.Source_Field__c);
			}
		}
		
		for(OpportunityToOrderEntryCriteria__c csCriteria : lstcsCriteria)
		{
			stringstoQuery.add(csCriteria.Field_Name__c);
		}
		if(Test.isRunningTest() == false)
		{
			stdController.addFields(stringstoQuery);
		}
		this.sOpportunity = (Opportunity)stdController.getRecord();
	}
	
	public pageReference init()
	{
			boolean bCriteriaMet = true;
			
			for(OpportunityToOrderEntryCriteria__c csCriteria : lstcsCriteria)
			{
				sObject sOppty				= sOpportunity;
				boolean bCriteriaVal		= (boolean)sOppty.get(csCriteria.Field_Name__c);
				
				if(bCriteriaVal != boolean.valueof(csCriteria.Required_Value__c))
				{
					system.debug('::: ErrorMsg :::' + csCriteria.Error_Message__c);
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,  csCriteria.Error_Message__c));
					bCriteriaMet = false;
				}
			}
			
			if(bCriteriaMet == true)
			{
				// use sObject instead to get dynamic references
				sObject sOrder = Schema.getGlobalDescribe().get('Order__c').newSObject();
				sObject sOppty = sOpportunity;
				
				for(OpportunityToOrderFieldMapping__c csMapping : lstcsMappings)
				{
					if(csMapping.Source_Object__c == 'Opportunity')
					{
						sOrder.put(csMapping.Destination_Field__c, sOppty.get(csMapping.Source_Field__c));
					}
				}
				
				insert sOrder;
				orderID = sOrder.Id;
				opptyID = sOpportunity.Id;
			
			list<sObject>			lstOrderLineItems	= new list<sObject>();
			list<sObject>			lstOpptyLineItems	= new list<sObject>();
			
			string strQuery = 'SELECT Id';
			
			for(OpportunityToOrderFieldMapping__c csMapping : lstcsMappings)
			{
				if(csMapping.Source_Object__c == 'OpportunityLineItem')
				{
					strQuery += ', ' + csMapping.Source_Field__c;
				}
			}
			
			strQuery += ' FROM OpportunityLineItem WHERE OpportunityId = : opptyID';

			lstOpptyLineItems = database.query(strQuery);
			
			for(sObject sOpptyLI : lstOpptyLineItems)
			{
				sObject sOrderLI = Schema.getGlobalDescribe().get('OrderLineItem__c').newSObject();
				
				for(OpportunityToOrderFieldMapping__c csMapping : lstcsMappings)
				{
					if(csMapping.Source_Object__c == 'OpportunityLineItem')
					{
						sOrderLI.put(csMapping.Destination_Field__c, sOpptyLI.get(csMapping.Source_Field__c));
					}
				}
				
				sOrderLI.put('Order__c', orderID);
				
				lstOrderLineItems.add(sOrderLI);
			}
			
			insert lstOrderLineItems;
			
			pageReference pageRef = new PageReference('/' + orderID);
			return pageRef;
			}
			
		return null;
	}
	
	public pagereference actionReturn()
	{
		pagereference pageRef = new pageReference('/' + sOpportunity.Id);
		return pageRef;
	}
	
}