src/objects/Order__c.object
<CustomObject>
    <description>CORE adopted from ICOM - Object to track Orders - integration with Bookmaster</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>&apos;New&apos; is the status for order that have not been completed yet
&apos;Approved&apos; is the status you should select when you want to trigger the sending of the order to Bookmaster</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hand Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <recordTypes>
        <fullName>Order</fullName>
        <active>true</active>
        <label>Order</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderLineItem__c.object
<CustomObject>
    <description>CORE adopted from ICOM</description>
    <fields>
        <fullName>Is_Active_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>OrderLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TU</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <description>Core: Captures information about Pearson Products</description>
        <label>Product</label>
    </recordTypes>
</CustomObject>

src/classes/ProductTriggerHandler.cls
/************************************************************************************************************
* Apex Class Name	: ProductTriggerHandler.cls
* Version 			: 1.0 
* Created Date  	: 06 MARCH 2014
* Function 			: Handler class for Product Object Trigger
* Modification Log	:
* Developer                   Date                    Description
* -----------------------------------------------------------------------------------------------------------
* Mitch Hunt                  06/03/2014              Created Default Handler Class Template
************************************************************************************************************/

public with sharing class ProductTriggerHandler
{
	private boolean m_bIsExecuting = false;
	private integer iBatchSize = 0;
	
	public ProductTriggerHandler(boolean bIsExecuting, integer iSize)
	{
		m_bIsExecuting = bIsExecuting;
		iBatchSize = iSize;
	}
	
	// EXECUTE BEFORE INSERT LOGIC
	//
	public void OnBeforeInsert(Product2[] lstNewProducts)
	{
		
	}
	
	// EXECUTE AFTER INSERT LOGIC
	//
	public void OnAfterInsert(Product2[] lstNewProducts)
	{
		
	}
	
	// BEFORE UPDATE LOGIC
	//
	public void OnBeforeUpdate(Product2[] lstOldProducts, Product2[] lstUpdatedProducts, map<ID, Product2> mapIDProduct)
	{
		
	}
	
	// AFTER UPDATE LOGIC
	//
	public void OnAfterUpdate(Product2[] lstOldProducts, Product2[] lstUpdatedProducts, map<ID, Product2> mapIDProduct)
	{
		// If a product is made inactive flow the status through to the order line item level
		map<Id,boolean> mapProductIDtoStatus = new map<Id,boolean>();
		list<OrderLineItem__c> lstOrderLineItemtoUpdate = new list<OrderLineItem__c>();
		
		for(Product2 oldProduct : lstOldProducts)
		{
			Product2 newProduct = mapIDProduct.get(OldProduct.Id);
			
			if(oldProduct.isActive != newProduct.isActive)
			{
				mapProductIDtoStatus.put(newProduct.Id, newProduct.isActive);
			}
		}
		
		for(OrderLineItem__c oli : [SELECT Id, Product__c FROM OrderLineItem__c WHERE Order__r.Status__c = 'New' AND Product__c IN : mapProductIDtoStatus.keyset()])
		{
			oli.Is_Active_Product__c = mapProductIDtoStatus.get(oli.Product__c);
			lstOrderLineItemtoUpdate.add(oli);
		}
		
		update lstOrderLineItemtoUpdate;
	}
	
	// BEFORE DELETE LOGIC
	//
	public void OnBeforeDelete(Product2[] lstProductsToDelete, map<ID, Product2> mapIDProduct)
	{
		
	}
	
	// AFTER DELETE LOGIC
	//
	public void OnAfterDelete(Product2[] lstDeletedProducts, map<ID, Product2> mapIDProduct)
	{
		
	}
	
	// AFTER UNDELETE LOGIC
	//
	public void OnUndelete(Product2[] lstRestoredProducts)
	{
		
	}
	
	public boolean bIsTriggerContext
	{
		get{ return m_bIsExecuting; }
	}
	
	public boolean bIsVisualforcePageContext
	{
		get{ return !bIsTriggerContext; }
	}
	
	public boolean bIsWebServiceContext
	{
		get{ return !bIsTriggerContext; }
	}
	
	public boolean bIsExecuteAnonymousContext
	{
		get{ return !bIsTriggerContext; }
	}

}