src/objects/Pearson_Course_Equivalent__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <description>This contains the Course.</description>
        <inlineHelpText>This contains the Course.</inlineHelpText>
        <label>Course/Catalog Code</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Pearson Course Equivalent</relationshipLabel>
        <relationshipName>Pearson_Course_Equivalent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate that the Pearson Course Code is the Primary Pearson Course Code for the Course.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Pearson Course Equivalent</label>
    <nameField>
        <displayFormat>CPCS-{000000}</displayFormat>
        <label>Pearson Course Equivalent	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pearson Course Equivalent</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestingPrimary.cls
public class TestingPrimary{
  
  public void updatePrimary(List<Pearson_Course_Equivalent__c> courseEqvList){
  
   List<Id> courseLst = new List<Id>();
   
   for(Pearson_Course_Equivalent__c ce: courseEqvList){
        courseLst.add(ce.Course__c);
   }
   
    List<Pearson_Course_Equivalent__c> courseeqlList = [select Course__c , Primary__c from Pearson_Course_Equivalent__c where Course__c IN :courseLst and Primary__c = true];
    List<Pearson_Course_Equivalent__c> listToupdate= new List<Pearson_Course_Equivalent__c>();
    system.debug('courseeqlList -----'+courseeqlList);
        for(Pearson_Course_Equivalent__c newce: courseeqlList){
            system.debug('newce.Primary__c----->'+newce.Primary__c);
            newce.Primary__c = false;
            listToupdate.add(newce);
         }
         if(!listToupdate.isEmpty()){
             update listToupdate;
         }           
    }
}