src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Apttus_Config2__ConfigurationType__c</fullName>
        <description>The product configuration type</description>
        <label>Configuration Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standalone</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>CTIMGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Field Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Indicates which Market is utilizing this product.</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relevance_Value__c</fullName>
        <label>Relevance (Value)</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Product</fullName>
        <active>true</active>
        <description>Core: Captures information about Pearson Products</description>
        <label>Product</label>
    </recordTypes>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>The business unit the user is assigned to within Pearson</description>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>CTIMGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Field Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>The user&apos;s line of business</description>
        <label>Line of Business</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Field used to &apos;tag&apos; records created by the user (records inherit a market from the creator) and also used in sharing rules to limit/extend record visibility</description>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PS_BatchPearsonChoiceCreation_Test.cls
@isTest(seeAllData=True)
public  class PS_BatchPearsonChoiceCreation_Test
{

    static testMethod void  myUnitTest() {     
        List<User> listWithUser = new List<User>();
        listWithUser  = TestDataFactory.createUser([select Id from Profile where Name =: 'System Administrator'].Id,1);
        Product2 prd = new Product2();
        List<Product2> prdList = new List<Product2>();
   
        prdList = TestDataFactory.createProduct(1);
        prd =  TestDataFactory.insertRelatedProducts();
        SYSTEM.debug('@@@/// PRD'+prd.Id); 
        
        List<Product2> plist=[select id,name,(select id,name from Apttus_Config2__RelatedProducts__r) from product2 where Market__c='US' and Apttus_Config2__ConfigurationType__c ='Bundle' and
                             Line_of_Business__c = 'Higher Ed' and Business_Unit__c='US Field Sales' and Relevance_value__c>=10 and 
                             relevance_value__c<=100 and Market__c='US' and id=:prd.Id];
        system.assert(plist.size()>0);
        system.debug('Relate Product size:'+plist[0].Apttus_Config2__RelatedProducts__r.size());
        System.runAs(listWithUser[0]){
        Test.startTest(); 

     
        
        PS_BatchPearsonChoiceCreation batchObject = new PS_BatchPearsonChoiceCreation('US','US Field Sales','US HE All',prd.Id); 
        //batchObject.PearsonChoiceCreation(); 
        //batchObject.InitProcessMaps(prdList);  
        database.executeBatch(batchObject);
        Test.stopTest();
        }
    }
}