src/objects/RelatedCourse__c.object
<CustomObject>
    <description>CORE - Junction objected used to capture the relationship between university courses</description>
    <fields>
        <fullName>Course__c</fullName>
        <description>CORE - The primary course we are linking to</description>
        <inlineHelpText>The primary course we are linking to</inlineHelpText>
        <label>Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Related Courses</relationshipLabel>
        <relationshipName>RelatedCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Related_Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>CORE - The related course</description>
        <label>Related Course</label>
        <referenceTo>UniversityCourse__c</referenceTo>
        <relationshipLabel>Related Courses (Related Course)</relationshipLabel>
        <relationshipName>Related_Courses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelationshipClone__c</fullName>
        <description>CORE - Hidden field used in the cloning of the related course</description>
        <label>RelationshipClone</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>CORE</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Partner Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross Campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Related Course</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Related Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RelatedCourseUtils.cls
/*******************************************************************************************************************
* Apex Class Name	: RelatedCourseUtils.cls
* Version 			: 1.0 
* Created Date  	: 09 APRIL 2014
* Function 			: Utility Class for RelatedCourse Object
* Modification Log	:
* Developer						Date                    Description
* ------------------------------------------------------------------------------------------------------------------
* Mitch Hunt					09/04/2014              Created Initial Version of Utility Class.
* Mitch Hunt					09/04/2014              Added method to
*******************************************************************************************************************/

public with sharing class RelatedCourseUtils
{
	// Clone Record
	// 
	// 
	public void cloneRecords(RelatedCourse__c[] lstRelatedCourses)
	{
		list<RelatedCourse__c>	lstRelatedCoursestoInsert	= new list<RelatedCourse__c>();
		list<RelatedCourse__c>	lstRelatedCoursestoUpdate	= new list<RelatedCourse__c>();
		map<ID,ID>				mapIDtoCloneID				= new map<ID,ID>();
		
		for(RelatedCourse__c sRelationship : lstRelatedCourses)
		{
			// If this is the first record being created, clone the record
			if(sRelationship.RelationshipClone__c == null)
			{
				lstRelatedCoursestoInsert.add(new RelatedCourse__c
											(	Course__c 				= sRelationship.Related_Course__c, 
												Related_Course__c			= sRelationship.Course__c,
												Type__c					= sRelationship.Type__c,
												RelationshipClone__c	= sRelationship.Id
											)
											);
			}
			
			// If this is the clone record being created update the original record with the correct Id
			if(sRelationship.RelationshipClone__c != null)
			{
				mapIDtoCloneID.put(sRelationship.RelationshipClone__c, sRelationship.Id);
			}
		}
		
		insert lstRelatedCoursestoInsert;
		
		for(RelatedCourse__c sRelationship : [SELECT Id FROM RelatedCourse__c WHERE Id IN : mapIDtoCloneID.keyset()])
		{
			sRelationship.RelationshipClone__c	= mapIDtoCloneID.get(sRelationship.Id);
			lstRelatedCoursestoUpdate.add(sRelationship);
		}
		
		update lstRelatedCoursestoUpdate;
	}
	
	// Update Record
	// 
	// 
	public void updateRecords(RelatedCourse__c[] lstOldRelatedCourses, map<ID, RelatedCourse__c> mapIDRelationship)
	{
		if(GlobalUtils.m_RelationshipUpdateTriggerFired == null || GlobalUtils.m_RelationshipUpdateTriggerFired == false)
		{
			GlobalUtils.m_RelationshipUpdateTriggerFired = true;
		}
		else if(GlobalUtils.m_RelationshipUpdateTriggerFired == true)
		{
			return;
		}
		
		list<RelatedCourse__c>		lstRelatedCoursestoUpdate		= new list<RelatedCourse__c>();
		
		for(RelatedCourse__c sOldRelationship : lstOldRelatedCourses)
		{
			RelatedCourse__c sRelationship = mapIDRelationship.get(sOldRelationship.Id);
			
			lstRelatedCoursestoUpdate.add(new RelatedCourse__c
										(	Id						= sRelationship.RelationshipClone__c,
											Course__c 				= sRelationship.Related_Course__c, 
											Related_Course__c		= sRelationship.Course__c,
											Type__c					= sRelationship.Type__c
										)
										);
										
			system.debug('lstRelatedCoursestoUpdate:::' + lstRelatedCoursestoUpdate);
		}
		
		update lstRelatedCoursestoUpdate;
		
		GlobalUtils.m_RelationshipUpdateTriggerFired = false;
	}
	
	
	// Delete Records
	// 
	// 
	public void deleteRecords(RelatedCourse__c[] lstDeletedRelatedCourses)
	{
		if(GlobalUtils.m_RelationshipDeleteTriggerFired == null || GlobalUtils.m_RelationshipDeleteTriggerFired == false)
		{
			GlobalUtils.m_RelationshipDeleteTriggerFired = true;
		}
		else if(GlobalUtils.m_RelationshipDeleteTriggerFired == true)
		{
			return;
		}
		
		set<ID>						setRelatedCoursestoDelete		= new set<ID>();
		set<ID>						setRelatedCoursesSFDCtoDelete	= new set<ID>();
		list<RelatedCourse__c>		lstRelatedCoursestoDelete		= new list<RelatedCourse__c>();
		
		// Push into a set so that if we are batch deleting we do not get duplicate values
		for(RelatedCourse__c sRelationship : lstDeletedRelatedCourses)
		{
			setRelatedCoursestoDelete.add(sRelationship.RelationshipClone__c);
			setRelatedCoursesSFDCtoDelete.add(sRelationship.ID);
		}
		
		// Now that we have a set of all of the RelatedCourses to delete, check if they are in the original delete list
		// that salesforce is going to perform, if they are not push all the ids into a list so that we can perform DML operation.
		for(ID sRelationshipID : setRelatedCoursestoDelete)
		{
			if(setRelatedCoursesSFDCtoDelete.contains(sRelationshipID) == false)
			{
				lstRelatedCoursestoDelete.add(new RelatedCourse__c
											(	Id						= sRelationshipID
											)
											);
			}
		}
		
		system.debug('lstRelatedCoursestoDelete:::' + lstRelatedCoursestoDelete);
		
		delete lstRelatedCoursestoDelete;
		
		GlobalUtils.m_RelationshipDeleteTriggerFired = false;
	}
	
}