src/objects/Relationship__c.object
<CustomObject>
    <description>CORE</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>CORE</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>CORE</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Influence_Type__c</fullName>
        <description>Indication of the direction of influence within the relationship</description>
        <label>Influence Type</label>
        <picklist>
            <picklistValues>
                <fullName>Influences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influenced By</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchases For</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchases Through</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Other_Type__c</fullName>
        <description>CORE</description>
        <label>Other Type</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>CORE</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Related To)</relationshipLabel>
        <relationshipName>RelatedTo</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelationshipClone__c</fullName>
        <description>CORE - In order to keep everything in one related list we are creating a clone relationship record with reversed relationship. This field should be hidden from the page.</description>
        <label>RelationshipClone</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>CORE</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bookstore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pathway Institution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diocese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RelationshipUtils.cls
/*******************************************************************************************************************
* Apex Class Name   : RelationshipUtils.cls
* Version           : 1.0 
* Created Date      : 14 MARCH 2014
* Function          : Utility Class for Relationship Object
* Modification Log  :
* Developer                   Date                    Description
* ------------------------------------------------------------------------------------------------------------------
* Mitch Hunt                  14/03/2014              Created Initial Version of Utility Class
* Mitch Hunt                  20/03/2014              Fixed deleteRecords to work with Batch Deletion.
*******************************************************************************************************************/

public with sharing class RelationshipUtils
{
    // Clone Record
    // 
    // 
    public void cloneRecords(Relationship__c[] lstRelationships)
    {
        list<Relationship__c>   lstRelationshipstoInsert    = new list<Relationship__c>();
        list<Relationship__c>   lstRelationshipstoUpdate    = new list<Relationship__c>();
        map<ID,ID>              mapIDtoCloneID              = new map<ID,ID>();
        
        for(Relationship__c sRelationship : lstRelationships)
        {
            // If this is the first record being created, clone the record
            if(sRelationship.RelationshipClone__c == null)
            {
                lstRelationshipstoInsert.add(new Relationship__c
                                            (   Account__c              = sRelationship.Related_To__c, 
                                                Related_To__c           = sRelationship.Account__c,
                                                Active__c               = sRelationship.Active__c,
                                                Type__c                 = sRelationship.Type__c,
                                                Other_Type__c           = sRelationship.Other_Type__c,
                                                RelationshipClone__c    = sRelationship.Id
                                            )
                                            );
            }
            
            // If this is the clone record being created update the original record with the correct Id
            if(sRelationship.RelationshipClone__c != null)
            {
                mapIDtoCloneID.put(sRelationship.RelationshipClone__c, sRelationship.Id);
            }
        }
        
        insert lstRelationshipstoInsert;
        
        for(Relationship__c sRelationship : [SELECT Id, Influence_Type__c FROM Relationship__c WHERE Id IN : mapIDtoCloneID.keyset()])
        {
            sRelationship.RelationshipClone__c  = mapIDtoCloneID.get(sRelationship.Id);
            /*Insert Logic for clone, not requested but available
            String inverseInfluence;
            if(sRelationship.Influence_Type__c == 'Influences'){inverseInfluence = 'Influenced By';}
            else if(sRelationship.Influence_Type__c == 'Influenced By'){inverseInfluence = 'Influences';}
            else if(sRelationship.Influence_Type__c == 'Purchases For'){inverseInfluence = 'Purchases Through';}
            else if(sRelationship.Influence_Type__c == 'Purchases Through'){inverseInfluence = 'Purchases For';}*/
            lstRelationshipstoUpdate.add(sRelationship);
        }
        
        update lstRelationshipstoUpdate;
    }
    
    // Update Record
    // 
    // 
    public void updateRecords(Relationship__c[] lstOldRelationships, map<ID, Relationship__c> mapIDRelationship)
    {
        if(GlobalUtils.m_RelationshipUpdateTriggerFired == null || GlobalUtils.m_RelationshipUpdateTriggerFired == false)
        {
            GlobalUtils.m_RelationshipUpdateTriggerFired = true;
        }
        else if(GlobalUtils.m_RelationshipUpdateTriggerFired == true)
        {
            return;
        }
        
        list<Relationship__c>       lstRelationshipstoUpdate        = new list<Relationship__c>();
        
        for(Relationship__c sOldRelationship : lstOldRelationships)
        {
            Relationship__c sRelationship = mapIDRelationship.get(sOldRelationship.Id);
            String inverseInfluence;
            if(sRelationship.Influence_Type__c == 'Influences'){inverseInfluence = 'Influenced By';}
            else if(sRelationship.Influence_Type__c == 'Influenced By'){inverseInfluence = 'Influences';}
            else if(sRelationship.Influence_Type__c == 'Purchases For'){inverseInfluence = 'Purchases Through';}
            else if(sRelationship.Influence_Type__c == 'Purchases Through'){inverseInfluence = 'Purchases For';}



            lstRelationshipstoUpdate.add(new Relationship__c
                                        (   Id                      = sRelationship.RelationshipClone__c,
                                            Account__c              = sRelationship.Related_To__c, 
                                            Related_To__c           = sRelationship.Account__c,
                                            Active__c               = sRelationship.Active__c,
                                            Type__c                 = sRelationship.Type__c,
                                            Other_Type__c           = sRelationship.Other_Type__c,
                                            Influence_Type__c       = inverseInfluence
                                        )
                                        );
                                        
            system.debug('lstRelationshipstoUpdate:::' + lstRelationshipstoUpdate);
        }
        
        update lstRelationshipstoUpdate;
        
        GlobalUtils.m_RelationshipUpdateTriggerFired = false;
    }
    
    
    // Delete Records
    // 
    // 
    public void deleteRecords(Relationship__c[] lstDeletedRelationships)
    {
        if(GlobalUtils.m_RelationshipDeleteTriggerFired == null || GlobalUtils.m_RelationshipDeleteTriggerFired == false)
        {
            GlobalUtils.m_RelationshipDeleteTriggerFired = true;
        }
        else if(GlobalUtils.m_RelationshipDeleteTriggerFired == true)
        {
            return;
        }
        
        set<ID>                     setRelationshipstoDelete        = new set<ID>();
        set<ID>                     setRelationshipsSFDCtoDelete    = new set<ID>();
        list<Relationship__c>       lstRelationshipstoDelete        = new list<Relationship__c>();
        
        // Push into a set so that if we are batch deleting we do not get duplicate values
        for(Relationship__c sRelationship : lstDeletedRelationships)
        {
            setRelationshipstoDelete.add(sRelationship.RelationshipClone__c);
            setRelationshipsSFDCtoDelete.add(sRelationship.ID);
        }
        
        // Now that we have a set of all of the Relationships to delete, check if they are in the original delete list
        // that salesforce is going to perform, if they are not push all the ids into a list so that we can perform DML operation.
        for(ID sRelationshipID : setRelationshipstoDelete)
        {
            if(setRelationshipsSFDCtoDelete.contains(sRelationshipID) == false)
            {
                lstRelationshipstoDelete.add(new Relationship__c
                                            (   Id                      = sRelationshipID
                                            )
                                            );
            }
        }
        
        system.debug('lstRelationshipstoDelete:::' + lstRelationshipstoDelete);
        
        delete lstRelationshipstoDelete;
        
        GlobalUtils.m_RelationshipDeleteTriggerFired = false;
    }
    
}